/* 00000000 */ struct /*VFT*/ ACamperPlayer_vtbl // sizeof=0x1098
/* 00000000 */ {
/* 00000000 */     void (__fastcall *~UObject)(struct UObject *this);
/* 00000008 */     void (__fastcall *RegisterDependencies)(struct UObject *this);
/* 00000010 */     void (__fastcall *DeferredRegister)(struct UObject *this, UClass *, const wchar_t *, const wchar_t *);
/* 00000018 */     bool (__fastcall *CanBeClusterRoot)(struct UObject *this);
/* 00000020 */     bool (__fastcall *CanBeInCluster)(struct UObject *this);
/* 00000028 */     void (__fastcall *CreateCluster)(struct UObject *this);
/* 00000030 */     void (__fastcall *AddToCluster)(struct UObject *this, UObjectBaseUtility *);
/* 00000038 */     FString *(__fastcall *GetDetailedInfoInternal)(UObject *this, FString *result);
/* 00000040 */     void (__fastcall *PostInitProperties)(UObject *this);
/* 00000048 */     bool (__fastcall *PreSaveRoot)(UObject *this, const wchar_t *, TArray<FString,FDefaultAllocator> *);
/* 00000050 */     void (__fastcall *PostSaveRoot)(UObject *this, bool);
/* 00000058 */     void (__fastcall *PreSave)(UObject *this, const ITargetPlatform *);
/* 00000060 */     bool (__fastcall *Modify)(UObject *this, bool);
/* 00000068 */     void (__fastcall *PostLoad)(UObject *this);
/* 00000070 */     void (__fastcall *PostLoadSubobjects)(UObject *this, FObjectInstancingGraph *);
/* 00000078 */     void (__fastcall *BeginDestroy)(UObject *this);
/* 00000080 */     bool (__fastcall *IsReadyForFinishDestroy)(UObject *this);
/* 00000088 */     void (__fastcall *FinishDestroy)(UObject *this);
/* 00000090 */     void (__fastcall *Serialize)(UObject *this, FArchive *);
/* 00000098 */     void (__fastcall *ShutdownAfterError)(UObject *this);
/* 000000A0 */     void (__fastcall *PostInterpChange)(UObject *this, UProperty *);
/* 000000A8 */     void (__fastcall *PostRename)(UObject *this, UObject *, const FName);
/* 000000B0 */     void (__fastcall *PostDuplicate)(UObject *this, bool);
/* 000000B8 */     bool (__fastcall *NeedsLoadForClient)(UObject *this);
/* 000000C0 */     bool (__fastcall *NeedsLoadForServer)(UObject *this);
/* 000000C8 */     bool (__fastcall *NeedsLoadForEditorGame)(UObject *this);
/* 000000D0 */     bool (__fastcall *IsPostLoadThreadSafe)(UObject *this);
/* 000000D8 */     void (__fastcall *ExportCustomProperties)(UObject *this, FOutputDevice *, unsigned int);
/* 000000E0 */     void (__fastcall *ImportCustomProperties)(UObject *this, const wchar_t *, FFeedbackContext *);
/* 000000E8 */     void (__fastcall *PostEditImport)(UObject *this);
/* 000000F0 */     void (__fastcall *PostReloadConfig)(UObject *this, UProperty *);
/* 000000F8 */     bool (__fastcall *Rename)(UObject *this, const wchar_t *, UObject *, unsigned int);
/* 00000100 */     FString *(__fastcall *GetDesc)(UObject *this, FString *result);
/* 00000108 */     UWorld *(__fastcall *GetWorld)(UObject *this);
/* 00000110 */     bool (__fastcall *GetNativePropertyValues)(UObject *this, TMap<FString,FString,FDefaultSetAllocator,TDefaultMapKeyFuncs<FString,FString,0> > *, unsigned int);
/* 00000118 */     unsigned __int64 (__fastcall *GetResourceSize)(UObject *this, EResourceSizeMode::Type);
/* 00000120 */     FName *(__fastcall *GetExporterName)(UObject *this, FName *result);
/* 00000128 */     FRestoreForUObjectOverwrite *(__fastcall *GetRestoreForUObjectOverwrite)(UObject *this);
/* 00000130 */     bool (__fastcall *AreNativePropertiesIdenticalTo)(UObject *this, UObject *);
/* 00000138 */     void (__fastcall *GetAssetRegistryTags)(UObject *this, TArray<UObject::FAssetRegistryTag,FDefaultAllocator> *);
/* 00000140 */     bool (__fastcall *IsAsset)(UObject *this);
/* 00000148 */     bool (__fastcall *IsLocalizedResource)(UObject *this);
/* 00000150 */     bool (__fastcall *IsSafeForRootSet)(UObject *this);
/* 00000158 */     void (__fastcall *TagSubobjects)(UObject *this, EObjectFlags);
/* 00000160 */     void (__fastcall *GetLifetimeReplicatedProps)(UObject *this, TArray<FLifetimeProperty,FDefaultAllocator> *);
/* 00000168 */     bool (__fastcall *IsNameStableForNetworking)(UObject *this);
/* 00000170 */     bool (__fastcall *IsFullNameStableForNetworking)(UObject *this);
/* 00000178 */     bool (__fastcall *IsSupportedForNetworking)(UObject *this);
/* 00000180 */     void (__fastcall *GetSubobjectsWithStableNamesForNetworking)(UObject *this, TArray<UObject *,FDefaultAllocator> *);
/* 00000188 */     void (__fastcall *PreNetReceive)(UObject *this);
/* 00000190 */     void (__fastcall *PostNetReceive)(UObject *this);
/* 00000198 */     void (__fastcall *PostRepNotifies)(UObject *this);
/* 000001A0 */     void (__fastcall *PreDestroyFromReplication)(UObject *this);
/* 000001A8 */     void (__fastcall *ProcessEvent)(UObject *this, UFunction *, void *);
/* 000001B0 */     int (__fastcall *GetFunctionCallspace)(UObject *this, UFunction *, void *, FFrame *);
/* 000001B8 */     bool (__fastcall *CallRemoteFunction)(UObject *this, UFunction *, void *, FOutParmRec *, FFrame *);
/* 000001C0 */     bool (__fastcall *ProcessConsoleExec)(UObject *this, const wchar_t *, FOutputDevice *, UObject *);
/* 000001C8 */     UClass *(__fastcall *RegenerateClass)(UObject *this, UClass *, UObject *, TArray<UObject *,FDefaultAllocator> *);
/* 000001D0 */     void (__fastcall *MarkAsEditorOnlySubobject)(UObject *this);
/* 000001D8 */     bool (__fastcall *CheckDefaultSubobjectsInternal)(UObject *this);
/* 000001E0 */     void (__fastcall *OnRep_ReplicateMovement)(AActor *this);
/* 000001E8 */     void (__fastcall *TearOff)(AActor *this);
/* 000001F0 */     bool (__fastcall *HasNetOwner)(AActor *this);
/* 000001F8 */     void (__fastcall *OnRep_Owner)(AActor *this);
/* 00000200 */     void (__fastcall *SetReplicateMovement)(AActor *this, bool);
/* 00000208 */     void (__fastcall *OnRep_AttachmentReplication)(AActor *this);
/* 00000210 */     bool (__fastcall *IsReplicationPausedForConnection)(AActor *this, const FNetViewer *);
/* 00000218 */     void (__fastcall *OnReplicationPausedChanged)(AActor *this, bool);
/* 00000220 */     bool (__fastcall *ReplicateSubobjects)(AActor *this, UActorChannel *, FOutBunch *, FReplicationFlags *);
/* 00000228 */     void (__fastcall *OnSubobjectCreatedFromReplication)(AActor *this, UObject *);
/* 00000230 */     void (__fastcall *OnSubobjectDestroyFromReplication)(AActor *this, UObject *);
/* 00000238 */     void (__fastcall *PreReplication)(AActor *this, IRepChangedPropertyTracker *);
/* 00000240 */     void (__fastcall *OnRep_Instigator)(AActor *this);
/* 00000248 */     void (__fastcall *EnableInput)(AActor *this, APlayerController *);
/* 00000250 */     void (__fastcall *DisableInput)(AActor *this, APlayerController *);
/* 00000258 */     FVector *(__fastcall *GetVelocity)(AActor *this, FVector *result);
/* 00000260 */     void (__fastcall *SetActorHiddenInGame)(AActor *this, bool);
/* 00000268 */     void (__fastcall *K2_DestroyActor)(AActor *this);
/* 00000270 */     void (__fastcall *AddTickPrerequisiteActor)(AActor *this, AActor *);
/* 00000278 */     void (__fastcall *AddTickPrerequisiteComponent)(AActor *this, UActorComponent *);
/* 00000280 */     void (__fastcall *RemoveTickPrerequisiteActor)(AActor *this, AActor *);
/* 00000288 */     void (__fastcall *RemoveTickPrerequisiteComponent)(AActor *this, UActorComponent *);
/* 00000290 */     void (__fastcall *BeginPlay)(AActor *this);
/* 00000298 */     void (__fastcall *NotifyActorBeginOverlap)(AActor *this, AActor *);
/* 000002A0 */     void (__fastcall *NotifyActorEndOverlap)(AActor *this, AActor *);
/* 000002A8 */     void (__fastcall *NotifyActorBeginCursorOver)(AActor *this);
/* 000002B0 */     void (__fastcall *NotifyActorEndCursorOver)(AActor *this);
/* 000002B8 */     void (__fastcall *NotifyActorOnClicked)(AActor *this, FKey);
/* 000002C0 */     void (__fastcall *NotifyActorOnReleased)(AActor *this, FKey);
/* 000002C8 */     void (__fastcall *NotifyActorOnInputTouchBegin)(AActor *this, const ETouchIndex::Type);
/* 000002D0 */     void (__fastcall *NotifyActorOnInputTouchEnd)(AActor *this, const ETouchIndex::Type);
/* 000002D8 */     void (__fastcall *NotifyActorOnInputTouchEnter)(AActor *this, const ETouchIndex::Type);
/* 000002E0 */     void (__fastcall *NotifyActorOnInputTouchLeave)(AActor *this, const ETouchIndex::Type);
/* 000002E8 */     void (__fastcall *NotifyHit)(AActor *this, UPrimitiveComponent *, AActor *, UPrimitiveComponent *, bool, FVector, FVector, FVector, const FHitResult *);
/* 000002F0 */     void (__fastcall *SetLifeSpan)(AActor *this, float);
/* 000002F8 */     float (__fastcall *GetLifeSpan)(AActor *this);
/* 00000300 */     void (__fastcall *GatherCurrentMovement)(AActor *this);
/* 00000308 */     USceneComponent *(__fastcall *GetDefaultAttachComponent)(AActor *this);
/* 00000310 */     void (__fastcall *ApplyWorldOffset)(AActor *this, const FVector *, bool);
/* 00000318 */     bool (__fastcall *IsLevelBoundsRelevant)(AActor *this);
/* 00000320 */     float (__fastcall *GetNetPriority)(AActor *this, const FVector *, const FVector *, APlayerController *, UActorChannel *, float, bool);
/* 00000328 */     float (__fastcall *GetNetPriority)(AActor *this, const FVector *, const FVector *, AActor *, AActor *, UActorChannel *, float, bool);
/* 00000330 */     float (__fastcall *GetReplayPriority)(AActor *this, const FVector *, const FVector *, AActor *, AActor *, UActorChannel *const, float);
/* 00000338 */     bool (__fastcall *GetNetDormancy)(AActor *this, const FVector *, const FVector *, APlayerController *, AActor *, UActorChannel *, float, bool);
/* 00000340 */     bool (__fastcall *GetNetDormancy)(AActor *this, const FVector *, const FVector *, AActor *, AActor *, UActorChannel *, float, bool);
/* 00000348 */     void (__fastcall *OnActorChannelOpen)(AActor *this, FInBunch *, UNetConnection *);
/* 00000350 */     bool (__fastcall *UseShortConnectTimeout)(AActor *this);
/* 00000358 */     void (__fastcall *OnSerializeNewActor)(AActor *this, FOutBunch *);
/* 00000360 */     void (__fastcall *OnNetCleanup)(AActor *this, UNetConnection *);
/* 00000368 */     void (__fastcall *TickActor)(AActor *this, float, ELevelTick, FActorTickFunction *);
/* 00000370 */     void (__fastcall *PostActorCreated)(AActor *this);
/* 00000378 */     void (__fastcall *LifeSpanExpired)(AActor *this);
/* 00000380 */     void (__fastcall *PostNetInit)(AActor *this);
/* 00000388 */     void (__fastcall *OnRep_ReplicatedMovement)(AActor *this);
/* 00000390 */     void (__fastcall *PostNetReceiveLocation)(AActor *this);
/* 00000398 */     void (__fastcall *PostNetReceiveLocationAndRotation)(AActor *this);
/* 000003A0 */     void (__fastcall *PostNetReceiveVelocity)(AActor *this, const FVector *);
/* 000003A8 */     void (__fastcall *PostNetReceivePhysicState)(AActor *this);
/* 000003B0 */     void (__fastcall *SetOwner)(AActor *this, AActor *);
/* 000003B8 */     bool (__fastcall *CheckStillInWorld)(AActor *this);
/* 000003C0 */     void (__fastcall *Tick)(AActor *this, float);
/* 000003C8 */     bool (__fastcall *ShouldTickIfViewportsOnly)(AActor *this);
/* 000003D0 */     bool (__fastcall *IsNetRelevantFor)(AActor *this, const APlayerController *, const AActor *, const FVector *);
/* 000003D8 */     bool (__fastcall *IsNetRelevantFor)(AActor *this, const AActor *, const AActor *, const FVector *);
/* 000003E0 */     bool (__fastcall *IsRelevancyOwnerFor)(AActor *this, const AActor *, const AActor *, const AActor *);
/* 000003E8 */     void (__fastcall *PreInitializeComponents)(AActor *this);
/* 000003F0 */     void (__fastcall *PostInitializeComponents)(AActor *this);
/* 000003F8 */     const AActor *(__fastcall *GetNetOwner)(AActor *this);
/* 00000400 */     UPlayer *(__fastcall *GetNetOwningPlayer)(AActor *this);
/* 00000408 */     UNetConnection *(__fastcall *GetNetConnection)(AActor *this);
/* 00000410 */     bool (__fastcall *DestroyNetworkActorHandled)(AActor *this);
/* 00000418 */     void (__fastcall *RegisterAllComponents)(AActor *this);
/* 00000420 */     void (__fastcall *PostRegisterAllComponents)(AActor *this);
/* 00000428 */     void (__fastcall *UnregisterAllComponents)(AActor *this, bool);
/* 00000430 */     void (__fastcall *PostUnregisterAllComponents)(AActor *this);
/* 00000438 */     void (__fastcall *ReregisterAllComponents)(AActor *this);
/* 00000440 */     void (__fastcall *MarkComponentsAsPendingKill)(AActor *this);
/* 00000448 */     void (__fastcall *InvalidateLightingCacheDetailed)(AActor *this, bool);
/* 00000450 */     bool (__fastcall *TeleportTo)(AActor *this, const FVector *, const FRotator *, bool, bool);
/* 00000458 */     void (__fastcall *TeleportSucceeded)(AActor *this, bool);
/* 00000460 */     void (__fastcall *ClearCrossLevelReferences)(AActor *this);
/* 00000468 */     void (__fastcall *EndPlay)(AActor *this, const EEndPlayReason::Type);
/* 00000470 */     bool (__fastcall *IsBasedOnActor)(AActor *this, const AActor *);
/* 00000478 */     bool (__fastcall *IsAttachedTo)(AActor *this, const AActor *);
/* 00000480 */     void (__fastcall *RerunConstructionScripts)(AActor *this);
/* 00000488 */     void (__fastcall *OnConstruction)(AActor *this, const FTransform *);
/* 00000490 */     void (__fastcall *RegisterActorTickFunctions)(AActor *this, bool);
/* 00000498 */     AActor *(__fastcall *GetAttachParentActor)(AActor *this);
/* 000004A0 */     FName *(__fastcall *GetAttachParentSocketName)(AActor *this, FName *result);
/* 000004A8 */     void (__fastcall *GetAttachedActors)(AActor *this, TArray<AActor *,FDefaultAllocator> *);
/* 000004B0 */     void (__fastcall *Destroyed)(AActor *this);
/* 000004B8 */     void (__fastcall *FellOutOfWorld)(AActor *this, const UDamageType *);
/* 000004C0 */     void (__fastcall *OutsideWorldBounds)(AActor *this);
/* 000004C8 */     FBox *(__fastcall *GetComponentsBoundingBox)(AActor *this, FBox *result, bool);
/* 000004D0 */     FBox *(__fastcall *CalculateComponentsBoundingBoxInLocalSpace)(AActor *this, FBox *result, bool);
/* 000004D8 */     void (__fastcall *GetComponentsBoundingCylinder)(AActor *this, float *, float *, bool);
/* 000004E0 */     void (__fastcall *GetSimpleCollisionCylinder)(AActor *this, float *, float *);
/* 000004E8 */     bool (__fastcall *IsRootComponentCollisionRegistered)(AActor *this);
/* 000004F0 */     void (__fastcall *TornOff)(AActor *this);
/* 000004F8 */     ECollisionResponse (__fastcall *GetComponentsCollisionResponseToChannel)(AActor *this, ECollisionChannel);
/* 00000500 */     bool (__fastcall *CanBeBaseForCharacter)(AActor *this, APawn *);
/* 00000508 */     float (__fastcall *TakeDamage)(AActor *this, float, const FDamageEvent *, AController *, AActor *);
/* 00000510 */     float (__fastcall *InternalTakeRadialDamage)(AActor *this, float, const FRadialDamageEvent *, AController *, AActor *);
/* 00000518 */     float (__fastcall *InternalTakePointDamage)(AActor *this, float, const FPointDamageEvent *, AController *, AActor *);
/* 00000520 */     void (__fastcall *BecomeViewTarget)(AActor *this, APlayerController *);
/* 00000528 */     void (__fastcall *EndViewTarget)(AActor *this, APlayerController *);
/* 00000530 */     void (__fastcall *CalcCamera)(AActor *this, float, FMinimalViewInfo *);
/* 00000538 */     bool (__fastcall *HasActiveCameraComponent)(AActor *this);
/* 00000540 */     bool (__fastcall *HasActivePawnControlCameraComponent)(AActor *this);
/* 00000548 */     FString *(__fastcall *GetHumanReadableName)(AActor *this, FString *result);
/* 00000550 */     void (__fastcall *Reset)(AActor *this);
/* 00000558 */     float (__fastcall *GetLastRenderTime)(AActor *this);
/* 00000560 */     void (__fastcall *ForceNetRelevant)(AActor *this);
/* 00000568 */     void (__fastcall *ForceNetUpdate)(AActor *this);
/* 00000570 */     void (__fastcall *PrestreamTextures)(AActor *this, float, bool, int);
/* 00000578 */     void (__fastcall *GetActorEyesViewPoint)(AActor *this, FVector *, FRotator *);
/* 00000580 */     FVector *(__fastcall *GetTargetLocation)(AActor *this, FVector *result, AActor *);
/* 00000588 */     void (__fastcall *PostRenderFor)(AActor *this, APlayerController *, UCanvas *, FVector, FVector);
/* 00000590 */     UActorComponent *(__fastcall *FindComponentByClass)(AActor *this, const TSubclassOf<UActorComponent>);
/* 00000598 */     bool (__fastcall *IsComponentRelevantForNavigation)(AActor *this, UActorComponent *);
/* 000005A0 */     void (__fastcall *DisplayDebug)(AActor *this, UCanvas *, const FDebugDisplayInfo *, float *, float *);
/* 000005A8 */     UPawnMovementComponent *(__fastcall *GetMovementComponent)(APawn *this);
/* 000005B0 */     UPrimitiveComponent *(__fastcall *GetMovementBase)(APawn *this);
/* 000005B8 */     UPawnNoiseEmitterComponent *(__fastcall *GetPawnNoiseEmitterComponent)(APawn *this);
/* 000005C0 */     void (__fastcall *TurnOff)(APawn *this);
/* 000005C8 */     void (__fastcall *Restart)(APawn *this);
/* 000005D0 */     void (__fastcall *PawnStartFire)(APawn *this, unsigned __int8);
/* 000005D8 */     void (__fastcall *UnPossessed)(APawn *this);
/* 000005E0 */     APhysicsVolume *(__fastcall *GetPawnPhysicsVolume)(APawn *this);
/* 000005E8 */     bool (__fastcall *ReachedDesiredRotation)(APawn *this);
/* 000005F0 */     float (__fastcall *GetDefaultHalfHeight)(APawn *this);
/* 000005F8 */     void (__fastcall *OnRep_Controller)(APawn *this);
/* 00000600 */     void (__fastcall *OnRep_PlayerState)(APawn *this);
/* 00000608 */     void (__fastcall *UpdateNavigationRelevance)(APawn *this);
/* 00000610 */     bool (__fastcall *ShouldTakeDamage)(APawn *this, float, const FDamageEvent *, AController *, AActor *);
/* 00000618 */     void (__fastcall *SetPlayerDefaults)(APawn *this);
/* 00000620 */     void (__fastcall *RecalculateBaseEyeHeight)(APawn *this);
/* 00000628 */     void (__fastcall *PossessedBy)(APawn *this, AController *);
/* 00000630 */     bool (__fastcall *IsLocallyControlled)(APawn *this);
/* 00000638 */     bool (__fastcall *IsPlayerControlled)(APawn *this);
/* 00000640 */     FRotator *(__fastcall *GetViewRotation)(APawn *this, FRotator *result);
/* 00000648 */     FVector *(__fastcall *GetPawnViewLocation)(APawn *this, FVector *result);
/* 00000650 */     FRotator *(__fastcall *GetBaseAimRotation)(APawn *this, FRotator *result);
/* 00000658 */     bool (__fastcall *InFreeCam)(APawn *this);
/* 00000660 */     void (__fastcall *PawnClientRestart)(APawn *this);
/* 00000668 */     void (__fastcall *ClientSetRotation)(APawn *this, FRotator);
/* 00000670 */     void (__fastcall *FaceRotation)(APawn *this, FRotator, float);
/* 00000678 */     void (__fastcall *DetachFromControllerPendingDestroy)(APawn *this);
/* 00000680 */     void (__fastcall *SpawnDefaultController)(APawn *this);
/* 00000688 */     AController *(__fastcall *GetDamageInstigator)(APawn *this, AController *, const UDamageType *);
/* 00000690 */     UInputComponent *(__fastcall *CreatePlayerInputComponent)(APawn *this);
/* 00000698 */     void (__fastcall *DestroyPlayerInputComponent)(APawn *this);
/* 000006A0 */     void (__fastcall *SetupPlayerInputComponent)(APawn *this, UInputComponent *);
/* 000006A8 */     void (__fastcall *AddMovementInput)(APawn *this, FVector, float, bool);
/* 000006B0 */     FVector *(__fastcall *ConsumeMovementInputVector)(APawn *this, FVector *result);
/* 000006B8 */     void (__fastcall *AddControllerPitchInput)(APawn *this, float);
/* 000006C0 */     void (__fastcall *AddControllerYawInput)(APawn *this, float);
/* 000006C8 */     void (__fastcall *AddControllerRollInput)(APawn *this, float);
/* 000006D0 */     bool (__fastcall *IsMoveInputIgnored)(APawn *this);
/* 000006D8 */     void (__fastcall *MoveIgnoreActorAdd)(APawn *this, AActor *);
/* 000006E0 */     void (__fastcall *MoveIgnoreActorRemove)(APawn *this, AActor *);
/* 000006E8 */     void (__fastcall *SetBase)(ACharacter *this, UPrimitiveComponent *, const FName, bool);
/* 000006F0 */     void (__fastcall *OnRep_ReplicatedBasedMovement)(ACharacter *this);
/* 000006F8 */     void (__fastcall *BaseChange)(ACharacter *this);
/* 00000700 */     const FQuat *(__fastcall *GetBaseRotationOffset)(ACharacter *this, const FQuat *result);
/* 00000708 */     void (__fastcall *OnRep_IsCrouched)(ACharacter *this);
/* 00000710 */     void (__fastcall *ApplyDamageMomentum)(ACharacter *this, float, const FDamageEvent *, APawn *, AActor *);
/* 00000718 */     void (__fastcall *Jump)(ACharacter *this);
/* 00000720 */     void (__fastcall *StopJumping)(ACharacter *this);
/* 00000728 */     bool (__fastcall *CanJumpInternal_Implementation)(ACharacter *this);
/* 00000730 */     bool (__fastcall *IsJumpProvidingForce)(ACharacter *this);
/* 00000738 */     bool (__fastcall *IsJumping)(ACharacter *this);
/* 00000740 */     float (__fastcall *PlayAnimMontage)(ACharacter *this, UAnimMontage *, float, FName);
/* 00000748 */     void (__fastcall *StopAnimMontage)(ACharacter *this, UAnimMontage *);
/* 00000750 */     bool (__fastcall *DoJump)(ACharacter *this, bool);
/* 00000758 */     void (__fastcall *LaunchCharacter)(ACharacter *this, FVector, bool, bool);
/* 00000760 */     void (__fastcall *OnJumped_Implementation)(ACharacter *this);
/* 00000768 */     void (__fastcall *Falling)(ACharacter *this);
/* 00000770 */     void (__fastcall *NotifyJumpApex)(ACharacter *this);
/* 00000778 */     void (__fastcall *Landed)(ACharacter *this, const FHitResult *);
/* 00000780 */     void (__fastcall *OnWalkingOffLedge_Implementation)(ACharacter *this);
/* 00000788 */     void (__fastcall *OnWalkingOffLedge_Implementation)(ACharacter *this, const FVector *, const FVector *, const FVector *, float);
/* 00000790 */     void (__fastcall *MoveBlockedBy)(ACharacter *this, const FHitResult *);
/* 00000798 */     void (__fastcall *Crouch)(ACharacter *this, bool);
/* 000007A0 */     void (__fastcall *UnCrouch)(ACharacter *this, bool);
/* 000007A8 */     bool (__fastcall *CanCrouch)(ACharacter *this);
/* 000007B0 */     void (__fastcall *OnEndCrouch)(ACharacter *this, float, float);
/* 000007B8 */     void (__fastcall *OnStartCrouch)(ACharacter *this, float, float);
/* 000007C0 */     void (__fastcall *OnMovementModeChanged)(ACharacter *this, EMovementMode, unsigned __int8);
/* 000007C8 */     bool (__fastcall *NotifyLanded)(ACharacter *this, const FHitResult *);
/* 000007D0 */     bool (__fastcall *ShouldNotifyLanded)(ACharacter *this, const FHitResult *);
/* 000007D8 */     void (__fastcall *CheckJumpInput)(ACharacter *this, float);
/* 000007E0 */     void (__fastcall *ClearJumpInput)(ACharacter *this);
/* 000007E8 */     float (__fastcall *GetJumpMaxHoldTime)(ACharacter *this);
/* 000007F0 */     void (__fastcall *UpdateFromCompressedFlags)(ACharacter *this, unsigned __int8);
/* 000007F8 */     void (__fastcall *ClientCheatGhost)(ACharacter *this);
/* 00000800 */     void (__fastcall *ClientCheatGhost_Implementation)(ACharacter *this);
/* 00000808 */     void (__fastcall *UpdateSimulatedPosition)(ACharacter *this, const FVector *, const FRotator *);
/* 00000810 */     void (__fastcall *OnUpdateSimulatedPosition)(ACharacter *this, const FVector *, const FQuat *);
/* 00000818 */     bool (__fastcall *IsRootMotionAllowed)(ACharacter *this);
/* 00000820 */     bool (__fastcall *Multicast_SetForceAuthoritativeMovement_Validate)(ADBDPlayer *this, bool);
/* 00000828 */     void (__fastcall *Multicast_SetForceAuthoritativeMovement_Implementation)(ADBDPlayer *this, bool);
/* 00000830 */     bool (__fastcall *Server_SetForceAuthoritativeMovement_Validate)(ADBDPlayer *this, bool);
/* 00000838 */     void (__fastcall *Server_SetForceAuthoritativeMovement_Implementation)(ADBDPlayer *this, bool);
/* 00000840 */     bool (__fastcall *Server_SendSecondaryActionPressed_Validate)(ADBDPlayer *this);
/* 00000848 */     void (__fastcall *Server_SendSecondaryActionPressed_Implementation)(ADBDPlayer *this);
/* 00000850 */     bool (__fastcall *Multicast_Ghost_Validate)(ADBDPlayer *this, bool);
/* 00000858 */     void (__fastcall *Multicast_Ghost_Implementation)(ADBDPlayer *this, bool);
/* 00000860 */     bool (__fastcall *Server_Ghost_Validate)(ADBDPlayer *this, bool);
/* 00000868 */     void (__fastcall *Server_Ghost_Implementation)(ADBDPlayer *this, bool);
/* 00000870 */     bool (__fastcall *Multicast_SetMaxWalkSpeed_Validate)(ADBDPlayer *this, float);
/* 00000878 */     void (__fastcall *Multicast_SetMaxWalkSpeed_Implementation)(ADBDPlayer *this, float);
/* 00000880 */     void (__fastcall *Multicast_AddToInventory_Implementation)(ADBDPlayer *this, ACollectable *);
/* 00000888 */     bool (__fastcall *Server_UpdateScreenAspectRatio_Validate)(ADBDPlayer *this, const float);
/* 00000890 */     void (__fastcall *Server_UpdateScreenAspectRatio_Implementation)(ADBDPlayer *this, const float);
/* 00000898 */     bool (__fastcall *Broadcast_PlayMontage_Multicast_Validate)(ADBDPlayer *this, FAnimationMontageDescriptor, float);
/* 000008A0 */     void (__fastcall *Broadcast_PlayMontage_Multicast_Implementation)(ADBDPlayer *this, FAnimationMontageDescriptor, float);
/* 000008A8 */     bool (__fastcall *Broadcast_PlayMontage_Server_Validate)(ADBDPlayer *this, FAnimationMontageDescriptor, float);
/* 000008B0 */     void (__fastcall *Broadcast_PlayMontage_Server_Implementation)(ADBDPlayer *this, FAnimationMontageDescriptor, float);
/* 000008B8 */     bool (__fastcall *Broadcast_AttackSubstate_Multicast_Validate)(ADBDPlayer *this, EAttackSubstate);
/* 000008C0 */     void (__fastcall *Broadcast_AttackSubstate_Multicast_Implementation)(ADBDPlayer *this, EAttackSubstate);
/* 000008C8 */     bool (__fastcall *Broadcast_AttackSubstate_Server_Validate)(ADBDPlayer *this, EAttackSubstate);
/* 000008D0 */     void (__fastcall *Broadcast_AttackSubstate_Server_Implementation)(ADBDPlayer *this, EAttackSubstate);
/* 000008D8 */     bool (__fastcall *Broadcast_LockOnTarget_Multicast_Validate)(ADBDPlayer *this, ADBDPlayer *);
/* 000008E0 */     void (__fastcall *Broadcast_LockOnTarget_Multicast_Implementation)(ADBDPlayer *this, ADBDPlayer *);
/* 000008E8 */     bool (__fastcall *Broadcast_LockOnTarget_Server_Validate)(ADBDPlayer *this, ADBDPlayer *);
/* 000008F0 */     void (__fastcall *Broadcast_LockOnTarget_Server_Implementation)(ADBDPlayer *this, ADBDPlayer *);
/* 000008F8 */     bool (__fastcall *Broadcast_DamageTarget_Multicast_Validate)(ADBDPlayer *this, ADBDPlayer *, EAttackType);
/* 00000900 */     void (__fastcall *Broadcast_DamageTarget_Multicast_Implementation)(ADBDPlayer *this, ADBDPlayer *, EAttackType);
/* 00000908 */     bool (__fastcall *Broadcast_DamageTarget_Server_Validate)(ADBDPlayer *this, ADBDPlayer *, EAttackType);
/* 00000910 */     void (__fastcall *Broadcast_DamageTarget_Server_Implementation)(ADBDPlayer *this, ADBDPlayer *, EAttackType);
/* 00000918 */     void (__fastcall *OnLocallyObservedChanged_Implementation)(ADBDPlayer *this, bool);
/* 00000920 */     bool (__fastcall *Broadcast_Multicast_BlinkDestination_Validate)(ADBDPlayer *this, FVector, FRotator);
/* 00000928 */     void (__fastcall *Broadcast_Multicast_BlinkDestination_Implementation)(ADBDPlayer *this, FVector, FRotator);
/* 00000930 */     bool (__fastcall *Broadcast_BlinkDestination_Validate)(ADBDPlayer *this, FVector, FRotator);
/* 00000938 */     void (__fastcall *Broadcast_BlinkDestination_Implementation)(ADBDPlayer *this, FVector, FRotator);
/* 00000940 */     bool (__fastcall *Client_TryInteractionType_Validate)(ADBDPlayer *this, EInputInteractionType, ADBDPlayer *);
/* 00000948 */     void (__fastcall *Client_TryInteractionType_Implementation)(ADBDPlayer *this, EInputInteractionType, ADBDPlayer *);
/* 00000950 */     bool (__fastcall *Server_SetCustomization_Validate)(ADBDPlayer *this, const TArray<FName,FDefaultAllocator> *);
/* 00000958 */     void (__fastcall *Server_SetCustomization_Implementation)(ADBDPlayer *this, const TArray<FName,FDefaultAllocator> *);
/* 00000960 */     bool (__fastcall *Multicast_SetCustomization_Validate)(ADBDPlayer *this, const TArray<FName,FDefaultAllocator> *);
/* 00000968 */     void (__fastcall *Multicast_SetCustomization_Implementation)(ADBDPlayer *this, const TArray<FName,FDefaultAllocator> *);
/* 00000970 */     bool (__fastcall *Multicast_ConfirmItemDrop_Validate)(ADBDPlayer *this, bool);
/* 00000978 */     void (__fastcall *Multicast_ConfirmItemDrop_Implementation)(ADBDPlayer *this, bool);
/* 00000980 */     bool (__fastcall *Server_SendItemDropInput_Validate)(ADBDPlayer *this, bool);
/* 00000988 */     void (__fastcall *Server_SendItemDropInput_Implementation)(ADBDPlayer *this, bool);
/* 00000990 */     bool (__fastcall *Server_SendItemUse_Validate)(ADBDPlayer *this, bool);
/* 00000998 */     void (__fastcall *Server_SendItemUse_Implementation)(ADBDPlayer *this, bool);
/* 000009A0 */     bool (__fastcall *Server_SendItemUseInput_Validate)(ADBDPlayer *this, bool);
/* 000009A8 */     void (__fastcall *Server_SendItemUseInput_Implementation)(ADBDPlayer *this, bool);
/* 000009B0 */     bool (__fastcall *CanInterrupt_BP_Implementation)(ADBDPlayer *this);
/* 000009B8 */     bool (__fastcall *CanAttack_BP_Implementation)(ADBDPlayer *this);
/* 000009C0 */     bool (__fastcall *Multicast_OnInsaneSkillCheck_Validate)(ADBDPlayer *this);
/* 000009C8 */     void (__fastcall *Multicast_OnInsaneSkillCheck_Implementation)(ADBDPlayer *this);
/* 000009D0 */     bool (__fastcall *Server_OnInsaneSkillCheck_Validate)(ADBDPlayer *this);
/* 000009D8 */     void (__fastcall *Server_OnInsaneSkillCheck_Implementation)(ADBDPlayer *this);
/* 000009E0 */     bool (__fastcall *Server_SetMaxWalkSpeed_Validate)(ADBDPlayer *this, float);
/* 000009E8 */     void (__fastcall *Server_SetMaxWalkSpeed_Implementation)(ADBDPlayer *this, float);
/* 000009F0 */     UCustomizedSkeletalMesh *(__fastcall *GetCustomizedSkeletalMesh_Implementation)(ADBDPlayer *this);
/* 000009F8 */     USceneComponent *(__fastcall *GetAttachPoint_Implementation)(ADBDPlayer *this, FName);
/* 00000A00 */     void (__fastcall *Local_NotifyMatchEnded_Implementation)(ADBDPlayer *this);
/* 00000A08 */     bool (__fastcall *Multicast_SetAuthoritativeMovement_Validate)(ADBDPlayer *this, bool);
/* 00000A10 */     void (__fastcall *Multicast_SetAuthoritativeMovement_Implementation)(ADBDPlayer *this, bool);
/* 00000A18 */     bool (__fastcall *Server_SetAuthoritativeMovement_Validate)(ADBDPlayer *this, bool);
/* 00000A20 */     void (__fastcall *Server_SetAuthoritativeMovement_Implementation)(ADBDPlayer *this, bool);
/* 00000A28 */     bool (__fastcall *Multicast_ServerResetMeshRelativeOffSet_Validate)(ADBDPlayer *this);
/* 00000A30 */     void (__fastcall *Multicast_ServerResetMeshRelativeOffSet_Implementation)(ADBDPlayer *this);
/* 00000A38 */     bool (__fastcall *Multicast_SetDebugCarry_Validate)(ADBDPlayer *this, bool);
/* 00000A40 */     void (__fastcall *Multicast_SetDebugCarry_Implementation)(ADBDPlayer *this, bool);
/* 00000A48 */     bool (__fastcall *Server_SetDebugCarry_Validate)(ADBDPlayer *this, bool);
/* 00000A50 */     void (__fastcall *Server_SetDebugCarry_Implementation)(ADBDPlayer *this, bool);
/* 00000A58 */     bool (__fastcall *Multicast_SetEnableServerPositionUpdates_Validate)(ADBDPlayer *this, bool);
/* 00000A60 */     void (__fastcall *Multicast_SetEnableServerPositionUpdates_Implementation)(ADBDPlayer *this, bool);
/* 00000A68 */     bool (__fastcall *Server_SetEnableServerPositionUpdates_Validate)(ADBDPlayer *this, bool);
/* 00000A70 */     void (__fastcall *Server_SetEnableServerPositionUpdates_Implementation)(ADBDPlayer *this, bool);
/* 00000A78 */     bool (__fastcall *Multicast_SetDebugSnapPoint_Validate)(ADBDPlayer *this, bool);
/* 00000A80 */     void (__fastcall *Multicast_SetDebugSnapPoint_Implementation)(ADBDPlayer *this, bool);
/* 00000A88 */     bool (__fastcall *Server_SetDebugSnapPoint_Validate)(ADBDPlayer *this, bool);
/* 00000A90 */     void (__fastcall *Server_SetDebugSnapPoint_Implementation)(ADBDPlayer *this, bool);
/* 00000A98 */     bool (__fastcall *Server_SetDebugFailAllInteractions_Validate)(ADBDPlayer *this, bool);
/* 00000AA0 */     void (__fastcall *Server_SetDebugFailAllInteractions_Implementation)(ADBDPlayer *this, bool);
/* 00000AA8 */     bool (__fastcall *Multicast_SetRunVaultEnabled_Validate)(ADBDPlayer *this, bool);
/* 00000AB0 */     void (__fastcall *Multicast_SetRunVaultEnabled_Implementation)(ADBDPlayer *this, bool);
/* 00000AB8 */     bool (__fastcall *Server_SetRunVaultEnabled_Validate)(ADBDPlayer *this, bool);
/* 00000AC0 */     void (__fastcall *Server_SetRunVaultEnabled_Implementation)(ADBDPlayer *this, bool);
/* 00000AC8 */     bool (__fastcall *Multicast_SetReverseTraverseEnabled_Validate)(ADBDPlayer *this, bool);
/* 00000AD0 */     void (__fastcall *Multicast_SetReverseTraverseEnabled_Implementation)(ADBDPlayer *this, bool);
/* 00000AD8 */     bool (__fastcall *Server_SetReverseTraverseEnabled_Validate)(ADBDPlayer *this, bool);
/* 00000AE0 */     void (__fastcall *Server_SetReverseTraverseEnabled_Implementation)(ADBDPlayer *this, bool);
/* 00000AE8 */     bool (__fastcall *Multicast_SetWindowFreeCam_Validate)(ADBDPlayer *this, bool);
/* 00000AF0 */     void (__fastcall *Multicast_SetWindowFreeCam_Implementation)(ADBDPlayer *this, bool);
/* 00000AF8 */     bool (__fastcall *Server_SetWindowFreeCam_Validate)(ADBDPlayer *this, bool);
/* 00000B00 */     void (__fastcall *Server_SetWindowFreeCam_Implementation)(ADBDPlayer *this, bool);
/* 00000B08 */     bool (__fastcall *Multicast_SetEthereal_Validate)(ADBDPlayer *this, bool);
/* 00000B10 */     void (__fastcall *Multicast_SetEthereal_Implementation)(ADBDPlayer *this, bool);
/* 00000B18 */     bool (__fastcall *Server_SetEthereal_Validate)(ADBDPlayer *this, bool);
/* 00000B20 */     void (__fastcall *Server_SetEthereal_Implementation)(ADBDPlayer *this, bool);
/* 00000B28 */     void (__fastcall *OnAttackFinished_Implementation)(ADBDPlayer *this, EAttackType);
/* 00000B30 */     bool (__fastcall *Multicast_AttackSubstate_Validate)(ADBDPlayer *this, EAttackSubstate);
/* 00000B38 */     void (__fastcall *Multicast_AttackSubstate_Implementation)(ADBDPlayer *this, EAttackSubstate);
/* 00000B40 */     bool (__fastcall *Multicast_DamageTarget_Validate)(ADBDPlayer *this, ADBDPlayer *, EAttackType);
/* 00000B48 */     void (__fastcall *Multicast_DamageTarget_Implementation)(ADBDPlayer *this, ADBDPlayer *, EAttackType);
/* 00000B50 */     bool (__fastcall *Multicast_LockOnTarget_Validate)(ADBDPlayer *this, ADBDPlayer *);
/* 00000B58 */     void (__fastcall *Multicast_LockOnTarget_Implementation)(ADBDPlayer *this, ADBDPlayer *);
/* 00000B60 */     bool (__fastcall *Multicast_PlayMontage_Validate)(ADBDPlayer *this, FAnimationMontageDescriptor, float);
/* 00000B68 */     void (__fastcall *Multicast_PlayMontage_Implementation)(ADBDPlayer *this, FAnimationMontageDescriptor, float);
/* 00000B70 */     bool (__fastcall *Multicast_AttackBegin_Validate)(ADBDPlayer *this, EAttackType);
/* 00000B78 */     void (__fastcall *Multicast_AttackBegin_Implementation)(ADBDPlayer *this, EAttackType);
/* 00000B80 */     void (__fastcall *Multicast_SetInteractingPlayer_Implementation)(ADBDPlayer *this, ADBDPlayer *);
/* 00000B88 */     bool (__fastcall *Client_SendCancelInteraction_Validate)(ADBDPlayer *this);
/* 00000B90 */     void (__fastcall *Client_SendCancelInteraction_Implementation)(ADBDPlayer *this);
/* 00000B98 */     bool (__fastcall *Multicast_SetContinuousPrintDebug_Validate)(ADBDPlayer *this, bool);
/* 00000BA0 */     void (__fastcall *Multicast_SetContinuousPrintDebug_Implementation)(ADBDPlayer *this, bool);
/* 00000BA8 */     bool (__fastcall *Server_SetContinuousPrintDebug_Validate)(ADBDPlayer *this, bool);
/* 00000BB0 */     void (__fastcall *Server_SetContinuousPrintDebug_Implementation)(ADBDPlayer *this, bool);
/* 00000BB8 */     bool (__fastcall *ServerResetMeshRelativeOffSet_Validate)(ADBDPlayer *this);
/* 00000BC0 */     void (__fastcall *ServerResetMeshRelativeOffSet_Implementation)(ADBDPlayer *this);
/* 00000BC8 */     bool (__fastcall *Server_TeleportTo_Validate)(ADBDPlayer *this, const FVector *, const FRotator *, bool, bool);
/* 00000BD0 */     void (__fastcall *Server_TeleportTo_Implementation)(ADBDPlayer *this, const FVector *, const FRotator *, bool, bool);
/* 00000BD8 */     bool (__fastcall *Server_SendFastInteractionInput_Validate)(ADBDPlayer *this, bool);
/* 00000BE0 */     void (__fastcall *Server_SendFastInteractionInput_Implementation)(ADBDPlayer *this, bool);
/* 00000BE8 */     bool (__fastcall *Server_SendInteractionInput_Validate)(ADBDPlayer *this, bool);
/* 00000BF0 */     void (__fastcall *Server_SendInteractionInput_Implementation)(ADBDPlayer *this, bool);
/* 00000BF8 */     bool (__fastcall *Multicast_TriggerSprint_Validate)(ADBDPlayer *this);
/* 00000C00 */     void (__fastcall *Multicast_TriggerSprint_Implementation)(ADBDPlayer *this);
/* 00000C08 */     bool (__fastcall *Multicast_TriggerSprintWithParams_Validate)(ADBDPlayer *this, float, UCurveFloat *, FName);
/* 00000C10 */     void (__fastcall *Multicast_TriggerSprintWithParams_Implementation)(ADBDPlayer *this, float, UCurveFloat *, FName);
/* 00000C18 */     bool (__fastcall *Server_OnMovementInput_Validate)(ADBDPlayer *this, ADBDPlayer *);
/* 00000C20 */     void (__fastcall *Server_OnMovementInput_Implementation)(ADBDPlayer *this, ADBDPlayer *);
/* 00000C28 */     bool (__fastcall *Multicast_SetEnableCapsuleDynamicResize_Validate)(ADBDPlayer *this, bool);
/* 00000C30 */     void (__fastcall *Multicast_SetEnableCapsuleDynamicResize_Implementation)(ADBDPlayer *this, bool);
/* 00000C38 */     bool (__fastcall *Server_SetSlasherAutoAttackOnCamperInteractFrameDelay_Validate)(ADBDPlayer *this, int);
/* 00000C40 */     void (__fastcall *Server_SetSlasherAutoAttackOnCamperInteractFrameDelay_Implementation)(ADBDPlayer *this, int);
/* 00000C48 */     bool (__fastcall *Server_SetEnableCapsuleDynamicResize_Validate)(ADBDPlayer *this, bool);
/* 00000C50 */     void (__fastcall *Server_SetEnableCapsuleDynamicResize_Implementation)(ADBDPlayer *this, bool);
/* 00000C58 */     bool (__fastcall *Server_PlayerReady_Validate)(ADBDPlayer *this);
/* 00000C60 */     void (__fastcall *Server_PlayerReady_Implementation)(ADBDPlayer *this);
/* 00000C68 */     bool (__fastcall *Server_FailInterruption_Validate)(ADBDPlayer *this, ADBDPlayer *);
/* 00000C70 */     void (__fastcall *Server_FailInterruption_Implementation)(ADBDPlayer *this, ADBDPlayer *);
/* 00000C78 */     bool (__fastcall *Server_RemoveStatusEffects_Validate)(ADBDPlayer *this);
/* 00000C80 */     void (__fastcall *Server_RemoveStatusEffects_Implementation)(ADBDPlayer *this);
/* 00000C88 */     bool (__fastcall *Server_RemoveStatusEffectByID_Validate)(ADBDPlayer *this, FName, bool);
/* 00000C90 */     void (__fastcall *Server_RemoveStatusEffectByID_Implementation)(ADBDPlayer *this, FName, bool);
/* 00000C98 */     bool (__fastcall *Server_SpawnStatusEffect_Validate)(ADBDPlayer *this, FName);
/* 00000CA0 */     void (__fastcall *Server_SpawnStatusEffect_Implementation)(ADBDPlayer *this, FName);
/* 00000CA8 */     bool (__fastcall *Server_SpawnItem_Validate)(ADBDPlayer *this, FName);
/* 00000CB0 */     void (__fastcall *Server_SpawnItem_Implementation)(ADBDPlayer *this, FName);
/* 00000CB8 */     bool (__fastcall *Server_SpawnItemAddon_Validate)(ADBDPlayer *this, FName);
/* 00000CC0 */     void (__fastcall *Server_SpawnItemAddon_Implementation)(ADBDPlayer *this, FName);
/* 00000CC8 */     bool (__fastcall *Server_RemovePerks_Validate)(ADBDPlayer *this);
/* 00000CD0 */     void (__fastcall *Server_RemovePerks_Implementation)(ADBDPlayer *this);
/* 00000CD8 */     bool (__fastcall *Server_SpawnPerk_Validate)(ADBDPlayer *this, FName, int);
/* 00000CE0 */     void (__fastcall *Server_SpawnPerk_Implementation)(ADBDPlayer *this, FName, int);
/* 00000CE8 */     void (__fastcall *Multicast_ClearAndDestroyInventory_Implementation)(ADBDPlayer *this);
/* 00000CF0 */     void (__fastcall *Multicast_RemoveFromInventory_Implementation)(ADBDPlayer *this, ACollectable *);
/* 00000CF8 */     bool (__fastcall *Server_Drop_Validate)(ADBDPlayer *this, ACollectable *, const FVector *, const FRotator *, bool);
/* 00000D00 */     void (__fastcall *Server_Drop_Implementation)(ADBDPlayer *this, ACollectable *, const FVector *, const FRotator *, bool);
/* 00000D08 */     bool (__fastcall *Server_CheatDispatchOnPostItemAddonsCreation_Validate)(ADBDPlayer *this);
/* 00000D10 */     void (__fastcall *Server_CheatDispatchOnPostItemAddonsCreation_Implementation)(ADBDPlayer *this);
/* 00000D18 */     bool (__fastcall *Server_Cheat_Validate)(ADBDPlayer *this);
/* 00000D20 */     void (__fastcall *Server_Cheat_Implementation)(ADBDPlayer *this);
/* 00000D28 */     UStillnessTrackerComponent *(__fastcall *GetStillnessComponent)(ADBDPlayer *this);
/* 00000D30 */     void (__fastcall *MoveForward)(ADBDPlayer *this, float);
/* 00000D38 */     void (__fastcall *MoveRight)(ADBDPlayer *this, float);
/* 00000D40 */     void (__fastcall *TurnAtRate)(ADBDPlayer *this, float);
/* 00000D48 */     void (__fastcall *LookUpAtRate)(ADBDPlayer *this, float);
/* 00000D50 */     void (__fastcall *Turn)(ADBDPlayer *this, float);
/* 00000D58 */     void (__fastcall *LookUp)(ADBDPlayer *this, float);
/* 00000D60 */     void (__fastcall *SecondaryActionInputPressed)(ADBDPlayer *this);
/* 00000D68 */     float (__fastcall *GetLuck)(ADBDPlayer *this);
/* 00000D70 */     void (__fastcall *DBDCrouch)(ADBDPlayer *this);
/* 00000D78 */     void (__fastcall *DBDUnCrouch)(ADBDPlayer *this);
/* 00000D80 */     bool (__fastcall *IsPartiallyHidden)(ADBDPlayer *this);
/* 00000D88 */     bool (__fastcall *IsTotallyHidden)(ADBDPlayer *this);
/* 00000D90 */     bool (__fastcall *IsIncapacitated)(ADBDPlayer *this);
/* 00000D98 */     bool (__fastcall *IsUnintentionallyIncapacitated)(ADBDPlayer *this);
/* 00000DA0 */     void (__fastcall *Authority_OnSlashed)(ADBDPlayer *this, ADBDPlayer *);
/* 00000DA8 */     void (__fastcall *Authority_ActivateAuthoritativeMovementOnDropped)(ADBDPlayer *this);
/* 00000DB0 */     bool (__fastcall *IsSlasherLocallyControlled)(ADBDPlayer *this);
/* 00000DB8 */     bool (__fastcall *IsLocallyObserved)(ADBDPlayer *this);
/* 00000DC0 */     void (__fastcall *UpdateCapsuleSize)(ADBDPlayer *this);
/* 00000DC8 */     void (__fastcall *UpdateStance)(ADBDPlayer *this);
/* 00000DD0 */     void (__fastcall *Authority_AddItemAddonToPlayer)(ADBDPlayer *this, UItemAddon *);
/* 00000DD8 */     FRotator *(__fastcall *GetPlayerDirection)(ADBDPlayer *this, FRotator *result);
/* 00000DE0 */     void (__fastcall *SetPlayerDirection)(ADBDPlayer *this, FRotator);
/* 00000DE8 */     void (__fastcall *UpdateRTPCValues)(ADBDPlayer *this);
/* 00000DF0 */     void (__fastcall *UpdateStrafe)(ADBDPlayer *this);
/* 00000DF8 */     bool (__fastcall *CheckTransitionAttack)(ADBDPlayer *this, EAttackType);
/* 00000E00 */     bool (__fastcall *CheckTransitionBlink)(ADBDPlayer *this);
/* 00000E08 */     bool (__fastcall *CheckTransitionGuidedAction)(ADBDPlayer *this);
/* 00000E10 */     bool (__fastcall *IsBeingInteractedWith)(ADBDPlayer *this);
/* 00000E18 */     UAnimMontage *(__fastcall *GetMontage)(ADBDPlayer *this, FAnimationMontageDescriptor);
/* 00000E20 */     ECollisionResponse (__fastcall *GetPawnCollisionChannel)(ADBDPlayer *this);
/* 00000E28 */     void (__fastcall *OnInteractionZoneOverlap)(ADBDPlayer *this, UInteractionDefinition *, bool);
/* 00000E30 */     float (__fastcall *GetPercentMovementSpeed)(ADBDPlayer *this);
/* 00000E38 */     bool (__fastcall *IsRunning)(ADBDPlayer *this);
/* 00000E40 */     bool (__fastcall *IsStrafing)(ADBDPlayer *this);
/* 00000E48 */     void (__fastcall *SetInParadise)(ADBDPlayer *this, bool);
/* 00000E50 */     void (__fastcall *RequestStun)(ADBDPlayer *this, EStunType, ADBDPlayer *);
/* 00000E58 */     void (__fastcall *OnMadeLoudNoise)(ADBDPlayer *this);
/* 00000E60 */     void (__fastcall *OnStun)(ADBDPlayer *this, EStunType);
/* 00000E68 */     void (__fastcall *OnPickupStart)(ADBDPlayer *this, ADBDPlayer *);
/* 00000E70 */     void (__fastcall *OnPickupEnd)(ADBDPlayer *this, ADBDPlayer *);
/* 00000E78 */     void (__fastcall *OnPickedupStart)(ADBDPlayer *this, ADBDPlayer *);
/* 00000E80 */     void (__fastcall *OnPickedupEnd)(ADBDPlayer *this, ADBDPlayer *);
/* 00000E88 */     void (__fastcall *RotateToTargetPercent)(ADBDPlayer *this, FVector, float, float);
/* 00000E90 */     bool (__fastcall *CanBeSlashed)(ADBDPlayer *this);
/* 00000E98 */     void (__fastcall *AuthorityAttemptEscapeCarry)(ADBDPlayer *this, ACamperPlayer *);
/* 00000EA0 */     void (__fastcall *AuthorityFlashlighted)(ADBDPlayer *this, ADBDPlayer *);
/* 00000EA8 */     bool (__fastcall *IsCloaked)(ADBDPlayer *this);
/* 00000EB0 */     bool (__fastcall *IsInStalkMode)(ADBDPlayer *this);
/* 00000EB8 */     void (__fastcall *ResetCamera)(ADBDPlayer *this);
/* 00000EC0 */     void (__fastcall *SetMontageMode)(ADBDPlayer *this, bool);
/* 00000EC8 */     void (__fastcall *AuthorityFailInterruption)(ADBDPlayer *this, ADBDPlayer *);
/* 00000ED0 */     UInterruptionDefinition *(__fastcall *FindPossibleInterruption)(ADBDPlayer *this, const ADBDPlayer *const);
/* 00000ED8 */     bool (__fastcall *CanInterrupt)(ADBDPlayer *this, ADBDPlayer *);
/* 00000EE0 */     bool (__fastcall *CanPerformInterruption)(ADBDPlayer *this, const ADBDPlayer *const, const UInterruptionDefinition *const);
/* 00000EE8 */     bool (__fastcall *CanInteractWith)(ADBDPlayer *this, const UInteractionDefinition *);
/* 00000EF0 */     float (__fastcall *GetProgressToEscapeCarry)(ADBDPlayer *this, ADBDPlayer *);
/* 00000EF8 */     void (__fastcall *OnFinishedPlaying)(ADBDPlayer *this);
/* 00000F00 */     void (__fastcall *AuthorityHandleLoadoutOnSpawn)(ADBDPlayer *this);
/* 00000F08 */     void (__fastcall *Multicast_PlayMontage)(ADBDPlayer *this, FAnimationMontageDescriptor, float);
/* 00000F10 */     void (__fastcall *Multicast_LockOnTarget)(ADBDPlayer *this, ADBDPlayer *);
/* 00000F18 */     void (__fastcall *OnLockOnTarget)(ADBDPlayer *this, ADBDPlayer *);
/* 00000F20 */     void (__fastcall *Multicast_DamageTarget)(ADBDPlayer *this, ADBDPlayer *, EAttackType);
/* 00000F28 */     void (__fastcall *Multicast_AttackSubstate)(ADBDPlayer *this, EAttackSubstate);
/* 00000F30 */     void (__fastcall *Authority_ApplyDamageToTarget)(ADBDPlayer *this, ADBDPlayer *, bool);
/* 00000F38 */     float (__fastcall *GetAttackOpenTime)(ADBDPlayer *this, EAttackType);
/* 00000F40 */     float (__fastcall *GetAttackHittingTime)(ADBDPlayer *this, EAttackType);
/* 00000F48 */     float (__fastcall *GetAttackSucceedCooldownTime)(ADBDPlayer *this, EAttackType);
/* 00000F50 */     float (__fastcall *GetAttackMissCooldownTime)(ADBDPlayer *this, EAttackType);
/* 00000F58 */     float (__fastcall *GetAttackObstructCooldownTime)(ADBDPlayer *this, EAttackType);
/* 00000F60 */     float (__fastcall *GetAttackSnapDistance)(ADBDPlayer *this, EAttackType);
/* 00000F68 */     float (__fastcall *GetAttackHittingPercentDamageBegin)(ADBDPlayer *this);
/* 00000F70 */     float (__fastcall *GetAttackAngleTrackingSpeed)(ADBDPlayer *this);
/* 00000F78 */     float (__fastcall *GetAttackYawSpeed)(ADBDPlayer *this, EAttackType);
/* 00000F80 */     float (__fastcall *GetAttackSnapTime)(ADBDPlayer *this, EAttackType);
/* 00000F88 */     UCurveFloat *(__fastcall *GetAttackCurve)(ADBDPlayer *this, EAttackType, EAttackSubstate);
/* 00000F90 */     bool (__fastcall *CanAuthoritativePush)(ADBDPlayer *this);
/* 00000F98 */     bool (__fastcall *CanBeAuthoritativePushed)(ADBDPlayer *this);
/* 00000FA0 */     bool (__fastcall *IsAuthoritativeMoveable)(ADBDPlayer *this);
/* 00000FA8 */     void (__fastcall *SetInStalkMode)(ADBDPlayer *this, bool, bool);
/* 00000FB0 */     void (__fastcall *Authority_Blinded)(ADBDPlayer *this, EBlindType, float, AActor *);
/* 00000FB8 */     float (__fastcall *GetMaximumMovementSpeed)(ADBDPlayer *this);
/* 00000FC0 */     float (__fastcall *GetBaseFOV)(ADBDPlayer *this);
/* 00000FC8 */     void (__fastcall *CameraUpdated)(ADBDPlayer *this);
/* 00000FD0 */     void (__fastcall *OnBlindChargeEmptied)(ADBDPlayer *this);
/* 00000FD8 */     void (__fastcall *UpdateMontageMode)(ADBDPlayer *this);
/* 00000FE0 */     void (__fastcall *OnMoveForwardInput)(ADBDPlayer *this, float);
/* 00000FE8 */     void (__fastcall *OnMoveRightInput)(ADBDPlayer *this, float);
/* 00000FF0 */     void (__fastcall *AuthorityHandleOfferingsOnSpawn)(ADBDPlayer *this);
/* 00000FF8 */     float (__fastcall *GetSpeedModifier)(ADBDPlayer *this);
/* 00001000 */     void (__fastcall *InitializeTunableValues)(ADBDPlayer *this);
/* 00001008 */     bool (__fastcall *CanSlash)(ADBDPlayer *this, const ADBDPlayer *);
/* 00001010 */     void (__fastcall *SetIsCloaked)(ADBDPlayer *this, bool, bool);
/* 00001018 */     void (__fastcall *DoItemUsePressed)(ADBDPlayer *this);
/* 00001020 */     void (__fastcall *DoItemUseReleased)(ADBDPlayer *this);
/* 00001028 */     bool (__fastcall *CanCrouchGameSpecific)(ADBDPlayer *this);
/* 00001030 */     void (__fastcall *Broadcast_DamageTarget_Server)(ADBDPlayer *this, ADBDPlayer *, EAttackType);
/* 00001038 */     void (__fastcall *Broadcast_DamageTarget_Multicast)(ADBDPlayer *this, ADBDPlayer *, EAttackType);
/* 00001040 */     void (__fastcall *Broadcast_LockOnTarget_Server)(ADBDPlayer *this, ADBDPlayer *);
/* 00001048 */     void (__fastcall *Broadcast_LockOnTarget_Multicast)(ADBDPlayer *this, ADBDPlayer *);
/* 00001050 */     void (__fastcall *Broadcast_AttackSubstate_Server)(ADBDPlayer *this, EAttackSubstate);
/* 00001058 */     void (__fastcall *Broadcast_AttackSubstate_Multicast)(ADBDPlayer *this, EAttackSubstate);
/* 00001060 */     void (__fastcall *Broadcast_PlayMontage_Server)(ADBDPlayer *this, FAnimationMontageDescriptor, float);
/* 00001068 */     void (__fastcall *Broadcast_PlayMontage_Multicast)(ADBDPlayer *this, FAnimationMontageDescriptor, float);
/* 00001070 */     bool (__fastcall *IsValidImpl)(ADBDPlayer *this);
/* 00001078 */     void (__fastcall *Authority_SpawnPerk)(ADBDPlayer *this, FName, int);
/* 00001080 */     void (__fastcall *Authority_SpawnItemAddon)(ADBDPlayer *this, FName);
/* 00001088 */     bool (__fastcall *CanAttack_Internal)(ADBDPlayer *this);
/* 00001090 */     void (__fastcall *UpdateCameraReset)(ADBDPlayer *this, float);
/* 00001098 */     bool (__fastcall *Multicast_SetAuthoritativeMovementFlag_Validate)(ACamperPlayer *this, EAuthoritativeMovementFlag, bool);
/* 000010A0 */     void (__fastcall *Multicast_SetAuthoritativeMovementFlag_Implementation)(ACamperPlayer *this, EAuthoritativeMovementFlag, bool);
/* 000010A8 */     bool (__fastcall *Multicast_OnFailedStruggling_Validate)(ACamperPlayer *this, UInteractionDefinition *);
/* 000010B0 */     void (__fastcall *Multicast_OnFailedStruggling_Implementation)(ACamperPlayer *this, UInteractionDefinition *);
/* 000010B8 */     bool (__fastcall *Server_CheatEscaped_Validate)(ACamperPlayer *this);
/* 000010C0 */     void (__fastcall *Server_CheatEscaped_Implementation)(ACamperPlayer *this);
/* 000010C8 */     bool (__fastcall *Multicast_SetImmobilized_Validate)(ACamperPlayer *this, ECamperImmobilizeState);
/* 000010D0 */     void (__fastcall *Multicast_SetImmobilized_Implementation)(ACamperPlayer *this, ECamperImmobilizeState);
/* 000010D8 */     bool (__fastcall *Server_SetImmobilized_Validate)(ACamperPlayer *this, ECamperImmobilizeState);
/* 000010E0 */     void (__fastcall *Server_SetImmobilized_Implementation)(ACamperPlayer *this, ECamperImmobilizeState);
/* 000010E8 */     void (__fastcall *Broadcast_SendItemPreventRun_Multicast_Implementation)(ACamperPlayer *this, bool);
/* 000010F0 */     bool (__fastcall *Broadcast_SendItemPreventRun_Server_Validate)(ACamperPlayer *this, bool);
/* 000010F8 */     void (__fastcall *Broadcast_SendItemPreventRun_Server_Implementation)(ACamperPlayer *this, bool);
/* 00001100 */     void (__fastcall *Broadcast_SendRunInput_Multicast_Implementation)(ACamperPlayer *this, bool);
/* 00001108 */     bool (__fastcall *Broadcast_SendRunInput_Server_Validate)(ACamperPlayer *this, bool);
/* 00001110 */     void (__fastcall *Broadcast_SendRunInput_Server_Implementation)(ACamperPlayer *this, bool);
/* 00001118 */     void (__fastcall *Multicast_OnKO_Implementation)(ACamperPlayer *this);
/* 00001120 */     bool (__fastcall *Multicast_SetOnHookDrainToNextStage_Validate)(ACamperPlayer *this, bool);
/* 00001128 */     void (__fastcall *Multicast_SetOnHookDrainToNextStage_Implementation)(ACamperPlayer *this, bool);
/* 00001130 */     bool (__fastcall *Multicast_SetHookEscapeAutoSuccess_Validate)(ACamperPlayer *this, bool);
/* 00001138 */     void (__fastcall *Multicast_SetHookEscapeAutoSuccess_Implementation)(ACamperPlayer *this, bool);
/* 00001140 */     bool (__fastcall *Multicast_SetEnableHookSlashableZone_Validate)(ACamperPlayer *this, bool);
/* 00001148 */     void (__fastcall *Multicast_SetEnableHookSlashableZone_Implementation)(ACamperPlayer *this, bool);
/* 00001150 */     bool (__fastcall *Client_OnSlashedOutOfTrap_Validate)(ACamperPlayer *this, ADBDPlayer *);
/* 00001158 */     void (__fastcall *Client_OnSlashedOutOfTrap_Implementation)(ACamperPlayer *this, ADBDPlayer *);
/* 00001160 */     bool (__fastcall *Server_SendLeftRightMashedInput_Validate)(ACamperPlayer *this, bool);
/* 00001168 */     void (__fastcall *Server_SendLeftRightMashedInput_Implementation)(ACamperPlayer *this, bool);
/* 00001170 */     bool (__fastcall *Server_SendInteractMashedInput_Validate)(ACamperPlayer *this, bool);
/* 00001178 */     void (__fastcall *Server_SendInteractMashedInput_Implementation)(ACamperPlayer *this, bool);
/* 00001180 */     UDBDSpringArmComponent *(__fastcall *GetSpringArmComponent_Implementation)(ACamperPlayer *this);
/* 00001188 */     bool (__fastcall *Server_MakeInvulnerable_Validate)(ACamperPlayer *this);
/* 00001190 */     void (__fastcall *Server_MakeInvulnerable_Implementation)(ACamperPlayer *this);
/* 00001198 */     bool (__fastcall *Server_SetItemNormalizedEnergyLevel_Validate)(ACamperPlayer *this, float);
/* 000011A0 */     void (__fastcall *Server_SetItemNormalizedEnergyLevel_Implementation)(ACamperPlayer *this, float);
/* 000011A8 */     bool (__fastcall *Server_SetItemEnergyLevel_Validate)(ACamperPlayer *this, float);
/* 000011B0 */     void (__fastcall *Server_SetItemEnergyLevel_Implementation)(ACamperPlayer *this, float);
/* 000011B8 */     bool (__fastcall *Server_RemoveHealth_Validate)(ACamperPlayer *this);
/* 000011C0 */     void (__fastcall *Server_RemoveHealth_Implementation)(ACamperPlayer *this);
/* 000011C8 */     bool (__fastcall *Server_IncreaseHealth_Validate)(ACamperPlayer *this);
/* 000011D0 */     void (__fastcall *Server_IncreaseHealth_Implementation)(ACamperPlayer *this);
/* 000011D8 */     int (__fastcall *GetMadnessTierBPNative_Implementation)(ACamperPlayer *this);
/* 000011E0 */     bool (__fastcall *Server_SetOnHookDrainToNextStage_Validate)(ACamperPlayer *this, bool);
/* 000011E8 */     void (__fastcall *Server_SetOnHookDrainToNextStage_Implementation)(ACamperPlayer *this, bool);
/* 000011F0 */     bool (__fastcall *Server_SetHookEscapeAutoSuccess_Validate)(ACamperPlayer *this, bool);
/* 000011F8 */     void (__fastcall *Server_SetHookEscapeAutoSuccess_Implementation)(ACamperPlayer *this, bool);
/* 00001200 */     bool (__fastcall *Server_SetEnableHookSlashableZone_Validate)(ACamperPlayer *this, bool);
/* 00001208 */     void (__fastcall *Server_SetEnableHookSlashableZone_Implementation)(ACamperPlayer *this, bool);
/* 00001210 */     bool (__fastcall *Server_Kill_Validate)(ACamperPlayer *this, bool);
/* 00001218 */     void (__fastcall *Server_Kill_Implementation)(ACamperPlayer *this, bool);
/* 00001220 */     bool (__fastcall *Multicast_SetGuidedAction_Validate)(ACamperPlayer *this, ECamperGuidedAction);
/* 00001228 */     void (__fastcall *Multicast_SetGuidedAction_Implementation)(ACamperPlayer *this, ECamperGuidedAction);
/* 00001230 */     bool (__fastcall *Multicast_OnHealed_Validate)(ACamperPlayer *this);
/* 00001238 */     void (__fastcall *Multicast_OnHealed_Implementation)(ACamperPlayer *this);
/* 00001240 */     bool (__fastcall *IsBeingKilled)(ACamperPlayer *this);
/* 00001248 */     void (__fastcall *Broadcast_SendRunInput_Server)(ACamperPlayer *this, bool);
/* 00001250 */     void (__fastcall *Broadcast_SendRunInput_Multicast)(ACamperPlayer *this, bool);
/* 00001258 */     void (__fastcall *Broadcast_SendItemPreventRun_Server)(ACamperPlayer *this, bool);
/* 00001260 */     void (__fastcall *Broadcast_SendItemPreventRun_Multicast)(ACamperPlayer *this, bool);
/* 00001268 */ };

/* 00000000 */ struct /*VFT*/ INavAgentInterface_vtbl // sizeof=0x50
/* 00000000 */ {
/* 00000000 */     void (__fastcall *~INavAgentInterface)(INavAgentInterface *this);
/* 00000008 */     UObject *(__fastcall *_getUObject)(INavAgentInterface *this);
/* 00000010 */     const FNavAgentProperties *(__fastcall *GetNavAgentPropertiesRef)(INavAgentInterface *this);
/* 00000018 */     FVector *(__fastcall *GetNavAgentLocation)(INavAgentInterface *this, FVector *result);
/* 00000020 */     FVector *(__fastcall *GetMoveGoalOffset)(INavAgentInterface *this, FVector *result, AActor *);
/* 00000028 */     FVector *(__fastcall *GetMoveGoalOffset)(INavAgentInterface *this, FVector *result, const AActor *);
/* 00000030 */     void (__fastcall *GetMoveGoalReachTest)(INavAgentInterface *this, AActor *, const FVector *, FVector *, float *, float *);
/* 00000038 */     void (__fastcall *GetMoveGoalReachTest)(INavAgentInterface *this, const AActor *, const FVector *, FVector *, float *, float *);
/* 00000040 */     bool (__fastcall *ShouldPostponePathUpdates)(INavAgentInterface *this);
/* 00000048 */     bool (__fastcall *IsFollowingAPath)(INavAgentInterface *this);
/* 00000050 */ };

/* 00000000 */ struct /*VFT*/ IPerkOwnerInterface_vtbl // sizeof=0x38
/* 00000000 */ {
/* 00000000 */     void (__fastcall *~IPerkOwnerInterface)(IPerkOwnerInterface *this);
/* 00000008 */     UObject *(__fastcall *_getUObject)(IPerkOwnerInterface *this);
/* 00000010 */     void (__fastcall *AppendPerksTo)(IPerkOwnerInterface *this, TArray<UPerk *,FDefaultAllocator> *);
/* 00000018 */     void (__fastcall *AppendOfferingsTo)(IPerkOwnerInterface *this, TArray<FOffering,FDefaultAllocator> *);
/* 00000020 */     void (__fastcall *AppendStatusEffectsTo)(IPerkOwnerInterface *this, TArray<UStatusEffect *,FDefaultAllocator> *);
/* 00000028 */     TArray<UItemAddon *,FDefaultAllocator> *(__fastcall *GetItemAddons)(IPerkOwnerInterface *this, TArray<UItemAddon *,FDefaultAllocator> *result);
/* 00000030 */     TArray<UItemModifier *,FDefaultAllocator> *(__fastcall *GetItemModifiers)(IPerkOwnerInterface *this, TArray<UItemModifier *,FDefaultAllocator> *result);
/* 00000038 */ };

/* 00000000 */ struct /*VFT*/ IPerkManagerOwnerInterface_vtbl // sizeof=0x18
/* 00000000 */ {
/* 00000000 */     void (__fastcall *~IPerkManagerOwnerInterface)(IPerkManagerOwnerInterface *this);
/* 00000008 */     UObject *(__fastcall *_getUObject)(IPerkManagerOwnerInterface *this);
/* 00000010 */     UPerkManager *(__fastcall *GetPerkManager)(IPerkManagerOwnerInterface *this);
/* 00000018 */ };

/* 00000000 */ struct /*VFT*/ IAnimTagProvider_vtbl // sizeof=0x18
/* 00000000 */ {
/* 00000000 */     void (__fastcall *~IAnimTagProvider)(IAnimTagProvider *this);
/* 00000008 */     UObject *(__fastcall *_getUObject)(IAnimTagProvider *this);
/* 00000010 */     void (__fastcall *GetAnimTags)(IAnimTagProvider *this, TArray<FName,FDefaultAllocator> *);
/* 00000018 */ };
