class __base(UStillnessTrackerComponent, 0) UCamperStillnessTrackerComponent
{
/*0x0000*/  struct UCamperStillnessTrackerComponent::VTable* vtable;
/*0x0008*/  __inherited enum EObjectFlags UObjectBase::ObjectFlags;
/*0x000c*/  __inherited int32_t UObjectBase::InternalIndex;
/*0x0010*/  __inherited class UClass* UObjectBase::ClassPrivate;
/*0x0018*/  __inherited class FName UObjectBase::NamePrivate;
/*0x0020*/  __inherited class UObject* UObjectBase::OuterPrivate;
/*0x0028*/  __inherited struct IInterface_AssetUserData::VTable* IInterface_AssetUserData::vtable;
/*0x0030*/  __inherited struct FActorComponentTickFunction UActorComponent::PrimaryComponentTick;
/*0x0080*/  __inherited class TArray<FName, FDefaultAllocator> UActorComponent::ComponentTags;
/*0x0090*/  __inherited class TArray<UAssetUserData*, FDefaultAllocator> UActorComponent::AssetUserData;
/*0x00a0*/  __inherited union
            {
                uint32_t bRegistered;
                uint32_t bRenderStateCreated;
                uint32_t bPhysicsStateCreated;
                uint32_t bReplicates;
                uint32_t bNetAddressable;
                uint32_t bRenderStateDirty;
                uint32_t bRenderTransformDirty;
                uint32_t bRenderDynamicDataDirty;
                uint32_t bRoutedPostRename;
                uint32_t bAutoRegister;
                uint32_t bAllowReregistration;
                uint32_t bTickInEditor;
                uint32_t bNeverNeedsRenderUpdate;
                uint32_t bAllowConcurrentTick;
                uint32_t bAllowAnyoneToDestroyMe;
                uint32_t bCreatedByConstructionScript_DEPRECATED;
                uint32_t bInstanceComponent_DEPRECATED;
                uint32_t bAutoActivate;
                uint32_t bIsActive;
                uint32_t bEditableWhenInherited;
                uint32_t bNavigationRelevant;
                uint32_t bCanEverAffectNavigation;
                uint32_t bWantsInitializeComponent;
                uint32_t bWantsBeginPlay;
                uint32_t bHasBeenCreated;
                uint32_t bHasBeenInitialized;
                uint32_t bHasBegunPlay;
                uint32_t bIsBeingDestroyed;
                uint32_t bTickFunctionsRegistered;
                uint32_t MarkedForEndOfFrameUpdateState;
            } __bitfielda0;
/*0x00a4*/  __inherited enum EComponentCreationMethod UActorComponent::CreationMethod;
/*0x00a8*/  __inherited class AActor* UActorComponent::OwnerPrivate;
/*0x00b0*/  __inherited class TArray<FSimpleMemberReference, FDefaultAllocator> UActorComponent::UCSModifiedProperties;
/*0x00c0*/  __inherited class FActorComponentActivatedSignature UActorComponent::OnComponentActivated;
/*0x00d0*/  __inherited class FActorComponentDeactivateSignature UActorComponent::OnComponentDeactivated;
/*0x00e0*/  __inherited class UWorld* UActorComponent::WorldPrivate;
/*0x00e8*/  __inherited float UStillnessTrackerComponent::SpeedThreshold;
/*0x00ec*/  __inherited float UStillnessTrackerComponent::DistanceThreshold;
/*0x00f0*/  __inherited float UStillnessTrackerComponent::DistanceDecay;
/*0x00f4*/  __inherited bool UStillnessTrackerComponent::DecayWhileMoving;
/*0x00f8*/  __inherited float UStillnessTrackerComponent::StillnessThreshhold;
/*0x00fc*/  __inherited float UStillnessTrackerComponent::StillnessTimerLimit;
/*0x0100*/  __inherited float UStillnessTrackerComponent::DecaySpeedMultiplier;
/*0x0104*/  __inherited float UStillnessTrackerComponent::_stillness;
/*0x0108*/  __inherited float UStillnessTrackerComponent::_stillnessTimer;
/*0x010c*/  __inherited struct TWeakObjectPtr<ADBDPlayer, FWeakObjectPtr> UStillnessTrackerComponent::_trackedPlayer;
/*0x0114*/  __inherited struct FVector UStillnessTrackerComponent::_accumulatedDistance;
/*0x0120*/  class TArray<float, FDefaultAllocator> ExposerSpawnTimes;
/*0x0130*/  class TArray<float, FDefaultAllocator> ExposerDespawnTimes;
/*0x0140*/  float ChickenShitModifier;
/*0x0144*/  float LoudNoiseTime;
/*0x0148*/  struct FTimerHandle _exposerLoudNoiseTimer;
/*0x0150*/  bool _hasTriggered;
            __padding char _151[7];
/*0x0158*/  class TSubclassOf<ACamperExposerInstance> _exposerInstanceToSpawn;
/*0x0160*/  class TArray<ACamperExposerInstance*, FDefaultAllocator> _exposerInstances;
/*0x0170*/  class UExposerInteriorZoneComponent* _interiorZone;
};
