class __base(UDBDCharacterMovementComponent, 0) UCamperMovementComponent
{
/*0x0000*/  struct UCamperMovementComponent::VTable* vtable;
/*0x0008*/  __inherited enum EObjectFlags UObjectBase::ObjectFlags;
/*0x000c*/  __inherited int32_t UObjectBase::InternalIndex;
/*0x0010*/  __inherited class UClass* UObjectBase::ClassPrivate;
/*0x0018*/  __inherited class FName UObjectBase::NamePrivate;
/*0x0020*/  __inherited class UObject* UObjectBase::OuterPrivate;
/*0x0028*/  __inherited struct IInterface_AssetUserData::VTable* IInterface_AssetUserData::vtable;
/*0x0030*/  __inherited struct FActorComponentTickFunction UActorComponent::PrimaryComponentTick;
/*0x0080*/  __inherited class TArray<FName, FDefaultAllocator> UActorComponent::ComponentTags;
/*0x0090*/  __inherited class TArray<UAssetUserData*, FDefaultAllocator> UActorComponent::AssetUserData;
/*0x00a0*/  __inherited union
            {
                uint32_t bRegistered;
                uint32_t bRenderStateCreated;
                uint32_t bPhysicsStateCreated;
                uint32_t bReplicates;
                uint32_t bNetAddressable;
                uint32_t bRenderStateDirty;
                uint32_t bRenderTransformDirty;
                uint32_t bRenderDynamicDataDirty;
                uint32_t bRoutedPostRename;
                uint32_t bAutoRegister;
                uint32_t bAllowReregistration;
                uint32_t bTickInEditor;
                uint32_t bNeverNeedsRenderUpdate;
                uint32_t bAllowConcurrentTick;
                uint32_t bAllowAnyoneToDestroyMe;
                uint32_t bCreatedByConstructionScript_DEPRECATED;
                uint32_t bInstanceComponent_DEPRECATED;
                uint32_t bAutoActivate;
                uint32_t bIsActive;
                uint32_t bEditableWhenInherited;
                uint32_t bNavigationRelevant;
                uint32_t bCanEverAffectNavigation;
                uint32_t bWantsInitializeComponent;
                uint32_t bWantsBeginPlay;
                uint32_t bHasBeenCreated;
                uint32_t bHasBeenInitialized;
                uint32_t bHasBegunPlay;
                uint32_t bIsBeingDestroyed;
                uint32_t bTickFunctionsRegistered;
                uint32_t MarkedForEndOfFrameUpdateState;
            } __bitfielda0;
/*0x00a4*/  __inherited enum EComponentCreationMethod UActorComponent::CreationMethod;
/*0x00a8*/  __inherited class AActor* UActorComponent::OwnerPrivate;
/*0x00b0*/  __inherited class TArray<FSimpleMemberReference, FDefaultAllocator> UActorComponent::UCSModifiedProperties;
/*0x00c0*/  __inherited class FActorComponentActivatedSignature UActorComponent::OnComponentActivated;
/*0x00d0*/  __inherited class FActorComponentDeactivateSignature UActorComponent::OnComponentDeactivated;
/*0x00e0*/  __inherited class UWorld* UActorComponent::WorldPrivate;
/*0x00e8*/  __inherited class USceneComponent* UMovementComponent::UpdatedComponent;
/*0x00f0*/  __inherited class UPrimitiveComponent* UMovementComponent::UpdatedPrimitive;
/*0x00f8*/  __inherited enum EMoveComponentFlags UMovementComponent::MoveComponentFlags;
/*0x00fc*/  __inherited struct FVector UMovementComponent::Velocity;
/*0x0108*/  __inherited union
            {
                uint32_t bConstrainToPlane;
                uint32_t bSnapToPlaneAtStart;
            } __bitfield108;
/*0x010c*/  __inherited enum EPlaneConstraintAxisSetting UMovementComponent::PlaneConstraintAxisSetting;
            __padding char _10d[3];
/*0x0110*/  __inherited struct FVector UMovementComponent::PlaneConstraintNormal;
/*0x011c*/  __inherited struct FVector UMovementComponent::PlaneConstraintOrigin;
/*0x0128*/  __inherited union
            {
                uint32_t bUpdateOnlyIfRendered;
                uint32_t bAutoUpdateTickRegistration;
                uint32_t bTickBeforeOwner;
                uint32_t bAutoRegisterUpdatedComponent;
            } __bitfield128;
/*0x012c*/  __inherited bool UMovementComponent::bInOnRegister;
/*0x012d*/  __inherited bool UMovementComponent::bInInitializeComponent;
            __padding char _12e[2];
/*0x0130*/  __inherited struct FNavAgentProperties UNavMovementComponent::NavAgentProps;
/*0x0150*/  __inherited float UNavMovementComponent::FixedPathBrakingDistance;
/*0x0154*/  __inherited union
            {
                uint32_t bUpdateNavAgentWithOwnersCollision;
                uint32_t bUseAccelerationForPaths;
                uint32_t bUseFixedBrakingDistanceForPaths;
                uint32_t bStopMovementAbortPaths;
            } __bitfield154;
/*0x0158*/  __inherited struct FMovementProperties UNavMovementComponent::MovementState;
/*0x015c*/  __inherited struct TWeakObjectPtr<UPathFollowingComponent, FWeakObjectPtr> UNavMovementComponent::PathFollowingComp;
/*0x0168*/  __inherited class APawn* UPawnMovementComponent::PawnOwner;
/*0x0170*/  __inherited struct UWheeledVehicleMovementComponent::IRVOAvoidanceInterface::VTable* IRVOAvoidanceInterface::vtable;
/*0x0178*/  __inherited struct INetworkPredictionInterface::VTable* INetworkPredictionInterface::vtable;
/*0x0180*/  __inherited class ACharacter* UCharacterMovementComponent::CharacterOwner;
/*0x0188*/  __inherited float UCharacterMovementComponent::GravityScale;
/*0x018c*/  __inherited float UCharacterMovementComponent::MaxStepHeight;
/*0x0190*/  __inherited float UCharacterMovementComponent::JumpZVelocity;
/*0x0194*/  __inherited float UCharacterMovementComponent::JumpOffJumpZFactor;
/*0x0198*/  __inherited float UCharacterMovementComponent::WalkableFloorAngle;
/*0x019c*/  __inherited float UCharacterMovementComponent::WalkableFloorZ;
/*0x01a0*/  __inherited class TEnumAsByte<enum EMovementMode> UCharacterMovementComponent::MovementMode;
/*0x01a1*/  __inherited bool UCharacterMovementComponent::CustomMovementMode;
            __padding char _1a2[2];
/*0x01a4*/  __inherited struct FVector UCharacterMovementComponent::OldBaseLocation;
/*0x01b0*/  __inherited struct FQuat UCharacterMovementComponent::OldBaseQuat;
/*0x01c0*/  __inherited float UCharacterMovementComponent::GroundFriction;
/*0x01c4*/  __inherited float UCharacterMovementComponent::MaxWalkSpeed;
/*0x01c8*/  __inherited float UCharacterMovementComponent::MaxWalkSpeedCrouched;
/*0x01cc*/  __inherited float UCharacterMovementComponent::MaxSwimSpeed;
/*0x01d0*/  __inherited float UCharacterMovementComponent::MaxFlySpeed;
/*0x01d4*/  __inherited float UCharacterMovementComponent::MaxCustomMovementSpeed;
/*0x01d8*/  __inherited float UCharacterMovementComponent::MaxAcceleration;
/*0x01dc*/  __inherited float UCharacterMovementComponent::BrakingFrictionFactor;
/*0x01e0*/  __inherited float UCharacterMovementComponent::BrakingFriction;
/*0x01e4*/  __inherited union
            {
                uint32_t bUseSeparateBrakingFriction;
            } __bitfield1e4;
/*0x01e8*/  __inherited float UCharacterMovementComponent::BrakingDecelerationWalking;
/*0x01ec*/  __inherited float UCharacterMovementComponent::BrakingDecelerationFalling;
/*0x01f0*/  __inherited float UCharacterMovementComponent::BrakingDecelerationSwimming;
/*0x01f4*/  __inherited float UCharacterMovementComponent::BrakingDecelerationFlying;
/*0x01f8*/  __inherited float UCharacterMovementComponent::AirControl;
/*0x01fc*/  __inherited float UCharacterMovementComponent::AirControlBoostMultiplier;
/*0x0200*/  __inherited float UCharacterMovementComponent::AirControlBoostVelocityThreshold;
/*0x0204*/  __inherited float UCharacterMovementComponent::FallingLateralFriction;
/*0x0208*/  __inherited float UCharacterMovementComponent::CrouchedHalfHeight;
/*0x020c*/  __inherited float UCharacterMovementComponent::Buoyancy;
/*0x0210*/  __inherited float UCharacterMovementComponent::PerchRadiusThreshold;
/*0x0214*/  __inherited float UCharacterMovementComponent::PerchAdditionalHeight;
/*0x0218*/  __inherited struct FRotator UCharacterMovementComponent::RotationRate;
/*0x0224*/  __inherited union
            {
                uint32_t bUseControllerDesiredRotation;
                uint32_t bOrientRotationToMovement;
                uint32_t bMovementInProgress;
                uint32_t bEnableScopedMovementUpdates;
                uint32_t bForceMaxAccel;
                uint32_t bRunPhysicsWithNoController;
                uint32_t bForceNextFloorCheck;
                uint32_t bShrinkProxyCapsule;
                uint32_t bCanWalkOffLedges;
                uint32_t bCanWalkOffLedgesWhenCrouching;
                uint32_t bNetworkSmoothingComplete;
                uint32_t bDeferUpdateMoveComponent;
            } __bitfield224;
/*0x0228*/  __inherited class USceneComponent* UCharacterMovementComponent::DeferredUpdatedMoveComponent;
/*0x0230*/  __inherited float UCharacterMovementComponent::MaxOutOfWaterStepHeight;
/*0x0234*/  __inherited float UCharacterMovementComponent::OutofWaterZ;
/*0x0238*/  __inherited float UCharacterMovementComponent::Mass;
/*0x023c*/  __inherited bool UCharacterMovementComponent::bEnablePhysicsInteraction;
/*0x023d*/  __inherited bool UCharacterMovementComponent::bTouchForceScaledToMass;
/*0x023e*/  __inherited bool UCharacterMovementComponent::bPushForceScaledToMass;
/*0x023f*/  __inherited bool UCharacterMovementComponent::bPushForceUsingZOffset;
/*0x0240*/  __inherited bool UCharacterMovementComponent::bScalePushForceToVelocity;
/*0x0244*/  __inherited float UCharacterMovementComponent::StandingDownwardForceScale;
/*0x0248*/  __inherited float UCharacterMovementComponent::InitialPushForceFactor;
/*0x024c*/  __inherited float UCharacterMovementComponent::PushForceFactor;
/*0x0250*/  __inherited float UCharacterMovementComponent::PushForcePointZOffsetFactor;
/*0x0254*/  __inherited float UCharacterMovementComponent::TouchForceFactor;
/*0x0258*/  __inherited float UCharacterMovementComponent::MinTouchForce;
/*0x025c*/  __inherited float UCharacterMovementComponent::MaxTouchForce;
/*0x0260*/  __inherited float UCharacterMovementComponent::RepulsionForce;
/*0x0264*/  __inherited union
            {
                uint32_t bForceBraking_DEPRECATED;
            } __bitfield264;
/*0x0268*/  __inherited float UCharacterMovementComponent::CrouchedSpeedMultiplier_DEPRECATED;
/*0x026c*/  __inherited float UCharacterMovementComponent::UpperImpactNormalScale_DEPRECATED;
/*0x0270*/  __inherited struct FVector UCharacterMovementComponent::Acceleration;
/*0x027c*/  __inherited struct FVector UCharacterMovementComponent::LastUpdateLocation;
            __padding char _288[8];
/*0x0290*/  __inherited struct FQuat UCharacterMovementComponent::LastUpdateRotation;
/*0x02a0*/  __inherited struct FVector UCharacterMovementComponent::LastUpdateVelocity;
/*0x02ac*/  __inherited float UCharacterMovementComponent::ServerLastTransformUpdateTimeStamp;
/*0x02b0*/  __inherited struct FVector UCharacterMovementComponent::PendingImpulseToApply;
/*0x02bc*/  __inherited struct FVector UCharacterMovementComponent::PendingForceToApply;
/*0x02c8*/  __inherited float UCharacterMovementComponent::AnalogInputModifier;
/*0x02cc*/  __inherited float UCharacterMovementComponent::LastStuckWarningTime;
/*0x02d0*/  __inherited uint32_t UCharacterMovementComponent::StuckWarningCountSinceNotify;
/*0x02d4*/  __inherited float UCharacterMovementComponent::MaxSimulationTimeStep;
/*0x02d8*/  __inherited int32_t UCharacterMovementComponent::MaxSimulationIterations;
/*0x02dc*/  __inherited float UCharacterMovementComponent::MaxDepenetrationWithGeometry;
/*0x02e0*/  __inherited float UCharacterMovementComponent::MaxDepenetrationWithGeometryAsProxy;
/*0x02e4*/  __inherited float UCharacterMovementComponent::MaxDepenetrationWithPawn;
/*0x02e8*/  __inherited float UCharacterMovementComponent::MaxDepenetrationWithPawnAsProxy;
/*0x02ec*/  __inherited float UCharacterMovementComponent::NetworkSimulatedSmoothLocationTime;
/*0x02f0*/  __inherited float UCharacterMovementComponent::NetworkSimulatedSmoothRotationTime;
/*0x02f4*/  __inherited float UCharacterMovementComponent::ListenServerNetworkSimulatedSmoothLocationTime;
/*0x02f8*/  __inherited float UCharacterMovementComponent::ListenServerNetworkSimulatedSmoothRotationTime;
/*0x02fc*/  __inherited float UCharacterMovementComponent::NetworkMaxSmoothUpdateDistance;
/*0x0300*/  __inherited float UCharacterMovementComponent::NetworkNoSmoothUpdateDistance;
/*0x0304*/  __inherited enum ENetworkSmoothingMode UCharacterMovementComponent::NetworkSmoothingMode;
/*0x0308*/  __inherited float UCharacterMovementComponent::LedgeCheckThreshold;
/*0x030c*/  __inherited float UCharacterMovementComponent::JumpOutOfWaterPitch;
/*0x0310*/  __inherited struct FFindFloorResult UCharacterMovementComponent::CurrentFloor;
/*0x03a8*/  __inherited class TEnumAsByte<enum EMovementMode> UCharacterMovementComponent::DefaultLandMovementMode;
/*0x03a9*/  __inherited class TEnumAsByte<enum EMovementMode> UCharacterMovementComponent::DefaultWaterMovementMode;
/*0x03aa*/  __inherited class TEnumAsByte<enum EMovementMode> UCharacterMovementComponent::GroundMovementMode;
            __padding char _3ab[1];
/*0x03ac*/  __inherited union
            {
                uint32_t bMaintainHorizontalGroundVelocity;
                uint32_t bImpartBaseVelocityX;
                uint32_t bImpartBaseVelocityY;
                uint32_t bImpartBaseVelocityZ;
                uint32_t bImpartBaseAngularVelocity;
                uint32_t bJustTeleported;
                uint32_t bNetworkUpdateReceived;
                uint32_t bNetworkMovementModeChanged;
                uint32_t bIgnoreClientMovementErrorChecksAndCorrection;
                uint32_t bNotifyApex;
                uint32_t bCheatFlying;
                uint32_t bWantsToCrouch;
                uint32_t bCrouchMaintainsBaseLocation;
                uint32_t bIgnoreBaseRotation;
                uint32_t bFastAttachedMove;
                uint32_t bAlwaysCheckFloor;
                uint32_t bUseFlatBaseForFloorChecks;
                uint32_t bPerformingJumpOff;
                uint32_t bWantsToLeaveNavWalking;
                uint32_t bUseRVOAvoidance;
                uint32_t bRequestedMoveUseAcceleration;
                uint32_t bHasRequestedVelocity;
                uint32_t bRequestedMoveWithMaxSpeed;
                uint32_t bWasAvoidanceUpdated;
                uint32_t bUseRVOPostProcess;
                uint32_t bDeferUpdateBasedMovement;
                uint32_t bProjectNavMeshWalking;
                uint32_t bProjectNavMeshOnBothWorldChannels;
            } __bitfield3ac;
/*0x03b0*/  __inherited struct FVector UCharacterMovementComponent::AvoidanceLockVelocity;
/*0x03bc*/  __inherited float UCharacterMovementComponent::AvoidanceLockTimer;
/*0x03c0*/  __inherited float UCharacterMovementComponent::AvoidanceConsiderationRadius;
/*0x03c4*/  __inherited struct FVector UCharacterMovementComponent::RequestedVelocity;
/*0x03d0*/  __inherited int32_t UCharacterMovementComponent::AvoidanceUID;
/*0x03d4*/  __inherited struct FNavAvoidanceMask UCharacterMovementComponent::AvoidanceGroup;
/*0x03d8*/  __inherited struct FNavAvoidanceMask UCharacterMovementComponent::GroupsToAvoid;
/*0x03dc*/  __inherited struct FNavAvoidanceMask UCharacterMovementComponent::GroupsToIgnore;
/*0x03e0*/  __inherited float UCharacterMovementComponent::AvoidanceWeight;
/*0x03e4*/  __inherited struct FVector UCharacterMovementComponent::PendingLaunchVelocity;
/*0x03f0*/  __inherited struct FNavLocation UCharacterMovementComponent::CachedNavLocation;
/*0x0408*/  __inherited struct FHitResult UCharacterMovementComponent::CachedProjectedNavMeshHitResult;
/*0x0490*/  __inherited float UCharacterMovementComponent::NavMeshProjectionInterval;
/*0x0494*/  __inherited float UCharacterMovementComponent::NavMeshProjectionTimer;
/*0x0498*/  __inherited float UCharacterMovementComponent::NavMeshProjectionInterpSpeed;
/*0x049c*/  __inherited float UCharacterMovementComponent::NavMeshProjectionHeightScaleUp;
/*0x04a0*/  __inherited float UCharacterMovementComponent::NavMeshProjectionHeightScaleDown;
            __padding char _4a4[4];
/*0x04a8*/  __inherited struct FCharacterMovementComponentPostPhysicsTickFunction UCharacterMovementComponent::PostPhysicsTickFunction;
/*0x04f8*/  __inherited class FNetworkPredictionData_Client_Character* UCharacterMovementComponent::ClientPredictionData;
/*0x0500*/  __inherited class FNetworkPredictionData_Server_Character* UCharacterMovementComponent::ServerPredictionData;
/*0x0508*/  __inherited float UCharacterMovementComponent::MinTimeBetweenTimeStampResets;
            __padding char _50c[4];
/*0x0510*/  __inherited struct FRootMotionSourceGroup UCharacterMovementComponent::CurrentRootMotion;
/*0x0610*/  __inherited class TArray<FRootMotionServerToLocalIDMapping, TInlineAllocator<16, FDefaultAllocator>> UCharacterMovementComponent::RootMotionIDMappings;
/*0x06a0*/  __inherited struct FRootMotionMovementParams UCharacterMovementComponent::RootMotionParams;
/*0x06e0*/  __inherited struct FVector UCharacterMovementComponent::AnimRootMotionVelocity;
/*0x06ec*/  __inherited bool UCharacterMovementComponent::bWasSimulatingRootMotion;
/*0x06f0*/  __inherited float UDBDCharacterMovementComponent::ProjectedWallSlidingFactor;
/*0x06f4*/  __inherited float UDBDCharacterMovementComponent::RandomInputFrontMultiplier;
/*0x06f8*/  __inherited float UDBDCharacterMovementComponent::RandomInputSideMultiplier;
/*0x06fc*/  __inherited float UDBDCharacterMovementComponent::RandomInputBackMultiplier;
/*0x0700*/  __inherited class UCurveFloat* UDBDCharacterMovementComponent::OnHitMaxSpeedCurve;
/*0x0708*/  __inherited class UCurveFloat* UDBDCharacterMovementComponent::OnSprintMaxSpeedCurve;
/*0x0710*/  __inherited class FName UDBDCharacterMovementComponent::SprintEffector;
/*0x0718*/  __inherited struct FDBDTimer UDBDCharacterMovementComponent::_hitSpeedBoostTimer;
/*0x0738*/  __inherited struct FDBDTimer UDBDCharacterMovementComponent::_sprintSpeedBoostDurationTimer;
/*0x0758*/  __inherited bool UDBDCharacterMovementComponent::_allowNavigation;
/*0x0759*/  __inherited class PerlinNoise2D UDBDCharacterMovementComponent::_perlinNoise;
/*0x075c*/  __inherited float UDBDCharacterMovementComponent::_randomInputTime;
/*0x0760*/  __inherited float UDBDCharacterMovementComponent::_randomInputAmplitude;
/*0x0768*/  __inherited class UCapsuleComponent* UDBDCharacterMovementComponent::_movementModifierDetector;
/*0x0770*/  __inherited class AMovementModifierActor* UDBDCharacterMovementComponent::_movementModifierActor;
/*0x0778*/  float MaxRunSpeed;
/*0x077с*/  float MaxRunSpeedFatigued;
/*0x0780*/  float MaxRunSpeedInjured;
/*0x0784*/  float MaxWalkSpeedInjured;
/*0x0788*/  float MaxDashAcceleration;
};
