/* 00000000 */ struct /*VFT*/ UCamperStateMachine_vtbl // sizeof=0x370
/* 00000000 */ {
/* 00000000 */     void (__fastcall *~UObject)(struct UObject *this);
/* 00000008 */     void (__fastcall *RegisterDependencies)(struct UObject *this);
/* 00000010 */     void (__fastcall *DeferredRegister)(struct UObject *this, UClass *, const wchar_t *, const wchar_t *);
/* 00000018 */     bool (__fastcall *CanBeClusterRoot)(struct UObject *this);
/* 00000020 */     bool (__fastcall *CanBeInCluster)(struct UObject *this);
/* 00000028 */     void (__fastcall *CreateCluster)(struct UObject *this);
/* 00000030 */     void (__fastcall *AddToCluster)(struct UObject *this, UObjectBaseUtility *);
/* 00000038 */     FString *(__fastcall *GetDetailedInfoInternal)(UObject *this, FString *result);
/* 00000040 */     void (__fastcall *PostInitProperties)(UObject *this);
/* 00000048 */     bool (__fastcall *PreSaveRoot)(UObject *this, const wchar_t *, TArray<FString,FDefaultAllocator> *);
/* 00000050 */     void (__fastcall *PostSaveRoot)(UObject *this, bool);
/* 00000058 */     void (__fastcall *PreSave)(UObject *this, const ITargetPlatform *);
/* 00000060 */     bool (__fastcall *Modify)(UObject *this, bool);
/* 00000068 */     void (__fastcall *PostLoad)(UObject *this);
/* 00000070 */     void (__fastcall *PostLoadSubobjects)(UObject *this, FObjectInstancingGraph *);
/* 00000078 */     void (__fastcall *BeginDestroy)(UObject *this);
/* 00000080 */     bool (__fastcall *IsReadyForFinishDestroy)(UObject *this);
/* 00000088 */     void (__fastcall *FinishDestroy)(UObject *this);
/* 00000090 */     void (__fastcall *Serialize)(UObject *this, FArchive *);
/* 00000098 */     void (__fastcall *ShutdownAfterError)(UObject *this);
/* 000000A0 */     void (__fastcall *PostInterpChange)(UObject *this, UProperty *);
/* 000000A8 */     void (__fastcall *PostRename)(UObject *this, UObject *, const FName);
/* 000000B0 */     void (__fastcall *PostDuplicate)(UObject *this, bool);
/* 000000B8 */     bool (__fastcall *NeedsLoadForClient)(UObject *this);
/* 000000C0 */     bool (__fastcall *NeedsLoadForServer)(UObject *this);
/* 000000C8 */     bool (__fastcall *NeedsLoadForEditorGame)(UObject *this);
/* 000000D0 */     bool (__fastcall *IsPostLoadThreadSafe)(UObject *this);
/* 000000D8 */     void (__fastcall *ExportCustomProperties)(UObject *this, FOutputDevice *, unsigned int);
/* 000000E0 */     void (__fastcall *ImportCustomProperties)(UObject *this, const wchar_t *, FFeedbackContext *);
/* 000000E8 */     void (__fastcall *PostEditImport)(UObject *this);
/* 000000F0 */     void (__fastcall *PostReloadConfig)(UObject *this, UProperty *);
/* 000000F8 */     bool (__fastcall *Rename)(UObject *this, const wchar_t *, UObject *, unsigned int);
/* 00000100 */     FString *(__fastcall *GetDesc)(UObject *this, FString *result);
/* 00000108 */     UWorld *(__fastcall *GetWorld)(UObject *this);
/* 00000110 */     bool (__fastcall *GetNativePropertyValues)(UObject *this, TMap<FString,FString,FDefaultSetAllocator,TDefaultMapKeyFuncs<FString,FString,0> > *, unsigned int);
/* 00000118 */     unsigned __int64 (__fastcall *GetResourceSize)(UObject *this, EResourceSizeMode::Type);
/* 00000120 */     FName *(__fastcall *GetExporterName)(UObject *this, FName *result);
/* 00000128 */     FRestoreForUObjectOverwrite *(__fastcall *GetRestoreForUObjectOverwrite)(UObject *this);
/* 00000130 */     bool (__fastcall *AreNativePropertiesIdenticalTo)(UObject *this, UObject *);
/* 00000138 */     void (__fastcall *GetAssetRegistryTags)(UObject *this, TArray<UObject::FAssetRegistryTag,FDefaultAllocator> *);
/* 00000140 */     bool (__fastcall *IsAsset)(UObject *this);
/* 00000148 */     bool (__fastcall *IsLocalizedResource)(UObject *this);
/* 00000150 */     bool (__fastcall *IsSafeForRootSet)(UObject *this);
/* 00000158 */     void (__fastcall *TagSubobjects)(UObject *this, EObjectFlags);
/* 00000160 */     void (__fastcall *GetLifetimeReplicatedProps)(UObject *this, TArray<FLifetimeProperty,FDefaultAllocator> *);
/* 00000168 */     bool (__fastcall *IsNameStableForNetworking)(UObject *this);
/* 00000170 */     bool (__fastcall *IsFullNameStableForNetworking)(UObject *this);
/* 00000178 */     bool (__fastcall *IsSupportedForNetworking)(UObject *this);
/* 00000180 */     void (__fastcall *GetSubobjectsWithStableNamesForNetworking)(UObject *this, TArray<UObject *,FDefaultAllocator> *);
/* 00000188 */     void (__fastcall *PreNetReceive)(UObject *this);
/* 00000190 */     void (__fastcall *PostNetReceive)(UObject *this);
/* 00000198 */     void (__fastcall *PostRepNotifies)(UObject *this);
/* 000001A0 */     void (__fastcall *PreDestroyFromReplication)(UObject *this);
/* 000001A8 */     void (__fastcall *ProcessEvent)(UObject *this, UFunction *, void *);
/* 000001B0 */     int (__fastcall *GetFunctionCallspace)(UObject *this, UFunction *, void *, FFrame *);
/* 000001B8 */     bool (__fastcall *CallRemoteFunction)(UObject *this, UFunction *, void *, FOutParmRec *, FFrame *);
/* 000001C0 */     bool (__fastcall *ProcessConsoleExec)(UObject *this, const wchar_t *, FOutputDevice *, UObject *);
/* 000001C8 */     UClass *(__fastcall *RegenerateClass)(UObject *this, UClass *, UObject *, TArray<UObject *,FDefaultAllocator> *);
/* 000001D0 */     void (__fastcall *MarkAsEditorOnlySubobject)(UObject *this);
/* 000001D8 */     bool (__fastcall *CheckDefaultSubobjectsInternal)(UObject *this);
/* 000001E0 */     void (__fastcall *Activate)(UActorComponent *this, bool);
/* 000001E8 */     void (__fastcall *Deactivate)(UActorComponent *this);
/* 000001F0 */     void (__fastcall *SetActive)(UActorComponent *this, bool, bool);
/* 000001F8 */     void (__fastcall *ToggleActive)(UActorComponent *this);
/* 00000200 */     bool (__fastcall *IsActive)(UActorComponent *this);
/* 00000208 */     bool (__fastcall *ReplicateSubobjects)(UActorComponent *this, UActorChannel *, FOutBunch *, FReplicationFlags *);
/* 00000210 */     void (__fastcall *PreReplication)(UActorComponent *this, IRepChangedPropertyTracker *);
/* 00000218 */     bool (__fastcall *GetComponentClassCanReplicate)(UActorComponent *this);
/* 00000220 */     bool (__fastcall *IsEditorOnly)(UActorComponent *this);
/* 00000228 */     bool (__fastcall *ShouldActivate)(UActorComponent *this);
/* 00000230 */     void (__fastcall *OnRegister)(UActorComponent *this);
/* 00000238 */     void (__fastcall *OnUnregister)(UActorComponent *this);
/* 00000240 */     bool (__fastcall *ShouldCreateRenderState)(UActorComponent *this);
/* 00000248 */     void (__fastcall *CreateRenderState_Concurrent)(UActorComponent *this);
/* 00000250 */     void (__fastcall *SendRenderTransform_Concurrent)(UActorComponent *this);
/* 00000258 */     void (__fastcall *SendRenderDynamicData_Concurrent)(UActorComponent *this);
/* 00000260 */     void (__fastcall *DestroyRenderState_Concurrent)(UActorComponent *this);
/* 00000268 */     void (__fastcall *OnCreatePhysicsState)(UActorComponent *this);
/* 00000270 */     void (__fastcall *OnDestroyPhysicsState)(UActorComponent *this);
/* 00000278 */     bool (__fastcall *ShouldCreatePhysicsState)(UActorComponent *this);
/* 00000280 */     bool (__fastcall *HasValidPhysicsState)(UActorComponent *this);
/* 00000288 */     void (__fastcall *RegisterComponentTickFunctions)(UActorComponent *this, bool);
/* 00000290 */     void (__fastcall *InitializeComponent)(UActorComponent *this);
/* 00000298 */     void (__fastcall *BeginPlay)(UActorComponent *this);
/* 000002A0 */     void (__fastcall *EndPlay)(UActorComponent *this, const EEndPlayReason::Type);
/* 000002A8 */     void (__fastcall *UninitializeComponent)(UActorComponent *this);
/* 000002B0 */     void (__fastcall *TickComponent)(UActorComponent *this, float, ELevelTick, FActorComponentTickFunction *);
/* 000002B8 */     void (__fastcall *SetComponentTickEnabled)(UActorComponent *this, bool);
/* 000002C0 */     void (__fastcall *SetComponentTickEnabledAsync)(UActorComponent *this, bool);
/* 000002C8 */     void (__fastcall *InvalidateLightingCacheDetailed)(UActorComponent *this, bool, bool);
/* 000002D0 */     void (__fastcall *UpdateComponentToWorld)(UActorComponent *this, EUpdateTransformFlags, ETeleportType);
/* 000002D8 */     bool (__fastcall *RequiresGameThreadEndOfFrameUpdates)(UActorComponent *this);
/* 000002E0 */     bool (__fastcall *RequiresGameThreadEndOfFrameRecreate)(UActorComponent *this);
/* 000002E8 */     void (__fastcall *OnActorEnableCollisionChanged)(UActorComponent *this);
/* 000002F0 */     FString *(__fastcall *GetReadableName)(UActorComponent *this, FString *result);
/* 000002F8 */     const UObject *(__fastcall *AdditionalStatObject)(UActorComponent *this);
/* 00000300 */     FActorComponentInstanceData *(__fastcall *GetComponentInstanceData)(UActorComponent *this);
/* 00000308 */     void (__fastcall *DestroyComponent)(UActorComponent *this, bool);
/* 00000310 */     void (__fastcall *OnComponentCreated)(UActorComponent *this);
/* 00000318 */     void (__fastcall *OnComponentDestroyed)(UActorComponent *this, bool);
/* 00000320 */     void (__fastcall *AddTickPrerequisiteActor)(UActorComponent *this, AActor *);
/* 00000328 */     void (__fastcall *AddTickPrerequisiteComponent)(UActorComponent *this, UActorComponent *);
/* 00000330 */     void (__fastcall *RemoveTickPrerequisiteActor)(UActorComponent *this, AActor *);
/* 00000338 */     void (__fastcall *RemoveTickPrerequisiteComponent)(UActorComponent *this, UActorComponent *);
/* 00000340 */     void (__fastcall *ApplyWorldOffset)(UActorComponent *this, const FVector *, bool);
/* 00000348 */     bool (__fastcall *IsNavigationRelevant)(UActorComponent *this);
/* 00000350 */     bool (__fastcall *Server_SetStateStack_Validate)(UStateMachine *this, const TArray<unsigned short,FDefaultAllocator> *);
/* 00000358 */     void (__fastcall *Server_SetStateStack_Implementation)(UStateMachine *this, const TArray<unsigned short,FDefaultAllocator> *);
/* 00000360 */     bool (__fastcall *Multicast_SetStateStack_Validate)(UStateMachine *this, const TArray<unsigned short,FDefaultAllocator> *);
/* 00000368 */     void (__fastcall *Multicast_SetStateStack_Implementation)(UStateMachine *this, const TArray<unsigned short,FDefaultAllocator> *);
/* 00000370 */ };

/* 00000000 */ struct /*VFT*/ IInterface_AssetUserData_vtbl // sizeof=0x30
/* 00000000 */ {
/* 00000000 */     void (__fastcall *~IInterface_AssetUserData)(IInterface_AssetUserData *this);
/* 00000008 */     UObject *(__fastcall *_getUObject)(IInterface_AssetUserData *this);
/* 00000010 */     void (__fastcall *AddAssetUserData)(IInterface_AssetUserData *this, UAssetUserData *);
/* 00000018 */     UAssetUserData *(__fastcall *GetAssetUserDataOfClass)(IInterface_AssetUserData *this, TSubclassOf<UAssetUserData>);
/* 00000020 */     const TArray<UAssetUserData *,FDefaultAllocator> *(__fastcall *GetAssetUserDataArray)(IInterface_AssetUserData *this);
/* 00000028 */     void (__fastcall *RemoveUserDataOfClass)(IInterface_AssetUserData *this, TSubclassOf<UAssetUserData>);
/* 00000030 */ };

/*00000000 */ struct /*VFT*/ IStateCollection_vtbl // sizeof=0x20
/*00000000 */ {
/*00000000 */     void (__fastcall *~IStateCollection)(IStateCollection *this);
/*00000008 */     bool (__fastcall *AddState)(IStateCollection *this, TSharedPtr<BaseState,0>);
/*00000010 */     bool (__fastcall *AddAndSetAsDefaultState)(IStateCollection *this, TSharedPtr<BaseState,0>);
/*00000018 */     TSharedPtr<BaseState,0> *(__fastcall *GetState)(IStateCollection *this, TSharedPtr<BaseState,0> *result, const FString *);
/*00000020 */ };
