/* 00000000 */ struct /*VFT*/ ADBDMenuPlayer_vtbl // sizeof=0x828
/* 00000000 */ {
/* 00000000 */     void (__fastcall *~UObject)(struct UObject *this);
/* 00000008 */     void (__fastcall *RegisterDependencies)(struct UObject *this);
/* 00000010 */     void (__fastcall *DeferredRegister)(struct UObject *this, UClass *, const wchar_t *, const wchar_t *);
/* 00000018 */     bool (__fastcall *CanBeClusterRoot)(struct UObject *this);
/* 00000020 */     bool (__fastcall *CanBeInCluster)(struct UObject *this);
/* 00000028 */     void (__fastcall *CreateCluster)(struct UObject *this);
/* 00000030 */     void (__fastcall *AddToCluster)(struct UObject *this, UObjectBaseUtility *);
/* 00000038 */     FString *(__fastcall *GetDetailedInfoInternal)(UObject *this, FString *result);
/* 00000040 */     void (__fastcall *PostInitProperties)(UObject *this);
/* 00000048 */     bool (__fastcall *PreSaveRoot)(UObject *this, const wchar_t *, TArray<FString,FDefaultAllocator> *);
/* 00000050 */     void (__fastcall *PostSaveRoot)(UObject *this, bool);
/* 00000058 */     void (__fastcall *PreSave)(UObject *this, const ITargetPlatform *);
/* 00000060 */     bool (__fastcall *Modify)(UObject *this, bool);
/* 00000068 */     void (__fastcall *PostLoad)(UObject *this);
/* 00000070 */     void (__fastcall *PostLoadSubobjects)(UObject *this, FObjectInstancingGraph *);
/* 00000078 */     void (__fastcall *BeginDestroy)(UObject *this);
/* 00000080 */     bool (__fastcall *IsReadyForFinishDestroy)(UObject *this);
/* 00000088 */     void (__fastcall *FinishDestroy)(UObject *this);
/* 00000090 */     void (__fastcall *Serialize)(UObject *this, FArchive *);
/* 00000098 */     void (__fastcall *ShutdownAfterError)(UObject *this);
/* 000000A0 */     void (__fastcall *PostInterpChange)(UObject *this, UProperty *);
/* 000000A8 */     void (__fastcall *PostRename)(UObject *this, UObject *, const FName);
/* 000000B0 */     void (__fastcall *PostDuplicate)(UObject *this, bool);
/* 000000B8 */     bool (__fastcall *NeedsLoadForClient)(UObject *this);
/* 000000C0 */     bool (__fastcall *NeedsLoadForServer)(UObject *this);
/* 000000C8 */     bool (__fastcall *NeedsLoadForEditorGame)(UObject *this);
/* 000000D0 */     bool (__fastcall *IsPostLoadThreadSafe)(UObject *this);
/* 000000D8 */     void (__fastcall *ExportCustomProperties)(UObject *this, FOutputDevice *, unsigned int);
/* 000000E0 */     void (__fastcall *ImportCustomProperties)(UObject *this, const wchar_t *, FFeedbackContext *);
/* 000000E8 */     void (__fastcall *PostEditImport)(UObject *this);
/* 000000F0 */     void (__fastcall *PostReloadConfig)(UObject *this, UProperty *);
/* 000000F8 */     bool (__fastcall *Rename)(UObject *this, const wchar_t *, UObject *, unsigned int);
/* 00000100 */     FString *(__fastcall *GetDesc)(UObject *this, FString *result);
/* 00000108 */     UWorld *(__fastcall *GetWorld)(UObject *this);
/* 00000110 */     bool (__fastcall *GetNativePropertyValues)(UObject *this, TMap<FString,FString,FDefaultSetAllocator,TDefaultMapKeyFuncs<FString,FString,0> > *, unsigned int);
/* 00000118 */     unsigned __int64 (__fastcall *GetResourceSize)(UObject *this, EResourceSizeMode::Type);
/* 00000120 */     FName *(__fastcall *GetExporterName)(UObject *this, FName *result);
/* 00000128 */     FRestoreForUObjectOverwrite *(__fastcall *GetRestoreForUObjectOverwrite)(UObject *this);
/* 00000130 */     bool (__fastcall *AreNativePropertiesIdenticalTo)(UObject *this, UObject *);
/* 00000138 */     void (__fastcall *GetAssetRegistryTags)(UObject *this, TArray<UObject::FAssetRegistryTag,FDefaultAllocator> *);
/* 00000140 */     bool (__fastcall *IsAsset)(UObject *this);
/* 00000148 */     bool (__fastcall *IsLocalizedResource)(UObject *this);
/* 00000150 */     bool (__fastcall *IsSafeForRootSet)(UObject *this);
/* 00000158 */     void (__fastcall *TagSubobjects)(UObject *this, EObjectFlags);
/* 00000160 */     void (__fastcall *GetLifetimeReplicatedProps)(UObject *this, TArray<FLifetimeProperty,FDefaultAllocator> *);
/* 00000168 */     bool (__fastcall *IsNameStableForNetworking)(UObject *this);
/* 00000170 */     bool (__fastcall *IsFullNameStableForNetworking)(UObject *this);
/* 00000178 */     bool (__fastcall *IsSupportedForNetworking)(UObject *this);
/* 00000180 */     void (__fastcall *GetSubobjectsWithStableNamesForNetworking)(UObject *this, TArray<UObject *,FDefaultAllocator> *);
/* 00000188 */     void (__fastcall *PreNetReceive)(UObject *this);
/* 00000190 */     void (__fastcall *PostNetReceive)(UObject *this);
/* 00000198 */     void (__fastcall *PostRepNotifies)(UObject *this);
/* 000001A0 */     void (__fastcall *PreDestroyFromReplication)(UObject *this);
/* 000001A8 */     void (__fastcall *ProcessEvent)(UObject *this, UFunction *, void *);
/* 000001B0 */     int (__fastcall *GetFunctionCallspace)(UObject *this, UFunction *, void *, FFrame *);
/* 000001B8 */     bool (__fastcall *CallRemoteFunction)(UObject *this, UFunction *, void *, FOutParmRec *, FFrame *);
/* 000001C0 */     bool (__fastcall *ProcessConsoleExec)(UObject *this, const wchar_t *, FOutputDevice *, UObject *);
/* 000001C8 */     UClass *(__fastcall *RegenerateClass)(UObject *this, UClass *, UObject *, TArray<UObject *,FDefaultAllocator> *);
/* 000001D0 */     void (__fastcall *MarkAsEditorOnlySubobject)(UObject *this);
/* 000001D8 */     bool (__fastcall *CheckDefaultSubobjectsInternal)(UObject *this);
/* 000001E0 */     void (__fastcall *OnRep_ReplicateMovement)(AActor *this);
/* 000001E8 */     void (__fastcall *TearOff)(AActor *this);
/* 000001F0 */     bool (__fastcall *HasNetOwner)(AActor *this);
/* 000001F8 */     void (__fastcall *OnRep_Owner)(AActor *this);
/* 00000200 */     void (__fastcall *SetReplicateMovement)(AActor *this, bool);
/* 00000208 */     void (__fastcall *OnRep_AttachmentReplication)(AActor *this);
/* 00000210 */     bool (__fastcall *IsReplicationPausedForConnection)(AActor *this, const FNetViewer *);
/* 00000218 */     void (__fastcall *OnReplicationPausedChanged)(AActor *this, bool);
/* 00000220 */     bool (__fastcall *ReplicateSubobjects)(AActor *this, UActorChannel *, FOutBunch *, FReplicationFlags *);
/* 00000228 */     void (__fastcall *OnSubobjectCreatedFromReplication)(AActor *this, UObject *);
/* 00000230 */     void (__fastcall *OnSubobjectDestroyFromReplication)(AActor *this, UObject *);
/* 00000238 */     void (__fastcall *PreReplication)(AActor *this, IRepChangedPropertyTracker *);
/* 00000240 */     void (__fastcall *OnRep_Instigator)(AActor *this);
/* 00000248 */     void (__fastcall *EnableInput)(AActor *this, APlayerController *);
/* 00000250 */     void (__fastcall *DisableInput)(AActor *this, APlayerController *);
/* 00000258 */     FVector *(__fastcall *GetVelocity)(AActor *this, FVector *result);
/* 00000260 */     void (__fastcall *SetActorHiddenInGame)(AActor *this, bool);
/* 00000268 */     void (__fastcall *K2_DestroyActor)(AActor *this);
/* 00000270 */     void (__fastcall *AddTickPrerequisiteActor)(AActor *this, AActor *);
/* 00000278 */     void (__fastcall *AddTickPrerequisiteComponent)(AActor *this, UActorComponent *);
/* 00000280 */     void (__fastcall *RemoveTickPrerequisiteActor)(AActor *this, AActor *);
/* 00000288 */     void (__fastcall *RemoveTickPrerequisiteComponent)(AActor *this, UActorComponent *);
/* 00000290 */     void (__fastcall *BeginPlay)(AActor *this);
/* 00000298 */     void (__fastcall *NotifyActorBeginOverlap)(AActor *this, AActor *);
/* 000002A0 */     void (__fastcall *NotifyActorEndOverlap)(AActor *this, AActor *);
/* 000002A8 */     void (__fastcall *NotifyActorBeginCursorOver)(AActor *this);
/* 000002B0 */     void (__fastcall *NotifyActorEndCursorOver)(AActor *this);
/* 000002B8 */     void (__fastcall *NotifyActorOnClicked)(AActor *this, FKey);
/* 000002C0 */     void (__fastcall *NotifyActorOnReleased)(AActor *this, FKey);
/* 000002C8 */     void (__fastcall *NotifyActorOnInputTouchBegin)(AActor *this, const ETouchIndex::Type);
/* 000002D0 */     void (__fastcall *NotifyActorOnInputTouchEnd)(AActor *this, const ETouchIndex::Type);
/* 000002D8 */     void (__fastcall *NotifyActorOnInputTouchEnter)(AActor *this, const ETouchIndex::Type);
/* 000002E0 */     void (__fastcall *NotifyActorOnInputTouchLeave)(AActor *this, const ETouchIndex::Type);
/* 000002E8 */     void (__fastcall *NotifyHit)(AActor *this, UPrimitiveComponent *, AActor *, UPrimitiveComponent *, bool, FVector, FVector, FVector, const FHitResult *);
/* 000002F0 */     void (__fastcall *SetLifeSpan)(AActor *this, float);
/* 000002F8 */     float (__fastcall *GetLifeSpan)(AActor *this);
/* 00000300 */     void (__fastcall *GatherCurrentMovement)(AActor *this);
/* 00000308 */     USceneComponent *(__fastcall *GetDefaultAttachComponent)(AActor *this);
/* 00000310 */     void (__fastcall *ApplyWorldOffset)(AActor *this, const FVector *, bool);
/* 00000318 */     bool (__fastcall *IsLevelBoundsRelevant)(AActor *this);
/* 00000320 */     float (__fastcall *GetNetPriority)(AActor *this, const FVector *, const FVector *, APlayerController *, UActorChannel *, float, bool);
/* 00000328 */     float (__fastcall *GetNetPriority)(AActor *this, const FVector *, const FVector *, AActor *, AActor *, UActorChannel *, float, bool);
/* 00000330 */     float (__fastcall *GetReplayPriority)(AActor *this, const FVector *, const FVector *, AActor *, AActor *, UActorChannel *const, float);
/* 00000338 */     bool (__fastcall *GetNetDormancy)(AActor *this, const FVector *, const FVector *, APlayerController *, AActor *, UActorChannel *, float, bool);
/* 00000340 */     bool (__fastcall *GetNetDormancy)(AActor *this, const FVector *, const FVector *, AActor *, AActor *, UActorChannel *, float, bool);
/* 00000348 */     void (__fastcall *OnActorChannelOpen)(AActor *this, FInBunch *, UNetConnection *);
/* 00000350 */     bool (__fastcall *UseShortConnectTimeout)(AActor *this);
/* 00000358 */     void (__fastcall *OnSerializeNewActor)(AActor *this, FOutBunch *);
/* 00000360 */     void (__fastcall *OnNetCleanup)(AActor *this, UNetConnection *);
/* 00000368 */     void (__fastcall *TickActor)(AActor *this, float, ELevelTick, FActorTickFunction *);
/* 00000370 */     void (__fastcall *PostActorCreated)(AActor *this);
/* 00000378 */     void (__fastcall *LifeSpanExpired)(AActor *this);
/* 00000380 */     void (__fastcall *PostNetInit)(AActor *this);
/* 00000388 */     void (__fastcall *OnRep_ReplicatedMovement)(AActor *this);
/* 00000390 */     void (__fastcall *PostNetReceiveLocation)(AActor *this);
/* 00000398 */     void (__fastcall *PostNetReceiveLocationAndRotation)(AActor *this);
/* 000003A0 */     void (__fastcall *PostNetReceiveVelocity)(AActor *this, const FVector *);
/* 000003A8 */     void (__fastcall *PostNetReceivePhysicState)(AActor *this);
/* 000003B0 */     void (__fastcall *SetOwner)(AActor *this, AActor *);
/* 000003B8 */     bool (__fastcall *CheckStillInWorld)(AActor *this);
/* 000003C0 */     void (__fastcall *Tick)(AActor *this, float);
/* 000003C8 */     bool (__fastcall *ShouldTickIfViewportsOnly)(AActor *this);
/* 000003D0 */     bool (__fastcall *IsNetRelevantFor)(AActor *this, const APlayerController *, const AActor *, const FVector *);
/* 000003D8 */     bool (__fastcall *IsNetRelevantFor)(AActor *this, const AActor *, const AActor *, const FVector *);
/* 000003E0 */     bool (__fastcall *IsRelevancyOwnerFor)(AActor *this, const AActor *, const AActor *, const AActor *);
/* 000003E8 */     void (__fastcall *PreInitializeComponents)(AActor *this);
/* 000003F0 */     void (__fastcall *PostInitializeComponents)(AActor *this);
/* 000003F8 */     const AActor *(__fastcall *GetNetOwner)(AActor *this);
/* 00000400 */     UPlayer *(__fastcall *GetNetOwningPlayer)(AActor *this);
/* 00000408 */     UNetConnection *(__fastcall *GetNetConnection)(AActor *this);
/* 00000410 */     bool (__fastcall *DestroyNetworkActorHandled)(AActor *this);
/* 00000418 */     void (__fastcall *RegisterAllComponents)(AActor *this);
/* 00000420 */     void (__fastcall *PostRegisterAllComponents)(AActor *this);
/* 00000428 */     void (__fastcall *UnregisterAllComponents)(AActor *this, bool);
/* 00000430 */     void (__fastcall *PostUnregisterAllComponents)(AActor *this);
/* 00000438 */     void (__fastcall *ReregisterAllComponents)(AActor *this);
/* 00000440 */     void (__fastcall *MarkComponentsAsPendingKill)(AActor *this);
/* 00000448 */     void (__fastcall *InvalidateLightingCacheDetailed)(AActor *this, bool);
/* 00000450 */     bool (__fastcall *TeleportTo)(AActor *this, const FVector *, const FRotator *, bool, bool);
/* 00000458 */     void (__fastcall *TeleportSucceeded)(AActor *this, bool);
/* 00000460 */     void (__fastcall *ClearCrossLevelReferences)(AActor *this);
/* 00000468 */     void (__fastcall *EndPlay)(AActor *this, const EEndPlayReason::Type);
/* 00000470 */     bool (__fastcall *IsBasedOnActor)(AActor *this, const AActor *);
/* 00000478 */     bool (__fastcall *IsAttachedTo)(AActor *this, const AActor *);
/* 00000480 */     void (__fastcall *RerunConstructionScripts)(AActor *this);
/* 00000488 */     void (__fastcall *OnConstruction)(AActor *this, const FTransform *);
/* 00000490 */     void (__fastcall *RegisterActorTickFunctions)(AActor *this, bool);
/* 00000498 */     AActor *(__fastcall *GetAttachParentActor)(AActor *this);
/* 000004A0 */     FName *(__fastcall *GetAttachParentSocketName)(AActor *this, FName *result);
/* 000004A8 */     void (__fastcall *GetAttachedActors)(AActor *this, TArray<AActor *,FDefaultAllocator> *);
/* 000004B0 */     void (__fastcall *Destroyed)(AActor *this);
/* 000004B8 */     void (__fastcall *FellOutOfWorld)(AActor *this, const UDamageType *);
/* 000004C0 */     void (__fastcall *OutsideWorldBounds)(AActor *this);
/* 000004C8 */     FBox *(__fastcall *GetComponentsBoundingBox)(AActor *this, FBox *result, bool);
/* 000004D0 */     FBox *(__fastcall *CalculateComponentsBoundingBoxInLocalSpace)(AActor *this, FBox *result, bool);
/* 000004D8 */     void (__fastcall *GetComponentsBoundingCylinder)(AActor *this, float *, float *, bool);
/* 000004E0 */     void (__fastcall *GetSimpleCollisionCylinder)(AActor *this, float *, float *);
/* 000004E8 */     bool (__fastcall *IsRootComponentCollisionRegistered)(AActor *this);
/* 000004F0 */     void (__fastcall *TornOff)(AActor *this);
/* 000004F8 */     ECollisionResponse (__fastcall *GetComponentsCollisionResponseToChannel)(AActor *this, ECollisionChannel);
/* 00000500 */     bool (__fastcall *CanBeBaseForCharacter)(AActor *this, APawn *);
/* 00000508 */     float (__fastcall *TakeDamage)(AActor *this, float, const FDamageEvent *, AController *, AActor *);
/* 00000510 */     float (__fastcall *InternalTakeRadialDamage)(AActor *this, float, const FRadialDamageEvent *, AController *, AActor *);
/* 00000518 */     float (__fastcall *InternalTakePointDamage)(AActor *this, float, const FPointDamageEvent *, AController *, AActor *);
/* 00000520 */     void (__fastcall *BecomeViewTarget)(AActor *this, APlayerController *);
/* 00000528 */     void (__fastcall *EndViewTarget)(AActor *this, APlayerController *);
/* 00000530 */     void (__fastcall *CalcCamera)(AActor *this, float, FMinimalViewInfo *);
/* 00000538 */     bool (__fastcall *HasActiveCameraComponent)(AActor *this);
/* 00000540 */     bool (__fastcall *HasActivePawnControlCameraComponent)(AActor *this);
/* 00000548 */     FString *(__fastcall *GetHumanReadableName)(AActor *this, FString *result);
/* 00000550 */     void (__fastcall *Reset)(AActor *this);
/* 00000558 */     float (__fastcall *GetLastRenderTime)(AActor *this);
/* 00000560 */     void (__fastcall *ForceNetRelevant)(AActor *this);
/* 00000568 */     void (__fastcall *ForceNetUpdate)(AActor *this);
/* 00000570 */     void (__fastcall *PrestreamTextures)(AActor *this, float, bool, int);
/* 00000578 */     void (__fastcall *GetActorEyesViewPoint)(AActor *this, FVector *, FRotator *);
/* 00000580 */     FVector *(__fastcall *GetTargetLocation)(AActor *this, FVector *result, AActor *);
/* 00000588 */     void (__fastcall *PostRenderFor)(AActor *this, APlayerController *, UCanvas *, FVector, FVector);
/* 00000590 */     UActorComponent *(__fastcall *FindComponentByClass)(AActor *this, const TSubclassOf<UActorComponent>);
/* 00000598 */     bool (__fastcall *IsComponentRelevantForNavigation)(AActor *this, UActorComponent *);
/* 000005A0 */     void (__fastcall *DisplayDebug)(AActor *this, UCanvas *, const FDebugDisplayInfo *, float *, float *);
/* 000005A8 */     UPawnMovementComponent *(__fastcall *GetMovementComponent)(APawn *this);
/* 000005B0 */     UPrimitiveComponent *(__fastcall *GetMovementBase)(APawn *this);
/* 000005B8 */     UPawnNoiseEmitterComponent *(__fastcall *GetPawnNoiseEmitterComponent)(APawn *this);
/* 000005C0 */     void (__fastcall *TurnOff)(APawn *this);
/* 000005C8 */     void (__fastcall *Restart)(APawn *this);
/* 000005D0 */     void (__fastcall *PawnStartFire)(APawn *this, unsigned __int8);
/* 000005D8 */     void (__fastcall *UnPossessed)(APawn *this);
/* 000005E0 */     APhysicsVolume *(__fastcall *GetPawnPhysicsVolume)(APawn *this);
/* 000005E8 */     bool (__fastcall *ReachedDesiredRotation)(APawn *this);
/* 000005F0 */     float (__fastcall *GetDefaultHalfHeight)(APawn *this);
/* 000005F8 */     void (__fastcall *OnRep_Controller)(APawn *this);
/* 00000600 */     void (__fastcall *OnRep_PlayerState)(APawn *this);
/* 00000608 */     void (__fastcall *UpdateNavigationRelevance)(APawn *this);
/* 00000610 */     bool (__fastcall *ShouldTakeDamage)(APawn *this, float, const FDamageEvent *, AController *, AActor *);
/* 00000618 */     void (__fastcall *SetPlayerDefaults)(APawn *this);
/* 00000620 */     void (__fastcall *RecalculateBaseEyeHeight)(APawn *this);
/* 00000628 */     void (__fastcall *PossessedBy)(APawn *this, AController *);
/* 00000630 */     bool (__fastcall *IsLocallyControlled)(APawn *this);
/* 00000638 */     bool (__fastcall *IsPlayerControlled)(APawn *this);
/* 00000640 */     FRotator *(__fastcall *GetViewRotation)(APawn *this, FRotator *result);
/* 00000648 */     FVector *(__fastcall *GetPawnViewLocation)(APawn *this, FVector *result);
/* 00000650 */     FRotator *(__fastcall *GetBaseAimRotation)(APawn *this, FRotator *result);
/* 00000658 */     bool (__fastcall *InFreeCam)(APawn *this);
/* 00000660 */     void (__fastcall *PawnClientRestart)(APawn *this);
/* 00000668 */     void (__fastcall *ClientSetRotation)(APawn *this, FRotator);
/* 00000670 */     void (__fastcall *FaceRotation)(APawn *this, FRotator, float);
/* 00000678 */     void (__fastcall *DetachFromControllerPendingDestroy)(APawn *this);
/* 00000680 */     void (__fastcall *SpawnDefaultController)(APawn *this);
/* 00000688 */     AController *(__fastcall *GetDamageInstigator)(APawn *this, AController *, const UDamageType *);
/* 00000690 */     UInputComponent *(__fastcall *CreatePlayerInputComponent)(APawn *this);
/* 00000698 */     void (__fastcall *DestroyPlayerInputComponent)(APawn *this);
/* 000006A0 */     void (__fastcall *SetupPlayerInputComponent)(APawn *this, UInputComponent *);
/* 000006A8 */     void (__fastcall *AddMovementInput)(APawn *this, FVector, float, bool);
/* 000006B0 */     FVector *(__fastcall *ConsumeMovementInputVector)(APawn *this, FVector *result);
/* 000006B8 */     void (__fastcall *AddControllerPitchInput)(APawn *this, float);
/* 000006C0 */     void (__fastcall *AddControllerYawInput)(APawn *this, float);
/* 000006C8 */     void (__fastcall *AddControllerRollInput)(APawn *this, float);
/* 000006D0 */     bool (__fastcall *IsMoveInputIgnored)(APawn *this);
/* 000006D8 */     void (__fastcall *MoveIgnoreActorAdd)(APawn *this, AActor *);
/* 000006E0 */     void (__fastcall *MoveIgnoreActorRemove)(APawn *this, AActor *);
/* 000006E8 */     void (__fastcall *SetBase)(ACharacter *this, UPrimitiveComponent *, const FName, bool);
/* 000006F0 */     void (__fastcall *OnRep_ReplicatedBasedMovement)(ACharacter *this);
/* 000006F8 */     void (__fastcall *BaseChange)(ACharacter *this);
/* 00000700 */     const FQuat *(__fastcall *GetBaseRotationOffset)(ACharacter *this, const FQuat *result);
/* 00000708 */     void (__fastcall *OnRep_IsCrouched)(ACharacter *this);
/* 00000710 */     void (__fastcall *ApplyDamageMomentum)(ACharacter *this, float, const FDamageEvent *, APawn *, AActor *);
/* 00000718 */     void (__fastcall *Jump)(ACharacter *this);
/* 00000720 */     void (__fastcall *StopJumping)(ACharacter *this);
/* 00000728 */     bool (__fastcall *CanJumpInternal_Implementation)(ACharacter *this);
/* 00000730 */     bool (__fastcall *IsJumpProvidingForce)(ACharacter *this);
/* 00000738 */     bool (__fastcall *IsJumping)(ACharacter *this);
/* 00000740 */     float (__fastcall *PlayAnimMontage)(ACharacter *this, UAnimMontage *, float, FName);
/* 00000748 */     void (__fastcall *StopAnimMontage)(ACharacter *this, UAnimMontage *);
/* 00000750 */     bool (__fastcall *DoJump)(ACharacter *this, bool);
/* 00000758 */     void (__fastcall *LaunchCharacter)(ACharacter *this, FVector, bool, bool);
/* 00000760 */     void (__fastcall *OnJumped_Implementation)(ACharacter *this);
/* 00000768 */     void (__fastcall *Falling)(ACharacter *this);
/* 00000770 */     void (__fastcall *NotifyJumpApex)(ACharacter *this);
/* 00000778 */     void (__fastcall *Landed)(ACharacter *this, const FHitResult *);
/* 00000780 */     void (__fastcall *OnWalkingOffLedge_Implementation)(ACharacter *this);
/* 00000788 */     void (__fastcall *OnWalkingOffLedge_Implementation)(ACharacter *this, const FVector *, const FVector *, const FVector *, float);
/* 00000790 */     void (__fastcall *MoveBlockedBy)(ACharacter *this, const FHitResult *);
/* 00000798 */     void (__fastcall *Crouch)(ACharacter *this, bool);
/* 000007A0 */     void (__fastcall *UnCrouch)(ACharacter *this, bool);
/* 000007A8 */     bool (__fastcall *CanCrouch)(ACharacter *this);
/* 000007B0 */     void (__fastcall *OnEndCrouch)(ACharacter *this, float, float);
/* 000007B8 */     void (__fastcall *OnStartCrouch)(ACharacter *this, float, float);
/* 000007C0 */     void (__fastcall *OnMovementModeChanged)(ACharacter *this, EMovementMode, unsigned __int8);
/* 000007C8 */     bool (__fastcall *NotifyLanded)(ACharacter *this, const FHitResult *);
/* 000007D0 */     bool (__fastcall *ShouldNotifyLanded)(ACharacter *this, const FHitResult *);
/* 000007D8 */     void (__fastcall *CheckJumpInput)(ACharacter *this, float);
/* 000007E0 */     void (__fastcall *ClearJumpInput)(ACharacter *this);
/* 000007E8 */     float (__fastcall *GetJumpMaxHoldTime)(ACharacter *this);
/* 000007F0 */     void (__fastcall *UpdateFromCompressedFlags)(ACharacter *this, unsigned __int8);
/* 000007F8 */     void (__fastcall *ClientCheatGhost)(ACharacter *this);
/* 00000800 */     void (__fastcall *ClientCheatGhost_Implementation)(ACharacter *this);
/* 00000808 */     void (__fastcall *UpdateSimulatedPosition)(ACharacter *this, const FVector *, const FRotator *);
/* 00000810 */     void (__fastcall *OnUpdateSimulatedPosition)(ACharacter *this, const FVector *, const FQuat *);
/* 00000818 */     bool (__fastcall *IsRootMotionAllowed)(ACharacter *this);
/* 00000820 */     void (__fastcall *BeginDestroySequence_Implementation)(ADBDMenuPlayer *this);
/* 00000828 */ };

/* 00000000 */ struct /*VFT*/ INavAgentInterface_vtbl // sizeof=0x50
/* 00000000 */ {
/* 00000000 */     void (__fastcall *~INavAgentInterface)(INavAgentInterface *this);
/* 00000008 */     UObject *(__fastcall *_getUObject)(INavAgentInterface *this);
/* 00000010 */     const FNavAgentProperties *(__fastcall *GetNavAgentPropertiesRef)(INavAgentInterface *this);
/* 00000018 */     FVector *(__fastcall *GetNavAgentLocation)(INavAgentInterface *this, FVector *result);
/* 00000020 */     FVector *(__fastcall *GetMoveGoalOffset)(INavAgentInterface *this, FVector *result, AActor *);
/* 00000028 */     FVector *(__fastcall *GetMoveGoalOffset)(INavAgentInterface *this, FVector *result, const AActor *);
/* 00000030 */     void (__fastcall *GetMoveGoalReachTest)(INavAgentInterface *this, AActor *, const FVector *, FVector *, float *, float *);
/* 00000038 */     void (__fastcall *GetMoveGoalReachTest)(INavAgentInterface *this, const AActor *, const FVector *, FVector *, float *, float *);
/* 00000040 */     bool (__fastcall *ShouldPostponePathUpdates)(INavAgentInterface *this);
/* 00000048 */     bool (__fastcall *IsFollowingAPath)(INavAgentInterface *this);
/* 00000050 */ };
