class __base(UOnlineSessionClient, 0) UDBDOnlineSessionClient
{
/*0x0000*/  struct UDBDOnlineSessionClient::VTable* vtable;
/*0x0008*/  __inherited enum EObjectFlags UObjectBase::ObjectFlags;
/*0x000c*/  __inherited int32_t UObjectBase::InternalIndex;
/*0x0010*/  __inherited class UClass* UObjectBase::ClassPrivate;
/*0x0018*/  __inherited class FName UObjectBase::NamePrivate;
/*0x0020*/  __inherited class UObject* UObjectBase::OuterPrivate;
            __padding char _28[8];
/*0x0030*/  __inherited class TBaseDelegate<void, FName, bool> UOnlineSessionClient::OnEndForJoinSessionCompleteDelegate;
/*0x0070*/  __inherited class TBaseDelegate<void, FName, bool> UOnlineSessionClient::OnDestroyForJoinSessionCompleteDelegate;
/*0x00b0*/  __inherited class TBaseDelegate<void, FName, bool> UOnlineSessionClient::OnDestroyForMainMenuCompleteDelegate;
/*0x00f0*/  __inherited class TBaseDelegate<void, FName, enum EOnJoinSessionCompleteResult::Type> UOnlineSessionClient::OnJoinSessionCompleteDelegate;
/*0x0130*/  __inherited class TBaseDelegate<void, bool const, int const, TSharedPtr<FUniqueNetId const, 0>, FOnlineSessionSearchResult const &> UOnlineSessionClient::OnSessionUserInviteAcceptedDelegate;
/*0x0170*/  __inherited class TBaseDelegate<void, int, TArray<TSharedPtr<FUniqueNetId const, 0>,FDefaultAllocator>> UOnlineSessionClient::OnPlayTogetherEventReceivedDelegate;
/*0x01b0*/  __inherited class FDelegateHandle UOnlineSessionClient::OnSessionInviteAcceptedDelegateHandle;
/*0x01b8*/  __inherited class FDelegateHandle UOnlineSessionClient::OnEndForJoinSessionCompleteDelegateHandle;
/*0x01c0*/  __inherited class FDelegateHandle UOnlineSessionClient::OnDestroyForJoinSessionCompleteDelegateHandle;
/*0x01c8*/  __inherited class FDelegateHandle UOnlineSessionClient::OnDestroyForMainMenuCompleteDelegateHandle;
/*0x01d0*/  __inherited class FDelegateHandle UOnlineSessionClient::OnJoinSessionCompleteDelegateHandle;
/*0x01d8*/  __inherited class FDelegateHandle UOnlineSessionClient::OnPlayTogetherEventReceivedDelegateHandle;
/*0x01e0*/  __inherited class FDelegateHandle UOnlineSessionClient::StartSessionCompleteHandle;
/*0x01e8*/  __inherited class FDelegateHandle UOnlineSessionClient::EndSessionCompleteHandle;
/*0x01f0*/  __inherited class FDelegateHandle UOnlineSessionClient::OnSessionUserInviteAcceptedDelegateHandle;
/*0x01f8*/  __inherited class FOnlineSessionSearchResult UOnlineSessionClient::CachedSessionResult;
/*0x02b0*/  __inherited bool UOnlineSessionClient::bIsFromInvite;
/*0x02b1*/  __inherited bool UOnlineSessionClient::bHandlingDisconnect;
            __padding char _2b2[0xe];
/*0x02c0*/  class TMulticastDelegate<void, bool const, int const, TSharedPtr<FUniqueNetId const, 0>, FOnlineSessionSearchResult const &> OnJoinFromInvite;
/*0x0330*/  class TMulticastDelegate<void, int const, TArray<TSharedPtr<FUniqueNetId const, 0>, FDefaultAllocator>> OnPlayTogetherHostRequest;
/*0x03a0*/  bool _allowAcceptedInvites;
/*0x03a1*/  bool _hasPlayTogetherNotification;
            __padding char _3a2[0xe];
/*0x03b0*/  class TBaseDelegate<void, FName, enum EOnJoinSessionCompleteResult::Type> DBDOnJoinSessionCompleteDelegate;
/*0x03f0*/  class TBaseDelegate<void, FName, bool> OnEndBeforeJoinSessionCompleteDelegate;
/*0x0430*/  class TBaseDelegate<void, FName, bool> OnDestroyBeforeJoinSessionCompleteDelegate;
/*0x0470*/  class TBaseDelegate<void> _onPlayerDisconnectedDelegate;
/*0x04b0*/  class FDelegateHandle DBDOnJoinSessionCompleteDelegateHandle;
/*0x04b8*/  class FDelegateHandle OnEndBeforeJoinSessionCompleteDelegateHandle;
/*0x04c0*/  class FDelegateHandle OnDestroyBeforeJoinSessionCompleteDelegateHandle;
/*0x04c8*/  class FDelegateHandle OnPlayerDisconnectedHandle;
/*0x04d0*/  class TArray<TSharedPtr<FUniqueNetId const, 0>, FDefaultAllocator> _playTogetherInviteList;
/*0x04e0*/  int32_t _playTogetherUserIndex;
};
