class __base(ADBDPlayerState_Menu, 0) ADBDPlayerState_Lobby
{
/*0x0000*/  struct ADBDPlayerState_Lobby::VTable* vtable;
/*0x0008*/  __inherited enum EObjectFlags UObjectBase::ObjectFlags;
/*0x000c*/  __inherited int32_t UObjectBase::InternalIndex;
/*0x0010*/  __inherited class UClass* UObjectBase::ClassPrivate;
/*0x0018*/  __inherited class FName UObjectBase::NamePrivate;
/*0x0020*/  __inherited class UObject* UObjectBase::OuterPrivate;
/*0x0028*/  __inherited struct FActorTickFunction AActor::PrimaryActorTick;
/*0x0078*/  __inherited float AActor::CustomTimeDilation;
/*0x007c*/  __inherited union
            {
              uint8_t bHidden;
              uint8_t bNetTemporary;
              uint8_t bNetStartup;
              uint8_t bOnlyRelevantToOwner;
              uint8_t bAlwaysRelevant;
              uint8_t bReplicateMovement;
              uint8_t bTearOff;
              uint8_t bExchangedRoles;
            } __bitfield7c;
/*0x007d*/  __inherited union
            {
              uint8_t bPendingNetUpdate;
              uint8_t bNetLoadOnClient;
              uint8_t bNetUseOwnerRelevancy;
              uint8_t bBlockInput;
              uint8_t bRunningUserConstructionScript;
              uint8_t bAllowTickBeforeBeginPlay;
              uint8_t bHasFinishedSpawning;
              uint8_t bTickFunctionsRegistered;
            } __bitfield7d;
/*0x007e*/  __inherited union
            {
              uint8_t bActorEnableCollision;
              uint8_t bNetCheckedInitialPhysicsState;
              uint8_t bReplicates;
            } __bitfield7e;
            __padding char _7f[1];
/*0x0080*/  __inherited class FName AActor::NetDriverName;
/*0x0088*/  __inherited class TEnumAsByte<enum ENetRole> AActor::RemoteRole;
/*0x0090*/  __inherited class AActor* AActor::Owner;
/*0x0098*/  __inherited struct FRepMovement AActor::ReplicatedMovement;
            __padding char _cc[4];
/*0x00d0*/  __inherited struct FRepAttachment AActor::AttachmentReplication;
/*0x0110*/  __inherited class TEnumAsByte<enum ENetRole> AActor::Role;
/*0x0111*/  __inherited class TEnumAsByte<enum ENetDormancy> AActor::NetDormancy;
/*0x0112*/  __inherited class TEnumAsByte<enum EAutoReceiveInput::Type> AActor::AutoReceiveInput;
/*0x0114*/  __inherited int32_t AActor::InputPriority;
/*0x0118*/  __inherited class UInputComponent* AActor::InputComponent;
/*0x0120*/  __inherited class TEnumAsByte<enum EInputConsumeOptions> AActor::InputConsumeOption_DEPRECATED;
/*0x0124*/  __inherited float AActor::NetCullDistanceSquared;
/*0x0128*/  __inherited int32_t AActor::NetTag;
/*0x012c*/  __inherited float AActor::NetUpdateTime;
/*0x0130*/  __inherited float AActor::NetUpdateFrequency;
/*0x0134*/  __inherited float AActor::MinNetUpdateFrequency;
/*0x0138*/  __inherited float AActor::NetPriority;
/*0x013c*/  __inherited float AActor::LastNetUpdateTime;
/*0x0140*/  __inherited union
            {
              uint8_t bAutoDestroyWhenFinished;
              uint8_t bCanBeDamaged;
              uint8_t bActorIsBeingDestroyed;
              uint8_t bCollideWhenPlacing;
              uint8_t bFindCameraComponentWhenViewTarget;
              uint8_t bRelevantForNetworkReplays;
              uint8_t bGenerateOverlapEventsDuringLevelStreaming;
            } __bitfield140;
/*0x0141*/  __inherited enum ESpawnActorCollisionHandlingMethod AActor::SpawnCollisionHandlingMethod;
/*0x0144*/  __inherited float AActor::CreationTime;
/*0x0148*/  __inherited class APawn* AActor::Instigator;
/*0x0150*/  __inherited class TArray<AActor *,FDefaultAllocator> AActor::Children;
/*0x0160*/  __inherited class USceneComponent* AActor::RootComponent;
/*0x0168*/  __inherited class TArray<AMatineeActor*, FDefaultAllocator> AActor::ControllingMatineeActors;
/*0x0178*/  __inherited float AActor::InitialLifeSpan;
/*0x017c*/  __padding char _17c[4];
/*0x0180*/  __inherited struct FTimerHandle AActor::TimerHandle_LifeSpanExpired;
/*0x0188*/  __inherited class TArray<FName, FDefaultAllocator> AActor::Layers;
/*0x0198*/  __inherited struct TWeakObjectPtr<AActor, FWeakObjectPtr> AActor::ParentComponentActor_DEPRECATED;
/*0x01a0*/  __inherited struct TWeakObjectPtr<UChildActorComponent, FWeakObjectPtr> AActor::ParentComponent;
/*0x01a8*/  __inherited union
            {
              uint8_t bAllowReceiveTickEventOnDedicatedServer;
              uint8_t bActorInitialized;
              enum AActor::EActorBeginPlayState ActorHasBegunPlay;
              uint8_t bActorSeamlessTraveled;
              uint8_t bIgnoresOriginShifting;
              uint8_t bEnableAutoLODGeneration;
            } __bitfield1a8;
            __padding char _1a9[7];
/*0x01b0*/  __inherited class TArray<FName, FDefaultAllocator> AActor::Tags;
/*0x01c0*/  __inherited uint64_t AActor::HiddenEditorViews;
/*0x01c8*/  __inherited class FTakeAnyDamageSignature AActor::OnTakeAnyDamage;
/*0x01d8*/  __inherited class FTakePointDamageSignature AActor::OnTakePointDamage;
/*0x01e8*/  __inherited class FActorBeginOverlapSignature AActor::OnActorBeginOverlap;
/*0x01f8*/  __inherited class FActorEndOverlapSignature AActor::OnActorEndOverlap;
/*0x0208*/  __inherited class FActorBeginCursorOverSignature AActor::OnBeginCursorOver;
/*0x0218*/  __inherited class FActorEndCursorOverSignature AActor::OnEndCursorOver;
/*0x0228*/  __inherited class FActorOnClickedSignature AActor::OnClicked;
/*0x0238*/  __inherited class FActorOnReleasedSignature AActor::OnReleased;
/*0x0248*/  __inherited class FActorOnInputTouchBeginSignature AActor::OnInputTouchBegin;
/*0x0258*/  __inherited class FActorOnInputTouchEndSignature AActor::OnInputTouchEnd;
/*0x0268*/  __inherited class FActorBeginTouchOverSignature AActor::OnInputTouchEnter;
/*0x0278*/  __inherited class FActorEndTouchOverSignature AActor::OnInputTouchLeave;
/*0x0288*/  __inherited class FActorHitSignature AActor::OnActorHit;
/*0x0298*/  __inherited class FActorDestroyedSignature AActor::OnDestroyed;
/*0x02a8*/  __inherited class FActorEndPlaySignature AActor::OnEndPlay;
/*0x02b8*/  __inherited class TSet<UActorComponent*, DefaultKeyFuncs<UActorComponent*, 0>,FDefaultSetAllocator> AActor::OwnedComponents;
/*0x0308*/  __inherited class TSet<UActorComponent*, DefaultKeyFuncs<UActorComponent*, 0>,FDefaultSetAllocator> AActor::ReplicatedComponents;
/*0x0358*/  __inherited class TArray<UActorComponent*, FDefaultAllocator> AActor::BlueprintCreatedComponents;
/*0x0368*/  __inherited class TArray<UActorComponent*, FDefaultAllocator> AActor::InstanceComponents;
/*0x0378*/  __inherited class FRenderCommandFence AActor::DetachFence;
/*0x0380*/  __inherited float APlayerState::Score;
/*0x0384*/  __inherited uint8_t APlayerState::Ping;
            __padding char _385[3];
/*0x0388*/  __inherited class FString APlayerState::PlayerName;
/*0x0398*/  __inherited class FString APlayerState::OldName;
/*0x03a8*/  __inherited int32_t APlayerState::PlayerId;
/*0x03ac*/  __inherited union
            {
                uint32_t bIsSpectator;
                uint32_t bOnlySpectator;
                uint32_t bIsABot;
                uint32_t bHasBeenWelcomed;
                uint32_t bIsInactive;
                uint32_t bFromPreviousLevel;
            } __bitfield3ac;
/*0x03b0*/  __inherited int32_t APlayerState::StartTime;
            __padding char _3b4[4];
/*0x03b8*/  __inherited class TSubclassOf<ULocalMessage> APlayerState::EngineMessageClass;
/*0x03c0*/  __inherited float APlayerState::ExactPing;
            __padding char _3c4[4];
/*0x03c8*/  __inherited class FString APlayerState::SavedNetworkAddress;
/*0x03d8*/  __inherited struct FUniqueNetIdRepl APlayerState::UniqueId;
/*0x03f0*/  __inherited class FName APlayerState::SessionName;
/*0x03f8*/  __inherited struct PingAvgData APlayerState::PingBucket[0x4];
/*0x0408*/  __inherited uint8_t APlayerState::CurPingBucket;
/*0x040c*/  __inherited float APlayerState::CurPingBucketTimestamp;
/*0x0410*/  __inherited class TMulticastDelegate<void,ADBDPlayerState *> ADBDPlayerState::_playerDataUpdatedDelegate;
/*0x0480*/  __inherited class TMulticastDelegate<void,enum EDBDScoreCategory,FString,int,float> ADBDPlayerState::_scoreEventDelegate;
/*0x04f0*/  __inherited class TMulticastDelegate<void,bool> ADBDPlayerState::_skillCheckUpdatedEventDelegate;
/*0x0560*/  __inherited class TMulticastDelegate<void,FName,int,int,float,int> ADBDPlayerState::_activePerkEventDelegate;
/*0x05d0*/  __inherited class TMulticastDelegate<void,FName,float,int,int> ADBDPlayerState::_activeStatusEffectEventDelegate;
/*0x0640*/  __inherited class TMulticastDelegate<void,FName,FName,FStatusViewSource const > ADBDPlayerState::_activeStatusViewEventDelegate;
/*0x06b0*/  __inherited class TMulticastDelegate<void> ADBDPlayerState::_onPlayerDisconnectedDelegate;
/*0x0720*/  __inherited bool ADBDPlayerState::GameLevelLoaded;
            __padding char _721[7];
/*0x0728*/  __inherited class FString ADBDPlayerState::MirrorsId;
/*0x0738*/  __inherited class FString ADBDPlayerState::SteamId;
/*0x0748*/  __inherited bool ADBDPlayerState::IsPlayerReady;
/*0x074c*/  __inherited int32_t ADBDPlayerState::SelectedCamperIndex;
/*0x0750*/  __inherited enum EPlayerRole ADBDPlayerState::GameRole;
/*0x0754*/  __inherited int32_t ADBDPlayerState::SelectedSlasherIndex;
/*0x0758*/  __inherited struct FCamperStateData ADBDPlayerState::CamperData;
/*0x0778*/  __inherited class URitualHandlerComponent* ADBDPlayerState::RitualHandler;
/*0x0780*/  __inherited class UAchievementHandlerComponent* ADBDPlayerState::AchievementHandler;
/*0x0788*/  __inherited class UActivityTrackerComponent* ADBDPlayerState::ActivityTracker;
/*0x0790*/  __inherited class UDBDBadgeEvaluatorComponent* ADBDPlayerState::BadgeEvaluator;
/*0x0798*/  __inherited struct FSlasherStateData ADBDPlayerState::SlasherData;
/*0x07b8*/  __inherited struct FPlayerStateData ADBDPlayerState::PlayerData;
/*0x0800*/  __inherited struct FSkillCheckInteractionData ADBDPlayerState::SkillCheckInteractionData;
/*0x0820*/  __inherited bool ADBDPlayerState::IsReadyToTravel;
            __padding char _821[7];
/*0x0828*/  __inherited class FPlayerGameplayEventDelegate ADBDPlayerState::OnPlayerGameplayEvent;
/*0x0838*/  __inherited class TMap<FName,FScoreEventArray,FDefaultSetAllocator,TDefaultMapKeyFuncs<FName,FScoreEventArray,0> > ADBDPlayerState::_scoreEvents;
/*0x0888*/  __inherited struct FUserGameStats ADBDPlayerState::_cachedUserGameStats;
/*0x0938*/  __inherited class TArray<FOngoingScoreData,FDefaultAllocator> ADBDPlayerState::_ongoingScoreEvents;
/*0x0948*/  __inherited struct FTimerHandle ADBDPlayerState::_ongoingScoreTimerHandle;
/*0x0950*/  __inherited struct FDBDRecentGameplayEvents ADBDPlayerState::_recentGameplayEvents;
/*0x09a0*/  __inherited bool ADBDPlayerState::_postGameInventoryHandled;
/*0x09a1*/  __inherited bool ADBDPlayerState::_inParadise;
/*0x09a2*/  __inherited enum EKillerJoiningState ADBDPlayerState::_killerJoiningState;
            __padding char _9a3[5];
/*0x09a8*/  __inherited class TMap<enum EDBDScoreTypes,FScoreAnalytics,FDefaultSetAllocator,TDefaultMapKeyFuncs<enum EDBDScoreTypes,FScoreAnalytics,0> > ADBDPlayerState::_playerScoreAnalyticsData;
/*0x09f8*/  __inherited class UGameplayNotificationManager* ADBDPlayerState::_gameplayNotificationManager;
/*0x0a00*/  __inherited struct TWeakObjectPtr<APlayerStart,FWeakObjectPtr> ADBDPlayerState_Menu::_playerSpawn;
/*0x0a08*/  __inherited struct TWeakObjectPtr<ADBDMenuPlayer,FWeakObjectPtr> ADBDPlayerState_Menu::_pawn;
/*0x0a10*/  __inherited int32_t ADBDPlayerState_Menu::_spawnedCharacterIndex;
/*0x0a14*/  __inherited bool ADBDPlayerState_Menu::_dirty;
/*0x0a15*/  __inherited bool ADBDPlayerState_Menu::_showPawn;
/*0x0a16*/  __inherited bool ADBDPlayerState_Menu::_runningDestroySequence;
            __padding char _a17[1];
/*0x0a18*/  __inherited class FDelegateHandle ADBDPlayerState_Menu::_pawnDestroyHandle;
/*0x0a20*/  __inherited struct FVector ADBDPlayerState_Menu::_slasherPOVTrackerOffset;
};
