class __base(ACharacter, 0) __base(IPerkOwnerInterface, 0x7a0) __base(IPerkManagerOwnerInterface, 0x7a8) __base(IAnimTagProvider, 0x7b0) ADBDPlayer
{
/*0x0000*/  struct ADBDPlayer::VTable* vtable;
/*0x0008*/  __inherited enum EObjectFlags UObjectBase::ObjectFlags;
/*0x000c*/  __inherited int32_t UObjectBase::InternalIndex;
/*0x0010*/  __inherited class UClass* UObjectBase::ClassPrivate;
/*0x0018*/  __inherited class FName UObjectBase::NamePrivate;
/*0x0020*/  __inherited class UObject* UObjectBase::OuterPrivate;
/*0x0028*/  __inherited struct FActorTickFunction AActor::PrimaryActorTick;
/*0x0078*/  __inherited float AActor::CustomTimeDilation;
/*0x007c*/  __inherited union
            {
              uint8_t bHidden;
              uint8_t bNetTemporary;
              uint8_t bNetStartup;
              uint8_t bOnlyRelevantToOwner;
              uint8_t bAlwaysRelevant;
              uint8_t bReplicateMovement;
              uint8_t bTearOff;
              uint8_t bExchangedRoles;
            } __bitfield7c;
/*0x007d*/  __inherited union
            {
              uint8_t bPendingNetUpdate;
              uint8_t bNetLoadOnClient;
              uint8_t bNetUseOwnerRelevancy;
              uint8_t bBlockInput;
              uint8_t bRunningUserConstructionScript;
              uint8_t bAllowTickBeforeBeginPlay;
              uint8_t bHasFinishedSpawning;
              uint8_t bTickFunctionsRegistered;
            } __bitfield7d;
/*0x007e*/  __inherited union
            {
              uint8_t bActorEnableCollision;
              uint8_t bNetCheckedInitialPhysicsState;
              uint8_t bReplicates;
            } __bitfield7e;
            __padding char _7f[1];
/*0x0080*/  __inherited class FName AActor::NetDriverName;
/*0x0088*/  __inherited class TEnumAsByte<enum ENetRole> AActor::RemoteRole;
/*0x0090*/  __inherited class AActor* AActor::Owner;
/*0x0098*/  __inherited struct FRepMovement AActor::ReplicatedMovement;
            __padding char _cc[4];
/*0x00d0*/  __inherited struct FRepAttachment AActor::AttachmentReplication;
/*0x0110*/  __inherited class TEnumAsByte<enum ENetRole> AActor::Role;
/*0x0111*/  __inherited class TEnumAsByte<enum ENetDormancy> AActor::NetDormancy;
/*0x0112*/  __inherited class TEnumAsByte<enum EAutoReceiveInput::Type> AActor::AutoReceiveInput;
/*0x0114*/  __inherited int32_t AActor::InputPriority;
/*0x0118*/  __inherited class UInputComponent* AActor::InputComponent;
/*0x0120*/  __inherited class TEnumAsByte<enum EInputConsumeOptions> AActor::InputConsumeOption_DEPRECATED;
/*0x0124*/  __inherited float AActor::NetCullDistanceSquared;
/*0x0128*/  __inherited int32_t AActor::NetTag;
/*0x012c*/  __inherited float AActor::NetUpdateTime;
/*0x0130*/  __inherited float AActor::NetUpdateFrequency;
/*0x0134*/  __inherited float AActor::MinNetUpdateFrequency;
/*0x0138*/  __inherited float AActor::NetPriority;
/*0x013c*/  __inherited float AActor::LastNetUpdateTime;
/*0x0140*/  __inherited union
            {
              uint8_t bAutoDestroyWhenFinished;
              uint8_t bCanBeDamaged;
              uint8_t bActorIsBeingDestroyed;
              uint8_t bCollideWhenPlacing;
              uint8_t bFindCameraComponentWhenViewTarget;
              uint8_t bRelevantForNetworkReplays;
              uint8_t bGenerateOverlapEventsDuringLevelStreaming;
            } __bitfield140;
/*0x0141*/  __inherited enum ESpawnActorCollisionHandlingMethod AActor::SpawnCollisionHandlingMethod;
/*0x0144*/  __inherited float AActor::CreationTime;
/*0x0148*/  __inherited class APawn* AActor::Instigator;
/*0x0150*/  __inherited class TArray<AActor *,FDefaultAllocator> AActor::Children;
/*0x0160*/  __inherited class USceneComponent* AActor::RootComponent;
/*0x0168*/  __inherited class TArray<AMatineeActor*, FDefaultAllocator> AActor::ControllingMatineeActors;
/*0x0178*/  __inherited float AActor::InitialLifeSpan;
/*0x017c*/  __padding char _17c[4];
/*0x0180*/  __inherited struct FTimerHandle AActor::TimerHandle_LifeSpanExpired;
/*0x0188*/  __inherited class TArray<FName, FDefaultAllocator> AActor::Layers;
/*0x0198*/  __inherited struct TWeakObjectPtr<AActor, FWeakObjectPtr> AActor::ParentComponentActor_DEPRECATED;
/*0x01a0*/  __inherited struct TWeakObjectPtr<UChildActorComponent, FWeakObjectPtr> AActor::ParentComponent;
/*0x01a8*/  __inherited union
            {
              uint8_t bAllowReceiveTickEventOnDedicatedServer;
              uint8_t bActorInitialized;
              enum AActor::EActorBeginPlayState ActorHasBegunPlay;
              uint8_t bActorSeamlessTraveled;
              uint8_t bIgnoresOriginShifting;
              uint8_t bEnableAutoLODGeneration;
            } __bitfield1a8;
            __padding char _1a9[7];
/*0x01b0*/  __inherited class TArray<FName, FDefaultAllocator> AActor::Tags;
/*0x01c0*/  __inherited uint64_t AActor::HiddenEditorViews;
/*0x01c8*/  __inherited class FTakeAnyDamageSignature AActor::OnTakeAnyDamage;
/*0x01d8*/  __inherited class FTakePointDamageSignature AActor::OnTakePointDamage;
/*0x01e8*/  __inherited class FActorBeginOverlapSignature AActor::OnActorBeginOverlap;
/*0x01f8*/  __inherited class FActorEndOverlapSignature AActor::OnActorEndOverlap;
/*0x0208*/  __inherited class FActorBeginCursorOverSignature AActor::OnBeginCursorOver;
/*0x0218*/  __inherited class FActorEndCursorOverSignature AActor::OnEndCursorOver;
/*0x0228*/  __inherited class FActorOnClickedSignature AActor::OnClicked;
/*0x0238*/  __inherited class FActorOnReleasedSignature AActor::OnReleased;
/*0x0248*/  __inherited class FActorOnInputTouchBeginSignature AActor::OnInputTouchBegin;
/*0x0258*/  __inherited class FActorOnInputTouchEndSignature AActor::OnInputTouchEnd;
/*0x0268*/  __inherited class FActorBeginTouchOverSignature AActor::OnInputTouchEnter;
/*0x0278*/  __inherited class FActorEndTouchOverSignature AActor::OnInputTouchLeave;
/*0x0288*/  __inherited class FActorHitSignature AActor::OnActorHit;
/*0x0298*/  __inherited class FActorDestroyedSignature AActor::OnDestroyed;
/*0x02a8*/  __inherited class FActorEndPlaySignature AActor::OnEndPlay;
/*0x02b8*/  __inherited class TSet<UActorComponent*, DefaultKeyFuncs<UActorComponent*, 0>,FDefaultSetAllocator> AActor::OwnedComponents;
/*0x0308*/  __inherited class TSet<UActorComponent*, DefaultKeyFuncs<UActorComponent*, 0>,FDefaultSetAllocator> AActor::ReplicatedComponents;
/*0x0358*/  __inherited class TArray<UActorComponent*, FDefaultAllocator> AActor::BlueprintCreatedComponents;
/*0x0368*/  __inherited class TArray<UActorComponent*, FDefaultAllocator> AActor::InstanceComponents;
/*0x0378*/  __inherited class FRenderCommandFence AActor::DetachFence;
/*0x0380*/  __inherited struct ADebugCameraController::APlayerController::AController::INavAgentInterface::VTable* INavAgentInterface::vtable;
/*0x0388*/  __inherited union
            {
              uint32_t bUseControllerRotationPitch;
              uint32_t bUseControllerRotationYaw;
              uint32_t bUseControllerRotationRoll;
              uint32_t bCanAffectNavigationGeneration;
              uint32_t bInputEnabled;
            } __bitfield388;
/*0x038c*/  __inherited float APawn::BaseEyeHeight;
/*0x0390*/  __inherited class TEnumAsByte<enum EAutoReceiveInput::Type> APawn::AutoPossessPlayer;
/*0x0391*/  __inherited enum EAutoPossessAI APawn::AutoPossessAI;
            __padding char _392[6];
/*0x0398*/  __inherited class TSubclassOf<AController> APawn::AIControllerClass;
/*0x03a0*/  __inherited class APlayerState* APawn::PlayerState;
/*0x03a8*/  __inherited uint8_t APawn::RemoteViewPitch;
/*0x03b0*/  __inherited class AController* APawn::LastHitBy;
/*0x03b8*/  __inherited class AController* APawn::Controller;
/*0x03c0*/  __inherited float APawn::AllowedYawError;
/*0x03c4*/  __inherited union
            {
              uint32_t bProcessingOutsideWorldBounds;
            } __bitfield3c4;
/*0x03c8*/  __inherited struct FVector APawn::ControlInputVector;
/*0x03d4*/  __inherited struct FVector APawn::LastControlInputVector;
/*0x03e0*/  __inherited class USkeletalMeshComponent* ACharacter::Mesh;
/*0x03e8*/  __inherited class UCharacterMovementComponent* ACharacter::CharacterMovement;
/*0x03f0*/  __inherited class UCapsuleComponent* ACharacter::CapsuleComponent;
/*0x03f8*/  __inherited struct FBasedMovementInfo ACharacter::BasedMovement;
/*0x0428*/  __inherited struct FBasedMovementInfo ACharacter::ReplicatedBasedMovement;
/*0x0458*/  __inherited float ACharacter::AnimRootMotionTranslationScale;
/*0x045c*/  __inherited struct FVector ACharacter::BaseTranslationOffset;
            __padding char _468[8];
/*0x0470*/  __inherited struct FQuat ACharacter::BaseRotationOffset;
/*0x0480*/  __inherited float ACharacter::ReplicatedServerLastTransformUpdateTimeStamp;
/*0x0484*/  __inherited uint8_t ACharacter::ReplicatedMovementMode;
/*0x0485*/  __inherited uint8_t ACharacter::bInBaseReplication;
/*0x0488*/  __inherited float ACharacter::CrouchedEyeHeight;
/*0x048c*/  __inherited union
            {
              uint32_t bIsCrouched;
              uint32_t bReplayHasRootMotionSources;
              uint32_t bPressedJump;
              uint32_t bClientUpdating;
              uint32_t bClientWasFalling;
              uint32_t bClientResimulateRootMotion;
              uint32_t bClientResimulateRootMotionSources;
              uint32_t bSimGravityDisabled;
              uint32_t bClientCheckEncroachmentOnNetUpdate;
              uint32_t bServerMoveIgnoreRootMotion;
            } __bitfield48c;
/*0x0490*/  __inherited float ACharacter::JumpKeyHoldTime;
/*0x0494*/  __inherited float ACharacter::JumpMaxHoldTime;
/*0x0498*/  __inherited int32_t ACharacter::JumpMaxCount;
/*0x049c*/  __inherited int32_t ACharacter::JumpCurrentCount;
/*0x04a0*/  __inherited union
            {
              uint32_t bJumpMaxCountExceeded;
            } __bitfield4a0;
            __padding char _4a4[4];
/*0x04a8*/  __inherited class FCharacterReachedApexSignature ACharacter::OnReachedJumpApex;
/*0x04b8*/  __inherited class FLandedSignature ACharacter::LandedDelegate;
/*0x04c8*/  __inherited class FMovementModeChangedSignature ACharacter::MovementModeChangedDelegate;
/*0x04d8*/  __inherited class FCharacterMovementUpdatedSignature ACharacter::OnCharacterMovementUpdated;
/*0x04e8*/  __inherited struct FRootMotionSourceGroup ACharacter::SavedRootMotion;
            __padding char _5e8[8];
/*0x05f0*/  __inherited struct FRootMotionMovementParams ACharacter::ClientRootMotionParams;
/*0x0630*/  __inherited class TArray<FSimulatedRootMotionReplicatedMove,FDefaultAllocator> ACharacter::RootMotionRepMoves;
/*0x0640*/  __inherited struct FRepRootMotionMontage ACharacter::RepRootMotion;
/*0x07a0*/  struct IPerkOwnerInterface::VTable* IPerkOwnerInterface::vtable;
/*0x07a8*/  struct IPerkManagerOwnerInterface::VTable* IPerkManagerOwnerInterface::vtable;
/*0x07b0*/  struct IAnimTagProvider::VTable* IAnimTagProvider::vtable;
/*0x07b8*/  float const kLoadingTime;
            __padding char _7bc[4];
/*0x07c0*/  class TSubclassOf<AInteractable> Interactable;
/*0x07c8*/  class FMovementInputDelegate OnMovementInput;
/*0x07d8*/  uint8_t AllowInterrupting;
            __padding char _7d9[3];
/*0x07dc*/  float MinFallHeight;
/*0x07e0*/  uint8_t IsInterruptable;
/*0x07e1*/  uint8_t IsStunned;
/*0x07e2*/  uint8_t IsAttacking;
/*0x07e3*/  uint8_t AllowNavigationInput;
/*0x07e4*/  uint8_t AllowNavigationBackwardInput;
/*0x07e5*/  uint8_t AllowTurningInput;
/*0x07e6*/  uint8_t AllowPitchInput;
/*0x07e8*/  float PitchLimitLower;
/*0x07ec*/  float PitchLimitUpper;
/*0x07f0*/  struct FVector StrafingOffset;
/*0x07fc*/  float PelvisHeight;
/*0x0800*/  float PelvisHeightForPounceOnStandingCamper;
/*0x0804*/  float PelvisHeightForPounceOnCrouchingCamper;
/*0x0808*/  class TSharedPtr<PollableEvent<bool>,0> MontageEndEvent;
/*0x0818*/  class TSharedPtr<PollableEvent<enum EAttackType>,0> AttackEvent;
/*0x0828*/  class TSharedPtr<ConsumableEvent<enum EAttackType>,0> AttackMontageEvent;
/*0x0838*/  class TSharedPtr<PollableEvent<bool>,0> InteractionCancelledEvent;
/*0x0848*/  class TSharedPtr<PollableEvent<FVector>,0> MovementInputEvent;
/*0x0858*/  class TSharedPtr<PollableEvent<bool>,0> BlinkEvent;
/*0x0868*/  class FAnimationStateDependencyUpdateDelegate OnAnimationStateDependencyUpdate;
/*0x0878*/  class FOnAttackedEvent OnAttackedDelegate;
            __padding char _888[8];
/*0x0890*/  class TBaseDelegate<void, ADBDPlayer*, enum EAttackType> OnAttackEvent;
/*0x08d0*/  class FOnSensedDelegate OnSensed;
/*0x08e0*/  class FAnimNotifyDelegate_Pickup OnAnimNotify_Pickup;
/*0x08f0*/  class FAnimNotifyDelegate_Release OnAnimNotify_Release;
/*0x0900*/  class FSecondaryActionInputDelegate OnSecondaryActionInput;
/*0x0910*/  class FOnFirstPersonModeChanged OnFirstPersonModeChanged;
/*0x0920*/  class USceneComponent* CameraAnchor;
/*0x0928*/  class USpringArmComponent* CameraBoom;
/*0x0930*/  class TBaseDelegate<void,UAnimMontage *,bool> OnMontageEndDelegate;
/*0x0970*/  class TBaseDelegate<void,UAnimMontage *,bool> OnMontageBlendingOutDelegate;
/*0x09b0*/  class TBaseDelegate<void,UInteractionDefinition *,bool> OnInteractionZoneOverlapDelegate;
/*0x09f0*/  uint8_t ForceDisableFootIK;
/*0x09f1*/  uint8_t ForceSkillChecks;
            __padding char _9f2[0xe];
/*0x0a00*/  struct FTransform IKLeftHandTransform;
/*0x0a30*/  struct FTransform IKRightHandTransform;
/*0x0a60*/  float CameraResetSpeed;
            __padding char _a64[4];
/*0x0a68*/  class FString CharacterName;
/*0x0a78*/  class FString CharacterClothes;
/*0x0a88*/  class FString CharacterShoes;
/*0x0a98*/  class FString CharacterWeapon;
/*0x0aa8*/  class FString CharacterAmbiance;
/*0x0ab8*/  class FString CharacterState;
/*0x0ac8*/  uint8_t _smLaunched;
/*0x0ac9*/  uint8_t _perksSpawned;
/*0x0aca*/  uint8_t _isMontageMode;
/*0x0acb*/  uint8_t DebugInteractionPriorityEnabled;
/*0x0acc*/  uint8_t CheatIsInterruptable;
/*0x0acd*/  uint8_t ForceDisableSkillChecks;
/*0x0ace*/  uint8_t DebugAutoInteractEnabled;
/*0x0ad0*/  float DebugAutoInteractDuration;
/*0x0ad4*/  float DebugAutoInteractPauseDelay;
/*0x0ad8*/  uint8_t DebugAutoItemInteractEnabled;
/*0x0ad9*/  uint8_t DebugAutoItemInteractPressed;
/*0x0adc*/  float DebugAutoItemInteractDuration;
/*0x0ae0*/  float DebugAutoItemInteractPauseDelay;
            __padding char _ae4[0xc];
/*0x0af0*/  class TBaseDelegate<void> OnEquippedItemUpdated;
/*0x0b30*/  float _emulatedYawInputDecay;
/*0x0b34*/  float _emulatedYawInputDecayWhenNoInput;
/*0x0b38*/  float _emulatedYawInputReleaseTime;
/*0x0b3c*/  float _emulatedYawInputDeadZone;
/*0x0b40*/  float _emulatedYawMinimumInput;
/*0x0b44*/  float _emulatedYawInputStrength;
/*0x0b48*/  class UCurveFloat* BlinkFOVCurve;
/*0x0b50*/  float CurrentBlinkDistance;
/*0x0b54*/  uint8_t IsInBlinkingState;
/*0x0b58*/  float AverageSpeedBufferTime;
/*0x0b5c*/  float AlmostCurrentSpeedBufferTime;
/*0x0b60*/  class UCurveFloat* GamepadYawCurve;
/*0x0b68*/  class UCurveFloat* GamepadPitchCurve;
/*0x0b70*/  class UChargeableComponent* BlindingChargeableComponent;
/*0x0b78*/  class FName CarryJointName;
/*0x0b80*/  class TArray<UCurveFloat *,FDefaultAllocator> AttackPounceCurves;
/*0x0b90*/  class TArray<UCurveFloat *,FDefaultAllocator> AttackLungeCurves;
/*0x0ba0*/  class TArray<UCurveFloat *,FDefaultAllocator> AttackSlashCurves;
/*0x0bb0*/  class TArray<UCurveFloat *,FDefaultAllocator> AttackChainsawCurves;
/*0x0bc0*/  class TArray<UCurveFloat *,FDefaultAllocator> AttackBlinkCurves;
/*0x0bd0*/  class TArray<UCurveFloat *,FDefaultAllocator> AttackPounceCurves_StalkTier0;
/*0x0be0*/  class TArray<UCurveFloat *,FDefaultAllocator> AttackPounceCurves_StalkTier1;
/*0x0bf0*/  class TArray<UCurveFloat *,FDefaultAllocator> AttackPounceCurves_StalkTier2;
/*0x0c00*/  float _pitchOffsetForInteractionPriority;
/*0x0c04*/  uint8_t IsInteracting;
/*0x0c05*/  uint8_t _cameraResetting;
/*0x0c08*/  float ClearPathTestRadiusMultiplier;
/*0x0c0c*/  float ClearPathTestHeightMultiplier;
/*0x0c10*/  float LocationClearTestRadiusMultiplier;
/*0x0c14*/  float LocationClearTestHeightMultiplier;
/*0x0c18*/  struct FDateTime _idleStart;
/*0x0c20*/  struct FDateTime _lastUpdate;
/*0x0c28*/  float ClearPathTestStepHeight;
/*0x0c2c*/  float GamePadTurnRate;
/*0x0c30*/  float GamePadLookUpRate;
/*0x0c34*/  float MouseTurnSpeedMultiplier;
/*0x0c38*/  float MouseLookUpSpeedMultiplier;
/*0x0c40*/  class USoundCue* DeathSound;
/*0x0c48*/  enum ECamperState CurrentCamperState;
            __padding char _c49[7];
/*0x0c50*/  class FName CollectableAttachPoint;
/*0x0c58*/  class TArray<ACollectable *,FDefaultAllocator> Inventory;
/*0x0c68*/  class TArray<UPerk *,FDefaultAllocator> _perks;
/*0x0c78*/  class TArray<FOffering,FDefaultAllocator> _offerings;
/*0x0c88*/  class TArray<UStatusEffect *,FDefaultAllocator> _statusEffects;
/*0x0c98*/  class TMap<AActor *,UFlashLightComponent *,FDefaultSetAllocator,TDefaultMapKeyFuncs<AActor *,UFlashLightComponent *,0> > _blindingEffectors;
/*0x0ce8*/  class UStateMachine* _SM;
/*0x0cf0*/  class UPlayerInteractionHandler* _interactionHandler;
/*0x0cf8*/  class UMontagePlayer* _montagePlayer;
/*0x0d00*/  class UPerkManager* _perkManager;
/*0x0d08*/  class UDBDPlayerData* _playerData;
/*0x0d10*/  class UAxisFlickMasher* _wiggleAxisFlickMasher;
/*0x0d18*/  class UInputMasher* _interactInputMasher;
/*0x0d20*/  uint8_t _isUsingGamepad;
            __padding char _d21[0xf];
/*0x0d30*/  class ADBDPlayer::FOnSwitchedInputControlsEvent _onSwitchedInputControlsEvent;
/*0x0da0*/  class AInteractable* _interactable;
/*0x0da8*/  class TMap<FName,float,FDefaultSetAllocator,TDefaultMapKeyFuncs<FName,float,0> > _tunableValueMap;
/*0x0df8*/  class TArray<ADBDPlayer *,FDefaultAllocator> _overlappingPlayers;
/*0x0e08*/  class ADBDPlayer* _guidingPlayer;
/*0x0e10*/  uint8_t _updateCapsuleSize;
/*0x0e11*/  uint8_t _crouchPressed;
/*0x0e18*/  class ADBDPlayer* _interactingPlayer;
/*0x0e20*/  struct FDBDTimer _loadingTimer;
/*0x0e40*/  float _movementSpeedMultiplier;
/*0x0e44*/  enum EAttackSubstate _nextAttackSubstate;
            __padding char _e45[2];
            __padding char _e47[1];
/*0x0e48*/  struct TWeakObjectPtr<ADBDPlayer,FWeakObjectPtr> _lockOnTarget;
/*0x0e50*/  struct TWeakObjectPtr<ADBDPlayer,FWeakObjectPtr> _damageTarget;
/*0x0e58*/  class UCharacterSnappingComponent* _characterSnappingComponent;
/*0x0e60*/  class UCameraHandlerComponent* _cameraHandlerComponent;
/*0x0e68*/  class USceneComponent* _itemDropOffPosition;
/*0x0e70*/  uint8_t _emulateGamepadForMouseYaw;
            __padding char _e71[7];
/*0x0e78*/  struct FDataTableProxy TunableDB;
/*0x0ea8*/  struct FDataTableProxy GlobalTunableDB;
/*0x0ed8*/  class TArray<AActor *,FDefaultAllocator> IgnoreActors;
/*0x0ee8*/  class TArray<FEffectCameraTypeSettings,FDefaultAllocator> EffectCameraTypeSettings;
/*0x0ef8*/  float _staminaRechargeRate;
/*0x0efc*/  struct FDBDTimer _postChaseTimer;
/*0x0f1c*/  float _postChaseTime;
/*0x0f20*/  struct FVector _targetStrafeOffset;
/*0x0f2c*/  struct FVector _startStrafeOffset;
/*0x0f38*/  float _strafeOffsetUpdateAlpha;
/*0x0f3c*/  float const kStrafeOffsetUpdateDuration;
/*0x0f40*/  uint8_t _isBeingInterrupted;
/*0x0f48*/  class UPollableEventListener* _eventListener;
/*0x0f50*/  uint8_t _debugAutoInteractPress;
            __padding char _f51[3];
/*0x0f54*/  struct FDBDTimer _debugAutoInteractTimer;
/*0x0f74*/  uint8_t _debugAutoItemInteractPress;
            __padding char _f75[3];
/*0x0f78*/  struct FDBDTimer _debugAutoItemInteractTimer;
/*0x0f98*/  uint8_t _isReadyToPlay;
/*0x0fa0*/  class UZoneDetectorComponent* _meatHookZoneDetector;
/*0x0fa8*/  uint8_t _feetAreOnGround;
/*0x0fa9*/  struct FAnimData _animData;
            __padding char _faa[2];
/*0x0fac*/  struct FVector _frameDisplacementAsSpeed;
/*0x0fb8*/  struct FVector _previousPosition;
/*0x0fc4*/  struct FVector _lastSafePosition;
/*0x0fd0*/  struct FVector _spawnPosition;
/*0x0fdc*/  float _secondsSinceLastSave;
/*0x0fe0*/  float _secondsSinceLastFell;
/*0x0fe4*/  uint8_t _invertLookUpAxis;
/*0x0fe8*/  int32_t _framesForSlasherAutoAttackOnCamperInteract;
/*0x0fec*/  float _originalGroundFriction;
/*0x0ff0*/  class FString _leftFootSurface;
/*0x1000*/  class FString _rightFootSurface;
/*0x1010*/  int32_t _numMeathooksInZone;
/*0x1014*/  enum EInteractionAnimation _interactionAnimation;
/*0x1018*/  float _attackingMaxSpeedPercent;
/*0x101c*/  float _interactingMaxSpeedPercent;
/*0x1020*/  uint8_t _isInterrupting;
/*0x1021*/  uint8_t _isSwappingInteraction;
/*0x1028*/  class UInteractionDefinition* _bookmarkedInteraction;
/*0x1030*/  class TMap<enum EDetectionZone,UPrimitiveComponent *,FDefaultSetAllocator,TDefaultMapKeyFuncs<enum EDetectionZone,UPrimitiveComponent *,0> > _detectionZoneMap;
/*0x1080*/  uint8_t _printServerPositionUpdateEnabled;
/*0x1081*/  uint8_t _inParadise;
/*0x1082*/  uint8_t _debugInteractionInZone;
            __padding char _1083[1];
/*0x1084*/  struct FDBDTimer _fastInteractInputPersistence;
/*0x10a8*/  class UAuthoritativeMovementComponent* _authoritativeMovementComponent;
/*0x10b0*/  struct FBitfield _authoritativeMovementFlags;
/*0x10b4*/  float _emulatedYawInput;
/*0x10b8*/  float _yawRateInput;
/*0x10bc*/  struct FDBDTimer _emulatedYawInputReleaseTimer;
/*0x10dc*/  uint8_t _forcedAuthoritativeUnmoveable;
/*0x10dd*/  uint8_t _windowFreeCam;
/*0x10de*/  uint8_t _reverseTraverse;
/*0x10df*/  uint8_t _runVault;
/*0x10e0*/  uint8_t _debugFailAllInteractions;
/*0x10e4*/  float _stamina;
/*0x10e8*/  struct FDBDTimer _staminaRechargeDelayTimer;
/*0x1108*/  struct FVector _blinkDestinationPosition;
/*0x1114*/  struct FRotator _blinkDestinationRotation;
/*0x1120*/  struct FVector _averageVelocity;
/*0x112c*/  struct FVector _almostCurrentVelocity;
/*0x1138*/  struct FDBDTimer _trapImmunityTimer;
/*0x1158*/  uint8_t _wasLocallyObserved;
            __padding char _1159[3];
/*0x115c*/  struct TWeakObjectPtr<UCameraComponent,FWeakObjectPtr> _cachedPlayerCamera;
/*0x1164*/  uint8_t _isHeadHidden;
/*0x1165*/  uint8_t _isInFirstPerson;
/*0x1168*/  float _blindnessRemainingTime;
/*0x116c*/  float _maxBlindnessDuration;
/*0x1170*/  float _recentlyBlindedCooldown;
/*0x1174*/  struct FDBDTimer _recentlyBlindedTimer;
            __padding char _1194[4];
/*0x1198*/  class FName InteractionKeys[31];
/*0x1290*/  float _screenAspectRatio;
};
