class __base(APlayerCameraManager, 0) ADBDPlayerCameraManager
{
/*0x0000*/  struct ADBDPlayer::VTable* vtable;
/*0x0008*/  __inherited enum EObjectFlags UObjectBase::ObjectFlags;
/*0x000c*/  __inherited int32_t UObjectBase::InternalIndex;
/*0x0010*/  __inherited class UClass* UObjectBase::ClassPrivate;
/*0x0018*/  __inherited class FName UObjectBase::NamePrivate;
/*0x0020*/  __inherited class UObject* UObjectBase::OuterPrivate;
/*0x0028*/  __inherited struct FActorTickFunction AActor::PrimaryActorTick;
/*0x0078*/  __inherited float AActor::CustomTimeDilation;
/*0x007c*/  __inherited union
            {
              uint8_t bHidden;
              uint8_t bNetTemporary;
              uint8_t bNetStartup;
              uint8_t bOnlyRelevantToOwner;
              uint8_t bAlwaysRelevant;
              uint8_t bReplicateMovement;
              uint8_t bTearOff;
              uint8_t bExchangedRoles;
            } __bitfield7c;
/*0x007d*/  __inherited union
            {
              uint8_t bPendingNetUpdate;
              uint8_t bNetLoadOnClient;
              uint8_t bNetUseOwnerRelevancy;
              uint8_t bBlockInput;
              uint8_t bRunningUserConstructionScript;
              uint8_t bAllowTickBeforeBeginPlay;
              uint8_t bHasFinishedSpawning;
              uint8_t bTickFunctionsRegistered;
            } __bitfield7d;
/*0x007e*/  __inherited union
            {
              uint8_t bActorEnableCollision;
              uint8_t bNetCheckedInitialPhysicsState;
              uint8_t bReplicates;
            } __bitfield7e;
            __padding char _7f[1];
/*0x0080*/  __inherited class FName AActor::NetDriverName;
/*0x0088*/  __inherited class TEnumAsByte<enum ENetRole> AActor::RemoteRole;
/*0x0090*/  __inherited class AActor* AActor::Owner;
/*0x0098*/  __inherited struct FRepMovement AActor::ReplicatedMovement;
            __padding char _cc[4];
/*0x00d0*/  __inherited struct FRepAttachment AActor::AttachmentReplication;
/*0x0110*/  __inherited class TEnumAsByte<enum ENetRole> AActor::Role;
/*0x0111*/  __inherited class TEnumAsByte<enum ENetDormancy> AActor::NetDormancy;
/*0x0112*/  __inherited class TEnumAsByte<enum EAutoReceiveInput::Type> AActor::AutoReceiveInput;
/*0x0114*/  __inherited int32_t AActor::InputPriority;
/*0x0118*/  __inherited class UInputComponent* AActor::InputComponent;
/*0x0120*/  __inherited class TEnumAsByte<enum EInputConsumeOptions> AActor::InputConsumeOption_DEPRECATED;
/*0x0124*/  __inherited float AActor::NetCullDistanceSquared;
/*0x0128*/  __inherited int32_t AActor::NetTag;
/*0x012c*/  __inherited float AActor::NetUpdateTime;
/*0x0130*/  __inherited float AActor::NetUpdateFrequency;
/*0x0134*/  __inherited float AActor::MinNetUpdateFrequency;
/*0x0138*/  __inherited float AActor::NetPriority;
/*0x013c*/  __inherited float AActor::LastNetUpdateTime;
/*0x0140*/  __inherited union
            {
              uint8_t bAutoDestroyWhenFinished;
              uint8_t bCanBeDamaged;
              uint8_t bActorIsBeingDestroyed;
              uint8_t bCollideWhenPlacing;
              uint8_t bFindCameraComponentWhenViewTarget;
              uint8_t bRelevantForNetworkReplays;
              uint8_t bGenerateOverlapEventsDuringLevelStreaming;
            } __bitfield140;
/*0x0141*/  __inherited enum ESpawnActorCollisionHandlingMethod AActor::SpawnCollisionHandlingMethod;
/*0x0144*/  __inherited float AActor::CreationTime;
/*0x0148*/  __inherited class APawn* AActor::Instigator;
/*0x0150*/  __inherited class TArray<AActor *,FDefaultAllocator> AActor::Children;
/*0x0160*/  __inherited class USceneComponent* AActor::RootComponent;
/*0x0168*/  __inherited class TArray<AMatineeActor*, FDefaultAllocator> AActor::ControllingMatineeActors;
/*0x0178*/  __inherited float AActor::InitialLifeSpan;
/*0x017c*/  __padding char _17c[4];
/*0x0180*/  __inherited struct FTimerHandle AActor::TimerHandle_LifeSpanExpired;
/*0x0188*/  __inherited class TArray<FName, FDefaultAllocator> AActor::Layers;
/*0x0198*/  __inherited struct TWeakObjectPtr<AActor, FWeakObjectPtr> AActor::ParentComponentActor_DEPRECATED;
/*0x01a0*/  __inherited struct TWeakObjectPtr<UChildActorComponent, FWeakObjectPtr> AActor::ParentComponent;
/*0x01a8*/  __inherited union
            {
              uint8_t bAllowReceiveTickEventOnDedicatedServer;
              uint8_t bActorInitialized;
              enum AActor::EActorBeginPlayState ActorHasBegunPlay;
              uint8_t bActorSeamlessTraveled;
              uint8_t bIgnoresOriginShifting;
              uint8_t bEnableAutoLODGeneration;
            } __bitfield1a8;
            __padding char _1a9[7];
/*0x01b0*/  __inherited class TArray<FName, FDefaultAllocator> AActor::Tags;
/*0x01c0*/  __inherited uint64_t AActor::HiddenEditorViews;
/*0x01c8*/  __inherited class FTakeAnyDamageSignature AActor::OnTakeAnyDamage;
/*0x01d8*/  __inherited class FTakePointDamageSignature AActor::OnTakePointDamage;
/*0x01e8*/  __inherited class FActorBeginOverlapSignature AActor::OnActorBeginOverlap;
/*0x01f8*/  __inherited class FActorEndOverlapSignature AActor::OnActorEndOverlap;
/*0x0208*/  __inherited class FActorBeginCursorOverSignature AActor::OnBeginCursorOver;
/*0x0218*/  __inherited class FActorEndCursorOverSignature AActor::OnEndCursorOver;
/*0x0228*/  __inherited class FActorOnClickedSignature AActor::OnClicked;
/*0x0238*/  __inherited class FActorOnReleasedSignature AActor::OnReleased;
/*0x0248*/  __inherited class FActorOnInputTouchBeginSignature AActor::OnInputTouchBegin;
/*0x0258*/  __inherited class FActorOnInputTouchEndSignature AActor::OnInputTouchEnd;
/*0x0268*/  __inherited class FActorBeginTouchOverSignature AActor::OnInputTouchEnter;
/*0x0278*/  __inherited class FActorEndTouchOverSignature AActor::OnInputTouchLeave;
/*0x0288*/  __inherited class FActorHitSignature AActor::OnActorHit;
/*0x0298*/  __inherited class FActorDestroyedSignature AActor::OnDestroyed;
/*0x02a8*/  __inherited class FActorEndPlaySignature AActor::OnEndPlay;
/*0x02b8*/  __inherited class TSet<UActorComponent*, DefaultKeyFuncs<UActorComponent*, 0>,FDefaultSetAllocator> AActor::OwnedComponents;
/*0x0308*/  __inherited class TSet<UActorComponent*, DefaultKeyFuncs<UActorComponent*, 0>,FDefaultSetAllocator> AActor::ReplicatedComponents;
/*0x0358*/  __inherited class TArray<UActorComponent*, FDefaultAllocator> AActor::BlueprintCreatedComponents;
/*0x0368*/  __inherited class TArray<UActorComponent*, FDefaultAllocator> AActor::InstanceComponents;
/*0x0378*/  __inherited class FRenderCommandFence AActor::DetachFence;
/*0xXXXXXXXXX*/  __inherited class APlayerController* APlayerCameraManager::PCOwner;
/*0x0378*/  __inherited class USceneComponent* APlayerCameraManager::TransformComponent;
/*0x0378*/  __inherited class FName APlayerCameraManager::CameraStyle;
/*0x0378*/  __inherited float APlayerCameraManager::DefaultFOV;
/*0x0378*/  __inherited float APlayerCameraManager::LockedFOV;
/*0x0378*/  __inherited float APlayerCameraManager::DefaultOrthoWidth;
/*0x0378*/  __inherited float APlayerCameraManager::LockedOrthoWidth;
/*0x0378*/  __inherited float APlayerCameraManager::DefaultAspectRatio;
/*0x0378*/  __inherited struct FLinearColor APlayerCameraManager::FadeColor;
/*0x0378*/  __inherited float APlayerCameraManager::FadeAmount;
/*0x0378*/  __inherited struct FVector APlayerCameraManager::ColorScale;
/*0x0378*/  __inherited struct FVector APlayerCameraManager::DesiredColorScale;
/*0x0378*/  __inherited struct FVector APlayerCameraManager::OriginalColorScale;
/*0x0378*/  __inherited float APlayerCameraManager::ColorScaleInterpDuration;
/*0x0378*/  __inherited float APlayerCameraManager::ColorScaleInterpStartTime;
            __padding char _3ec[4];
/*0x0378*/  __inherited struct FCameraCacheEntry APlayerCameraManager::CameraCache;
/*0x0378*/  __inherited struct FCameraCacheEntry APlayerCameraManager::LastFrameCameraCache;
/*0x0378*/  __inherited struct FTViewTarget APlayerCameraManager::ViewTarget;
/*0x0378*/  __inherited struct FTViewTarget APlayerCameraManager::PendingViewTarget;
/*0x0378*/  __inherited float APlayerCameraManager::BlendTimeToGo;
/*0x0378*/  __inherited struct FViewTargetTransitionParams APlayerCameraManager::BlendParams;
            __padding char _1394[4];
/*0x0378*/  __inherited class TArray<UCameraModifier *,FDefaultAllocator> APlayerCameraManager::ModifierList;
/*0x0378*/  __inherited class TArray<TSubclassOf<UCameraModifier>,FDefaultAllocator> APlayerCameraManager::DefaultModifiers;
/*0x0378*/  __inherited float APlayerCameraManager::FreeCamDistance;
/*0x0378*/  __inherited struct FVector APlayerCameraManager::FreeCamOffset;
/*0x0378*/  __inherited struct FVector APlayerCameraManager::ViewTargetOffset;
/*0x0378*/  __inherited struct FVector2D APlayerCameraManager::FadeAlpha;
/*0x0378*/  __inherited float APlayerCameraManager::FadeTime;
/*0x0378*/  __inherited float APlayerCameraManager::FadeTimeRemaining;
            __padding char _13e4[4];
/*0x0378*/  __inherited class TArray<AEmitterCameraLensEffectBase *,FDefaultAllocator> APlayerCameraManager::CameraLensEffects;
/*0x0378*/  __inherited class UCameraModifier_CameraShake* APlayerCameraManager::CachedCameraShakeMod;
/*0x0378*/  __inherited class UCameraAnimInst* APlayerCameraManager::AnimInstPool[0x8];
/*0x0378*/  __inherited class TArray<FPostProcessSettings,FDefaultAllocator> APlayerCameraManager::PostProcessBlendCache;
/*0x0378*/  __inherited class TArray<float,FDefaultAllocator> APlayerCameraManager::PostProcessBlendCacheWeights;
/*0x0378*/  __inherited class TArray<UCameraAnimInst *,FDefaultAllocator> APlayerCameraManager::ActiveAnims;
/*0x0378*/  __inherited class TArray<UCameraAnimInst *,FDefaultAllocator> APlayerCameraManager::FreeAnims;
/*0x0378*/  __inherited class ACameraActor* APlayerCameraManager::AnimCameraActor;
/*0x0378*/  __inherited union
            {
                uint32_t bIsOrthographic;
                uint32_t bEnableFading;
                uint32_t bFadeAudio;
                uint32_t bEnableColorScaling;
                uint32_t bEnableColorScaleInterp;
                uint32_t bClientSimulatingViewTarget;
                uint32_t bUseClientSideCameraUpdates;
                uint32_t bDebugClientSideCamera;
                uint32_t bShouldSendClientSideCameraUpdate;
                uint32_t bGameCameraCutThisFrame;
                uint32_t bHoldFadeWhenFinished;
                uint32_t bAutoAnimateFade;
                uint32_t bAlwaysApplyModifiers;
            } __bitfield1488;
/*0x0378*/  __inherited float APlayerCameraManager::ViewPitchMin;
/*0x0378*/  __inherited float APlayerCameraManager::ViewPitchMax;
/*0x0378*/  __inherited float APlayerCameraManager::ViewYawMin;
/*0x0378*/  __inherited float APlayerCameraManager::ViewYawMax;
/*0x0378*/  __inherited float APlayerCameraManager::ViewRollMin;
/*0x0378*/  __inherited float APlayerCameraManager::ViewRollMax;
            __padding char _14a4[4];
/*0x0378*/  float NormalFOV;
/*0x0378*/  float TargetingFOV;
};
