/* 00000000 */ struct /*VFT*/ ADBDPlayerController_Menu_vtbl // sizeof=0xE20
/* 00000000 */ {
/* 00000000 */     void (__fastcall *~UObject)(struct UObject *this);
/* 00000008 */     void (__fastcall *RegisterDependencies)(struct UObject *this);
/* 00000010 */     void (__fastcall *DeferredRegister)(struct UObject *this, UClass *, const wchar_t *, const wchar_t *);
/* 00000018 */     bool (__fastcall *CanBeClusterRoot)(struct UObject *this);
/* 00000020 */     bool (__fastcall *CanBeInCluster)(struct UObject *this);
/* 00000028 */     void (__fastcall *CreateCluster)(struct UObject *this);
/* 00000030 */     void (__fastcall *AddToCluster)(struct UObject *this, UObjectBaseUtility *);
/* 00000038 */     FString *(__fastcall *GetDetailedInfoInternal)(UObject *this, FString *result);
/* 00000040 */     void (__fastcall *PostInitProperties)(UObject *this);
/* 00000048 */     bool (__fastcall *PreSaveRoot)(UObject *this, const wchar_t *, TArray<FString,FDefaultAllocator> *);
/* 00000050 */     void (__fastcall *PostSaveRoot)(UObject *this, bool);
/* 00000058 */     void (__fastcall *PreSave)(UObject *this, const ITargetPlatform *);
/* 00000060 */     bool (__fastcall *Modify)(UObject *this, bool);
/* 00000068 */     void (__fastcall *PostLoad)(UObject *this);
/* 00000070 */     void (__fastcall *PostLoadSubobjects)(UObject *this, FObjectInstancingGraph *);
/* 00000078 */     void (__fastcall *BeginDestroy)(UObject *this);
/* 00000080 */     bool (__fastcall *IsReadyForFinishDestroy)(UObject *this);
/* 00000088 */     void (__fastcall *FinishDestroy)(UObject *this);
/* 00000090 */     void (__fastcall *Serialize)(UObject *this, FArchive *);
/* 00000098 */     void (__fastcall *ShutdownAfterError)(UObject *this);
/* 000000A0 */     void (__fastcall *PostInterpChange)(UObject *this, UProperty *);
/* 000000A8 */     void (__fastcall *PostRename)(UObject *this, UObject *, const FName);
/* 000000B0 */     void (__fastcall *PostDuplicate)(UObject *this, bool);
/* 000000B8 */     bool (__fastcall *NeedsLoadForClient)(UObject *this);
/* 000000C0 */     bool (__fastcall *NeedsLoadForServer)(UObject *this);
/* 000000C8 */     bool (__fastcall *NeedsLoadForEditorGame)(UObject *this);
/* 000000D0 */     bool (__fastcall *IsPostLoadThreadSafe)(UObject *this);
/* 000000D8 */     void (__fastcall *ExportCustomProperties)(UObject *this, FOutputDevice *, unsigned int);
/* 000000E0 */     void (__fastcall *ImportCustomProperties)(UObject *this, const wchar_t *, FFeedbackContext *);
/* 000000E8 */     void (__fastcall *PostEditImport)(UObject *this);
/* 000000F0 */     void (__fastcall *PostReloadConfig)(UObject *this, UProperty *);
/* 000000F8 */     bool (__fastcall *Rename)(UObject *this, const wchar_t *, UObject *, unsigned int);
/* 00000100 */     FString *(__fastcall *GetDesc)(UObject *this, FString *result);
/* 00000108 */     UWorld *(__fastcall *GetWorld)(UObject *this);
/* 00000110 */     bool (__fastcall *GetNativePropertyValues)(UObject *this, TMap<FString,FString,FDefaultSetAllocator,TDefaultMapKeyFuncs<FString,FString,0> > *, unsigned int);
/* 00000118 */     unsigned __int64 (__fastcall *GetResourceSize)(UObject *this, EResourceSizeMode::Type);
/* 00000120 */     FName *(__fastcall *GetExporterName)(UObject *this, FName *result);
/* 00000128 */     FRestoreForUObjectOverwrite *(__fastcall *GetRestoreForUObjectOverwrite)(UObject *this);
/* 00000130 */     bool (__fastcall *AreNativePropertiesIdenticalTo)(UObject *this, UObject *);
/* 00000138 */     void (__fastcall *GetAssetRegistryTags)(UObject *this, TArray<UObject::FAssetRegistryTag,FDefaultAllocator> *);
/* 00000140 */     bool (__fastcall *IsAsset)(UObject *this);
/* 00000148 */     bool (__fastcall *IsLocalizedResource)(UObject *this);
/* 00000150 */     bool (__fastcall *IsSafeForRootSet)(UObject *this);
/* 00000158 */     void (__fastcall *TagSubobjects)(UObject *this, EObjectFlags);
/* 00000160 */     void (__fastcall *GetLifetimeReplicatedProps)(UObject *this, TArray<FLifetimeProperty,FDefaultAllocator> *);
/* 00000168 */     bool (__fastcall *IsNameStableForNetworking)(UObject *this);
/* 00000170 */     bool (__fastcall *IsFullNameStableForNetworking)(UObject *this);
/* 00000178 */     bool (__fastcall *IsSupportedForNetworking)(UObject *this);
/* 00000180 */     void (__fastcall *GetSubobjectsWithStableNamesForNetworking)(UObject *this, TArray<UObject *,FDefaultAllocator> *);
/* 00000188 */     void (__fastcall *PreNetReceive)(UObject *this);
/* 00000190 */     void (__fastcall *PostNetReceive)(UObject *this);
/* 00000198 */     void (__fastcall *PostRepNotifies)(UObject *this);
/* 000001A0 */     void (__fastcall *PreDestroyFromReplication)(UObject *this);
/* 000001A8 */     void (__fastcall *ProcessEvent)(UObject *this, UFunction *, void *);
/* 000001B0 */     int (__fastcall *GetFunctionCallspace)(UObject *this, UFunction *, void *, FFrame *);
/* 000001B8 */     bool (__fastcall *CallRemoteFunction)(UObject *this, UFunction *, void *, FOutParmRec *, FFrame *);
/* 000001C0 */     bool (__fastcall *ProcessConsoleExec)(UObject *this, const wchar_t *, FOutputDevice *, UObject *);
/* 000001C8 */     UClass *(__fastcall *RegenerateClass)(UObject *this, UClass *, UObject *, TArray<UObject *,FDefaultAllocator> *);
/* 000001D0 */     void (__fastcall *MarkAsEditorOnlySubobject)(UObject *this);
/* 000001D8 */     bool (__fastcall *CheckDefaultSubobjectsInternal)(UObject *this);
/* 000001E0 */     void (__fastcall *OnRep_ReplicateMovement)(AActor *this);
/* 000001E8 */     void (__fastcall *TearOff)(AActor *this);
/* 000001F0 */     bool (__fastcall *HasNetOwner)(AActor *this);
/* 000001F8 */     void (__fastcall *OnRep_Owner)(AActor *this);
/* 00000200 */     void (__fastcall *SetReplicateMovement)(AActor *this, bool);
/* 00000208 */     void (__fastcall *OnRep_AttachmentReplication)(AActor *this);
/* 00000210 */     bool (__fastcall *IsReplicationPausedForConnection)(AActor *this, const FNetViewer *);
/* 00000218 */     void (__fastcall *OnReplicationPausedChanged)(AActor *this, bool);
/* 00000220 */     bool (__fastcall *ReplicateSubobjects)(AActor *this, UActorChannel *, FOutBunch *, FReplicationFlags *);
/* 00000228 */     void (__fastcall *OnSubobjectCreatedFromReplication)(AActor *this, UObject *);
/* 00000230 */     void (__fastcall *OnSubobjectDestroyFromReplication)(AActor *this, UObject *);
/* 00000238 */     void (__fastcall *PreReplication)(AActor *this, IRepChangedPropertyTracker *);
/* 00000240 */     void (__fastcall *OnRep_Instigator)(AActor *this);
/* 00000248 */     void (__fastcall *EnableInput)(AActor *this, APlayerController *);
/* 00000250 */     void (__fastcall *DisableInput)(AActor *this, APlayerController *);
/* 00000258 */     FVector *(__fastcall *GetVelocity)(AActor *this, FVector *result);
/* 00000260 */     void (__fastcall *SetActorHiddenInGame)(AActor *this, bool);
/* 00000268 */     void (__fastcall *K2_DestroyActor)(AActor *this);
/* 00000270 */     void (__fastcall *AddTickPrerequisiteActor)(AActor *this, AActor *);
/* 00000278 */     void (__fastcall *AddTickPrerequisiteComponent)(AActor *this, UActorComponent *);
/* 00000280 */     void (__fastcall *RemoveTickPrerequisiteActor)(AActor *this, AActor *);
/* 00000288 */     void (__fastcall *RemoveTickPrerequisiteComponent)(AActor *this, UActorComponent *);
/* 00000290 */     void (__fastcall *BeginPlay)(AActor *this);
/* 00000298 */     void (__fastcall *NotifyActorBeginOverlap)(AActor *this, AActor *);
/* 000002A0 */     void (__fastcall *NotifyActorEndOverlap)(AActor *this, AActor *);
/* 000002A8 */     void (__fastcall *NotifyActorBeginCursorOver)(AActor *this);
/* 000002B0 */     void (__fastcall *NotifyActorEndCursorOver)(AActor *this);
/* 000002B8 */     void (__fastcall *NotifyActorOnClicked)(AActor *this, FKey);
/* 000002C0 */     void (__fastcall *NotifyActorOnReleased)(AActor *this, FKey);
/* 000002C8 */     void (__fastcall *NotifyActorOnInputTouchBegin)(AActor *this, const ETouchIndex::Type);
/* 000002D0 */     void (__fastcall *NotifyActorOnInputTouchEnd)(AActor *this, const ETouchIndex::Type);
/* 000002D8 */     void (__fastcall *NotifyActorOnInputTouchEnter)(AActor *this, const ETouchIndex::Type);
/* 000002E0 */     void (__fastcall *NotifyActorOnInputTouchLeave)(AActor *this, const ETouchIndex::Type);
/* 000002E8 */     void (__fastcall *NotifyHit)(AActor *this, UPrimitiveComponent *, AActor *, UPrimitiveComponent *, bool, FVector, FVector, FVector, const FHitResult *);
/* 000002F0 */     void (__fastcall *SetLifeSpan)(AActor *this, float);
/* 000002F8 */     float (__fastcall *GetLifeSpan)(AActor *this);
/* 00000300 */     void (__fastcall *GatherCurrentMovement)(AActor *this);
/* 00000308 */     USceneComponent *(__fastcall *GetDefaultAttachComponent)(AActor *this);
/* 00000310 */     void (__fastcall *ApplyWorldOffset)(AActor *this, const FVector *, bool);
/* 00000318 */     bool (__fastcall *IsLevelBoundsRelevant)(AActor *this);
/* 00000320 */     float (__fastcall *GetNetPriority)(AActor *this, const FVector *, const FVector *, APlayerController *, UActorChannel *, float, bool);
/* 00000328 */     float (__fastcall *GetNetPriority)(AActor *this, const FVector *, const FVector *, AActor *, AActor *, UActorChannel *, float, bool);
/* 00000330 */     float (__fastcall *GetReplayPriority)(AActor *this, const FVector *, const FVector *, AActor *, AActor *, UActorChannel *const, float);
/* 00000338 */     bool (__fastcall *GetNetDormancy)(AActor *this, const FVector *, const FVector *, APlayerController *, AActor *, UActorChannel *, float, bool);
/* 00000340 */     bool (__fastcall *GetNetDormancy)(AActor *this, const FVector *, const FVector *, AActor *, AActor *, UActorChannel *, float, bool);
/* 00000348 */     void (__fastcall *OnActorChannelOpen)(AActor *this, FInBunch *, UNetConnection *);
/* 00000350 */     bool (__fastcall *UseShortConnectTimeout)(AActor *this);
/* 00000358 */     void (__fastcall *OnSerializeNewActor)(AActor *this, FOutBunch *);
/* 00000360 */     void (__fastcall *OnNetCleanup)(AActor *this, UNetConnection *);
/* 00000368 */     void (__fastcall *TickActor)(AActor *this, float, ELevelTick, FActorTickFunction *);
/* 00000370 */     void (__fastcall *PostActorCreated)(AActor *this);
/* 00000378 */     void (__fastcall *LifeSpanExpired)(AActor *this);
/* 00000380 */     void (__fastcall *PostNetInit)(AActor *this);
/* 00000388 */     void (__fastcall *OnRep_ReplicatedMovement)(AActor *this);
/* 00000390 */     void (__fastcall *PostNetReceiveLocation)(AActor *this);
/* 00000398 */     void (__fastcall *PostNetReceiveLocationAndRotation)(AActor *this);
/* 000003A0 */     void (__fastcall *PostNetReceiveVelocity)(AActor *this, const FVector *);
/* 000003A8 */     void (__fastcall *PostNetReceivePhysicState)(AActor *this);
/* 000003B0 */     void (__fastcall *SetOwner)(AActor *this, AActor *);
/* 000003B8 */     bool (__fastcall *CheckStillInWorld)(AActor *this);
/* 000003C0 */     void (__fastcall *Tick)(AActor *this, float);
/* 000003C8 */     bool (__fastcall *ShouldTickIfViewportsOnly)(AActor *this);
/* 000003D0 */     bool (__fastcall *IsNetRelevantFor)(AActor *this, const APlayerController *, const AActor *, const FVector *);
/* 000003D8 */     bool (__fastcall *IsNetRelevantFor)(AActor *this, const AActor *, const AActor *, const FVector *);
/* 000003E0 */     bool (__fastcall *IsRelevancyOwnerFor)(AActor *this, const AActor *, const AActor *, const AActor *);
/* 000003E8 */     void (__fastcall *PreInitializeComponents)(AActor *this);
/* 000003F0 */     void (__fastcall *PostInitializeComponents)(AActor *this);
/* 000003F8 */     const AActor *(__fastcall *GetNetOwner)(AActor *this);
/* 00000400 */     UPlayer *(__fastcall *GetNetOwningPlayer)(AActor *this);
/* 00000408 */     UNetConnection *(__fastcall *GetNetConnection)(AActor *this);
/* 00000410 */     bool (__fastcall *DestroyNetworkActorHandled)(AActor *this);
/* 00000418 */     void (__fastcall *RegisterAllComponents)(AActor *this);
/* 00000420 */     void (__fastcall *PostRegisterAllComponents)(AActor *this);
/* 00000428 */     void (__fastcall *UnregisterAllComponents)(AActor *this, bool);
/* 00000430 */     void (__fastcall *PostUnregisterAllComponents)(AActor *this);
/* 00000438 */     void (__fastcall *ReregisterAllComponents)(AActor *this);
/* 00000440 */     void (__fastcall *MarkComponentsAsPendingKill)(AActor *this);
/* 00000448 */     void (__fastcall *InvalidateLightingCacheDetailed)(AActor *this, bool);
/* 00000450 */     bool (__fastcall *TeleportTo)(AActor *this, const FVector *, const FRotator *, bool, bool);
/* 00000458 */     void (__fastcall *TeleportSucceeded)(AActor *this, bool);
/* 00000460 */     void (__fastcall *ClearCrossLevelReferences)(AActor *this);
/* 00000468 */     void (__fastcall *EndPlay)(AActor *this, const EEndPlayReason::Type);
/* 00000470 */     bool (__fastcall *IsBasedOnActor)(AActor *this, const AActor *);
/* 00000478 */     bool (__fastcall *IsAttachedTo)(AActor *this, const AActor *);
/* 00000480 */     void (__fastcall *RerunConstructionScripts)(AActor *this);
/* 00000488 */     void (__fastcall *OnConstruction)(AActor *this, const FTransform *);
/* 00000490 */     void (__fastcall *RegisterActorTickFunctions)(AActor *this, bool);
/* 00000498 */     AActor *(__fastcall *GetAttachParentActor)(AActor *this);
/* 000004A0 */     FName *(__fastcall *GetAttachParentSocketName)(AActor *this, FName *result);
/* 000004A8 */     void (__fastcall *GetAttachedActors)(AActor *this, TArray<AActor *,FDefaultAllocator> *);
/* 000004B0 */     void (__fastcall *Destroyed)(AActor *this);
/* 000004B8 */     void (__fastcall *FellOutOfWorld)(AActor *this, const UDamageType *);
/* 000004C0 */     void (__fastcall *OutsideWorldBounds)(AActor *this);
/* 000004C8 */     FBox *(__fastcall *GetComponentsBoundingBox)(AActor *this, FBox *result, bool);
/* 000004D0 */     FBox *(__fastcall *CalculateComponentsBoundingBoxInLocalSpace)(AActor *this, FBox *result, bool);
/* 000004D8 */     void (__fastcall *GetComponentsBoundingCylinder)(AActor *this, float *, float *, bool);
/* 000004E0 */     void (__fastcall *GetSimpleCollisionCylinder)(AActor *this, float *, float *);
/* 000004E8 */     bool (__fastcall *IsRootComponentCollisionRegistered)(AActor *this);
/* 000004F0 */     void (__fastcall *TornOff)(AActor *this);
/* 000004F8 */     ECollisionResponse (__fastcall *GetComponentsCollisionResponseToChannel)(AActor *this, ECollisionChannel);
/* 00000500 */     bool (__fastcall *CanBeBaseForCharacter)(AActor *this, APawn *);
/* 00000508 */     float (__fastcall *TakeDamage)(AActor *this, float, const FDamageEvent *, AController *, AActor *);
/* 00000510 */     float (__fastcall *InternalTakeRadialDamage)(AActor *this, float, const FRadialDamageEvent *, AController *, AActor *);
/* 00000518 */     float (__fastcall *InternalTakePointDamage)(AActor *this, float, const FPointDamageEvent *, AController *, AActor *);
/* 00000520 */     void (__fastcall *BecomeViewTarget)(AActor *this, APlayerController *);
/* 00000528 */     void (__fastcall *EndViewTarget)(AActor *this, APlayerController *);
/* 00000530 */     void (__fastcall *CalcCamera)(AActor *this, float, FMinimalViewInfo *);
/* 00000538 */     bool (__fastcall *HasActiveCameraComponent)(AActor *this);
/* 00000540 */     bool (__fastcall *HasActivePawnControlCameraComponent)(AActor *this);
/* 00000548 */     FString *(__fastcall *GetHumanReadableName)(AActor *this, FString *result);
/* 00000550 */     void (__fastcall *Reset)(AActor *this);
/* 00000558 */     float (__fastcall *GetLastRenderTime)(AActor *this);
/* 00000560 */     void (__fastcall *ForceNetRelevant)(AActor *this);
/* 00000568 */     void (__fastcall *ForceNetUpdate)(AActor *this);
/* 00000570 */     void (__fastcall *PrestreamTextures)(AActor *this, float, bool, int);
/* 00000578 */     void (__fastcall *GetActorEyesViewPoint)(AActor *this, FVector *, FRotator *);
/* 00000580 */     FVector *(__fastcall *GetTargetLocation)(AActor *this, FVector *result, AActor *);
/* 00000588 */     void (__fastcall *PostRenderFor)(AActor *this, APlayerController *, UCanvas *, FVector, FVector);
/* 00000590 */     UActorComponent *(__fastcall *FindComponentByClass)(AActor *this, const TSubclassOf<UActorComponent>);
/* 00000598 */     bool (__fastcall *IsComponentRelevantForNavigation)(AActor *this, UActorComponent *);
/* 000005A0 */     void (__fastcall *DisplayDebug)(AActor *this, UCanvas *, const FDebugDisplayInfo *, float *, float *);
/* 000005A8 */     void (__fastcall *ClientSetRotation_Implementation)(AController *this, FRotator, bool);
/* 000005B0 */     void (__fastcall *ClientSetLocation_Implementation)(AController *this, FVector, FRotator);
/* 000005B8 */     FRotator *(__fastcall *GetControlRotation)(AController *this, FRotator *result);
/* 000005C0 */     void (__fastcall *SetControlRotation)(AController *this, const FRotator *);
/* 000005C8 */     void (__fastcall *SetInitialLocationAndRotation)(AController *this, const FVector *, const FRotator *);
/* 000005D0 */     void (__fastcall *AttachToPawn)(AController *this, APawn *);
/* 000005D8 */     void (__fastcall *DetachFromPawn)(AController *this);
/* 000005E0 */     void (__fastcall *AddPawnTickDependency)(AController *this, APawn *);
/* 000005E8 */     void (__fastcall *RemovePawnTickDependency)(AController *this, APawn *);
/* 000005F0 */     void (__fastcall *ChangeState)(AController *this, FName);
/* 000005F8 */     bool (__fastcall *LineOfSightTo)(AController *this, const AActor *, FVector, bool);
/* 00000600 */     void (__fastcall *OnRep_Pawn)(AController *this);
/* 00000608 */     void (__fastcall *OnRep_PlayerState)(AController *this);
/* 00000610 */     void (__fastcall *SetPawn)(AController *this, APawn *);
/* 00000618 */     AActor *(__fastcall *GetViewTarget)(AController *this);
/* 00000620 */     FRotator *(__fastcall *GetDesiredRotation)(AController *this, FRotator *result);
/* 00000628 */     bool (__fastcall *IsLocalController)(AController *this);
/* 00000630 */     void (__fastcall *CleanupPlayerState)(AController *this);
/* 00000638 */     void (__fastcall *Possess)(AController *this, APawn *);
/* 00000640 */     void (__fastcall *UnPossess)(AController *this);
/* 00000648 */     void (__fastcall *PawnPendingDestroy)(AController *this, APawn *);
/* 00000650 */     void (__fastcall *NotifyKilled)(AController *this, AController *, AController *, APawn *, const UDamageType *);
/* 00000658 */     void (__fastcall *InstigatedAnyDamage)(AController *this, float, const UDamageType *, AActor *, AActor *);
/* 00000660 */     void (__fastcall *InitPlayerState)(AController *this);
/* 00000668 */     void (__fastcall *GameHasEnded)(AController *this, AActor *, bool);
/* 00000670 */     void (__fastcall *GetPlayerViewPoint)(AController *this, FVector *, FRotator *);
/* 00000678 */     void (__fastcall *FailedToSpawnPawn)(AController *this);
/* 00000680 */     void (__fastcall *InitNavigationControl)(AController *this, UPathFollowingComponent **);
/* 00000688 */     void (__fastcall *UpdateNavigationComponents)(AController *this);
/* 00000690 */     void (__fastcall *StopMovement)(AController *this);
/* 00000698 */     void (__fastcall *SetIgnoreMoveInput)(AController *this, bool);
/* 000006A0 */     void (__fastcall *ResetIgnoreMoveInput)(AController *this);
/* 000006A8 */     bool (__fastcall *IsMoveInputIgnored)(AController *this);
/* 000006B0 */     void (__fastcall *SetIgnoreLookInput)(AController *this, bool);
/* 000006B8 */     void (__fastcall *ResetIgnoreLookInput)(AController *this);
/* 000006C0 */     bool (__fastcall *IsLookInputIgnored)(AController *this);
/* 000006C8 */     void (__fastcall *ResetIgnoreInputFlags)(AController *this);
/* 000006D0 */     void (__fastcall *BeginInactiveState)(AController *this);
/* 000006D8 */     void (__fastcall *EndInactiveState)(AController *this);
/* 000006E0 */     void (__fastcall *CurrentLevelUnloaded)(AController *this);
/* 000006E8 */     void (__fastcall *OnServerStartedVisualLogger_Implementation)(APlayerController *this, bool);
/* 000006F0 */     bool (__fastcall *ServerToggleAILogging_Validate)(APlayerController *this);
/* 000006F8 */     void (__fastcall *ServerToggleAILogging_Implementation)(APlayerController *this);
/* 00000700 */     void (__fastcall *ClientTeamMessage_Implementation)(APlayerController *this, APlayerState *, const FString *, FName, float);
/* 00000708 */     bool (__fastcall *ServerViewSelf_Validate)(APlayerController *this, FViewTargetTransitionParams);
/* 00000710 */     void (__fastcall *ServerViewSelf_Implementation)(APlayerController *this, FViewTargetTransitionParams);
/* 00000718 */     bool (__fastcall *ServerViewPrevPlayer_Validate)(APlayerController *this);
/* 00000720 */     void (__fastcall *ServerViewPrevPlayer_Implementation)(APlayerController *this);
/* 00000728 */     bool (__fastcall *ServerViewNextPlayer_Validate)(APlayerController *this);
/* 00000730 */     void (__fastcall *ServerViewNextPlayer_Implementation)(APlayerController *this);
/* 00000738 */     bool (__fastcall *ServerVerifyViewTarget_Validate)(APlayerController *this);
/* 00000740 */     void (__fastcall *ServerVerifyViewTarget_Implementation)(APlayerController *this);
/* 00000748 */     bool (__fastcall *ServerUpdateCamera_Validate)(APlayerController *this, FVector_NetQuantize, int);
/* 00000750 */     void (__fastcall *ServerUpdateCamera_Implementation)(APlayerController *this, FVector_NetQuantize, int);
/* 00000758 */     bool (__fastcall *ServerShortTimeout_Validate)(APlayerController *this);
/* 00000760 */     void (__fastcall *ServerShortTimeout_Implementation)(APlayerController *this);
/* 00000768 */     bool (__fastcall *ServerCheckClientPossessionReliable_Validate)(APlayerController *this);
/* 00000770 */     void (__fastcall *ServerCheckClientPossessionReliable_Implementation)(APlayerController *this);
/* 00000778 */     bool (__fastcall *ServerCheckClientPossession_Validate)(APlayerController *this);
/* 00000780 */     void (__fastcall *ServerCheckClientPossession_Implementation)(APlayerController *this);
/* 00000788 */     bool (__fastcall *ServerSetSpectatorLocation_Validate)(APlayerController *this, FVector, FRotator);
/* 00000790 */     void (__fastcall *ServerSetSpectatorLocation_Implementation)(APlayerController *this, FVector, FRotator);
/* 00000798 */     bool (__fastcall *ServerRestartPlayer_Validate)(APlayerController *this);
/* 000007A0 */     void (__fastcall *ServerRestartPlayer_Implementation)(APlayerController *this);
/* 000007A8 */     bool (__fastcall *ServerPause_Validate)(APlayerController *this);
/* 000007B0 */     void (__fastcall *ServerPause_Implementation)(APlayerController *this);
/* 000007B8 */     bool (__fastcall *ServerChangeName_Validate)(APlayerController *this, const FString *);
/* 000007C0 */     void (__fastcall *ServerChangeName_Implementation)(APlayerController *this, const FString *);
/* 000007C8 */     bool (__fastcall *ServerCamera_Validate)(APlayerController *this, FName);
/* 000007D0 */     void (__fastcall *ServerCamera_Implementation)(APlayerController *this, FName);
/* 000007D8 */     bool (__fastcall *ServerAcknowledgePossession_Validate)(APlayerController *this, APawn *);
/* 000007E0 */     void (__fastcall *ServerAcknowledgePossession_Implementation)(APlayerController *this, APawn *);
/* 000007E8 */     void (__fastcall *ClientReceiveLocalizedMessage_Implementation)(APlayerController *this, TSubclassOf<ULocalMessage>, int, APlayerState *, APlayerState *, UObject *);
/* 000007F0 */     void (__fastcall *ClientRetryClientRestart_Implementation)(APlayerController *this, APawn *);
/* 000007F8 */     void (__fastcall *ClientEndOnlineSession_Implementation)(APlayerController *this);
/* 00000800 */     void (__fastcall *ClientStartOnlineSession_Implementation)(APlayerController *this);
/* 00000808 */     void (__fastcall *ClientWasKicked_Implementation)(APlayerController *this, unsigned int, unsigned int, const FString *);
/* 00000810 */     void (__fastcall *ClientUpdateLevelStreamingStatus_Implementation)(APlayerController *this, FName, bool, bool, bool, int);
/* 00000818 */     void (__fastcall *ClientTravelInternal_Implementation)(APlayerController *this, const FString *, ETravelType, bool, FGuid);
/* 00000820 */     void (__fastcall *ClientStopForceFeedback_Implementation)(APlayerController *this, UForceFeedbackEffect *, FName);
/* 00000828 */     void (__fastcall *ClientPlayForceFeedback_Implementation)(APlayerController *this, UForceFeedbackEffect *, bool, FName);
/* 00000830 */     void (__fastcall *ClientStopCameraShake_Implementation)(APlayerController *this, TSubclassOf<UCameraShake>, bool);
/* 00000838 */     void (__fastcall *ClientStopCameraAnim_Implementation)(APlayerController *this, UCameraAnim *);
/* 00000840 */     void (__fastcall *ClientClearCameraLensEffects_Implementation)(APlayerController *this);
/* 00000848 */     void (__fastcall *ClientSpawnCameraLensEffect_Implementation)(APlayerController *this, TSubclassOf<AEmitterCameraLensEffectBase>);
/* 00000850 */     void (__fastcall *ClientSetViewTarget_Implementation)(APlayerController *this, AActor *, FViewTargetTransitionParams);
/* 00000858 */     void (__fastcall *ClientSetHUD_Implementation)(APlayerController *this, TSubclassOf<AHUD>);
/* 00000860 */     void (__fastcall *ClientSetForceMipLevelsToBeResident_Implementation)(APlayerController *this, UMaterialInterface *, float, int);
/* 00000868 */     void (__fastcall *ClientSetCinematicMode_Implementation)(APlayerController *this, bool, bool, bool, bool);
/* 00000870 */     void (__fastcall *ClientSetCameraMode_Implementation)(APlayerController *this, FName);
/* 00000878 */     void (__fastcall *ClientSetCameraFade_Implementation)(APlayerController *this, bool, FColor, FVector2D, float, bool);
/* 00000880 */     void (__fastcall *ClientSetBlockOnAsyncLoading_Implementation)(APlayerController *this);
/* 00000888 */     void (__fastcall *ClientRestart_Implementation)(APlayerController *this, APawn *);
/* 00000890 */     void (__fastcall *ClientReset_Implementation)(APlayerController *this);
/* 00000898 */     void (__fastcall *ClientPrestreamTextures_Implementation)(APlayerController *this, AActor *, float, bool, int);
/* 000008A0 */     void (__fastcall *ClientPrepareMapChange_Implementation)(APlayerController *this, FName, bool, bool);
/* 000008A8 */     void (__fastcall *ClientPlaySoundAtLocation_Implementation)(APlayerController *this, USoundBase *, FVector, float, float);
/* 000008B0 */     void (__fastcall *ClientPlaySound_Implementation)(APlayerController *this, USoundBase *, float, float);
/* 000008B8 */     void (__fastcall *ClientPlayCameraShake_Implementation)(APlayerController *this, TSubclassOf<UCameraShake>, float, ECameraAnimPlaySpace::Type, FRotator);
/* 000008C0 */     void (__fastcall *ClientPlayCameraAnim_Implementation)(APlayerController *this, UCameraAnim *, float, float, float, float, bool, bool, ECameraAnimPlaySpace::Type, FRotator);
/* 000008C8 */     void (__fastcall *ClientMessage_Implementation)(APlayerController *this, const FString *, FName, float);
/* 000008D0 */     void (__fastcall *ClientIgnoreMoveInput_Implementation)(APlayerController *this, bool);
/* 000008D8 */     void (__fastcall *ClientIgnoreLookInput_Implementation)(APlayerController *this, bool);
/* 000008E0 */     void (__fastcall *ClientGotoState_Implementation)(APlayerController *this, FName);
/* 000008E8 */     void (__fastcall *ClientGameEnded_Implementation)(APlayerController *this, AActor *, bool);
/* 000008F0 */     void (__fastcall *ClientForceGarbageCollection_Implementation)(APlayerController *this);
/* 000008F8 */     void (__fastcall *ClientCommitMapChange_Implementation)(APlayerController *this);
/* 00000900 */     void (__fastcall *ClientCapBandwidth_Implementation)(APlayerController *this, int);
/* 00000908 */     void (__fastcall *ClientCancelPendingMapChange_Implementation)(APlayerController *this);
/* 00000910 */     void (__fastcall *ClientUnmutePlayer_Implementation)(APlayerController *this, FUniqueNetIdRepl);
/* 00000918 */     void (__fastcall *ClientMutePlayer_Implementation)(APlayerController *this, FUniqueNetIdRepl);
/* 00000920 */     bool (__fastcall *ServerUnmutePlayer_Validate)(APlayerController *this, FUniqueNetIdRepl);
/* 00000928 */     void (__fastcall *ServerUnmutePlayer_Implementation)(APlayerController *this, FUniqueNetIdRepl);
/* 00000930 */     bool (__fastcall *ServerMutePlayer_Validate)(APlayerController *this, FUniqueNetIdRepl);
/* 00000938 */     void (__fastcall *ServerMutePlayer_Implementation)(APlayerController *this, FUniqueNetIdRepl);
/* 00000940 */     void (__fastcall *ClientVoiceHandshakeComplete_Implementation)(APlayerController *this);
/* 00000948 */     void (__fastcall *ClientEnableNetworkVoice_Implementation)(APlayerController *this, bool);
/* 00000950 */     void (__fastcall *ClientRepObjRef_Implementation)(APlayerController *this, UObject *);
/* 00000958 */     void (__fastcall *ClientReturnToMainMenu_Implementation)(APlayerController *this, const FString *);
/* 00000960 */     void (__fastcall *ClientSetSpectatorWaiting_Implementation)(APlayerController *this, bool);
/* 00000968 */     bool (__fastcall *ServerSetSpectatorWaiting_Validate)(APlayerController *this, bool);
/* 00000970 */     void (__fastcall *ServerSetSpectatorWaiting_Implementation)(APlayerController *this, bool);
/* 00000978 */     void (__fastcall *EnableCheats)(APlayerController *this);
/* 00000980 */     void (__fastcall *UnFreeze)(APlayerController *this);
/* 00000988 */     float (__fastcall *GetMinRespawnDelay)(APlayerController *this);
/* 00000990 */     void (__fastcall *FOV)(APlayerController *this, float);
/* 00000998 */     void (__fastcall *RestartLevel)(APlayerController *this);
/* 000009A0 */     void (__fastcall *LocalTravel)(APlayerController *this, const FString *);
/* 000009A8 */     void (__fastcall *ClientReturnToMainMenu)(APlayerController *this, const FString *);
/* 000009B0 */     void (__fastcall *ClientRepObjRef)(APlayerController *this, UObject *);
/* 000009B8 */     bool (__fastcall *SetPause)(APlayerController *this, bool, TBaseDelegate<bool>);
/* 000009C0 */     void (__fastcall *Pause)(APlayerController *this);
/* 000009C8 */     void (__fastcall *SetName)(APlayerController *this, const FString *);
/* 000009D0 */     void (__fastcall *SwitchLevel)(APlayerController *this, const FString *);
/* 000009D8 */     void (__fastcall *NotifyLoadedWorld)(APlayerController *this, FName, bool);
/* 000009E0 */     void (__fastcall *PlayerTick)(APlayerController *this, float);
/* 000009E8 */     void (__fastcall *PreProcessInput)(APlayerController *this, const float, const bool);
/* 000009F0 */     void (__fastcall *PostProcessInput)(APlayerController *this, const float, const bool);
/* 000009F8 */     void (__fastcall *SetCinematicMode)(APlayerController *this, bool, bool, bool, bool, bool);
/* 00000A00 */     void (__fastcall *SetCinematicMode)(APlayerController *this, bool, bool, bool);
/* 00000A08 */     void (__fastcall *UpdateRotation)(APlayerController *this, float);
/* 00000A10 */     void (__fastcall *BeginPlayingState)(APlayerController *this);
/* 00000A18 */     void (__fastcall *EndPlayingState)(APlayerController *this);
/* 00000A20 */     void (__fastcall *StartFire)(APlayerController *this, unsigned __int8);
/* 00000A28 */     void (__fastcall *DelayedPrepareMapChange)(APlayerController *this);
/* 00000A30 */     void (__fastcall *GetSeamlessTravelActorList)(APlayerController *this, bool, TArray<AActor *,FDefaultAllocator> *);
/* 00000A38 */     void (__fastcall *SeamlessTravelTo)(APlayerController *this, APlayerController *);
/* 00000A40 */     void (__fastcall *SeamlessTravelFrom)(APlayerController *this, APlayerController *);
/* 00000A48 */     void (__fastcall *ClientEnableNetworkVoice)(APlayerController *this, bool);
/* 00000A50 */     void (__fastcall *ToggleSpeaking)(APlayerController *this, bool);
/* 00000A58 */     void (__fastcall *ClientVoiceHandshakeComplete)(APlayerController *this);
/* 00000A60 */     void (__fastcall *ServerMutePlayer)(APlayerController *this, FUniqueNetIdRepl);
/* 00000A68 */     void (__fastcall *ServerUnmutePlayer)(APlayerController *this, FUniqueNetIdRepl);
/* 00000A70 */     void (__fastcall *ClientMutePlayer)(APlayerController *this, FUniqueNetIdRepl);
/* 00000A78 */     void (__fastcall *ClientUnmutePlayer)(APlayerController *this, FUniqueNetIdRepl);
/* 00000A80 */     bool (__fastcall *IsPlayerMuted)(APlayerController *this, const FUniqueNetId *);
/* 00000A88 */     void (__fastcall *NotifyDirectorControl)(APlayerController *this, bool, AMatineeActor *);
/* 00000A90 */     void (__fastcall *ConsoleKey)(APlayerController *this, FKey);
/* 00000A98 */     void (__fastcall *SendToConsole)(APlayerController *this, const FString *);
/* 00000AA0 */     void (__fastcall *ClientClearCameraLensEffects)(APlayerController *this);
/* 00000AA8 */     void (__fastcall *ClientWasKickedImpl)(APlayerController *this, unsigned int, unsigned int, const FString *);
/* 00000AB0 */     void (__fastcall *SafeRetryClientRestart)(APlayerController *this);
/* 00000AB8 */     void (__fastcall *SafeServerCheckClientPossession)(APlayerController *this);
/* 00000AC0 */     void (__fastcall *AddPitchInput)(APlayerController *this, float);
/* 00000AC8 */     void (__fastcall *AddYawInput)(APlayerController *this, float);
/* 00000AD0 */     void (__fastcall *AddRollInput)(APlayerController *this, float);
/* 00000AD8 */     void (__fastcall *ActivateTouchInterface)(APlayerController *this, UTouchInterface *);
/* 00000AE0 */     void (__fastcall *SetVirtualJoystickVisibility)(APlayerController *this, bool);
/* 00000AE8 */     void (__fastcall *SetInputMode)(APlayerController *this, const FInputModeDataBase *);
/* 00000AF0 */     void (__fastcall *Camera)(APlayerController *this, FName);
/* 00000AF8 */     void (__fastcall *SetViewTargetWithBlend)(APlayerController *this, AActor *, float, EViewTargetBlendFunction, float, bool);
/* 00000B00 */     void (__fastcall *SetupInactiveStateInputComponent)(APlayerController *this, UInputComponent *);
/* 00000B08 */     void (__fastcall *UpdateStateInputComponents)(APlayerController *this);
/* 00000B10 */     void (__fastcall *FlushPressedKeys)(APlayerController *this);
/* 00000B18 */     bool (__fastcall *InputKey)(APlayerController *this, FKey, EInputEvent, float, bool);
/* 00000B20 */     bool (__fastcall *InputTouch)(APlayerController *this, unsigned int, ETouchType::Type, const FVector2D *, FDateTime, unsigned int);
/* 00000B28 */     bool (__fastcall *InputAxis)(APlayerController *this, FKey, float, float, int, bool);
/* 00000B30 */     bool (__fastcall *InputMotion)(APlayerController *this, const FVector *, const FVector *, const FVector *, const FVector *);
/* 00000B38 */     void (__fastcall *SetPlayer)(APlayerController *this, UPlayer *);
/* 00000B40 */     void (__fastcall *SmoothTargetViewRotation)(APlayerController *this, APawn *, float);
/* 00000B48 */     FString *(__fastcall *ConsoleCommand)(APlayerController *this, FString *result, const FString *, bool);
/* 00000B50 */     void (__fastcall *NotifyActorChannelFailure)(APlayerController *this, UActorChannel *);
/* 00000B58 */     void (__fastcall *UpdateHiddenActors)(APlayerController *this, const FVector *);
/* 00000B60 */     void (__fastcall *UpdateHiddenComponents)(APlayerController *this, const FVector *, TSet<FPrimitiveComponentId,DefaultKeyFuncs<FPrimitiveComponentId,0>,FDefaultSetAllocator> *);
/* 00000B68 */     void (__fastcall *SpawnPlayerCameraManager)(APlayerController *this);
/* 00000B70 */     void (__fastcall *GetAudioListenerPosition)(APlayerController *this, FVector *, FVector *, FVector *);
/* 00000B78 */     void (__fastcall *ProcessPlayerInput)(APlayerController *this, const float, const bool);
/* 00000B80 */     void (__fastcall *BuildInputStack)(APlayerController *this, TArray<UInputComponent *,FDefaultAllocator> *);
/* 00000B88 */     bool (__fastcall *IsInViewportClient)(APlayerController *this, UGameViewportClient *);
/* 00000B90 */     void (__fastcall *SetupInputComponent)(APlayerController *this);
/* 00000B98 */     void (__fastcall *CleanUpAudioComponents)(APlayerController *this);
/* 00000BA0 */     void (__fastcall *AddCheats)(APlayerController *this, bool);
/* 00000BA8 */     void (__fastcall *SpawnDefaultHUD)(APlayerController *this);
/* 00000BB0 */     void (__fastcall *CreateTouchInterface)(APlayerController *this);
/* 00000BB8 */     void (__fastcall *CleanupGameViewport)(APlayerController *this);
/* 00000BC0 */     void (__fastcall *AcknowledgePossession)(APlayerController *this, APawn *);
/* 00000BC8 */     void (__fastcall *PawnLeavingGame)(APlayerController *this);
/* 00000BD0 */     void (__fastcall *UpdatePing)(APlayerController *this, float);
/* 00000BD8 */     APlayerState *(__fastcall *GetNextViewablePlayer)(APlayerController *this, int);
/* 00000BE0 */     void (__fastcall *ViewAPlayer)(APlayerController *this, int);
/* 00000BE8 */     bool (__fastcall *CanRestartPlayer)(APlayerController *this);
/* 00000BF0 */     void (__fastcall *UpdateCameraManager)(APlayerController *this, float);
/* 00000BF8 */     void (__fastcall *ReceivedGameModeClass)(APlayerController *this, TSubclassOf<AGameMode>);
/* 00000C00 */     bool (__fastcall *NotifyServerReceivedClientData)(APlayerController *this, APawn *, float);
/* 00000C08 */     void (__fastcall *StartSpectatingOnly)(APlayerController *this);
/* 00000C10 */     bool (__fastcall *DefaultCanUnpause)(APlayerController *this);
/* 00000C18 */     void (__fastcall *SetViewTarget)(APlayerController *this, AActor *, FViewTargetTransitionParams);
/* 00000C20 */     void (__fastcall *AutoManageActiveCameraTarget)(APlayerController *this, AActor *);
/* 00000C28 */     ACameraActor *(__fastcall *GetAutoActivateCameraForPlayer)(APlayerController *this);
/* 00000C30 */     bool (__fastcall *ShouldShowMouseCursor)(APlayerController *this);
/* 00000C38 */     EMouseCursor::Type (__fastcall *GetMouseCursor)(APlayerController *this);
/* 00000C40 */     void (__fastcall *ReceivedSpectatorClass)(APlayerController *this, TSubclassOf<ASpectatorPawn>);
/* 00000C48 */     FVector *(__fastcall *GetFocalLocation)(APlayerController *this, FVector *result);
/* 00000C50 */     void (__fastcall *BeginSpectatingState)(APlayerController *this);
/* 00000C58 */     void (__fastcall *EndSpectatingState)(APlayerController *this);
/* 00000C60 */     void (__fastcall *SetSpectatorPawn)(APlayerController *this, ASpectatorPawn *);
/* 00000C68 */     ASpectatorPawn *(__fastcall *SpawnSpectatorPawn)(APlayerController *this);
/* 00000C70 */     void (__fastcall *DestroySpectatorPawn)(APlayerController *this);
/* 00000C78 */     void (__fastcall *SetSpawnLocation)(APlayerController *this, const FVector *);
/* 00000C80 */     void (__fastcall *ReceivedPlayer)(APlayerController *this);
/* 00000C88 */     void (__fastcall *InitInputSystem)(APlayerController *this);
/* 00000C90 */     bool (__fastcall *IsFrozen)(APlayerController *this);
/* 00000C98 */     void (__fastcall *PreClientTravel)(APlayerController *this, const FString *, ETravelType, bool);
/* 00000CA0 */     void (__fastcall *SetCameraMode)(APlayerController *this, FName);
/* 00000CA8 */     void (__fastcall *ResetCameraMode)(APlayerController *this);
/* 00000CB0 */     void (__fastcall *SendClientAdjustment)(APlayerController *this);
/* 00000CB8 */     bool (__fastcall *Server_SendClientAuthentication_Validate)(ADBDPlayerControllerBase *this, const FString *, unsigned __int64, unsigned int);
/* 00000CC0 */     void (__fastcall *Server_SendClientAuthentication_Implementation)(ADBDPlayerControllerBase *this, const FString *, unsigned __int64, unsigned int);
/* 00000CC8 */     bool (__fastcall *Client_SendServerAuthentication_Validate)(ADBDPlayerControllerBase *this, const FString *, unsigned __int64, unsigned int);
/* 00000CD0 */     void (__fastcall *Client_SendServerAuthentication_Implementation)(ADBDPlayerControllerBase *this, const FString *, unsigned __int64, unsigned int);
/* 00000CD8 */     bool (__fastcall *Server_CheatFireScoreEvent_Validate)(ADBDPlayerControllerBase *this, EDBDScoreTypes, float);
/* 00000CE0 */     void (__fastcall *Server_CheatFireScoreEvent_Implementation)(ADBDPlayerControllerBase *this, EDBDScoreTypes, float);
/* 00000CE8 */     void (__fastcall *Client_FinishedPlaying_Implementation)(ADBDPlayerControllerBase *this, const TArray<FBadgeAnalyticEntry,FDefaultAllocator> *);
/* 00000CF0 */     bool (__fastcall *CallConsoleCmdOnServer_Server_Validate)(ADBDPlayerControllerBase *this, const FString *);
/* 00000CF8 */     void (__fastcall *CallConsoleCmdOnServer_Server_Implementation)(ADBDPlayerControllerBase *this, const FString *);
/* 00000D00 */     void (__fastcall *Client_ValidateServer_Implementation)(ADBDPlayerControllerBase *this);
/* 00000D08 */     void (__fastcall *Client_EACMessageFromServer_Implementation)(ADBDPlayerControllerBase *this, const TArray<unsigned char,FDefaultAllocator> *, unsigned int);
/* 00000D10 */     bool (__fastcall *Server_EACMessageFromClient_Validate)(ADBDPlayerControllerBase *this, const TArray<unsigned char,FDefaultAllocator> *, unsigned int);
/* 00000D18 */     void (__fastcall *Server_EACMessageFromClient_Implementation)(ADBDPlayerControllerBase *this, const TArray<unsigned char,FDefaultAllocator> *, unsigned int);
/* 00000D20 */     bool (__fastcall *Server_SendMessage_Validate)(ADBDPlayerControllerBase *this, int, const FString *, const FString *);
/* 00000D28 */     void (__fastcall *Server_SendMessage_Implementation)(ADBDPlayerControllerBase *this, int, const FString *, const FString *);
/* 00000D30 */     bool (__fastcall *Server_SelectSlasher_Validate)(ADBDPlayerControllerBase *this, int);
/* 00000D38 */     void (__fastcall *Server_SelectSlasher_Implementation)(ADBDPlayerControllerBase *this, int);
/* 00000D40 */     bool (__fastcall *Server_SelectCamper_Validate)(ADBDPlayerControllerBase *this, int);
/* 00000D48 */     void (__fastcall *Server_SelectCamper_Implementation)(ADBDPlayerControllerBase *this, int);
/* 00000D50 */     bool (__fastcall *Server_UpdateReplicatedSkulls_Validate)(ADBDPlayerControllerBase *this, int);
/* 00000D58 */     void (__fastcall *Server_UpdateReplicatedSkulls_Implementation)(ADBDPlayerControllerBase *this, int);
/* 00000D60 */     void (__fastcall *Client_GameEnded_Implementation)(ADBDPlayerControllerBase *this);
/* 00000D68 */     bool (__fastcall *Server_ReceivePlayerProfile_Validate)(ADBDPlayerControllerBase *this, const FString *, FPlayerSavedProfileDataShared, FPlayerLoadoutData);
/* 00000D70 */     void (__fastcall *Server_ReceivePlayerProfile_Implementation)(ADBDPlayerControllerBase *this, const FString *, FPlayerSavedProfileDataShared, FPlayerLoadoutData);
/* 00000D78 */     void (__fastcall *Client_RequestPlayerProfile_Implementation)(ADBDPlayerControllerBase *this, bool);
/* 00000D80 */     bool (__fastcall *Server_BuildProceduralLevelFromSeed_Validate)(ADBDPlayerControllerBase *this, int);
/* 00000D88 */     void (__fastcall *Server_BuildProceduralLevelFromSeed_Implementation)(ADBDPlayerControllerBase *this, int);
/* 00000D90 */     bool (__fastcall *Server_BuildProceduralLevelFromMap_Validate)(ADBDPlayerControllerBase *this, const FString *);
/* 00000D98 */     void (__fastcall *Server_BuildProceduralLevelFromMap_Implementation)(ADBDPlayerControllerBase *this, const FString *);
/* 00000DA0 */     void (__fastcall *Local_SendCharacterData)(ADBDPlayerControllerBase *this);
/* 00000DA8 */     void (__fastcall *Local_WriteGameEndStats)(ADBDPlayerControllerBase *this);
/* 00000DB0 */     bool (__fastcall *Server_SetEquipedPerks_Validate)(ADBDPlayerController_Menu *this, const TArray<FName,FDefaultAllocator> *, const TArray<int,FDefaultAllocator> *, bool);
/* 00000DB8 */     void (__fastcall *Server_SetEquipedPerks_Implementation)(ADBDPlayerController_Menu *this, const TArray<FName,FDefaultAllocator> *, const TArray<int,FDefaultAllocator> *, bool);
/* 00000DC0 */     bool (__fastcall *Server_SetCustomizationMesh_Validate)(ADBDPlayerController_Menu *this, FName);
/* 00000DC8 */     void (__fastcall *Server_SetCustomizationMesh_Implementation)(ADBDPlayerController_Menu *this, FName);
/* 00000DD0 */     bool (__fastcall *Server_SetCharacterLevel_Validate)(ADBDPlayerController_Menu *this, int, int, bool);
/* 00000DD8 */     void (__fastcall *Server_SetCharacterLevel_Implementation)(ADBDPlayerController_Menu *this, int, int, bool);
/* 00000DE0 */     bool (__fastcall *Server_SetCharacterData_Validate)(ADBDPlayerController_Menu *this, int, const FPlayerDataSync *);
/* 00000DE8 */     void (__fastcall *Server_SetCharacterData_Implementation)(ADBDPlayerController_Menu *this, int, const FPlayerDataSync *);
/* 00000DF0 */     bool (__fastcall *Server_SetReadyToTravel_Validate)(ADBDPlayerController_Menu *this);
/* 00000DF8 */     void (__fastcall *Server_SetReadyToTravel_Implementation)(ADBDPlayerController_Menu *this);
/* 00000E00 */     bool (__fastcall *Server_SetPlayerReady_Validate)(ADBDPlayerController_Menu *this, bool);
/* 00000E08 */     void (__fastcall *Server_SetPlayerReady_Implementation)(ADBDPlayerController_Menu *this, bool);
/* 00000E10 */     bool (__fastcall *Server_SetPlayerLoadout_Validate)(ADBDPlayerController_Menu *this, FPlayerLoadoutData);
/* 00000E18 */     void (__fastcall *Server_SetPlayerLoadout_Implementation)(ADBDPlayerController_Menu *this, FPlayerLoadoutData);
/* 00000E20 */ };

/* 00000000 */ struct /*VFT*/ INavAgentInterface_vtbl // sizeof=0x50
/* 00000000 */ {
/* 00000000 */     void (__fastcall *~INavAgentInterface)(INavAgentInterface *this);
/* 00000008 */     UObject *(__fastcall *_getUObject)(INavAgentInterface *this);
/* 00000010 */     const FNavAgentProperties *(__fastcall *GetNavAgentPropertiesRef)(INavAgentInterface *this);
/* 00000018 */     FVector *(__fastcall *GetNavAgentLocation)(INavAgentInterface *this, FVector *result);
/* 00000020 */     FVector *(__fastcall *GetMoveGoalOffset)(INavAgentInterface *this, FVector *result, AActor *);
/* 00000028 */     FVector *(__fastcall *GetMoveGoalOffset)(INavAgentInterface *this, FVector *result, const AActor *);
/* 00000030 */     void (__fastcall *GetMoveGoalReachTest)(INavAgentInterface *this, AActor *, const FVector *, FVector *, float *, float *);
/* 00000038 */     void (__fastcall *GetMoveGoalReachTest)(INavAgentInterface *this, const AActor *, const FVector *, FVector *, float *, float *);
/* 00000040 */     bool (__fastcall *ShouldPostponePathUpdates)(INavAgentInterface *this);
/* 00000048 */     bool (__fastcall *IsFollowingAPath)(INavAgentInterface *this);
/* 00000050 */ };
