class __base(UActorComponent, 0) UPlayerInteractionHandler
{
/*0x0000*/  struct UPlayerInteractionHandler::VTable* vtable;
/*0x0008*/  __inherited enum EObjectFlags UObjectBase::ObjectFlags;
/*0x000c*/  __inherited int32_t UObjectBase::InternalIndex;
/*0x0010*/  __inherited class UClass* UObjectBase::ClassPrivate;
/*0x0018*/  __inherited class FName UObjectBase::NamePrivate;
/*0x0020*/  __inherited class UObject* UObjectBase::OuterPrivate;
/*0x0028*/  __inherited struct IInterface_AssetUserData::VTable* IInterface_AssetUserData::vtable;
/*0x0030*/  __inherited struct FActorComponentTickFunction UActorComponent::PrimaryComponentTick;
/*0x0080*/  __inherited class TArray<FName, FDefaultAllocator> UActorComponent::ComponentTags;
/*0x0090*/  __inherited class TArray<UAssetUserData*, FDefaultAllocator> UActorComponent::AssetUserData;
/*0x00a0*/  __inherited union
            {
                uint32_t bRegistered;
                uint32_t bRenderStateCreated;
                uint32_t bPhysicsStateCreated;
                uint32_t bReplicates;
                uint32_t bNetAddressable;
                uint32_t bRenderStateDirty;
                uint32_t bRenderTransformDirty;
                uint32_t bRenderDynamicDataDirty;
                uint32_t bRoutedPostRename;
                uint32_t bAutoRegister;
                uint32_t bAllowReregistration;
                uint32_t bTickInEditor;
                uint32_t bNeverNeedsRenderUpdate;
                uint32_t bAllowConcurrentTick;
                uint32_t bAllowAnyoneToDestroyMe;
                uint32_t bCreatedByConstructionScript_DEPRECATED;
                uint32_t bInstanceComponent_DEPRECATED;
                uint32_t bAutoActivate;
                uint32_t bIsActive;
                uint32_t bEditableWhenInherited;
                uint32_t bNavigationRelevant;
                uint32_t bCanEverAffectNavigation;
                uint32_t bWantsInitializeComponent;
                uint32_t bWantsBeginPlay;
                uint32_t bHasBeenCreated;
                uint32_t bHasBeenInitialized;
                uint32_t bHasBegunPlay;
                uint32_t bIsBeingDestroyed;
                uint32_t bTickFunctionsRegistered;
                uint32_t MarkedForEndOfFrameUpdateState;
            } __bitfielda0;
/*0x00a4*/  __inherited enum EComponentCreationMethod UActorComponent::CreationMethod;
/*0x00a8*/  __inherited class AActor* UActorComponent::OwnerPrivate;
/*0x00b0*/  __inherited class TArray<FSimpleMemberReference, FDefaultAllocator> UActorComponent::UCSModifiedProperties;
/*0x00c0*/  __inherited class FActorComponentActivatedSignature UActorComponent::OnComponentActivated;
/*0x00d0*/  __inherited class FActorComponentDeactivateSignature UActorComponent::OnComponentDeactivated;
/*0x00e0*/  __inherited class UWorld* UActorComponent::WorldPrivate;
/*0x00e8*/  float const kWaitForOtherInteractionEndTimeout;
/*0x00ec*/  float const kSkillCheckTriggerFrequency;
/*0x00f0*/  float PriorityConeAngle;
            __padding char _f4[4];
/*0x00f8*/  class TArray<UInteractionDefinition*, FDefaultAllocator> InteractionsInZone;
            __padding char _108[8];
/*0x0110*/  class TBaseDelegate<void> InteractionPressDelegate;
/*0x0150*/  class TBaseDelegate<void> SecondaryActionInteractionPressDelegate;
/*0x0190*/  enum EInteractionLayer InteractionLayer;
            __padding char _191[3];
/*0x0194*/  struct TWeakObjectPtr<ADBDPlayer, FWeakObjectPtr> OwningCharacter;
            __padding char _19c[4];
/*0x01a0*/  class FOnDesactivateSkillCheck OnDesactivateSkillCheckDelegate;
/*0x01b0*/  bool _hasInteractionRequest;
/*0x01b1*/  bool _hasInteractionRequestInBuffer;
/*0x01b8*/  class UInteractionDefinition* _requestedInteraction;
/*0x01c0*/  enum EInputInteractionType _requestedInteractionType;
/*0x01c1*/  enum ERequestState _requestedInteractionState;
/*0x01c8*/  class UInteractionDefinition* _currentInteraction;
/*0x01d0*/  struct FInteractionProperties* _currentInteractionProperties;
/*0x01d8*/  struct FInteractionPlayerProperties _currentInteractionPlayerProperties;
/*0x0220*/  bool _currentInteractionChargeCompleted;
            __padding char _221[7];
/*0x0228*/  class TArray<ADBDPlayer*, FDefaultAllocator> _currentPlayerDependencies;
/*0x0238*/  enum EInputInteractionType _currentInteractionType;
/*0x0240*/  class USkillCheck* _skillCheck;
/*0x0248*/  struct FTimerHandle _skillCheckTimerHandle;
/*0x0250*/  class TArray<float, FDefaultAllocator> _progressBasedSkillChecks;
/*0x0260*/  class TMap<FName, TWeakObjectPtr<UInteractionDefinition, FWeakObjectPtr>, FDefaultSetAllocator, TDefaultMapKeyFuncs<FName, TWeakObjectPtr<UInteractionDefinition, FWeakObjectPtr>, 0>> _availableInteractions;
/*0x02b0*/  struct TWeakObjectPtr<UInteractor, FWeakObjectPtr> _attachedInteractor;
/*0x02b8*/  bool _hasInterruptionRequest;
/*0x02b9*/  bool _hasInterruptionRequestInBuffer;
/*0x02ba*/  enum ERequestState _requestedInterruptionState;
/*0x02c0*/  class ADBDPlayer* _requestedInterruptionOtherParty;
/*0x02c8*/  class UInterruptionDefinition* _requestedInterruptionDefinition;
/*0x02d0*/  bool _requestedInterruptionIsInterruptor;
/*0x02d8*/  class ADBDPlayer* _currentInterruptionOtherParty;
/*0x02e0*/  class UInterruptionDefinition* _currentInterruptionDefinition;
/*0x02e8*/  bool _currentInterruptionIsInterruptor;
/*0x02e9*/  bool _interactionInProgress;
            __padding char _2ea[2];
/*0x02ec*/  struct FDBDTimer _waitForOtherInteractionEndTimer;
/*0x030c*/  bool _scanForInteractions;
};
