class __base(ADBDPlayer, 0) ASlasherPlayer
{
/*0x0000*/  struct ASlasherPlayer::VTable* vtable;
/*0x0008*/  __inherited enum EObjectFlags UObjectBase::ObjectFlags;
/*0x000c*/  __inherited int32_t UObjectBase::InternalIndex;
/*0x0010*/  __inherited class UClass* UObjectBase::ClassPrivate;
/*0x0018*/  __inherited class FName UObjectBase::NamePrivate;
/*0x0020*/  __inherited class UObject* UObjectBase::OuterPrivate;
/*0x0028*/  __inherited struct FActorTickFunction AActor::PrimaryActorTick;
/*0x0078*/  __inherited float AActor::CustomTimeDilation;
/*0x007c*/  __inherited union
            {
              uint8_t bHidden;
              uint8_t bNetTemporary;
              uint8_t bNetStartup;
              uint8_t bOnlyRelevantToOwner;
              uint8_t bAlwaysRelevant;
              uint8_t bReplicateMovement;
              uint8_t bTearOff;
              uint8_t bExchangedRoles;
            } __bitfield7c;
/*0x007d*/  __inherited union
            {
              uint8_t bPendingNetUpdate;
              uint8_t bNetLoadOnClient;
              uint8_t bNetUseOwnerRelevancy;
              uint8_t bBlockInput;
              uint8_t bRunningUserConstructionScript;
              uint8_t bAllowTickBeforeBeginPlay;
              uint8_t bHasFinishedSpawning;
              uint8_t bTickFunctionsRegistered;
            } __bitfield7d;
/*0x007e*/  __inherited union
            {
              uint8_t bActorEnableCollision;
              uint8_t bNetCheckedInitialPhysicsState;
              uint8_t bReplicates;
            } __bitfield7e;
            __padding char _7f[1];
/*0x0080*/  __inherited class FName AActor::NetDriverName;
/*0x0088*/  __inherited class TEnumAsByte<enum ENetRole> AActor::RemoteRole;
/*0x0090*/  __inherited class AActor* AActor::Owner;
/*0x0098*/  __inherited struct FRepMovement AActor::ReplicatedMovement;
            __padding char _cc[4];
/*0x00d0*/  __inherited struct FRepAttachment AActor::AttachmentReplication;
/*0x0110*/  __inherited class TEnumAsByte<enum ENetRole> AActor::Role;
/*0x0111*/  __inherited class TEnumAsByte<enum ENetDormancy> AActor::NetDormancy;
/*0x0112*/  __inherited class TEnumAsByte<enum EAutoReceiveInput::Type> AActor::AutoReceiveInput;
/*0x0114*/  __inherited int32_t AActor::InputPriority;
/*0x0118*/  __inherited class UInputComponent* AActor::InputComponent;
/*0x0120*/  __inherited class TEnumAsByte<enum EInputConsumeOptions> AActor::InputConsumeOption_DEPRECATED;
/*0x0124*/  __inherited float AActor::NetCullDistanceSquared;
/*0x0128*/  __inherited int32_t AActor::NetTag;
/*0x012c*/  __inherited float AActor::NetUpdateTime;
/*0x0130*/  __inherited float AActor::NetUpdateFrequency;
/*0x0134*/  __inherited float AActor::MinNetUpdateFrequency;
/*0x0138*/  __inherited float AActor::NetPriority;
/*0x013c*/  __inherited float AActor::LastNetUpdateTime;
/*0x0140*/  __inherited union
            {
              uint8_t bAutoDestroyWhenFinished;
              uint8_t bCanBeDamaged;
              uint8_t bActorIsBeingDestroyed;
              uint8_t bCollideWhenPlacing;
              uint8_t bFindCameraComponentWhenViewTarget;
              uint8_t bRelevantForNetworkReplays;
              uint8_t bGenerateOverlapEventsDuringLevelStreaming;
            } __bitfield140;
/*0x0141*/  __inherited enum ESpawnActorCollisionHandlingMethod AActor::SpawnCollisionHandlingMethod;
/*0x0144*/  __inherited float AActor::CreationTime;
/*0x0148*/  __inherited class APawn* AActor::Instigator;
/*0x0150*/  __inherited class TArray<AActor *,FDefaultAllocator> AActor::Children;
/*0x0160*/  __inherited class USceneComponent* AActor::RootComponent;
/*0x0168*/  __inherited class TArray<AMatineeActor*, FDefaultAllocator> AActor::ControllingMatineeActors;
/*0x0178*/  __inherited float AActor::InitialLifeSpan;
/*0x017c*/  __padding char _17c[4];
/*0x0180*/  __inherited struct FTimerHandle AActor::TimerHandle_LifeSpanExpired;
/*0x0188*/  __inherited class TArray<FName, FDefaultAllocator> AActor::Layers;
/*0x0198*/  __inherited struct TWeakObjectPtr<AActor, FWeakObjectPtr> AActor::ParentComponentActor_DEPRECATED;
/*0x01a0*/  __inherited struct TWeakObjectPtr<UChildActorComponent, FWeakObjectPtr> AActor::ParentComponent;
/*0x01a8*/  __inherited union
            {
              uint8_t bAllowReceiveTickEventOnDedicatedServer;
              uint8_t bActorInitialized;
              enum AActor::EActorBeginPlayState ActorHasBegunPlay;
              uint8_t bActorSeamlessTraveled;
              uint8_t bIgnoresOriginShifting;
              uint8_t bEnableAutoLODGeneration;
            } __bitfield1a8;
            __padding char _1a9[7];
/*0x01b0*/  __inherited class TArray<FName, FDefaultAllocator> AActor::Tags;
/*0x01c0*/  __inherited uint64_t AActor::HiddenEditorViews;
/*0x01c8*/  __inherited class FTakeAnyDamageSignature AActor::OnTakeAnyDamage;
/*0x01d8*/  __inherited class FTakePointDamageSignature AActor::OnTakePointDamage;
/*0x01e8*/  __inherited class FActorBeginOverlapSignature AActor::OnActorBeginOverlap;
/*0x01f8*/  __inherited class FActorEndOverlapSignature AActor::OnActorEndOverlap;
/*0x0208*/  __inherited class FActorBeginCursorOverSignature AActor::OnBeginCursorOver;
/*0x0218*/  __inherited class FActorEndCursorOverSignature AActor::OnEndCursorOver;
/*0x0228*/  __inherited class FActorOnClickedSignature AActor::OnClicked;
/*0x0238*/  __inherited class FActorOnReleasedSignature AActor::OnReleased;
/*0x0248*/  __inherited class FActorOnInputTouchBeginSignature AActor::OnInputTouchBegin;
/*0x0258*/  __inherited class FActorOnInputTouchEndSignature AActor::OnInputTouchEnd;
/*0x0268*/  __inherited class FActorBeginTouchOverSignature AActor::OnInputTouchEnter;
/*0x0278*/  __inherited class FActorEndTouchOverSignature AActor::OnInputTouchLeave;
/*0x0288*/  __inherited class FActorHitSignature AActor::OnActorHit;
/*0x0298*/  __inherited class FActorDestroyedSignature AActor::OnDestroyed;
/*0x02a8*/  __inherited class FActorEndPlaySignature AActor::OnEndPlay;
/*0x02b8*/  __inherited class TSet<UActorComponent*, DefaultKeyFuncs<UActorComponent*, 0>,FDefaultSetAllocator> AActor::OwnedComponents;
/*0x0308*/  __inherited class TSet<UActorComponent*, DefaultKeyFuncs<UActorComponent*, 0>,FDefaultSetAllocator> AActor::ReplicatedComponents;
/*0x0358*/  __inherited class TArray<UActorComponent*, FDefaultAllocator> AActor::BlueprintCreatedComponents;
/*0x0368*/  __inherited class TArray<UActorComponent*, FDefaultAllocator> AActor::InstanceComponents;
/*0x0378*/  __inherited class FRenderCommandFence AActor::DetachFence;
/*0x0380*/  __inherited struct ADebugCameraController::APlayerController::AController::INavAgentInterface::VTable* INavAgentInterface::vtable;
/*0x0388*/  __inherited union
            {
              uint32_t bUseControllerRotationPitch;
              uint32_t bUseControllerRotationYaw;
              uint32_t bUseControllerRotationRoll;
              uint32_t bCanAffectNavigationGeneration;
              uint32_t bInputEnabled;
            } __bitfield388;
/*0x038c*/  __inherited float APawn::BaseEyeHeight;
/*0x0390*/  __inherited class TEnumAsByte<enum EAutoReceiveInput::Type> APawn::AutoPossessPlayer;
/*0x0391*/  __inherited enum EAutoPossessAI APawn::AutoPossessAI;
            __padding char _392[6];
/*0x0398*/  __inherited class TSubclassOf<AController> APawn::AIControllerClass;
/*0x03a0*/  __inherited class APlayerState* APawn::PlayerState;
/*0x03a8*/  __inherited uint8_t APawn::RemoteViewPitch;
/*0x03b0*/  __inherited class AController* APawn::LastHitBy;
/*0x03b8*/  __inherited class AController* APawn::Controller;
/*0x03c0*/  __inherited float APawn::AllowedYawError;
/*0x03c4*/  __inherited union
            {
              uint32_t bProcessingOutsideWorldBounds;
            } __bitfield3c4;
/*0x03c8*/  __inherited struct FVector APawn::ControlInputVector;
/*0x03d4*/  __inherited struct FVector APawn::LastControlInputVector;
/*0x03e0*/  __inherited class USkeletalMeshComponent* ACharacter::Mesh;
/*0x03e8*/  __inherited class UCharacterMovementComponent* ACharacter::CharacterMovement;
/*0x03f0*/  __inherited class UCapsuleComponent* ACharacter::CapsuleComponent;
/*0x03f8*/  __inherited struct FBasedMovementInfo ACharacter::BasedMovement;
/*0x0428*/  __inherited struct FBasedMovementInfo ACharacter::ReplicatedBasedMovement;
/*0x0458*/  __inherited float ACharacter::AnimRootMotionTranslationScale;
/*0x045c*/  __inherited struct FVector ACharacter::BaseTranslationOffset;
            __padding char _468[8];
/*0x0470*/  __inherited struct FQuat ACharacter::BaseRotationOffset;
/*0x0480*/  __inherited float ACharacter::ReplicatedServerLastTransformUpdateTimeStamp;
/*0x0484*/  __inherited uint8_t ACharacter::ReplicatedMovementMode;
/*0x0485*/  __inherited uint8_t ACharacter::bInBaseReplication;
/*0x0488*/  __inherited float ACharacter::CrouchedEyeHeight;
/*0x048c*/  __inherited union
            {
              uint32_t bIsCrouched;
              uint32_t bReplayHasRootMotionSources;
              uint32_t bPressedJump;
              uint32_t bClientUpdating;
              uint32_t bClientWasFalling;
              uint32_t bClientResimulateRootMotion;
              uint32_t bClientResimulateRootMotionSources;
              uint32_t bSimGravityDisabled;
              uint32_t bClientCheckEncroachmentOnNetUpdate;
              uint32_t bServerMoveIgnoreRootMotion;
            } __bitfield48c;
/*0x0490*/  __inherited float ACharacter::JumpKeyHoldTime;
/*0x0494*/  __inherited float ACharacter::JumpMaxHoldTime;
/*0x0498*/  __inherited int32_t ACharacter::JumpMaxCount;
/*0x049c*/  __inherited int32_t ACharacter::JumpCurrentCount;
/*0x04a0*/  __inherited union
            {
              uint32_t bJumpMaxCountExceeded;
            } __bitfield4a0;
            __padding char _4a4[4];
/*0x04a8*/  __inherited class FCharacterReachedApexSignature ACharacter::OnReachedJumpApex;
/*0x04b8*/  __inherited class FLandedSignature ACharacter::LandedDelegate;
/*0x04c8*/  __inherited class FMovementModeChangedSignature ACharacter::MovementModeChangedDelegate;
/*0x04d8*/  __inherited class FCharacterMovementUpdatedSignature ACharacter::OnCharacterMovementUpdated;
/*0x04e8*/  __inherited struct FRootMotionSourceGroup ACharacter::SavedRootMotion;
            __padding char _5e8[8];
/*0x05f0*/  __inherited struct FRootMotionMovementParams ACharacter::ClientRootMotionParams;
/*0x0630*/  __inherited class TArray<FSimulatedRootMotionReplicatedMove,FDefaultAllocator> ACharacter::RootMotionRepMoves;
/*0x0640*/  __inherited struct FRepRootMotionMontage ACharacter::RepRootMotion;
/*0x07a0*/  __inherited struct IPerkOwnerInterface::VTable* IPerkOwnerInterface::vtable;
/*0x07a8*/  __inherited struct IPerkManagerOwnerInterface::VTable* IPerkManagerOwnerInterface::vtable;
/*0x07b0*/  __inherited struct IAnimTagProvider::VTable* IAnimTagProvider::vtable;
/*0x07b8*/  __inherited float const kLoadingTime;
            __inherited __padding char _7bc[4];
/*0x07c0*/  __inherited class TSubclassOf<AInteractable> Interactable;
/*0x07c8*/  __inherited class FMovementInputDelegate OnMovementInput;
/*0x07d8*/  __inherited bool AllowInterrupting;
            __inherited __padding char _7d9[3];
/*0x07dc*/  __inherited float MinFallHeight;
/*0x07e0*/  __inherited bool IsInterruptable;
/*0x07e1*/  __inherited bool IsStunned;
/*0x07e2*/  __inherited bool IsAttacking;
/*0x07e3*/  __inherited bool AllowNavigationInput;
/*0x07e4*/  __inherited bool AllowNavigationBackwardInput;
/*0x07e5*/  __inherited bool AllowTurningInput;
/*0x07e6*/  __inherited bool AllowPitchInput;
/*0x07e8*/  __inherited float PitchLimitLower;
/*0x07ec*/  __inherited float PitchLimitUpper;
/*0x07f0*/  __inherited struct FVector StrafingOffset;
/*0x07fc*/  __inherited float PelvisHeight;
/*0x0800*/  __inherited float PelvisHeightForPounceOnStandingCamper;
/*0x0804*/  __inherited float PelvisHeightForPounceOnCrouchingCamper;
/*0x0808*/  __inherited class TSharedPtr<PollableEvent<bool>, 0> MontageEndEvent;
/*0x0818*/  __inherited class TSharedPtr<PollableEvent<enum EAttackType>, 0> AttackEvent;
/*0x0828*/  __inherited class TSharedPtr<ConsumableEvent<enum EAttackType>, 0> AttackMontageEvent;
/*0x0838*/  __inherited class TSharedPtr<PollableEvent<bool>, 0> InteractionCancelledEvent;
/*0x0848*/  __inherited class TSharedPtr<PollableEvent<FVector>, 0> MovementInputEvent;
/*0x0858*/  __inherited class TSharedPtr<PollableEvent<bool>, 0> BlinkEvent;
/*0x0868*/  __inherited class FAnimationStateDependencyUpdateDelegate OnAnimationStateDependencyUpdate;
/*0x0878*/  __inherited class FOnAttackedEvent OnAttackedDelegate;
            __inherited __padding char _888[8];
/*0x0890*/  __inherited class TBaseDelegate<void, ADBDPlayer*, enum EAttackType> OnAttackEvent;
/*0x08d0*/  __inherited class FOnSensedDelegate OnSensed;
/*0x08e0*/  __inherited class FAnimNotifyDelegate_Pickup OnAnimNotify_Pickup;
/*0x08f0*/  __inherited class FAnimNotifyDelegate_Release OnAnimNotify_Release;
/*0x0900*/  __inherited class FSecondaryActionInputDelegate OnSecondaryActionInput;
/*0x0910*/  __inherited class FOnFirstPersonModeChanged OnFirstPersonModeChanged;
/*0x0920*/  __inherited class USceneComponent* CameraAnchor;
/*0x0928*/  __inherited class USpringArmComponent* CameraBoom;
/*0x0930*/  __inherited class TBaseDelegate<void, UAnimMontage*, bool> OnMontageEndDelegate;
/*0x0970*/  __inherited class TBaseDelegate<void, UAnimMontage*, bool> OnMontageBlendingOutDelegate;
/*0x09b0*/  __inherited class TBaseDelegate<void, UInteractionDefinition*, bool> OnInteractionZoneOverlapDelegate;
/*0x09f0*/  __inherited bool ForceDisableFootIK;
/*0x09f1*/  __inherited bool ForceSkillChecks;
            __inherited __padding char _9f2[0xe];
/*0x0a00*/  __inherited struct FTransform IKLeftHandTransform;
/*0x0a30*/  __inherited struct FTransform IKRightHandTransform;
/*0x0a60*/  __inherited float CameraResetSpeed;
            __inherited __padding char _a64[4];
/*0x0a68*/  __inherited class FString CharacterName;
/*0x0a78*/  __inherited class FString CharacterClothes;
/*0x0a88*/  __inherited class FString CharacterShoes;
/*0x0a98*/  __inherited class FString CharacterWeapon;
/*0x0aa8*/  __inherited class FString CharacterAmbiance;
/*0x0ab8*/  __inherited class FString CharacterState;
/*0x0ac8*/  __inherited bool _smLaunched;
/*0x0ac9*/  __inherited bool _perksSpawned;
/*0x0aca*/  __inherited bool _isMontageMode;
/*0x0acb*/  __inherited bool DebugInteractionPriorityEnabled;
/*0x0acc*/  __inherited bool CheatIsInterruptable;
/*0x0acd*/  __inherited bool ForceDisableSkillChecks;
/*0x0ace*/  __inherited bool DebugAutoInteractEnabled;
/*0x0ad0*/  __inherited float DebugAutoInteractDuration;
/*0x0ad4*/  __inherited float DebugAutoInteractPauseDelay;
/*0x0ad8*/  __inherited bool DebugAutoItemInteractEnabled;
/*0x0ad9*/  __inherited bool DebugAutoItemInteractPressed;
/*0x0adc*/  __inherited float DebugAutoItemInteractDuration;
/*0x0ae0*/  __inherited float DebugAutoItemInteractPauseDelay;
            __inherited __padding char _ae4[0xc];
/*0x0af0*/  __inherited class TBaseDelegate<void> OnEquippedItemUpdated;
/*0x0b30*/  __inherited float _emulatedYawInputDecay;
/*0x0b34*/  __inherited float _emulatedYawInputDecayWhenNoInput;
/*0x0b38*/  __inherited float _emulatedYawInputReleaseTime;
/*0x0b3c*/  __inherited float _emulatedYawInputDeadZone;
/*0x0b40*/  __inherited float _emulatedYawMinimumInput;
/*0x0b44*/  __inherited float _emulatedYawInputStrength;
/*0x0b48*/  __inherited class UCurveFloat* BlinkFOVCurve;
/*0x0b50*/  __inherited float CurrentBlinkDistance;
/*0x0b54*/  __inherited bool IsInBlinkingState;
/*0x0b58*/  __inherited float AverageSpeedBufferTime;
/*0x0b5c*/  __inherited float AlmostCurrentSpeedBufferTime;
/*0x0b60*/  __inherited class UCurveFloat* GamepadYawCurve;
/*0x0b68*/  __inherited class UCurveFloat* GamepadPitchCurve;
/*0x0b70*/  __inherited class UChargeableComponent* BlindingChargeableComponent;
/*0x0b78*/  __inherited class FName CarryJointName;
/*0x0b80*/  __inherited class TArray<UCurveFloat*, FDefaultAllocator> AttackPounceCurves;
/*0x0b90*/  __inherited class TArray<UCurveFloat*, FDefaultAllocator> AttackLungeCurves;
/*0x0ba0*/  __inherited class TArray<UCurveFloat*, FDefaultAllocator> AttackSlashCurves;
/*0x0bb0*/  __inherited class TArray<UCurveFloat*, FDefaultAllocator> AttackChainsawCurves;
/*0x0bc0*/  __inherited class TArray<UCurveFloat*, FDefaultAllocator> AttackBlinkCurves;
/*0x0bd0*/  __inherited class TArray<UCurveFloat*, FDefaultAllocator> AttackPounceCurves_StalkTier0;
/*0x0be0*/  __inherited class TArray<UCurveFloat*, FDefaultAllocator> AttackPounceCurves_StalkTier1;
/*0x0bf0*/  __inherited class TArray<UCurveFloat*, FDefaultAllocator> AttackPounceCurves_StalkTier2;
/*0x0c00*/  __inherited float _pitchOffsetForInteractionPriority;
/*0x0c04*/  __inherited bool IsInteracting;
/*0x0c05*/  __inherited bool _cameraResetting;
/*0x0c08*/  __inherited float ClearPathTestRadiusMultiplier;
/*0x0c0c*/  __inherited float ClearPathTestHeightMultiplier;
/*0x0c10*/  __inherited float LocationClearTestRadiusMultiplier;
/*0x0c14*/  __inherited float LocationClearTestHeightMultiplier;
/*0x0c18*/  __inherited struct FDateTime _idleStart;
/*0x0c20*/  __inherited struct FDateTime _lastUpdate;
/*0x0c28*/  __inherited float ClearPathTestStepHeight;
/*0x0c2c*/  __inherited float GamePadTurnRate;
/*0x0c30*/  __inherited float GamePadLookUpRate;
/*0x0c34*/  __inherited float MouseTurnSpeedMultiplier;
/*0x0c38*/  __inherited float MouseLookUpSpeedMultiplier;
/*0x0c40*/  __inherited class USoundCue* DeathSound;
/*0x0c48*/  __inherited enum ECamperState CurrentCamperState;
            __inherited __padding char _c49[7];
/*0x0c50*/  __inherited class FName CollectableAttachPoint;
/*0x0c58*/  __inherited class TArray<ACollectable*, FDefaultAllocator> Inventory;
/*0x0c68*/  __inherited class TArray<UPerk*, FDefaultAllocator> _perks;
/*0x0c78*/  __inherited class TArray<FOffering, FDefaultAllocator> _offerings;
/*0x0c88*/  __inherited class TArray<UStatusEffect*, FDefaultAllocator> _statusEffects;
/*0x0c98*/  __inherited class TMap<AActor*, UFlashLightComponent*, FDefaultSetAllocator, TDefaultMapKeyFuncs<AActor*, UFlashLightComponent*, 0>> _blindingEffectors;
/*0x0ce8*/  __inherited class UStateMachine* _SM;
/*0x0cf0*/  __inherited class UPlayerInteractionHandler* _interactionHandler;
/*0x0cf8*/  __inherited class UMontagePlayer* _montagePlayer;
/*0x0d00*/  __inherited class UPerkManager* _perkManager;
/*0x0d08*/  __inherited class UDBDPlayerData* _playerData;
/*0x0d10*/  __inherited class UAxisFlickMasher* _wiggleAxisFlickMasher;
/*0x0d18*/  __inherited class UInputMasher* _interactInputMasher;
/*0x0d20*/  __inherited bool _isUsingGamepad;
            __inherited __padding char _d21[0xf];
/*0x0d30*/  __inherited class ADBDPlayer::FOnSwitchedInputControlsEvent _onSwitchedInputControlsEvent;
/*0x0da0*/  __inherited class AInteractable* _interactable;
/*0x0da8*/  __inherited class TMap<FName, float, FDefaultSetAllocator, TDefaultMapKeyFuncs<FName, float, 0>> _tunableValueMap;
/*0x0df8*/  __inherited class TArray<ADBDPlayer*, FDefaultAllocator> _overlappingPlayers;
/*0x0e08*/  __inherited class ADBDPlayer* _guidingPlayer;
/*0x0e10*/  __inherited bool _updateCapsuleSize;
/*0x0e11*/  __inherited bool _crouchPressed;
/*0x0e18*/  __inherited class ADBDPlayer* _interactingPlayer;
/*0x0e20*/  __inherited struct FDBDTimer _loadingTimer;
/*0x0e40*/  __inherited float _movementSpeedMultiplier;
/*0x0e44*/  __inherited enum EAttackSubstate _nextAttackSubstate;
            __inherited __padding char _e45[2];
            __inherited __padding char _e47[1];
/*0x0e48*/ __inherited  struct TWeakObjectPtr<ADBDPlayer, FWeakObjectPtr> _lockOnTarget;
/*0x0e50*/  __inherited struct TWeakObjectPtr<ADBDPlayer, FWeakObjectPtr> _damageTarget;
/*0x0e58*/  __inherited class UCharacterSnappingComponent* _characterSnappingComponent;
/*0x0e60*/  __inherited class UCameraHandlerComponent* _cameraHandlerComponent;
/*0x0e68*/  __inherited class USceneComponent* _itemDropOffPosition;
/*0x0e70*/  __inherited bool _emulateGamepadForMouseYaw;
            __inherited __padding char _e71[7];
/*0x0e78*/  __inherited struct FDataTableProxy TunableDB;
/*0x0ea8*/  __inherited struct FDataTableProxy GlobalTunableDB;
/*0x0ed8*/  __inherited class TArray<AActor*, FDefaultAllocator> IgnoreActors;
/*0x0ee8*/  __inherited class TArray<FEffectCameraTypeSettings, FDefaultAllocator> EffectCameraTypeSettings;
/*0x0ef8*/  __inherited float _staminaRechargeRate;
/*0x0efc*/  __inherited struct FDBDTimer _postChaseTimer;
/*0x0f1c*/  __inherited float _postChaseTime;
/*0x0f20*/  __inherited struct FVector _targetStrafeOffset;
/*0x0f2c*/  __inherited struct FVector _startStrafeOffset;
/*0x0f38*/  __inherited float _strafeOffsetUpdateAlpha;
/*0x0f3c*/  __inherited float const kStrafeOffsetUpdateDuration;
/*0x0f40*/  __inherited bool _isBeingInterrupted;
/*0x0f48*/  __inherited class UPollableEventListener* _eventListener;
/*0x0f50*/  __inherited bool _debugAutoInteractPress;
            __inherited __padding char _f51[3];
/*0x0f54*/  __inherited struct FDBDTimer _debugAutoInteractTimer;
/*0x0f74*/  __inherited bool _debugAutoItemInteractPress;
            __inherited __padding char _f75[3];
/*0x0f78*/  __inherited struct FDBDTimer _debugAutoItemInteractTimer;
/*0x0f98*/  __inherited bool _isReadyToPlay;
/*0x0fa0*/  __inherited class UZoneDetectorComponent* _meatHookZoneDetector;
/*0x0fa8*/  __inherited bool _feetAreOnGround;
/*0x0fa9*/  __inherited struct FAnimData _animData;
            __inherited __padding char _faa[2];
/*0x0fac*/  __inherited struct FVector _frameDisplacementAsSpeed;
/*0x0fb8*/  __inherited struct FVector _previousPosition;
/*0x0fc4*/  __inherited struct FVector _lastSafePosition;
/*0x0fd0*/  __inherited struct FVector _spawnPosition;
/*0x0fdc*/  __inherited float _secondsSinceLastSave;
/*0x0fe0*/  __inherited float _secondsSinceLastFell;
/*0x0fe4*/  __inherited bool _invertLookUpAxis;
/*0x0fe8*/  __inherited int32_t _framesForSlasherAutoAttackOnCamperInteract;
/*0x0fec*/  __inherited float _originalGroundFriction;
/*0x0ff0*/  __inherited class FString _leftFootSurface;
/*0x1000*/  __inherited class FString _rightFootSurface;
/*0x1010*/  __inherited int32_t _numMeathooksInZone;
/*0x1014*/  __inherited enum EInteractionAnimation _interactionAnimation;
/*0x1018*/  __inherited float _attackingMaxSpeedPercent;
/*0x101c*/  __inherited float _interactingMaxSpeedPercent;
/*0x1020*/  __inherited bool _isInterrupting;
/*0x1021*/  __inherited bool _isSwappingInteraction;
/*0x1028*/  __inherited class UInteractionDefinition* _bookmarkedInteraction;
/*0x1030*/  __inherited class TMap<enum EDetectionZone, UPrimitiveComponent*, FDefaultSetAllocator, TDefaultMapKeyFuncs<enum EDetectionZone, UPrimitiveComponent*, 0>> _detectionZoneMap;
/*0x1080*/  __inherited bool _printServerPositionUpdateEnabled;
/*0x1081*/  __inherited bool _inParadise;
/*0x1082*/  __inherited bool _debugInteractionInZone;
            __inherited __padding char _1083[1];
/*0x1084*/  __inherited struct FDBDTimer _fastInteractInputPersistence;
/*0x10a8*/  __inherited class UAuthoritativeMovementComponent* _authoritativeMovementComponent;
/*0x10b0*/  __inherited struct FBitfield _authoritativeMovementFlags;
/*0x10b4*/  __inherited float _emulatedYawInput;
/*0x10b8*/  __inherited float _yawRateInput;
/*0x10bc*/  __inherited struct FDBDTimer _emulatedYawInputReleaseTimer;
/*0x10dc*/  __inherited bool _forcedAuthoritativeUnmoveable;
/*0x10dd*/  __inherited bool _windowFreeCam;
/*0x10de*/  __inherited bool _reverseTraverse;
/*0x10df*/  __inherited bool _runVault;
/*0x10e8*/  __inherited bool _debugFailAllInteractions;
/*0x10e4*/  __inherited float _stamina;
/*0x10e8*/  __inherited struct FDBDTimer _staminaRechargeDelayTimer;
/*0x1108*/  __inherited struct FVector _blinkDestinationPosition;
/*0x1114*/  __inherited struct FRotator _blinkDestinationRotation;
/*0x1120*/  __inherited struct FVector _averageVelocity;
/*0x112c*/  __inherited struct FVector _almostCurrentVelocity;
/*0x1138*/  __inherited struct FDBDTimer _trapImmunityTimer;
/*0x1158*/  __inherited bool _wasLocallyObserved;
            __inherited __padding char _1159[3];
/*0x115c*/  __inherited struct TWeakObjectPtr<UCameraComponent, FWeakObjectPtr> _cachedPlayerCamera;
/*0x1164*/  __inherited bool _isHeadHidden;
/*0x1165*/  __inherited bool _isInFirstPerson;
/*0x1168*/  __inherited float _blindnessRemainingTime;
/*0x116c*/  __inherited float _maxBlindnessDuration;
/*0x1170*/  __inherited float _recentlyBlindedCooldown;
/*0x1174*/  __inherited struct FDBDTimer _recentlyBlindedTimer;
            __inherited __padding char _1194[4];
/*0x1198*/  __inherited class FName InteractionKeys[31];
/*0x1290*/  __inherited float _screenAspectRatio;
            __inherited __padding char _1294[4];
/*0x1298*/  float const kAnimDirectionInterpSpeed;
/*0x129c*/  float const kAnimDirectionForwardThreshold;
/*0x12a0*/  float const kAnimDirectionSideThreshold;
            __padding char _12a4[4];
/*0x12a8*/  class FChaseEndDelegate OnChaseEnded;
/*0x12b8*/  class FChaseStartDelegate OnChaseStarted;
/*0x12c8*/  class FOffensiveActionDelegate OnOffensiveAction;
/*0x12d8*/  struct FVector PutDownTraceLocation;
            __padding char _12e4[4];
/*0x12e8*/  class FName DefaultSlasherPower;
/*0x12f0*/  float LoudNoiseDisplayTime;
/*0x12f4*/  float TerrorRadius;
/*0x12f8*/  struct FVector TargetPriorityFactor;
            __padding char _1304[4];
/*0x1308*/  class TSubclassOf<ACamperExposerInstance> CamperExposer;
/*0x1310*/  bool CheatChainsaw;
/*0x1311*/  bool CheatAlwaysPounce;
/*0x1312*/  enum EKillerMoodInfluence KillerMoodInfluence;
            __padding char _1313[5];
/*0x1318*/  class TArray<enum EKillerAbilities, FDefaultAllocator> KillerAbilities;
/*0x1328*/  bool ShowKillerPowerDebugInfo;
/*0x1329*/  bool TempUseRageMechanic;
/*0x1330*/  class UCurveFloat* AttackForwardInputSmoothingCurve;
/*0x1338*/  struct TWeakObjectPtr<UAkComponent, FWeakObjectPtr> _audioComponent;
/*0x1340*/  float _attackAcceleration;
/*0x1344*/  float _slasherStealthRatio;
/*0x1348*/  float _slasherLightIntensity;
/*0x1350*/  class ACamperPlayer* _guidedCamper;
/*0x1358*/  class FDelegateHandle _soundDelegateHandle;
/*0x1360*/  class TMap<ADBDPlayer*, FChaseTimer, FDefaultSetAllocator, TDefaultMapKeyFuncs<ADBDPlayer*, FChaseTimer, 0>> _chaseTimers;
/*0x13b0*/  class TMap<ADBDPlayer*, FChaseTimer, FDefaultSetAllocator, TDefaultMapKeyFuncs<ADBDPlayer*, FChaseTimer, 0>> _stalkTimers;
/*0x1400*/  class UDBDPawnSensingComponent* _camperSensor;
/*0x1408*/  class UStillnessTrackerComponent* _stillnessTracker;
/*0x1410*/  class TArray<UItemAddon*, FDefaultAllocator> _powerAddons;
/*0x1420*/  struct FDBDTimer _recentlyCloakedTimer;
/*0x1440*/  struct FDBDTimer _flashlightBlindEvasionScoreTimer;
/*0x1460*/  struct FDBDTimer _flashlightBurnoutEvasionScoreTimer;
/*0x1480*/  float _stalkTierWalkSpeedMultiplier;
/*0x1484*/  float _baseTerrorRadius;
/*0x1488*/  float _terrorRadius;
            __padding char _148c[4];
/*0x1490*/  class FDelegateHandle _soundEventHandle;
/*0x1498*/  class ULoudNoiseHUDIndicator* _loudNoiseIndicator;
/*0x14a0*/  class UFlashLightReceiverComponent* _fullBodyFlashLightReceiver;
/*0x14a8*/  class UChargeableComponent* _invisibilityBurnoutChargeableComponent;
/*0x14b0*/  float _stealthDelay;
/*0x14b4*/  float _stealthIncreaseRate;
/*0x14b8*/  float _stealthDecreaseRate;
            __padding char _14bc[4];
/*0x14c0*/  struct FDateTime _stealthStartTime;
/*0x14c8*/  float _flashlightEvasionScoreCooldown;
/*0x14cc*/  bool _stealthEnabled;
/*0x14d0*/  float _chaseStartMaxDistance;
/*0x14d4*/  float _chaseMaxDistance;
/*0x14d8*/  float _chaseSightCooldown;
/*0x14dc*/  bool _isCloaked;
/*0x14dd*/  bool _isInStalkMode;
/*0x14de*/  bool _isChainBlinking;
/*0x14df*/  bool _isInBlinkCooldown;
/*0x14e0*/  bool _isBeingWiggled;
/*0x14e1*/  bool _isChainsawSprinting;
/*0x14e2*/  bool _isKilling;
/*0x14e4*/  int32_t _allowedKillCount;
/*0x14e8*/  int32_t _allowedKillAfterHookingCount;
/*0x14ec*/  int32_t _lungeType;
/*0x14f0*/  float _ragePercent;
/*0x14f4*/  float _ragePecentSmooth;
/*0x14f8*/  float _animDirection;
};
