/* 00000000 */ struct /*VFT*/ USlasherMovementComponent_vtbl // sizeof=0x990
/* 00000000 */ {
/* 00000000 */     void (__fastcall *~UObject)(struct UObject *this);
/* 00000008 */     void (__fastcall *RegisterDependencies)(struct UObject *this);
/* 00000010 */     void (__fastcall *DeferredRegister)(struct UObject *this, UClass *, const wchar_t *, const wchar_t *);
/* 00000018 */     bool (__fastcall *CanBeClusterRoot)(struct UObject *this);
/* 00000020 */     bool (__fastcall *CanBeInCluster)(struct UObject *this);
/* 00000028 */     void (__fastcall *CreateCluster)(struct UObject *this);
/* 00000030 */     void (__fastcall *AddToCluster)(struct UObject *this, UObjectBaseUtility *);
/* 00000038 */     FString *(__fastcall *GetDetailedInfoInternal)(UObject *this, FString *result);
/* 00000040 */     void (__fastcall *PostInitProperties)(UObject *this);
/* 00000048 */     bool (__fastcall *PreSaveRoot)(UObject *this, const wchar_t *, TArray<FString,FDefaultAllocator> *);
/* 00000050 */     void (__fastcall *PostSaveRoot)(UObject *this, bool);
/* 00000058 */     void (__fastcall *PreSave)(UObject *this, const ITargetPlatform *);
/* 00000060 */     bool (__fastcall *Modify)(UObject *this, bool);
/* 00000068 */     void (__fastcall *PostLoad)(UObject *this);
/* 00000070 */     void (__fastcall *PostLoadSubobjects)(UObject *this, FObjectInstancingGraph *);
/* 00000078 */     void (__fastcall *BeginDestroy)(UObject *this);
/* 00000080 */     bool (__fastcall *IsReadyForFinishDestroy)(UObject *this);
/* 00000088 */     void (__fastcall *FinishDestroy)(UObject *this);
/* 00000090 */     void (__fastcall *Serialize)(UObject *this, FArchive *);
/* 00000098 */     void (__fastcall *ShutdownAfterError)(UObject *this);
/* 000000A0 */     void (__fastcall *PostInterpChange)(UObject *this, UProperty *);
/* 000000A8 */     void (__fastcall *PostRename)(UObject *this, UObject *, const FName);
/* 000000B0 */     void (__fastcall *PostDuplicate)(UObject *this, bool);
/* 000000B8 */     bool (__fastcall *NeedsLoadForClient)(UObject *this);
/* 000000C0 */     bool (__fastcall *NeedsLoadForServer)(UObject *this);
/* 000000C8 */     bool (__fastcall *NeedsLoadForEditorGame)(UObject *this);
/* 000000D0 */     bool (__fastcall *IsPostLoadThreadSafe)(UObject *this);
/* 000000D8 */     void (__fastcall *ExportCustomProperties)(UObject *this, FOutputDevice *, unsigned int);
/* 000000E0 */     void (__fastcall *ImportCustomProperties)(UObject *this, const wchar_t *, FFeedbackContext *);
/* 000000E8 */     void (__fastcall *PostEditImport)(UObject *this);
/* 000000F0 */     void (__fastcall *PostReloadConfig)(UObject *this, UProperty *);
/* 000000F8 */     bool (__fastcall *Rename)(UObject *this, const wchar_t *, UObject *, unsigned int);
/* 00000100 */     FString *(__fastcall *GetDesc)(UObject *this, FString *result);
/* 00000108 */     UWorld *(__fastcall *GetWorld)(UObject *this);
/* 00000110 */     bool (__fastcall *GetNativePropertyValues)(UObject *this, TMap<FString,FString,FDefaultSetAllocator,TDefaultMapKeyFuncs<FString,FString,0> > *, unsigned int);
/* 00000118 */     unsigned __int64 (__fastcall *GetResourceSize)(UObject *this, EResourceSizeMode::Type);
/* 00000120 */     FName *(__fastcall *GetExporterName)(UObject *this, FName *result);
/* 00000128 */     FRestoreForUObjectOverwrite *(__fastcall *GetRestoreForUObjectOverwrite)(UObject *this);
/* 00000130 */     bool (__fastcall *AreNativePropertiesIdenticalTo)(UObject *this, UObject *);
/* 00000138 */     void (__fastcall *GetAssetRegistryTags)(UObject *this, TArray<UObject::FAssetRegistryTag,FDefaultAllocator> *);
/* 00000140 */     bool (__fastcall *IsAsset)(UObject *this);
/* 00000148 */     bool (__fastcall *IsLocalizedResource)(UObject *this);
/* 00000150 */     bool (__fastcall *IsSafeForRootSet)(UObject *this);
/* 00000158 */     void (__fastcall *TagSubobjects)(UObject *this, EObjectFlags);
/* 00000160 */     void (__fastcall *GetLifetimeReplicatedProps)(UObject *this, TArray<FLifetimeProperty,FDefaultAllocator> *);
/* 00000168 */     bool (__fastcall *IsNameStableForNetworking)(UObject *this);
/* 00000170 */     bool (__fastcall *IsFullNameStableForNetworking)(UObject *this);
/* 00000178 */     bool (__fastcall *IsSupportedForNetworking)(UObject *this);
/* 00000180 */     void (__fastcall *GetSubobjectsWithStableNamesForNetworking)(UObject *this, TArray<UObject *,FDefaultAllocator> *);
/* 00000188 */     void (__fastcall *PreNetReceive)(UObject *this);
/* 00000190 */     void (__fastcall *PostNetReceive)(UObject *this);
/* 00000198 */     void (__fastcall *PostRepNotifies)(UObject *this);
/* 000001A0 */     void (__fastcall *PreDestroyFromReplication)(UObject *this);
/* 000001A8 */     void (__fastcall *ProcessEvent)(UObject *this, UFunction *, void *);
/* 000001B0 */     int (__fastcall *GetFunctionCallspace)(UObject *this, UFunction *, void *, FFrame *);
/* 000001B8 */     bool (__fastcall *CallRemoteFunction)(UObject *this, UFunction *, void *, FOutParmRec *, FFrame *);
/* 000001C0 */     bool (__fastcall *ProcessConsoleExec)(UObject *this, const wchar_t *, FOutputDevice *, UObject *);
/* 000001C8 */     UClass *(__fastcall *RegenerateClass)(UObject *this, UClass *, UObject *, TArray<UObject *,FDefaultAllocator> *);
/* 000001D0 */     void (__fastcall *MarkAsEditorOnlySubobject)(UObject *this);
/* 000001D8 */     bool (__fastcall *CheckDefaultSubobjectsInternal)(UObject *this);
/* 000001E0 */     void (__fastcall *Activate)(UActorComponent *this, bool);
/* 000001E8 */     void (__fastcall *Deactivate)(UActorComponent *this);
/* 000001F0 */     void (__fastcall *SetActive)(UActorComponent *this, bool, bool);
/* 000001F8 */     void (__fastcall *ToggleActive)(UActorComponent *this);
/* 00000200 */     bool (__fastcall *IsActive)(UActorComponent *this);
/* 00000208 */     bool (__fastcall *ReplicateSubobjects)(UActorComponent *this, UActorChannel *, FOutBunch *, FReplicationFlags *);
/* 00000210 */     void (__fastcall *PreReplication)(UActorComponent *this, IRepChangedPropertyTracker *);
/* 00000218 */     bool (__fastcall *GetComponentClassCanReplicate)(UActorComponent *this);
/* 00000220 */     bool (__fastcall *IsEditorOnly)(UActorComponent *this);
/* 00000228 */     bool (__fastcall *ShouldActivate)(UActorComponent *this);
/* 00000230 */     void (__fastcall *OnRegister)(UActorComponent *this);
/* 00000238 */     void (__fastcall *OnUnregister)(UActorComponent *this);
/* 00000240 */     bool (__fastcall *ShouldCreateRenderState)(UActorComponent *this);
/* 00000248 */     void (__fastcall *CreateRenderState_Concurrent)(UActorComponent *this);
/* 00000250 */     void (__fastcall *SendRenderTransform_Concurrent)(UActorComponent *this);
/* 00000258 */     void (__fastcall *SendRenderDynamicData_Concurrent)(UActorComponent *this);
/* 00000260 */     void (__fastcall *DestroyRenderState_Concurrent)(UActorComponent *this);
/* 00000268 */     void (__fastcall *OnCreatePhysicsState)(UActorComponent *this);
/* 00000270 */     void (__fastcall *OnDestroyPhysicsState)(UActorComponent *this);
/* 00000278 */     bool (__fastcall *ShouldCreatePhysicsState)(UActorComponent *this);
/* 00000280 */     bool (__fastcall *HasValidPhysicsState)(UActorComponent *this);
/* 00000288 */     void (__fastcall *RegisterComponentTickFunctions)(UActorComponent *this, bool);
/* 00000290 */     void (__fastcall *InitializeComponent)(UActorComponent *this);
/* 00000298 */     void (__fastcall *BeginPlay)(UActorComponent *this);
/* 000002A0 */     void (__fastcall *EndPlay)(UActorComponent *this, const EEndPlayReason::Type);
/* 000002A8 */     void (__fastcall *UninitializeComponent)(UActorComponent *this);
/* 000002B0 */     void (__fastcall *TickComponent)(UActorComponent *this, float, ELevelTick, FActorComponentTickFunction *);
/* 000002B8 */     void (__fastcall *SetComponentTickEnabled)(UActorComponent *this, bool);
/* 000002C0 */     void (__fastcall *SetComponentTickEnabledAsync)(UActorComponent *this, bool);
/* 000002C8 */     void (__fastcall *InvalidateLightingCacheDetailed)(UActorComponent *this, bool, bool);
/* 000002D0 */     void (__fastcall *UpdateComponentToWorld)(UActorComponent *this, EUpdateTransformFlags, ETeleportType);
/* 000002D8 */     bool (__fastcall *RequiresGameThreadEndOfFrameUpdates)(UActorComponent *this);
/* 000002E0 */     bool (__fastcall *RequiresGameThreadEndOfFrameRecreate)(UActorComponent *this);
/* 000002E8 */     void (__fastcall *OnActorEnableCollisionChanged)(UActorComponent *this);
/* 000002F0 */     FString *(__fastcall *GetReadableName)(UActorComponent *this, FString *result);
/* 000002F8 */     const UObject *(__fastcall *AdditionalStatObject)(UActorComponent *this);
/* 00000300 */     FActorComponentInstanceData *(__fastcall *GetComponentInstanceData)(UActorComponent *this);
/* 00000308 */     void (__fastcall *DestroyComponent)(UActorComponent *this, bool);
/* 00000310 */     void (__fastcall *OnComponentCreated)(UActorComponent *this);
/* 00000318 */     void (__fastcall *OnComponentDestroyed)(UActorComponent *this, bool);
/* 00000320 */     void (__fastcall *AddTickPrerequisiteActor)(UActorComponent *this, AActor *);
/* 00000328 */     void (__fastcall *AddTickPrerequisiteComponent)(UActorComponent *this, UActorComponent *);
/* 00000330 */     void (__fastcall *RemoveTickPrerequisiteActor)(UActorComponent *this, AActor *);
/* 00000338 */     void (__fastcall *RemoveTickPrerequisiteComponent)(UActorComponent *this, UActorComponent *);
/* 00000340 */     void (__fastcall *ApplyWorldOffset)(UActorComponent *this, const FVector *, bool);
/* 00000348 */     bool (__fastcall *IsNavigationRelevant)(UActorComponent *this);
/* 00000350 */     float (__fastcall *GetGravityZ)(UMovementComponent *this);
/* 00000358 */     float (__fastcall *GetMaxSpeed)(UMovementComponent *this);
/* 00000360 */     float (__fastcall *GetMaxSpeedModifier)(UMovementComponent *this);
/* 00000368 */     float (__fastcall *K2_GetMaxSpeedModifier)(UMovementComponent *this);
/* 00000370 */     float (__fastcall *GetModifiedMaxSpeed)(UMovementComponent *this);
/* 00000378 */     float (__fastcall *K2_GetModifiedMaxSpeed)(UMovementComponent *this);
/* 00000380 */     bool (__fastcall *IsExceedingMaxSpeed)(UMovementComponent *this, float);
/* 00000388 */     void (__fastcall *StopMovementImmediately)(UMovementComponent *this);
/* 00000390 */     bool (__fastcall *ShouldSkipUpdate)(UMovementComponent *this, float);
/* 00000398 */     bool (__fastcall *SkipUpdate)(UMovementComponent *this, float);
/* 000003A0 */     APhysicsVolume *(__fastcall *GetPhysicsVolume)(UMovementComponent *this);
/* 000003A8 */     void (__fastcall *PhysicsVolumeChanged)(UMovementComponent *this, APhysicsVolume *);
/* 000003B0 */     void (__fastcall *SetUpdatedComponent)(UMovementComponent *this, USceneComponent *);
/* 000003B8 */     bool (__fastcall *IsInWater)(UMovementComponent *this);
/* 000003C0 */     void (__fastcall *UpdateTickRegistration)(UMovementComponent *this);
/* 000003C8 */     void (__fastcall *HandleImpact)(UMovementComponent *this, const FHitResult *, float, const FVector *);
/* 000003D0 */     void (__fastcall *UpdateComponentVelocity)(UMovementComponent *this);
/* 000003D8 */     void (__fastcall *InitCollisionParams)(UMovementComponent *this, FCollisionQueryParams *, FCollisionResponseParams *);
/* 000003E0 */     bool (__fastcall *OverlapTest)(UMovementComponent *this, const FVector *, const FQuat *, const ECollisionChannel, const FCollisionShape *, const AActor *);
/* 000003E8 */     bool (__fastcall *MoveUpdatedComponentImpl)(UMovementComponent *this, const FVector *, const FQuat *, bool, FHitResult *, ETeleportType);
/* 000003F0 */     FVector *(__fastcall *GetPenetrationAdjustment)(UMovementComponent *this, FVector *result, const FHitResult *);
/* 000003F8 */     bool (__fastcall *ResolvePenetrationImpl)(UMovementComponent *this, const FVector *, const FHitResult *, const FQuat *);
/* 00000400 */     FVector *(__fastcall *ComputeSlideVector)(UMovementComponent *this, FVector *result, const FVector *, const float, const FVector *, const FHitResult *);
/* 00000408 */     float (__fastcall *SlideAlongSurface)(UMovementComponent *this, const FVector *, float, const FVector *, FHitResult *, bool);
/* 00000410 */     void (__fastcall *TwoWallAdjust)(UMovementComponent *this, FVector *, const FHitResult *, const FVector *);
/* 00000418 */     void (__fastcall *AddRadialForce)(UMovementComponent *this, const FVector *, float, float, ERadialImpulseFalloff);
/* 00000420 */     void (__fastcall *AddRadialImpulse)(UMovementComponent *this, const FVector *, float, float, ERadialImpulseFalloff, bool);
/* 00000428 */     void (__fastcall *SetPlaneConstraintAxisSetting)(UMovementComponent *this, EPlaneConstraintAxisSetting);
/* 00000430 */     void (__fastcall *SetPlaneConstraintNormal)(UMovementComponent *this, FVector);
/* 00000438 */     void (__fastcall *SetPlaneConstraintFromVectors)(UMovementComponent *this, FVector, FVector);
/* 00000440 */     void (__fastcall *SetPlaneConstraintOrigin)(UMovementComponent *this, FVector);
/* 00000448 */     void (__fastcall *SetPlaneConstraintEnabled)(UMovementComponent *this, bool);
/* 00000450 */     FVector *(__fastcall *ConstrainDirectionToPlane)(UMovementComponent *this, FVector *result, FVector);
/* 00000458 */     FVector *(__fastcall *ConstrainLocationToPlane)(UMovementComponent *this, FVector *result, FVector);
/* 00000460 */     FVector *(__fastcall *ConstrainNormalToPlane)(UMovementComponent *this, FVector *result, FVector);
/* 00000468 */     void (__fastcall *SnapUpdatedComponentToPlane)(UMovementComponent *this);
/* 00000470 */     void (__fastcall *OnTeleported)(UMovementComponent *this);
/* 00000478 */     void (__fastcall *StopActiveMovement)(UNavMovementComponent *this);
/* 00000480 */     FBasedPosition *(__fastcall *GetActorFeetLocationBased)(UNavMovementComponent *this, FBasedPosition *result);
/* 00000488 */     void (__fastcall *RequestDirectMove)(UNavMovementComponent *this, const FVector *, bool);
/* 00000490 */     void (__fastcall *RequestPathMove)(UNavMovementComponent *this, const FVector *);
/* 00000498 */     bool (__fastcall *CanStopPathFollowing)(UNavMovementComponent *this);
/* 000004A0 */     float (__fastcall *GetPathFollowingBrakingDistance)(UNavMovementComponent *this, float);
/* 000004A8 */     bool (__fastcall *CanStartPathFollowing)(UNavMovementComponent *this);
/* 000004B0 */     bool (__fastcall *IsCrouching)(UNavMovementComponent *this);
/* 000004B8 */     bool (__fastcall *IsFalling)(UNavMovementComponent *this);
/* 000004C0 */     bool (__fastcall *IsMovingOnGround)(UNavMovementComponent *this);
/* 000004C8 */     bool (__fastcall *IsSwimming)(UNavMovementComponent *this);
/* 000004D0 */     bool (__fastcall *IsFlying)(UNavMovementComponent *this);
/* 000004D8 */     void (__fastcall *AddInputVector)(UPawnMovementComponent *this, FVector, bool);
/* 000004E0 */     FVector *(__fastcall *ConsumeInputVector)(UPawnMovementComponent *this, FVector *result);
/* 000004E8 */     bool (__fastcall *IsMoveInputIgnored)(UPawnMovementComponent *this);
/* 000004F0 */     void (__fastcall *NotifyBumpedPawn)(UPawnMovementComponent *this, APawn *);
/* 000004F8 */     float (__fastcall *ComputeAnalogInputModifier)(UCharacterMovementComponent *this);
/* 00000500 */     void (__fastcall *SimulatedRootMotionPositionFixup)(UCharacterMovementComponent *this, float);
/* 00000508 */     void (__fastcall *SetMovementMode)(UCharacterMovementComponent *this, EMovementMode, unsigned __int8);
/* 00000510 */     void (__fastcall *OnMovementModeChanged)(UCharacterMovementComponent *this, EMovementMode, unsigned __int8);
/* 00000518 */     void (__fastcall *ApplyNetworkMovementMode)(UCharacterMovementComponent *this, const unsigned __int8);
/* 00000520 */     void (__fastcall *DisableMovement)(UCharacterMovementComponent *this);
/* 00000528 */     bool (__fastcall *HasValidData)(UCharacterMovementComponent *this);
/* 00000530 */     void (__fastcall *PerformAirControlForPathFollowing)(UCharacterMovementComponent *this, FVector, float);
/* 00000538 */     void (__fastcall *PerformAirControl)(UCharacterMovementComponent *this, FVector, float);
/* 00000540 */     void (__fastcall *StartFalling)(UCharacterMovementComponent *this, int, float, float, const FVector *, const FVector *);
/* 00000548 */     bool (__fastcall *ShouldCatchAir)(UCharacterMovementComponent *this, const FFindFloorResult *, const FFindFloorResult *);
/* 00000550 */     void (__fastcall *AdjustFloorHeight)(UCharacterMovementComponent *this);
/* 00000558 */     void (__fastcall *MaybeUpdateBasedMovement)(UCharacterMovementComponent *this, float);
/* 00000560 */     void (__fastcall *UpdateBasedMovement)(UCharacterMovementComponent *this, float);
/* 00000568 */     void (__fastcall *UpdateBasedRotation)(UCharacterMovementComponent *this, FRotator *, const FRotator *);
/* 00000570 */     void (__fastcall *MaybeSaveBaseLocation)(UCharacterMovementComponent *this);
/* 00000578 */     void (__fastcall *SaveBaseLocation)(UCharacterMovementComponent *this);
/* 00000580 */     void (__fastcall *StartNewPhysics)(UCharacterMovementComponent *this, float, int);
/* 00000588 */     bool (__fastcall *DoJump)(UCharacterMovementComponent *this, bool);
/* 00000590 */     void (__fastcall *Launch)(UCharacterMovementComponent *this, const FVector *);
/* 00000598 */     bool (__fastcall *HandlePendingLaunch)(UCharacterMovementComponent *this);
/* 000005A0 */     FVector *(__fastcall *GetImpartedMovementBaseVelocity)(UCharacterMovementComponent *this, FVector *result);
/* 000005A8 */     void (__fastcall *JumpOff)(UCharacterMovementComponent *this, AActor *);
/* 000005B0 */     FVector *(__fastcall *GetBestDirectionOffActor)(UCharacterMovementComponent *this, FVector *result, AActor *);
/* 000005B8 */     bool (__fastcall *ShouldJumpOutOfWater)(UCharacterMovementComponent *this, FVector *);
/* 000005C0 */     void (__fastcall *JumpOutOfWater)(UCharacterMovementComponent *this, FVector);
/* 000005C8 */     FRotator *(__fastcall *GetDeltaRotation)(UCharacterMovementComponent *this, FRotator *result, float);
/* 000005D0 */     FRotator *(__fastcall *ComputeOrientToMovementRotation)(UCharacterMovementComponent *this, FRotator *result, const FRotator *, float, FRotator *);
/* 000005D8 */     bool (__fastcall *ApplyRequestedMove)(UCharacterMovementComponent *this, float, float, float, float, float, FVector *, float *);
/* 000005E0 */     void (__fastcall *NotifyJumpApex)(UCharacterMovementComponent *this);
/* 000005E8 */     FVector *(__fastcall *NewFallVelocity)(UCharacterMovementComponent *this, FVector *result, const FVector *, const FVector *, float);
/* 000005F0 */     float (__fastcall *ImmersionDepth)(UCharacterMovementComponent *this);
/* 000005F8 */     void (__fastcall *CalcVelocity)(UCharacterMovementComponent *this, float, float, bool, float);
/* 00000600 */     float (__fastcall *GetMaxJumpHeight)(UCharacterMovementComponent *this);
/* 00000608 */     float (__fastcall *GetModifiedMaxAcceleration)(UCharacterMovementComponent *this);
/* 00000610 */     float (__fastcall *K2_GetModifiedMaxAcceleration)(UCharacterMovementComponent *this);
/* 00000618 */     float (__fastcall *GetMaxAcceleration)(UCharacterMovementComponent *this);
/* 00000620 */     bool (__fastcall *CanStepUp)(UCharacterMovementComponent *this, const FHitResult *);
/* 00000628 */     bool (__fastcall *StepUp)(UCharacterMovementComponent *this, const FVector *, const FVector *, const FHitResult *, UCharacterMovementComponent::FStepDownResult *);
/* 00000630 */     void (__fastcall *SetBase)(UCharacterMovementComponent *this, UPrimitiveComponent *, const FName, bool);
/* 00000638 */     void (__fastcall *ApplyDownwardForce)(UCharacterMovementComponent *this, float);
/* 00000640 */     void (__fastcall *ApplyRepulsionForce)(UCharacterMovementComponent *this, float);
/* 00000648 */     void (__fastcall *ApplyAccumulatedForces)(UCharacterMovementComponent *this, float);
/* 00000650 */     void (__fastcall *PhysFalling)(UCharacterMovementComponent *this, float, int);
/* 00000658 */     FVector *(__fastcall *GetFallingLateralAcceleration)(UCharacterMovementComponent *this, FVector *result, float);
/* 00000660 */     FVector *(__fastcall *GetAirControl)(UCharacterMovementComponent *this, FVector *result, float, float, const FVector *);
/* 00000668 */     float (__fastcall *BoostAirControl)(UCharacterMovementComponent *this, float, float, const FVector *);
/* 00000670 */     bool (__fastcall *FindAirControlImpact)(UCharacterMovementComponent *this, float, float, const FVector *, const FVector *, const FVector *, FHitResult *);
/* 00000678 */     FVector *(__fastcall *LimitAirControl)(UCharacterMovementComponent *this, FVector *result, float, const FVector *, const FHitResult *, bool);
/* 00000680 */     void (__fastcall *ProcessLanded)(UCharacterMovementComponent *this, const FHitResult *, float, int);
/* 00000688 */     void (__fastcall *SetPostLandedPhysics)(UCharacterMovementComponent *this, const FHitResult *);
/* 00000690 */     void (__fastcall *SetNavWalkingPhysics)(UCharacterMovementComponent *this, bool);
/* 00000698 */     bool (__fastcall *TryToLeaveNavWalking)(UCharacterMovementComponent *this);
/* 000006A0 */     FVector *(__fastcall *ProjectLocationFromNavMesh)(UCharacterMovementComponent *this, FVector *result, float, const FVector *, const FVector *, float, float);
/* 000006A8 */     void (__fastcall *FindBestNavMeshLocation)(UCharacterMovementComponent *this, const FVector *, const FVector *, const FVector *, const FVector *, FHitResult *);
/* 000006B0 */     void (__fastcall *Crouch)(UCharacterMovementComponent *this, bool);
/* 000006B8 */     void (__fastcall *UnCrouch)(UCharacterMovementComponent *this, bool);
/* 000006C0 */     bool (__fastcall *CanCrouchInCurrentState)(UCharacterMovementComponent *this);
/* 000006C8 */     bool (__fastcall *CheckLedgeDirection)(UCharacterMovementComponent *this, const FVector *, const FVector *, const FVector *);
/* 000006D0 */     FVector *(__fastcall *GetLedgeMove)(UCharacterMovementComponent *this, FVector *result, const FVector *, const FVector *, const FVector *);
/* 000006D8 */     bool (__fastcall *CheckFall)(UCharacterMovementComponent *this, const FFindFloorResult *, const FHitResult *, const FVector *, const FVector *, float, float, int, bool);
/* 000006E0 */     void (__fastcall *PhysicsRotation)(UCharacterMovementComponent *this, float);
/* 000006E8 */     void (__fastcall *SetDefaultMovementMode)(UCharacterMovementComponent *this);
/* 000006F0 */     void (__fastcall *MoveSmooth)(UCharacterMovementComponent *this, const FVector *, const float, UCharacterMovementComponent::FStepDownResult *);
/* 000006F8 */     FString *(__fastcall *GetMovementName)(UCharacterMovementComponent *this, FString *result);
/* 00000700 */     void (__fastcall *AddImpulse)(UCharacterMovementComponent *this, FVector, bool);
/* 00000708 */     void (__fastcall *AddForce)(UCharacterMovementComponent *this, FVector);
/* 00000710 */     void (__fastcall *DisplayDebug)(UCharacterMovementComponent *this, UCanvas *, const FDebugDisplayInfo *, float *, float *);
/* 00000718 */     void (__fastcall *VisualizeMovement)(UCharacterMovementComponent *this);
/* 00000720 */     bool (__fastcall *CheckWaterJump)(UCharacterMovementComponent *this, FVector, FVector *);
/* 00000728 */     bool (__fastcall *CanWalkOffLedges)(UCharacterMovementComponent *this);
/* 00000730 */     bool (__fastcall *IsWalkable)(UCharacterMovementComponent *this, const FHitResult *);
/* 00000738 */     void (__fastcall *PostPhysicsTickComponent)(UCharacterMovementComponent *this, float, FCharacterMovementComponentPostPhysicsTickFunction *);
/* 00000740 */     void (__fastcall *PhysWalking)(UCharacterMovementComponent *this, float, int);
/* 00000748 */     void (__fastcall *PhysNavWalking)(UCharacterMovementComponent *this, float, int);
/* 00000750 */     void (__fastcall *PhysFlying)(UCharacterMovementComponent *this, float, int);
/* 00000758 */     void (__fastcall *PhysSwimming)(UCharacterMovementComponent *this, float, int);
/* 00000760 */     void (__fastcall *PhysCustom)(UCharacterMovementComponent *this, float, int);
/* 00000768 */     FVector *(__fastcall *ComputeGroundMovementDelta)(UCharacterMovementComponent *this, FVector *result, const FVector *, const FHitResult *, const bool);
/* 00000770 */     void (__fastcall *MoveAlongFloor)(UCharacterMovementComponent *this, const FVector *, float, UCharacterMovementComponent::FStepDownResult *);
/* 00000778 */     void (__fastcall *OnCharacterStuckInGeometry)(UCharacterMovementComponent *this, const FHitResult *);
/* 00000780 */     void (__fastcall *MaintainHorizontalGroundVelocity)(UCharacterMovementComponent *this);
/* 00000788 */     void (__fastcall *ApplyImpactPhysicsForces)(UCharacterMovementComponent *this, const FHitResult *, const FVector *, const FVector *);
/* 00000790 */     FVector *(__fastcall *AdjustUpperHemisphereImpact)(UCharacterMovementComponent *this, FVector *result, const FVector *, const FHitResult *);
/* 00000798 */     FVector *(__fastcall *HandleSlopeBoosting)(UCharacterMovementComponent *this, FVector *result, const FVector *, const FVector *, const float, const FVector *, const FHitResult *);
/* 000007A0 */     void (__fastcall *ApplyVelocityBraking)(UCharacterMovementComponent *this, float, float, float);
/* 000007A8 */     bool (__fastcall *IsWithinEdgeTolerance)(UCharacterMovementComponent *this, const FVector *, const FVector *, const float);
/* 000007B0 */     void (__fastcall *FindFloor)(UCharacterMovementComponent *this, const FVector *, FFindFloorResult *, bool, const FHitResult *);
/* 000007B8 */     void (__fastcall *ComputeFloorDist)(UCharacterMovementComponent *this, const FVector *, float, float, FFindFloorResult *, float, const FHitResult *);
/* 000007C0 */     bool (__fastcall *FloorSweepTest)(UCharacterMovementComponent *this, FHitResult *, const FVector *, const FVector *, ECollisionChannel, const FCollisionShape *, const FCollisionQueryParams *, const FCollisionResponseParams *);
/* 000007C8 */     bool (__fastcall *IsValidLandingSpot)(UCharacterMovementComponent *this, const FVector *, const FHitResult *);
/* 000007D0 */     bool (__fastcall *ShouldCheckForValidLandingSpot)(UCharacterMovementComponent *this, float, const FVector *, const FHitResult *);
/* 000007D8 */     bool (__fastcall *ShouldComputePerchResult)(UCharacterMovementComponent *this, const FHitResult *, bool);
/* 000007E0 */     bool (__fastcall *ComputePerchResult)(UCharacterMovementComponent *this, const float, const FHitResult *, const float, FFindFloorResult *);
/* 000007E8 */     void (__fastcall *CapsuleTouched)(UCharacterMovementComponent *this, UPrimitiveComponent *, AActor *, UPrimitiveComponent *, int, bool, const FHitResult *);
/* 000007F0 */     void (__fastcall *AdjustProxyCapsuleSize)(UCharacterMovementComponent *this);
/* 000007F8 */     FVector *(__fastcall *ConstrainInputAcceleration)(UCharacterMovementComponent *this, FVector *result, const FVector *);
/* 00000800 */     FVector *(__fastcall *ScaleInputAcceleration)(UCharacterMovementComponent *this, FVector *result, const FVector *);
/* 00000808 */     void (__fastcall *OnMovementUpdated)(UCharacterMovementComponent *this, float, const FVector *, const FVector *);
/* 00000810 */     void (__fastcall *CallMovementUpdateDelegate)(UCharacterMovementComponent *this, float, const FVector *, const FVector *);
/* 00000818 */     void (__fastcall *OnUnableToFollowBaseMove)(UCharacterMovementComponent *this, const FVector *, const FVector *, const FHitResult *);
/* 00000820 */     void (__fastcall *RefreshMovementModeOnTeleport)(UCharacterMovementComponent *this, UPrimitiveComponent *, UPrimitiveComponent *);
/* 00000828 */     bool (__fastcall *FindNavFloor)(UCharacterMovementComponent *this, const FVector *, FNavLocation *);
/* 00000830 */     void (__fastcall *PerformMovement)(UCharacterMovementComponent *this, float);
/* 00000838 */     void (__fastcall *SimulateMovement)(UCharacterMovementComponent *this, float);
/* 00000840 */     void (__fastcall *ForceReplicationUpdate)(UCharacterMovementComponent *this);
/* 00000848 */     float (__fastcall *GetNetworkSafeRandomAngleDegrees)(UCharacterMovementComponent *this);
/* 00000850 */     FVector *(__fastcall *RoundAcceleration)(UCharacterMovementComponent *this, FVector *result, FVector);
/* 00000858 */     void (__fastcall *SmoothClientPosition)(UCharacterMovementComponent *this, float);
/* 00000860 */     void (__fastcall *ReplicateMoveToServer)(UCharacterMovementComponent *this, float, const FVector *);
/* 00000868 */     bool (__fastcall *ClientUpdatePositionAfterServerUpdate)(UCharacterMovementComponent *this);
/* 00000870 */     void (__fastcall *CallServerMove)(UCharacterMovementComponent *this, const FSavedMove_Character *, const FSavedMove_Character *);
/* 00000878 */     void (__fastcall *ServerMoveHandleClientError)(UCharacterMovementComponent *this, float, float, const FVector *, const FVector *, UPrimitiveComponent *, FName, unsigned __int8);
/* 00000880 */     bool (__fastcall *ServerCheckClientError)(UCharacterMovementComponent *this, float, float, const FVector *, const FVector *, const FVector *, UPrimitiveComponent *, FName, unsigned __int8);
/* 00000888 */     void (__fastcall *MoveAutonomous)(UCharacterMovementComponent *this, float, float, unsigned __int8, const FVector *);
/* 00000890 */     void (__fastcall *UpdateFromCompressedFlags)(UCharacterMovementComponent *this, unsigned __int8);
/* 00000898 */     bool (__fastcall *CanDelaySendingMove)(UCharacterMovementComponent *this, const TSharedPtr<FSavedMove_Character,0> *);
/* 000008A0 */     bool (__fastcall *ShouldCancelAdaptiveReplication)(UCharacterMovementComponent *this);
/* 000008A8 */     void (__fastcall *UpdateFloorFromAdjustment)(UCharacterMovementComponent *this);
/* 000008B0 */     bool (__fastcall *VerifyClientTimeStamp)(UCharacterMovementComponent *this, float, FNetworkPredictionData_Server_Character *);
/* 000008B8 */     void (__fastcall *OnClientTimeStampResetDetected)(UCharacterMovementComponent *this);
/* 000008C0 */     void (__fastcall *ProcessClientTimeStampForTimeDiscrepancy)(UCharacterMovementComponent *this, float, FNetworkPredictionData_Server_Character *);
/* 000008C8 */     void (__fastcall *OnTimeDiscrepancyDetected)(UCharacterMovementComponent *this, float, float, float, float);
/* 000008D0 */     void (__fastcall *ServerMove)(UCharacterMovementComponent *this, float, FVector_NetQuantize10, FVector_NetQuantize100, unsigned __int8, unsigned __int8, unsigned int, UPrimitiveComponent *, FName, unsigned __int8);
/* 000008D8 */     void (__fastcall *ServerMove_Implementation)(UCharacterMovementComponent *this, float, FVector_NetQuantize10, FVector_NetQuantize100, unsigned __int8, unsigned __int8, unsigned int, UPrimitiveComponent *, FName, unsigned __int8);
/* 000008E0 */     bool (__fastcall *ServerMove_Validate)(UCharacterMovementComponent *this, float, FVector_NetQuantize10, FVector_NetQuantize100, unsigned __int8, unsigned __int8, unsigned int, UPrimitiveComponent *, FName, unsigned __int8);
/* 000008E8 */     void (__fastcall *ServerMoveDual)(UCharacterMovementComponent *this, float, FVector_NetQuantize10, unsigned __int8, unsigned int, float, FVector_NetQuantize10, FVector_NetQuantize100, unsigned __int8, unsigned __int8, unsigned int, UPrimitiveComponent *, FName, unsigned __int8);
/* 000008F0 */     void (__fastcall *ServerMoveDual_Implementation)(UCharacterMovementComponent *this, float, FVector_NetQuantize10, unsigned __int8, unsigned int, float, FVector_NetQuantize10, FVector_NetQuantize100, unsigned __int8, unsigned __int8, unsigned int, UPrimitiveComponent *, FName, unsigned __int8);
/* 000008F8 */     bool (__fastcall *ServerMoveDual_Validate)(UCharacterMovementComponent *this, float, FVector_NetQuantize10, unsigned __int8, unsigned int, float, FVector_NetQuantize10, FVector_NetQuantize100, unsigned __int8, unsigned __int8, unsigned int, UPrimitiveComponent *, FName, unsigned __int8);
/* 00000900 */     void (__fastcall *ServerMoveDualHybridRootMotion)(UCharacterMovementComponent *this, float, FVector_NetQuantize10, unsigned __int8, unsigned int, float, FVector_NetQuantize10, FVector_NetQuantize100, unsigned __int8, unsigned __int8, unsigned int, UPrimitiveComponent *, FName, unsigned __int8);
/* 00000908 */     void (__fastcall *ServerMoveDualHybridRootMotion_Implementation)(UCharacterMovementComponent *this, float, FVector_NetQuantize10, unsigned __int8, unsigned int, float, FVector_NetQuantize10, FVector_NetQuantize100, unsigned __int8, unsigned __int8, unsigned int, UPrimitiveComponent *, FName, unsigned __int8);
/* 00000910 */     bool (__fastcall *ServerMoveDualHybridRootMotion_Validate)(UCharacterMovementComponent *this, float, FVector_NetQuantize10, unsigned __int8, unsigned int, float, FVector_NetQuantize10, FVector_NetQuantize100, unsigned __int8, unsigned __int8, unsigned int, UPrimitiveComponent *, FName, unsigned __int8);
/* 00000918 */     void (__fastcall *ServerMoveOld)(UCharacterMovementComponent *this, float, FVector_NetQuantize10, unsigned __int8);
/* 00000920 */     void (__fastcall *ServerMoveOld_Implementation)(UCharacterMovementComponent *this, float, FVector_NetQuantize10, unsigned __int8);
/* 00000928 */     bool (__fastcall *ServerMoveOld_Validate)(UCharacterMovementComponent *this, float, FVector_NetQuantize10, unsigned __int8);
/* 00000930 */     void (__fastcall *ClientAckGoodMove)(UCharacterMovementComponent *this, float);
/* 00000938 */     void (__fastcall *ClientAckGoodMove_Implementation)(UCharacterMovementComponent *this, float);
/* 00000940 */     void (__fastcall *ClientAdjustPosition)(UCharacterMovementComponent *this, float, FVector, FVector, UPrimitiveComponent *, FName, bool, bool, unsigned __int8);
/* 00000948 */     void (__fastcall *ClientAdjustPosition_Implementation)(UCharacterMovementComponent *this, float, FVector, FVector, UPrimitiveComponent *, FName, bool, bool, unsigned __int8);
/* 00000950 */     void (__fastcall *ClientVeryShortAdjustPosition)(UCharacterMovementComponent *this, float, FVector, UPrimitiveComponent *, FName, bool, bool, unsigned __int8);
/* 00000958 */     void (__fastcall *ClientVeryShortAdjustPosition_Implementation)(UCharacterMovementComponent *this, float, FVector, UPrimitiveComponent *, FName, bool, bool, unsigned __int8);
/* 00000960 */     void (__fastcall *OnRootMotionSourceBeingApplied)(UCharacterMovementComponent *this, const FRootMotionSource *);
/* 00000968 */     FVector *(__fastcall *CalcAnimRootMotionVelocity)(UCharacterMovementComponent *this, FVector *result, const FVector *, float, const FVector *);
/* 00000970 */     FVector *(__fastcall *CalcRootMotionVelocity)(UCharacterMovementComponent *this, FVector *result, const FVector *, float, const FVector *);
/* 00000978 */     FVector *(__fastcall *ConstrainAnimRootMotionVelocity)(UCharacterMovementComponent *this, FVector *result, const FVector *, const FVector *);
/* 00000980 */     void (__fastcall *CalcAvoidanceVelocity)(UCharacterMovementComponent *this, float);
/* 00000988 */     void (__fastcall *PostProcessAvoidanceVelocity)(UCharacterMovementComponent *this, FVector *);
/* 00000990 */ };

/* 00000000 */ struct /*VFT*/ IInterface_AssetUserData_vtbl // sizeof=0x30
/* 00000000 */ {
/* 00000000 */     void (__fastcall *~IInterface_AssetUserData)(IInterface_AssetUserData *this);
/* 00000008 */     UObject *(__fastcall *_getUObject)(IInterface_AssetUserData *this);
/* 00000010 */     void (__fastcall *AddAssetUserData)(IInterface_AssetUserData *this, UAssetUserData *);
/* 00000018 */     UAssetUserData *(__fastcall *GetAssetUserDataOfClass)(IInterface_AssetUserData *this, TSubclassOf<UAssetUserData>);
/* 00000020 */     const TArray<UAssetUserData *,FDefaultAllocator> *(__fastcall *GetAssetUserDataArray)(IInterface_AssetUserData *this);
/* 00000028 */     void (__fastcall *RemoveUserDataOfClass)(IInterface_AssetUserData *this, TSubclassOf<UAssetUserData>);
/* 00000030 */ };

/* 00000000 */ struct /*VFT*/ IRVOAvoidanceInterface_vtbl // sizeof=0x70
/* 00000000 */ {
/* 00000000 */     void (__fastcall *~IRVOAvoidanceInterface)(IRVOAvoidanceInterface *this);
/* 00000008 */     UObject *(__fastcall *_getUObject)(IRVOAvoidanceInterface *this);
/* 00000010 */     void (__fastcall *SetRVOAvoidanceUID)(IRVOAvoidanceInterface *this, int);
/* 00000018 */     int (__fastcall *GetRVOAvoidanceUID)(IRVOAvoidanceInterface *this);
/* 00000020 */     void (__fastcall *SetRVOAvoidanceWeight)(IRVOAvoidanceInterface *this, float);
/* 00000028 */     float (__fastcall *GetRVOAvoidanceWeight)(IRVOAvoidanceInterface *this);
/* 00000030 */     FVector *(__fastcall *GetRVOAvoidanceOrigin)(IRVOAvoidanceInterface *this, FVector *result);
/* 00000038 */     float (__fastcall *GetRVOAvoidanceRadius)(IRVOAvoidanceInterface *this);
/* 00000040 */     float (__fastcall *GetRVOAvoidanceHeight)(IRVOAvoidanceInterface *this);
/* 00000048 */     float (__fastcall *GetRVOAvoidanceConsiderationRadius)(IRVOAvoidanceInterface *this);
/* 00000050 */     FVector *(__fastcall *GetVelocityForRVOConsideration)(IRVOAvoidanceInterface *this, FVector *result);
/* 00000058 */     int (__fastcall *GetAvoidanceGroupMask)(IRVOAvoidanceInterface *this);
/* 00000060 */     int (__fastcall *GetGroupsToAvoidMask)(IRVOAvoidanceInterface *this);
/* 00000068 */     int (__fastcall *GetGroupsToIgnoreMask)(IRVOAvoidanceInterface *this);
/* 00000070 */ };

/* 00000000 */ struct /*VFT*/ INetworkPredictionInterface_vtbl // sizeof=0x58
/* 00000000 */ {
/* 00000000 */     void (__fastcall *~INetworkPredictionInterface)(INetworkPredictionInterface *this);
/* 00000008 */     UObject *(__fastcall *_getUObject)(INetworkPredictionInterface *this);
/* 00000010 */     void (__fastcall *SendClientAdjustment)(INetworkPredictionInterface *this);
/* 00000018 */     void (__fastcall *ForcePositionUpdate)(INetworkPredictionInterface *this, float);
/* 00000020 */     void (__fastcall *SmoothCorrection)(INetworkPredictionInterface *this, const FVector *, const FQuat *, const FVector *, const FQuat *);
/* 00000028 */     FNetworkPredictionData_Client *(__fastcall *GetPredictionData_Client)(INetworkPredictionInterface *this);
/* 00000030 */     FNetworkPredictionData_Server *(__fastcall *GetPredictionData_Server)(INetworkPredictionInterface *this);
/* 00000038 */     bool (__fastcall *HasPredictionData_Client)(INetworkPredictionInterface *this);
/* 00000040 */     bool (__fastcall *HasPredictionData_Server)(INetworkPredictionInterface *this);
/* 00000048 */     void (__fastcall *ResetPredictionData_Client)(INetworkPredictionInterface *this);
/* 00000050 */     void (__fastcall *ResetPredictionData_Server)(INetworkPredictionInterface *this);
/* 00000058 */ };
