/* 00000000 */ struct /*VFT*/ UDBDAuthentication_vtbl // sizeof=0x1E0
/* 00000000 */ {
/* 00000000 */     void(__fastcall * ~UDBDAuthentication)(struct UDBDAuthentication* this);
/* 00000008 */     void(__fastcall* RegisterDependencies)(struct UDBDAuthentication* this);
/* 00000010 */     void(__fastcall * DeferredRegister)(struct UDBDAuthentication* this, UClass*, const wchar_t*, const wchar_t*);
/* 00000018 */     bool(__fastcall* CanBeClusterRoot)(struct UDBDAuthentication* this);
/* 00000020 */     bool(__fastcall * CanBeInCluster)(struct UDBDAuthentication* this);
/* 00000028 */     void(__fastcall* CreateCluster)(struct UDBDAuthentication* this);
/* 00000030 */     void(__fastcall * AddToCluster)(struct UDBDAuthentication* this, UObjectBaseUtility*);
/* 00000038 */     FString* (__fastcall* GetDetailedInfoInternal)(struct UDBDAuthentication* this, FString* result);
/* 00000040 */     void(__fastcall * PostInitProperties)(struct UDBDAuthentication* this);
/* 00000048 */     bool(__fastcall* PreSaveRoot)(struct UDBDAuthentication* this, const wchar_t*, TArray<FString, FDefaultAllocator>*);
/* 00000050 */     void(__fastcall * PostSaveRoot)(struct UDBDAuthentication* this, bool);
/* 00000058 */     void(__fastcall* PreSave)(struct UDBDAuthentication* this, const ITargetPlatform*);
/* 00000060 */     bool(__fastcall * Modify)(struct UDBDAuthentication* this, bool);
/* 00000068 */     void(__fastcall* PostLoad)(struct UDBDAuthentication* this);
/* 00000070 */     void(__fastcall * PostLoadSubobjects)(struct UDBDAuthentication* this, FObjectInstancingGraph*);
/* 00000078 */     void(__fastcall* BeginDestroy)(struct UDBDAuthentication* this);
/* 00000080 */     bool(__fastcall* IsReadyForFinishDestroy)(struct UDBDAuthentication* this);
/* 00000088 */     void(__fastcall* FinishDestroy)(struct UDBDAuthentication* this);
/* 00000090 */     void(__fastcall* Serialize)(struct UDBDAuthentication* this, FArchive*);
/* 00000098 */     void(__fastcall* ShutdownAfterError)(struct UDBDAuthentication* this);
/* 000000A0 */     void(__fastcall * PostInterpChange)(struct UDBDAuthentication* this, UProperty*);
/* 000000A8 */     void(__fastcall * PostRename)(struct UDBDAuthentication* this, UObject*, const FName);
/* 000000B0 */     void(__fastcall * PostDuplicate)(struct UDBDAuthentication* this, bool);
/* 000000B8 */     bool(__fastcall * NeedsLoadForClient)(struct UDBDAuthentication* this);
/* 000000C0 */     bool(__fastcall * NeedsLoadForServer)(struct UDBDAuthentication* this);
/* 000000C8 */     bool(__fastcall * NeedsLoadForEditorGame)(struct UDBDAuthentication* this);
/* 000000D0 */     bool(__fastcall * IsPostLoadThreadSafe)(struct UDBDAuthentication* this);
/* 000000D8 */     void(__fastcall * ExportCustomProperties)(struct UDBDAuthentication* this, FOutputDevice*, unsigned int);
/* 000000E0 */     void(__fastcall * ImportCustomProperties)(struct UDBDAuthentication* this, const wchar_t*, FFeedbackContext*);
/* 000000E8 */     void(__fastcall * PostEditImport)(struct UDBDAuthentication* this);
/* 000000F0 */     void(__fastcall * PostReloadConfig)(struct UDBDAuthentication* this, UProperty*);
/* 000000F8 */     bool(__fastcall * Rename)(struct UDBDAuthentication* this, const wchar_t*, UObject*, unsigned int);
/* 00000100 */     FString * (__fastcall * GetDesc)(struct UDBDAuthentication* this, FString * result);
/* 00000108 */     UWorld* (__fastcall* GetWorld)(struct UDBDAuthentication* this);
/* 00000110 */     bool(__fastcall * GetNativePropertyValues)(struct UDBDAuthentication* this, TMap<FString, FString, FDefaultSetAllocator, TDefaultMapKeyFuncs<FString, FString, 0> > *, unsigned int);
/* 00000118 */     unsigned __int64(__fastcall* GetResourceSize)(struct UDBDAuthentication* this, EResourceSizeMode::Type);
/* 00000120 */     FName * (__fastcall * GetExporterName)(struct UDBDAuthentication* this, FName * result);
/* 00000128 */     FRestoreForUObjectOverwrite* (__fastcall* GetRestoreForUObjectOverwrite)(struct UDBDAuthentication* this);
/* 00000130 */     bool(__fastcall * AreNativePropertiesIdenticalTo)(struct UDBDAuthentication* this, UObject*);
/* 00000138 */     void(__fastcall* GetAssetRegistryTags)(struct UDBDAuthentication* this, TArray<UObject::FAssetRegistryTag, FDefaultAllocator>*);
/* 00000140 */     bool(__fastcall * IsAsset)(struct UDBDAuthentication* this);
/* 00000148 */     bool(__fastcall* IsLocalizedResource)(struct UDBDAuthentication* this);
/* 00000150 */     bool(__fastcall * IsSafeForRootSet)(struct UDBDAuthentication* this);
/* 00000158 */     void(__fastcall* TagSubobjects)(struct UDBDAuthentication* this, EObjectFlags);
/* 00000160 */     void(__fastcall * GetLifetimeReplicatedProps)(struct UDBDAuthentication* this, TArray<FLifetimeProperty, FDefaultAllocator> *);
/* 00000168 */     bool(__fastcall* IsNameStableForNetworking)(struct UDBDAuthentication* this);
/* 00000170 */     bool(__fastcall * IsFullNameStableForNetworking)(struct UDBDAuthentication* this);
/* 00000178 */     bool(__fastcall* IsSupportedForNetworking)(struct UDBDAuthentication* this);
/* 00000180 */     void(__fastcall* GetSubobjectsWithStableNamesForNetworking)(struct UDBDAuthentication* this, TArray<UObject*, FDefaultAllocator>*);
/* 00000188 */     void(__fastcall* PreNetReceive)(struct UDBDAuthentication* this);
/* 00000190 */     void(__fastcall* PostNetReceive)(struct UDBDAuthentication* this);
/* 00000198 */     void(__fastcall* PostRepNotifies)(struct UDBDAuthentication* this);
/* 000001A0 */     void(__fastcall * PreDestroyFromReplication)(struct UDBDAuthentication* this);
/* 000001A8 */     void(__fastcall * ProcessEvent)(struct UDBDAuthentication* this, UFunction*, void*);
/* 000001B0 */     int(__fastcall * GetFunctionCallspace)(struct UDBDAuthentication* this, UFunction*, void*, FFrame*);
/* 000001B8 */     bool(__fastcall * CallRemoteFunction)(struct UDBDAuthentication* this, UFunction*, void*, FOutParmRec*, FFrame*);
/* 000001C0 */     bool(__fastcall * ProcessConsoleExec)(struct UDBDAuthentication* this, const wchar_t*, FOutputDevice*, UObject*);
/* 000001C8 */     UClass * (__fastcall * RegenerateClass)(struct UDBDAuthentication* this, UClass*, UObject*, TArray<UObject*, FDefaultAllocator> *);
/* 000001D0 */     void(__fastcall * MarkAsEditorOnlySubobject)(struct UDBDAuthentication* this);
/* 000001D8 */     bool(__fastcall * CheckDefaultSubobjectsInternal)(struct UDBDAuthentication* this);
/* 000001E0 */ };