class __base(UGameInstance, 0) UDBDGameInstance
{
/* 0x0000 */    struct UDBDGameInstance::VTable* vtable;
/* 0x0008 */    __inherited enum EObjectFlags UObjectBase::ObjectFlags;
/* 0x000c */    __inherited int32_t UObjectBase::InternalIndex;
/* 0x0010 */    __inherited class UClass* UObjectBase::ClassPrivate;
/* 0x0018 */    __inherited class FName UObjectBase::NamePrivate;
/* 0x0020 */    __inherited class UObject* UObjectBase::OuterPrivate;
/* 0x0028 */    __inherited struct UChildConnection::UNetConnection::UPlayer::FExec::VTable* FExec::vtable;
/* 0x0030 */    __inherited struct FWorldContext* UGameInstance::WorldContext;
/* 0x0038 */    __inherited class TArray<ULocalPlayer *,FDefaultAllocator> UGameInstance::LocalPlayers;
/* 0x0048 */    __inherited class UOnlineSession* UGameInstance::OnlineSession;
/* 0x0050 */    __inherited class TMulticastDelegate<void,FString const &,enum ETravelType,bool> UGameInstance::NotifyPreClientTravelDelegates;
/* 0x00c0 */    __inherited class FDelegateHandle UGameInstance::OnPlayTogetherEventReceivedDelegateHandle;
/* 0x00c8 */    __inherited class FString UGameInstance::PIEMapName;
/* 0x00d8 */    __inherited class FTimerManager* UGameInstance::TimerManager;
/* 0x00e0 */    __inherited struct FLatentActionManager* UGameInstance::LatentActionManager;
/* 0x00e8 */    class TSubclassOf<UDBDDesignTunables> DesignTunableClass;
/* 0x00f0 */    class UDBDDesignTunables* DesignTunables;
/* 0x00f8 */    class TSubclassOf<URegionFinder> RegionClass;
/* 0x0100 */    class URegionFinder* RegionFinder;
/* 0x0108 */    class UGameEventTracker* GameEventTracker;
/* 0x0110 */    class UDBDKeyDisplayInfo* KeyDisplayInfo;
/* 0x0118 */    uint8_t LeaveGameRequested;
/* 0x011c */    float LockOutTimer;
/* 0x0120 */    class UPlayerProfileDAL* PlayerProfileDAL;
/* 0x0128 */    class TMap<enum EOfferingEffectType,TMap<int,FOfferingEffect,FDefaultSetAllocator,TDefaultMapKeyFuncs<int,FOfferingEffect,0> >,FDefaultSetAllocator,TDefaultMapKeyFuncs<enum EOfferingEffectType,TMap<int,FOfferingEffect,FDefaultSetAllocator,TDefaultMapKeyFuncs<int,FOfferingEffect,0> >,0> > _resultEffects01;
/* 0x0178 */    struct TWeakObjectPtr<AProceduralLevelBuilder,FWeakObjectPtr> Builder;
/* 0x0180 */    int32_t GenerationSeed;
/* 0x0184 */    __padding char _184[4];
/* 0x0188 */    class FString PaperTileAssetName;
/* 0x0198 */    struct TWeakObjectPtr<AChatManager,FWeakObjectPtr> ChatManager;
/* 0x01a0 */    struct TWeakObjectPtr<ASeasonManager,FWeakObjectPtr> SeasonManager;
/* 0x01a8 */    struct TWeakObjectPtr<ATutorialsManager,FWeakObjectPtr> TutorialsManager;
/* 0x01b0 */    struct TWeakObjectPtr<ALevelParadise,FWeakObjectPtr> Paradise;
/* 0x01b8 */    struct TWeakObjectPtr<AOfferingSequenceManager,FWeakObjectPtr> OfferingSequence;
/* 0x01c0 */    class TArray<FParadiseData,FDefaultAllocator> ParadiseData;
/* 0x01d0 */    uint8_t PlayerProfileLoadFailed;
/* 0x01d1 */    uint8_t SeasonEnded;
/* 0x01d2 */    __padding char _1d2[6];
/* 0x01d8 */    class FString PendingReportSteamId;
/* 0x01e8 */    class FString PendingReportPlayerName;
/* 0x01f8 */    enum EPlayerRole PendingReportPlayerRole;
/* 0x01f9 */    __padding char _1f9[7];
/* 0x0200 */    class TArray<FString,FDefaultAllocator> ReportedPlayers;
/* 0x0210 */    int32_t MatchRateValue;
/* 0x0214 */    __padding char _214[4];
/* 0x0218 */    class TArray<FBonusPointsEventData,FDefaultAllocator> BonusPointsEvents;
/* 0x0228 */    uint8_t ShouldRequestBonusPointsEvents;
/* 0x0229 */    enum EDisconnectErrors DisconnectError;
/* 0x022c */    uint32_t LastAuthOrEACErrorCode;
/* 0x0230 */    class FString AuthOrEACErrorAdditionalInfo;
/* 0x0240 */    uint8_t HasServerLeftMatch;
/* 0x0241 */    uint8_t HasWrittenGameEndStats;
/* 0x0242 */    __padding char _242[6];
/* 0x0248 */    struct FStreamableManager AssetLoader;
/* 0x02e8 */    class TArray<int,FDefaultAllocator> PlayerIds;
/* 0x02f8 */    class FPlayerDisconnectDelegate OnPlayerDisconnect;
/* 0x0308 */    __padding char _308[8];
/* 0x0310 */    class TMulticastDelegate<void> OnFenceInitialized;
/* 0x0380 */    class TSharedPtr<FDBDAnalogCursor,0> AnalogCursor;
/* 0x0390 */    struct TWeakObjectPtr<ANetworkFenceActor,FWeakObjectPtr> _localFence;
/* 0x0398 */    struct FTimerHandle _onNetworkConnectionTimedOut;
/* 0x03a0 */    class FDelegateHandle _onConnectionChangedHandle;
/* 0x03a8 */    class FDelegateHandle _onAdditionalContentInstalled;
/* 0x03b0 */    class UGameFlowContextSystem* _contextSystem;
/* 0x03b8 */    class UDBDPersistentData* _persistentData;
/* 0x03c0 */    class UPlayerDataStorageFacade* _playerDataFacade;
/* 0x03c8 */    class SoundEventSystem* _soundEventSystem;
/* 0x03d0 */    class USequencer* _sacrificeSequencer;
/* 0x03d8 */    class ULightingHelper* _ligthingHelper;
/* 0x03e0 */    class UOfferingHandler* _offeringHandler;
/* 0x03e8 */    uint8_t _simulationFlow;
/* 0x03e9 */    __padding char _3e9[7];
/* 0x03f0 */    class TArray<UActorKnowledgeCollection *,FDefaultAllocator> _actorKnowledgeCollections;
/* 0x0400 */    class UMapActorDB* _mapActorDB;
/* 0x0408 */    class TArray<UAkAudioBank *,FDefaultAllocator> _audioBanks;
/* 0x0418 */    class TArray<UInteractionProficiency *,FDefaultAllocator> _interactionProficiencies;
/* 0x0428 */    class UDBDHud* _theHud;
/* 0x0430 */    class TArray<ULoadAsyncBankData *,FDefaultAllocator> _asyncAudioBanksPendingLoadData;
/* 0x0440 */    class TBaseDelegate<bool> _onCloseRequested;
/* 0x0480 */    class TMulticastDelegate<void,enum EOnlineServerConnectionStatus::Type,enum EOnlineServerConnectionStatus::Type> _onConnectionChanged;
/* 0x04f0 */    class UBloodwebManager* BloodwebManager;
/* 0x04f8 */    class UDBDAuthentication* _auth;
/* 0x0500 */    class UDBDEasyAntiCheat* _eac;
/* 0x0508 */    class TMap<FString,unsigned char,FDefaultSetAllocator,TDefaultMapKeyFuncs<FString,unsigned char,0> > _cachePlayerStatus;
/* 0x0558 */    uint8_t _initializedFromCloud;
/* 0x0559 */    uint8_t _saveCorruptionPopupEnabled;
/* 0x055a */    uint8_t _saveCorruptionDetected;
/* 0x055b */    __padding char _55b[5];
/* 0x0560 */    struct FSaveValidationData _localSaveValidationData;
/* 0x05c0 */    class FWindowsCriticalSection LoadAudioCriticalSection;
/* 0x05e8 */    class TArray<ADBDPlayer *,FDefaultAllocator> _players;
/* 0x05f8 */    class TArray<TWeakObjectPtr<UObject,FWeakObjectPtr>,FDefaultAllocator> _execObjects;
/* 0x0608 */    uint8_t _networkFailureDetected;
/* 0x0609 */    uint8_t _networkConnectionMonitoringOnly;
/* 0x060a */    uint8_t _achievementStatsUploadEnabled;
/* 0x060b */    uint8_t _isDisconnected;
/* 0x060c */    uint8_t _isMirrorsSessionKilled;
/* 0x060d */    uint8_t _isGamepadReconnected;
/* 0x060e */    uint8_t _isProfileOffline;
/* 0x060f */    uint8_t _isAppSuspended;
/* 0x0610 */    uint8_t _isAppResumed;
/* 0x0611 */    uint8_t _isInvitationRejected;
/* 0x0612 */    uint8_t _isAdditionalContentInstalled;
/* 0x0613 */    enum ELegalTermsStatus _legalTermsStatus;
/* 0x0614 */    uint8_t _networkErrorSpecialUIFlow;
/* 0x0618 */    enum EOnlineServerConnectionStatus::Type _ConnectionStatus;
/* 0x061c */    __padding char _61c[4];
/* 0x0620 */    class TMap<int,TMulticastDelegate<void>,FDefaultSetAllocator,TDefaultMapKeyFuncs<int,TMulticastDelegate<void>,0> > _systemPromptCallbackMap;
/* 0x0670 */    struct FAnalyticsManager _analyticsManager;
/* 0x09b0 */    uint8_t _travelingToSplash;
/* 0x09b1 */    uint8_t _showingNetworkError;
/* 0x09b2 */    uint8_t _allowPresencePluginNotifications;
/* 0x09b3 */    __padding char _9b3[0xd];
/* 0x09c0 */
};