class __base(AGameState, 0) ADBDGameState
{
    struct ADBDGameState::VTable* vtable;
    __inherited enum EObjectFlags UObjectBase::ObjectFlags;
    __inherited int32_t UObjectBase::InternalIndex;
    __inherited class UClass* UObjectBase::ClassPrivate;
    __inherited class FName UObjectBase::NamePrivate;
    __inherited class UObject* UObjectBase::OuterPrivate;
    __inherited struct FActorTickFunction AActor::PrimaryActorTick;
    __inherited float AActor::CustomTimeDilation;
    __inherited union
    {
        uint8_t bHidden;
        uint8_t bNetTemporary;
        uint8_t bNetStartup;
        uint8_t bOnlyRelevantToOwner;
        uint8_t bAlwaysRelevant;
        uint8_t bReplicateMovement;
        uint8_t bTearOff;
        uint8_t bExchangedRoles;
    } __bitfield7c;
    __inherited union
    {
        uint8_t bPendingNetUpdate;
        uint8_t bNetLoadOnClient;
        uint8_t bNetUseOwnerRelevancy;
        uint8_t bBlockInput;
        uint8_t bRunningUserConstructionScript;
        uint8_t bAllowTickBeforeBeginPlay;
        uint8_t bHasFinishedSpawning;
        uint8_t bTickFunctionsRegistered;
    } __bitfield7d;
    __inherited union
    {
        uint8_t bActorEnableCollision;
        uint8_t bNetCheckedInitialPhysicsState;
        uint8_t bReplicates;
    } __bitfield7e;
    __padding char _7f[1];
    __inherited class FName AActor::NetDriverName;
    __inherited class TEnumAsByte<enum ENetRole> AActor::RemoteRole;
    __inherited class AActor* AActor::Owner;
    __inherited struct FRepMovement AActor::ReplicatedMovement;
    __padding char _cc[4];
    __inherited struct FRepAttachment AActor::AttachmentReplication;
    __inherited class TEnumAsByte<enum ENetRole> AActor::Role;
    __inherited class TEnumAsByte<enum ENetDormancy> AActor::NetDormancy;
    __inherited class TEnumAsByte<enum EAutoReceiveInput::Type> AActor::AutoReceiveInput;
    __inherited int32_t AActor::InputPriority;
    __inherited class UInputComponent* AActor::InputComponent;
    __inherited class TEnumAsByte<enum EInputConsumeOptions> AActor::InputConsumeOption_DEPRECATED;
    __inherited float AActor::NetCullDistanceSquared;
    __inherited int32_t AActor::NetTag;
    __inherited float AActor::NetUpdateTime;
    __inherited float AActor::NetUpdateFrequency;
    __inherited float AActor::MinNetUpdateFrequency;
    __inherited float AActor::NetPriority;
    __inherited float AActor::LastNetUpdateTime;
    __inherited union
    {
        uint8_t bAutoDestroyWhenFinished;
        uint8_t bCanBeDamaged;
        uint8_t bActorIsBeingDestroyed;
        uint8_t bCollideWhenPlacing;
        uint8_t bFindCameraComponentWhenViewTarget;
        uint8_t bRelevantForNetworkReplays;
        uint8_t bGenerateOverlapEventsDuringLevelStreaming;
    } __bitfield140;
    __inherited enum ESpawnActorCollisionHandlingMethod AActor::SpawnCollisionHandlingMethod;
    __inherited float AActor::CreationTime;
    __inherited class APawn* AActor::Instigator;
    __inherited class TArray<AActor *,FDefaultAllocator> AActor::Children;
    __inherited class USceneComponent* AActor::RootComponent;
    __inherited class TArray<AMatineeActor *,FDefaultAllocator> AActor::ControllingMatineeActors;
    __inherited float AActor::InitialLifeSpan;
    __padding char _17c[4];
    __inherited struct FTimerHandle AActor::TimerHandle_LifeSpanExpired;
    __inherited class TArray<FName,FDefaultAllocator> AActor::Layers;
    __inherited struct TWeakObjectPtr<AActor,FWeakObjectPtr> AActor::ParentComponentActor_DEPRECATED;
    __inherited struct TWeakObjectPtr<UChildActorComponent,FWeakObjectPtr> AActor::ParentComponent;
    __inherited union
    {
        uint8_t bAllowReceiveTickEventOnDedicatedServer;
        uint8_t bActorInitialized;
        enum AActor::EActorBeginPlayState ActorHasBegunPlay;
        uint8_t bActorSeamlessTraveled;
        uint8_t bIgnoresOriginShifting;
        uint8_t bEnableAutoLODGeneration;
    } __bitfield1a8;
    __padding char _1a9[7];
    __inherited class TArray<FName,FDefaultAllocator> AActor::Tags;
    __inherited uint64_t AActor::HiddenEditorViews;
    __inherited class FTakeAnyDamageSignature AActor::OnTakeAnyDamage;
    __inherited class FTakePointDamageSignature AActor::OnTakePointDamage;
    __inherited class FActorBeginOverlapSignature AActor::OnActorBeginOverlap;
    __inherited class FActorEndOverlapSignature AActor::OnActorEndOverlap;
    __inherited class FActorBeginCursorOverSignature AActor::OnBeginCursorOver;
    __inherited class FActorEndCursorOverSignature AActor::OnEndCursorOver;
    __inherited class FActorOnClickedSignature AActor::OnClicked;
    __inherited class FActorOnReleasedSignature AActor::OnReleased;
    __inherited class FActorOnInputTouchBeginSignature AActor::OnInputTouchBegin;
    __inherited class FActorOnInputTouchEndSignature AActor::OnInputTouchEnd;
    __inherited class FActorBeginTouchOverSignature AActor::OnInputTouchEnter;
    __inherited class FActorEndTouchOverSignature AActor::OnInputTouchLeave;
    __inherited class FActorHitSignature AActor::OnActorHit;
    __inherited class FActorDestroyedSignature AActor::OnDestroyed;
    __inherited class FActorEndPlaySignature AActor::OnEndPlay;
    __inherited class TSet<UActorComponent *,DefaultKeyFuncs<UActorComponent *,0>,FDefaultSetAllocator> AActor::OwnedComponents;
    __inherited class TSet<UActorComponent *,DefaultKeyFuncs<UActorComponent *,0>,FDefaultSetAllocator> AActor::ReplicatedComponents;
    __inherited class TArray<UActorComponent *,FDefaultAllocator> AActor::BlueprintCreatedComponents;
    __inherited class TArray<UActorComponent *,FDefaultAllocator> AActor::InstanceComponents;
    __inherited class FRenderCommandFence AActor::DetachFence;
    __inherited class TSubclassOf<AGameMode> AGameState::GameModeClass;
    __inherited class AGameMode* AGameState::AuthorityGameMode;
    __inherited class TSubclassOf<ASpectatorPawn> AGameState::SpectatorClass;
    __inherited class FName AGameState::MatchState;
    __inherited class FName AGameState::PreviousMatchState;
    __inherited int32_t AGameState::ElapsedTime;
    __padding char _3ac[4];
    __inherited class TArray<APlayerState *,FDefaultAllocator> AGameState::PlayerArray;
    __inherited float AGameState::ReplicatedWorldTimeSeconds;
    __inherited float AGameState::ServerWorldTimeSecondsDelta;
    __inherited float AGameState::ServerWorldTimeSecondsUpdateFrequency;
    __padding char _3cc[4];
    __inherited struct FTimerHandle AGameState::TimerHandle_DefaultTimer;
    __inherited struct FTimerHandle AGameState::TimerHandle_UpdateServerTimeSeconds;
    class FEscapeDoorActivatedEvent OnEscapeDoorActivated;
    class TMulticastDelegate<void> OnEscapeDoorActivatedHud;
    class TMulticastDelegate<void,bool> OnHatchOpened;
    class TMulticastDelegate<void,ADBDGameState *> _gameDataUpdatedDelegate;
    class FLevelReadyToPlayEvent OnLevelReadyToPlay;
    class FSurvivorsLeftChangedEvent OnSurvivorsLeftChanged;
    class FAllPlayerLoadedEvent AuthorityOnAllPlayerLoaded;
    class TMulticastDelegate<void,int> OnActivatedGeneratorCountChanged;
    class FActivatedGeneratorCountChangedDynamicEvent OnActivatedGeneratorCountChangedDynamic;
    class ASlasherPlayer* Slasher;
    int32_t GeneratorNeeded;
    int32_t CamperDeadCount;
    int32_t CamperInMeatLockerCount;
    int32_t CamperEscaped;
    int32_t WaitingForEscape;
    int32_t CamperCount;
    uint8_t LeaveSpectateRequested;
    uint8_t IsGameEnded;
    uint8_t PlayersReadyToStart;
    int32_t SecondsLeftInLobby;
    union
    {
        uint32_t HasServerLeftTheGame;
    } __bitfield618;
    uint8_t _lightingGenerated;
    uint8_t _introCompleted;
    uint8_t _displayMapName;
    float _killerIntroCompleted;
    uint8_t _gameLevelLoaded;
    __padding char _625[3];
    struct FBuiltLevelData _builtLevelData;
    struct FOfferingData _levelOfferings;
    class AClipManager* _clipManager;
    struct FServerJoiningData _serverJoiningData;
    class FDelegateHandle _onJoinSessionLogDelegateHandle;
    class FDelegateHandle _onLobbySessionFoundDelegateHandle;
    class FDelegateHandle _onJoinSessionsCompleteDelegateHandle;
    class FDelegateHandle _onOnJoinSessionErrorDelegateHandle;
    class FDelegateHandle _onFindFriendSessionCompleteDelegateHandle;
    struct FGuid _sessionId;
    int32_t _activatedGeneratorCount;
    uint8_t _escapeDoorActivated;
    uint8_t _isHatchOpen;
    uint8_t _levelReadyToPlay;
    uint8_t _playerDistributionReady;
    uint8_t _usingWeakenedMechanic;
    int32_t _survivorLeft;
    uint8_t _gameHasBeenSetup;
    int32_t _killerServerSearchAttempt;
    uint8_t _travelToKillerServer;
    uint8_t _killerServerSearchFailed;
    uint8_t _killerServerSearchStarted;
    enum ESurvivorGroupTransitionSteps _currentSurvivorGroupTransitionStep;
    __padding char _704[4];
    class TArray<unsigned int,FDefaultAllocator> JoinedKillerIds;
    int32_t _camperEscapedThroughHatch;
    class ACamperPlayer* _obsessionTarget;
    uint8_t _cachedObsessionEscaped;
    int32_t _totalObsessionWeight;
    class TArray<AActor *,FDefaultAllocator> _heartbeatEmitters;
    class TArray<AInteractable *,FDefaultAllocator> _traps;
    uint8_t _gamePresetDataInit;
    __padding char _751[7];
    struct FGamePresetData _gamePresetData;
};
