/* 00000000 */struct /*VFT*/ UDBDGameInstance_vtbl // sizeof=0x270
/* 00000000 */{
/* 00000000 */    void(__fastcall * ~UObject)(struct UObject* this);
/* 00000008 */    void(__fastcall* RegisterDependencies)(struct UObject* this);
/* 00000010 */    void(__fastcall * DeferredRegister)(struct UObject* this, UClass*, const wchar_t*, const wchar_t*);
/* 00000018 */    bool(__fastcall* CanBeClusterRoot)(struct UObject* this);
/* 00000020 */    bool(__fastcall * CanBeInCluster)(struct UObject* this);
/* 00000028 */    void(__fastcall* CreateCluster)(struct UObject* this);
/* 00000030 */    void(__fastcall * AddToCluster)(struct UObject* this, UObjectBaseUtility*);
/* 00000038 */    FString* (__fastcall* GetDetailedInfoInternal)(UObject* this, FString* result);
/* 00000040 */    void(__fastcall * PostInitProperties)(UObject * this);
/* 00000048 */    bool(__fastcall* PreSaveRoot)(UObject* this, const wchar_t*, TArray<FString, FDefaultAllocator>*);
/* 00000050 */    void(__fastcall * PostSaveRoot)(UObject * this, bool);
/* 00000058 */    void(__fastcall* PreSave)(UObject* this, const ITargetPlatform*);
/* 00000060 */    bool(__fastcall * Modify)(UObject * this, bool);
/* 00000068 */    void(__fastcall* PostLoad)(UObject* this);
/* 00000070 */    void(__fastcall * PostLoadSubobjects)(UObject * this, FObjectInstancingGraph*);
/* 00000078 */    void(__fastcall* BeginDestroy)(UObject* this);
/* 00000080 */    bool(__fastcall* IsReadyForFinishDestroy)(UObject* this);
/* 00000088 */    void(__fastcall* FinishDestroy)(UObject* this);
/* 00000090 */    void(__fastcall* Serialize)(UObject* this, FArchive*);
/* 00000098 */    void(__fastcall* ShutdownAfterError)(UObject* this);
/* 000000A0 */    void(__fastcall * PostInterpChange)(UObject * this, UProperty*);
/* 000000A8 */    void(__fastcall * PostRename)(UObject * this, UObject*, const FName);
/* 000000B0 */    void(__fastcall * PostDuplicate)(UObject * this, bool);
/* 000000B8 */    bool(__fastcall * NeedsLoadForClient)(UObject * this);
/* 000000C0 */    bool(__fastcall * NeedsLoadForServer)(UObject * this);
/* 000000C8 */    bool(__fastcall * NeedsLoadForEditorGame)(UObject * this);
/* 000000D0 */    bool(__fastcall * IsPostLoadThreadSafe)(UObject * this);
/* 000000D8 */    void(__fastcall * ExportCustomProperties)(UObject * this, FOutputDevice*, unsigned int);
/* 000000E0 */    void(__fastcall * ImportCustomProperties)(UObject * this, const wchar_t*, FFeedbackContext*);
/* 000000E8 */    void(__fastcall * PostEditImport)(UObject * this);
/* 000000F0 */    void(__fastcall * PostReloadConfig)(UObject * this, UProperty*);
/* 000000F8 */    bool(__fastcall * Rename)(UObject * this, const wchar_t*, UObject*, unsigned int);
/* 00000100 */    FString * (__fastcall * GetDesc)(UObject * this, FString * result);
/* 00000108 */    UWorld* (__fastcall* GetWorld)(UObject* this);
/* 00000110 */    bool(__fastcall * GetNativePropertyValues)(UObject * this, TMap<FString, FString, FDefaultSetAllocator, TDefaultMapKeyFuncs<FString, FString, 0> > *, unsigned int);
/* 00000118 */    unsigned __int64(__fastcall* GetResourceSize)(UObject* this, EResourceSizeMode::Type);
/* 00000120 */    FName * (__fastcall * GetExporterName)(UObject * this, FName * result);
/* 00000128 */    FRestoreForUObjectOverwrite* (__fastcall* GetRestoreForUObjectOverwrite)(UObject* this);
/* 00000130 */    bool(__fastcall * AreNativePropertiesIdenticalTo)(UObject * this, UObject*);
/* 00000138 */    void(__fastcall* GetAssetRegistryTags)(UObject* this, TArray<UObject::FAssetRegistryTag, FDefaultAllocator>*);
/* 00000140 */    bool(__fastcall * IsAsset)(UObject * this);
/* 00000148 */    bool(__fastcall* IsLocalizedResource)(UObject* this);
/* 00000150 */    bool(__fastcall * IsSafeForRootSet)(UObject * this);
/* 00000158 */    void(__fastcall* TagSubobjects)(UObject* this, EObjectFlags);
/* 00000160 */    void(__fastcall * GetLifetimeReplicatedProps)(UObject * this, TArray<FLifetimeProperty, FDefaultAllocator> *);
/* 00000168 */    bool(__fastcall* IsNameStableForNetworking)(UObject* this);
/* 00000170 */    bool(__fastcall * IsFullNameStableForNetworking)(UObject * this);
/* 00000178 */    bool(__fastcall* IsSupportedForNetworking)(UObject* this);
/* 00000180 */    void(__fastcall* GetSubobjectsWithStableNamesForNetworking)(UObject* this, TArray<UObject*, FDefaultAllocator>*);
/* 00000188 */    void(__fastcall* PreNetReceive)(UObject* this);
/* 00000190 */    void(__fastcall* PostNetReceive)(UObject* this);
/* 00000198 */    void(__fastcall* PostRepNotifies)(UObject* this);
/* 000001A0 */    void(__fastcall * PreDestroyFromReplication)(UObject * this);
/* 000001A8 */    void(__fastcall * ProcessEvent)(UObject * this, UFunction*, void*);
/* 000001B0 */    int(__fastcall * GetFunctionCallspace)(UObject * this, UFunction*, void*, FFrame*);
/* 000001B8 */    bool(__fastcall * CallRemoteFunction)(UObject * this, UFunction*, void*, FOutParmRec*, FFrame*);
/* 000001C0 */    bool(__fastcall * ProcessConsoleExec)(UObject * this, const wchar_t*, FOutputDevice*, UObject*);
/* 000001C8 */    UClass * (__fastcall * RegenerateClass)(UObject * this, UClass*, UObject*, TArray<UObject*, FDefaultAllocator> *);
/* 000001D0 */    void(__fastcall * MarkAsEditorOnlySubobject)(UObject * this);
/* 000001D8 */    bool(__fastcall * CheckDefaultSubobjectsInternal)(UObject * this);
/* 000001E0 */    bool(__fastcall * HandleOpenCommand)(UGameInstance * this, const wchar_t*, FOutputDevice*, UWorld*);
/* 000001E8 */    void(__fastcall * Init)(UGameInstance * this);
/* 000001F0 */    void(__fastcall * Shutdown)(UGameInstance * this);
/* 000001F8 */    void(__fastcall * StartGameInstance)(UGameInstance * this);
/* 00000200 */    bool(__fastcall * JoinSession)(UGameInstance * this, ULocalPlayer*, const FOnlineSessionSearchResult*);
/* 00000208 */    bool(__fastcall* JoinSession)(UGameInstance* this, ULocalPlayer*, int);
/* 00000210 */    void(__fastcall * DebugCreatePlayer)(UGameInstance * this, int);
/* 00000218 */    void(__fastcall* DebugRemovePlayer)(UGameInstance* this, int);
/* 00000220 */    ULocalPlayer * (__fastcall * CreateInitialPlayer)(UGameInstance * this, FString*);
/* 00000228 */    void(__fastcall* HandleDemoPlaybackFailure)(UGameInstance* this, EDemoPlayFailure::Type, const FString*);
/* 00000230 */    void(__fastcall * StartRecordingReplay)(UGameInstance * this, const FString*, const FString*, const TArray<FString, FDefaultAllocator> *);
/* 00000238 */    void(__fastcall* StopRecordingReplay)(UGameInstance* this);
/* 00000240 */    void(__fastcall * PlayReplay)(UGameInstance * this, const FString*, UWorld*, const TArray<FString, FDefaultAllocator> *);
/* 00000248 */    bool(__fastcall* AreExtraConditionsMet)(UGameInstance* this);
/* 00000250 */    void(__fastcall * AddUserToReplay)(UGameInstance * this, const FString*);
/* 00000258 */    void(__fastcall* HandleGameNetControlMessage)(UGameInstance* this, UNetConnection*, unsigned __int8, const FString*);
/* 00000260 */    bool(__fastcall * DelayPendingNetGameTravel)(UGameInstance * this);
/* 00000268 */    TSubclassOf<UOnlineSession>* (__fastcall* GetOnlineSessionClass)(UGameInstance* this, TSubclassOf<UOnlineSession>* result);
/* 00000270 */};