void __fastcall UDBDGameInstance::UDBDGameInstance(UDBDGameInstance* this, const FObjectInitializer* ObjectInitializer)
{
	UGameInstance::UGameInstance(this, ObjectInitializer);
	this->UGameInstance::UObject::UObjectBaseUtility::UObjectBase::__vftable = (UDBDGameInstance_vtbl*)&UDBDGameInstance::`vftable'{for `UObject'};
	this->UGameInstance::FExec::__vftable = (FExec_vtbl*)&UDBDGameInstance::`vftable'{for `FExec'};
	*((_QWORD*)&this->LatentActionManager + 1) = 0;
	this->RegionClass.Class = 0;
	this->LeaveGameRequested = 0;
	this->LockOutTimer = 0.0;
	this->_resultEffects01.Pairs.Elements.Data.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->_resultEffects01.Pairs.Elements.Data.ArrayNum = 0;
	this->_resultEffects01.Pairs.Elements.AllocationFlags.AllocatorInstance.SecondaryData.Data = 0;
	*(_QWORD*)&this->_resultEffects01.Pairs.Elements.AllocationFlags.NumBits = 0;
	this->_resultEffects01.Pairs.Elements.FirstFreeIndex = -1;
	this->_resultEffects01.Pairs.Elements.NumFreeIndices = 0;
	this->_resultEffects01.Pairs.Hash.SecondaryData.Data = 0;
	this->_resultEffects01.Pairs.HashSize = 0;
	this->Builder.ObjectIndex = -1;
	this->Builder.ObjectSerialNumber = 0;
	this->PaperTileAssetName.Data.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->PaperTileAssetName.Data.ArrayNum = 0;
	this->ChatManager.ObjectIndex = -1;
	this->ChatManager.ObjectSerialNumber = 0;
	this->SeasonManager.ObjectIndex = -1;
	this->SeasonManager.ObjectSerialNumber = 0;
	this->TutorialsManager.ObjectIndex = -1;
	this->TutorialsManager.ObjectSerialNumber = 0;
	this->Paradise.ObjectIndex = -1;
	this->Paradise.ObjectSerialNumber = 0;
	this->OfferingSequence.ObjectIndex = -1;
	this->OfferingSequence.ObjectSerialNumber = 0;
	this->ParadiseData.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->ParadiseData.ArrayNum = 0;
	*(_WORD*)&this->PlayerProfileLoadFailed = 0;
	this->PendingReportSteamId.Data.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->PendingReportSteamId.Data.ArrayNum = 0;
	this->PendingReportPlayerName.Data.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->PendingReportPlayerName.Data.ArrayNum = 0;
	this->ReportedPlayers.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->ReportedPlayers.ArrayNum = 0;
	this->MatchRateValue = 0;
	this->BonusPointsEvents.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->BonusPointsEvents.ArrayNum = 0;
	*(_WORD*)&this->ShouldRequestBonusPointsEvents = 1;
	this->AuthOrEACErrorAdditionalInfo.Data.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->AuthOrEACErrorAdditionalInfo.Data.ArrayNum = 0;
	*(_WORD*)&this->HasServerLeftMatch = 0;
	FStreamableManager::FStreamableManager(&this->AssetLoader);
	this->PlayerIds.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->PlayerIds.ArrayNum = 0;
	this->OnPlayerDisconnect.InvocationList.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->OnPlayerDisconnect.InvocationList.ArrayNum = 0;
	this->OnFenceInitialized.InvocationList.AllocatorInstance.SecondaryData.Data = 0;
	*(_QWORD*)&this->OnFenceInitialized.InvocationList.ArrayNum = 0;
	*(_QWORD*)&this->OnFenceInitialized.CompactionThreshold = 2;
	this->AnalogCursor.Object = 0;
	this->AnalogCursor.SharedReferenceCount.ReferenceController = 0;
	this->_localFence.ObjectIndex = -1;
	this->_localFence.ObjectSerialNumber = 0;
	this->_onNetworkConnectionTimedOut.Handle = 0;
	this->_onConnectionChangedHandle.ID = 0;
	this->_onAdditionalContentInstalled.ID = 0;
	this->_contextSystem = 0;
	this->_persistentData = 0;
	this->_soundEventSystem = 0;
	this->_simulationFlow = 0;
	this->_actorKnowledgeCollections.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->_actorKnowledgeCollections.ArrayNum = 0;
	this->_audioBanks.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->_audioBanks.ArrayNum = 0;
	this->_interactionProficiencies.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->_interactionProficiencies.ArrayNum = 0;
	this->_asyncAudioBanksPendingLoadData.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->_asyncAudioBanksPendingLoadData.ArrayNum = 0;
	this->_onCloseRequested.DelegateAllocator.SecondaryData.Data = 0;
	this->_onCloseRequested.DelegateSize = 0;
	this->_onConnectionChanged.InvocationList.AllocatorInstance.SecondaryData.Data = 0;
	*(_QWORD*)&this->_onConnectionChanged.InvocationList.ArrayNum = 0;
	*(_QWORD*)&this->_onConnectionChanged.CompactionThreshold = 2;
	this->_cachePlayerStatus.Pairs.Elements.Data.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->_cachePlayerStatus.Pairs.Elements.Data.ArrayNum = 0;
	this->_cachePlayerStatus.Pairs.Elements.AllocationFlags.AllocatorInstance.SecondaryData.Data = 0;
	*(_QWORD*)&this->_cachePlayerStatus.Pairs.Elements.AllocationFlags.NumBits = 0;
	this->_cachePlayerStatus.Pairs.Elements.FirstFreeIndex = -1;
	this->_cachePlayerStatus.Pairs.Elements.NumFreeIndices = 0;
	this->_cachePlayerStatus.Pairs.Hash.SecondaryData.Data = 0;
	this->_cachePlayerStatus.Pairs.HashSize = 0;
	*(_WORD*)&this->_initializedFromCloud = 256;
	this->_saveCorruptionDetected = 0;
	this->_localSaveValidationData.PlayerUID.Data.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->_localSaveValidationData.PlayerUID.Data.ArrayNum = 0;
	this->_localSaveValidationData.CharacterData.Pairs.Elements.Data.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->_localSaveValidationData.CharacterData.Pairs.Elements.Data.ArrayNum = 0;
	this->_localSaveValidationData.CharacterData.Pairs.Elements.AllocationFlags.AllocatorInstance.SecondaryData.Data = 0;
	*(_QWORD*)&this->_localSaveValidationData.CharacterData.Pairs.Elements.AllocationFlags.NumBits = 0;
	this->_localSaveValidationData.CharacterData.Pairs.Elements.FirstFreeIndex = -1;
	this->_localSaveValidationData.CharacterData.Pairs.Elements.NumFreeIndices = 0;
	this->_localSaveValidationData.CharacterData.Pairs.Hash.SecondaryData.Data = 0;
	this->_localSaveValidationData.CharacterData.Pairs.HashSize = 0;
	InitializeCriticalSection(&this->LoadAudioCriticalSection.CriticalSection);
	SetCriticalSectionSpinCount(&this->LoadAudioCriticalSection.CriticalSection, 0xFA0u);
	this->_players.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->_players.ArrayNum = 0;
	this->_execObjects.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->_execObjects.ArrayNum = 0;
	*(_QWORD*)&this->_networkFailureDetected = 0x10000;
	*(_DWORD*)&this->_isAppResumed = 0;
	this->_networkErrorSpecialUIFlow = 0;
	this->_ConnectionStatus = Lowest;
	this->_systemPromptCallbackMap.Pairs.Elements.Data.AllocatorInstance.Data = 0;
	*(_QWORD*)&this->_systemPromptCallbackMap.Pairs.Elements.Data.ArrayNum = 0;
	this->_systemPromptCallbackMap.Pairs.Elements.AllocationFlags.AllocatorInstance.SecondaryData.Data = 0;
	*(_QWORD*)&this->_systemPromptCallbackMap.Pairs.Elements.AllocationFlags.NumBits = 0;
	this->_systemPromptCallbackMap.Pairs.Elements.FirstFreeIndex = -1;
	this->_systemPromptCallbackMap.Pairs.Elements.NumFreeIndices = 0;
	this->_systemPromptCallbackMap.Pairs.Hash.SecondaryData.Data = 0;
	this->_systemPromptCallbackMap.Pairs.HashSize = 0;
	FMatchInfoAnalyticsController::FMatchInfoAnalyticsController(&this->_analyticsManager.MatchInfoAnalytics);
	FWaitTimeAnalyticsController::FWaitTimeAnalyticsController(&this->_analyticsManager.WaitTimeAnalytics);
	FGameplay_KillerAnalyticsController::FGameplay_KillerAnalyticsController(&this->_analyticsManager.GameplayKillerAnalytics);
	FGameplay_SurvivorAnalyticsController::FGameplay_SurvivorAnalyticsController(&this->_analyticsManager.GameplaySurvivorAnalytics);
	FReportAnalyticsController::FReportAnalyticsController(&this->_analyticsManager.ReportAnalytics);
	*(_WORD*)&this->_travelingToSplash = 0;
	this->_allowPresencePluginNotifications = 0;
}