/* 00000000 */ struct /*VFT*/ ADBDGame_Start_vtbl // sizeof=0x820
/* 00000000 */ {
/* 00000000 */     void (__fastcall *~UObject)(struct UObject *this);
/* 00000008 */     void (__fastcall *RegisterDependencies)(struct UObject *this);
/* 00000010 */     void (__fastcall *DeferredRegister)(struct UObject *this, UClass *, const wchar_t *, const wchar_t *);
/* 00000018 */     bool (__fastcall *CanBeClusterRoot)(struct UObject *this);
/* 00000020 */     bool (__fastcall *CanBeInCluster)(struct UObject *this);
/* 00000028 */     void (__fastcall *CreateCluster)(struct UObject *this);
/* 00000030 */     void (__fastcall *AddToCluster)(struct UObject *this, UObjectBaseUtility *);
/* 00000038 */     FString *(__fastcall *GetDetailedInfoInternal)(UObject *this, FString *result);
/* 00000040 */     void (__fastcall *PostInitProperties)(UObject *this);
/* 00000048 */     bool (__fastcall *PreSaveRoot)(UObject *this, const wchar_t *, TArray<FString,FDefaultAllocator> *);
/* 00000050 */     void (__fastcall *PostSaveRoot)(UObject *this, bool);
/* 00000058 */     void (__fastcall *PreSave)(UObject *this, const ITargetPlatform *);
/* 00000060 */     bool (__fastcall *Modify)(UObject *this, bool);
/* 00000068 */     void (__fastcall *PostLoad)(UObject *this);
/* 00000070 */     void (__fastcall *PostLoadSubobjects)(UObject *this, FObjectInstancingGraph *);
/* 00000078 */     void (__fastcall *BeginDestroy)(UObject *this);
/* 00000080 */     bool (__fastcall *IsReadyForFinishDestroy)(UObject *this);
/* 00000088 */     void (__fastcall *FinishDestroy)(UObject *this);
/* 00000090 */     void (__fastcall *Serialize)(UObject *this, FArchive *);
/* 00000098 */     void (__fastcall *ShutdownAfterError)(UObject *this);
/* 000000A0 */     void (__fastcall *PostInterpChange)(UObject *this, UProperty *);
/* 000000A8 */     void (__fastcall *PostRename)(UObject *this, UObject *, const FName);
/* 000000B0 */     void (__fastcall *PostDuplicate)(UObject *this, bool);
/* 000000B8 */     bool (__fastcall *NeedsLoadForClient)(UObject *this);
/* 000000C0 */     bool (__fastcall *NeedsLoadForServer)(UObject *this);
/* 000000C8 */     bool (__fastcall *NeedsLoadForEditorGame)(UObject *this);
/* 000000D0 */     bool (__fastcall *IsPostLoadThreadSafe)(UObject *this);
/* 000000D8 */     void (__fastcall *ExportCustomProperties)(UObject *this, FOutputDevice *, unsigned int);
/* 000000E0 */     void (__fastcall *ImportCustomProperties)(UObject *this, const wchar_t *, FFeedbackContext *);
/* 000000E8 */     void (__fastcall *PostEditImport)(UObject *this);
/* 000000F0 */     void (__fastcall *PostReloadConfig)(UObject *this, UProperty *);
/* 000000F8 */     bool (__fastcall *Rename)(UObject *this, const wchar_t *, UObject *, unsigned int);
/* 00000100 */     FString *(__fastcall *GetDesc)(UObject *this, FString *result);
/* 00000108 */     UWorld *(__fastcall *GetWorld)(UObject *this);
/* 00000110 */     bool (__fastcall *GetNativePropertyValues)(UObject *this, TMap<FString,FString,FDefaultSetAllocator,TDefaultMapKeyFuncs<FString,FString,0> > *, unsigned int);
/* 00000118 */     unsigned __int64 (__fastcall *GetResourceSize)(UObject *this, EResourceSizeMode::Type);
/* 00000120 */     FName *(__fastcall *GetExporterName)(UObject *this, FName *result);
/* 00000128 */     FRestoreForUObjectOverwrite *(__fastcall *GetRestoreForUObjectOverwrite)(UObject *this);
/* 00000130 */     bool (__fastcall *AreNativePropertiesIdenticalTo)(UObject *this, UObject *);
/* 00000138 */     void (__fastcall *GetAssetRegistryTags)(UObject *this, TArray<UObject::FAssetRegistryTag,FDefaultAllocator> *);
/* 00000140 */     bool (__fastcall *IsAsset)(UObject *this);
/* 00000148 */     bool (__fastcall *IsLocalizedResource)(UObject *this);
/* 00000150 */     bool (__fastcall *IsSafeForRootSet)(UObject *this);
/* 00000158 */     void (__fastcall *TagSubobjects)(UObject *this, EObjectFlags);
/* 00000160 */     void (__fastcall *GetLifetimeReplicatedProps)(UObject *this, TArray<FLifetimeProperty,FDefaultAllocator> *);
/* 00000168 */     bool (__fastcall *IsNameStableForNetworking)(UObject *this);
/* 00000170 */     bool (__fastcall *IsFullNameStableForNetworking)(UObject *this);
/* 00000178 */     bool (__fastcall *IsSupportedForNetworking)(UObject *this);
/* 00000180 */     void (__fastcall *GetSubobjectsWithStableNamesForNetworking)(UObject *this, TArray<UObject *,FDefaultAllocator> *);
/* 00000188 */     void (__fastcall *PreNetReceive)(UObject *this);
/* 00000190 */     void (__fastcall *PostNetReceive)(UObject *this);
/* 00000198 */     void (__fastcall *PostRepNotifies)(UObject *this);
/* 000001A0 */     void (__fastcall *PreDestroyFromReplication)(UObject *this);
/* 000001A8 */     void (__fastcall *ProcessEvent)(UObject *this, UFunction *, void *);
/* 000001B0 */     int (__fastcall *GetFunctionCallspace)(UObject *this, UFunction *, void *, FFrame *);
/* 000001B8 */     bool (__fastcall *CallRemoteFunction)(UObject *this, UFunction *, void *, FOutParmRec *, FFrame *);
/* 000001C0 */     bool (__fastcall *ProcessConsoleExec)(UObject *this, const wchar_t *, FOutputDevice *, UObject *);
/* 000001C8 */     UClass *(__fastcall *RegenerateClass)(UObject *this, UClass *, UObject *, TArray<UObject *,FDefaultAllocator> *);
/* 000001D0 */     void (__fastcall *MarkAsEditorOnlySubobject)(UObject *this);
/* 000001D8 */     bool (__fastcall *CheckDefaultSubobjectsInternal)(UObject *this);
/* 000001E0 */     void (__fastcall *OnRep_ReplicateMovement)(AActor *this);
/* 000001E8 */     void (__fastcall *TearOff)(AActor *this);
/* 000001F0 */     bool (__fastcall *HasNetOwner)(AActor *this);
/* 000001F8 */     void (__fastcall *OnRep_Owner)(AActor *this);
/* 00000200 */     void (__fastcall *SetReplicateMovement)(AActor *this, bool);
/* 00000208 */     void (__fastcall *OnRep_AttachmentReplication)(AActor *this);
/* 00000210 */     bool (__fastcall *IsReplicationPausedForConnection)(AActor *this, const FNetViewer *);
/* 00000218 */     void (__fastcall *OnReplicationPausedChanged)(AActor *this, bool);
/* 00000220 */     bool (__fastcall *ReplicateSubobjects)(AActor *this, UActorChannel *, FOutBunch *, FReplicationFlags *);
/* 00000228 */     void (__fastcall *OnSubobjectCreatedFromReplication)(AActor *this, UObject *);
/* 00000230 */     void (__fastcall *OnSubobjectDestroyFromReplication)(AActor *this, UObject *);
/* 00000238 */     void (__fastcall *PreReplication)(AActor *this, IRepChangedPropertyTracker *);
/* 00000240 */     void (__fastcall *OnRep_Instigator)(AActor *this);
/* 00000248 */     void (__fastcall *EnableInput)(AActor *this, APlayerController *);
/* 00000250 */     void (__fastcall *DisableInput)(AActor *this, APlayerController *);
/* 00000258 */     FVector *(__fastcall *GetVelocity)(AActor *this, FVector *result);
/* 00000260 */     void (__fastcall *SetActorHiddenInGame)(AActor *this, bool);
/* 00000268 */     void (__fastcall *K2_DestroyActor)(AActor *this);
/* 00000270 */     void (__fastcall *AddTickPrerequisiteActor)(AActor *this, AActor *);
/* 00000278 */     void (__fastcall *AddTickPrerequisiteComponent)(AActor *this, UActorComponent *);
/* 00000280 */     void (__fastcall *RemoveTickPrerequisiteActor)(AActor *this, AActor *);
/* 00000288 */     void (__fastcall *RemoveTickPrerequisiteComponent)(AActor *this, UActorComponent *);
/* 00000290 */     void (__fastcall *BeginPlay)(AActor *this);
/* 00000298 */     void (__fastcall *NotifyActorBeginOverlap)(AActor *this, AActor *);
/* 000002A0 */     void (__fastcall *NotifyActorEndOverlap)(AActor *this, AActor *);
/* 000002A8 */     void (__fastcall *NotifyActorBeginCursorOver)(AActor *this);
/* 000002B0 */     void (__fastcall *NotifyActorEndCursorOver)(AActor *this);
/* 000002B8 */     void (__fastcall *NotifyActorOnClicked)(AActor *this, FKey);
/* 000002C0 */     void (__fastcall *NotifyActorOnReleased)(AActor *this, FKey);
/* 000002C8 */     void (__fastcall *NotifyActorOnInputTouchBegin)(AActor *this, const ETouchIndex::Type);
/* 000002D0 */     void (__fastcall *NotifyActorOnInputTouchEnd)(AActor *this, const ETouchIndex::Type);
/* 000002D8 */     void (__fastcall *NotifyActorOnInputTouchEnter)(AActor *this, const ETouchIndex::Type);
/* 000002E0 */     void (__fastcall *NotifyActorOnInputTouchLeave)(AActor *this, const ETouchIndex::Type);
/* 000002E8 */     void (__fastcall *NotifyHit)(AActor *this, UPrimitiveComponent *, AActor *, UPrimitiveComponent *, bool, FVector, FVector, FVector, const FHitResult *);
/* 000002F0 */     void (__fastcall *SetLifeSpan)(AActor *this, float);
/* 000002F8 */     float (__fastcall *GetLifeSpan)(AActor *this);
/* 00000300 */     void (__fastcall *GatherCurrentMovement)(AActor *this);
/* 00000308 */     USceneComponent *(__fastcall *GetDefaultAttachComponent)(AActor *this);
/* 00000310 */     void (__fastcall *ApplyWorldOffset)(AActor *this, const FVector *, bool);
/* 00000318 */     bool (__fastcall *IsLevelBoundsRelevant)(AActor *this);
/* 00000320 */     float (__fastcall *GetNetPriority)(AActor *this, const FVector *, const FVector *, APlayerController *, UActorChannel *, float, bool);
/* 00000328 */     float (__fastcall *GetNetPriority)(AActor *this, const FVector *, const FVector *, AActor *, AActor *, UActorChannel *, float, bool);
/* 00000330 */     float (__fastcall *GetReplayPriority)(AActor *this, const FVector *, const FVector *, AActor *, AActor *, UActorChannel *const, float);
/* 00000338 */     bool (__fastcall *GetNetDormancy)(AActor *this, const FVector *, const FVector *, APlayerController *, AActor *, UActorChannel *, float, bool);
/* 00000340 */     bool (__fastcall *GetNetDormancy)(AActor *this, const FVector *, const FVector *, AActor *, AActor *, UActorChannel *, float, bool);
/* 00000348 */     void (__fastcall *OnActorChannelOpen)(AActor *this, FInBunch *, UNetConnection *);
/* 00000350 */     bool (__fastcall *UseShortConnectTimeout)(AActor *this);
/* 00000358 */     void (__fastcall *OnSerializeNewActor)(AActor *this, FOutBunch *);
/* 00000360 */     void (__fastcall *OnNetCleanup)(AActor *this, UNetConnection *);
/* 00000368 */     void (__fastcall *TickActor)(AActor *this, float, ELevelTick, FActorTickFunction *);
/* 00000370 */     void (__fastcall *PostActorCreated)(AActor *this);
/* 00000378 */     void (__fastcall *LifeSpanExpired)(AActor *this);
/* 00000380 */     void (__fastcall *PostNetInit)(AActor *this);
/* 00000388 */     void (__fastcall *OnRep_ReplicatedMovement)(AActor *this);
/* 00000390 */     void (__fastcall *PostNetReceiveLocation)(AActor *this);
/* 00000398 */     void (__fastcall *PostNetReceiveLocationAndRotation)(AActor *this);
/* 000003A0 */     void (__fastcall *PostNetReceiveVelocity)(AActor *this, const FVector *);
/* 000003A8 */     void (__fastcall *PostNetReceivePhysicState)(AActor *this);
/* 000003B0 */     void (__fastcall *SetOwner)(AActor *this, AActor *);
/* 000003B8 */     bool (__fastcall *CheckStillInWorld)(AActor *this);
/* 000003C0 */     void (__fastcall *Tick)(AActor *this, float);
/* 000003C8 */     bool (__fastcall *ShouldTickIfViewportsOnly)(AActor *this);
/* 000003D0 */     bool (__fastcall *IsNetRelevantFor)(AActor *this, const APlayerController *, const AActor *, const FVector *);
/* 000003D8 */     bool (__fastcall *IsNetRelevantFor)(AActor *this, const AActor *, const AActor *, const FVector *);
/* 000003E0 */     bool (__fastcall *IsRelevancyOwnerFor)(AActor *this, const AActor *, const AActor *, const AActor *);
/* 000003E8 */     void (__fastcall *PreInitializeComponents)(AActor *this);
/* 000003F0 */     void (__fastcall *PostInitializeComponents)(AActor *this);
/* 000003F8 */     const AActor *(__fastcall *GetNetOwner)(AActor *this);
/* 00000400 */     UPlayer *(__fastcall *GetNetOwningPlayer)(AActor *this);
/* 00000408 */     UNetConnection *(__fastcall *GetNetConnection)(AActor *this);
/* 00000410 */     bool (__fastcall *DestroyNetworkActorHandled)(AActor *this);
/* 00000418 */     void (__fastcall *RegisterAllComponents)(AActor *this);
/* 00000420 */     void (__fastcall *PostRegisterAllComponents)(AActor *this);
/* 00000428 */     void (__fastcall *UnregisterAllComponents)(AActor *this, bool);
/* 00000430 */     void (__fastcall *PostUnregisterAllComponents)(AActor *this);
/* 00000438 */     void (__fastcall *ReregisterAllComponents)(AActor *this);
/* 00000440 */     void (__fastcall *MarkComponentsAsPendingKill)(AActor *this);
/* 00000448 */     void (__fastcall *InvalidateLightingCacheDetailed)(AActor *this, bool);
/* 00000450 */     bool (__fastcall *TeleportTo)(AActor *this, const FVector *, const FRotator *, bool, bool);
/* 00000458 */     void (__fastcall *TeleportSucceeded)(AActor *this, bool);
/* 00000460 */     void (__fastcall *ClearCrossLevelReferences)(AActor *this);
/* 00000468 */     void (__fastcall *EndPlay)(AActor *this, const EEndPlayReason::Type);
/* 00000470 */     bool (__fastcall *IsBasedOnActor)(AActor *this, const AActor *);
/* 00000478 */     bool (__fastcall *IsAttachedTo)(AActor *this, const AActor *);
/* 00000480 */     void (__fastcall *RerunConstructionScripts)(AActor *this);
/* 00000488 */     void (__fastcall *OnConstruction)(AActor *this, const FTransform *);
/* 00000490 */     void (__fastcall *RegisterActorTickFunctions)(AActor *this, bool);
/* 00000498 */     AActor *(__fastcall *GetAttachParentActor)(AActor *this);
/* 000004A0 */     FName *(__fastcall *GetAttachParentSocketName)(AActor *this, FName *result);
/* 000004A8 */     void (__fastcall *GetAttachedActors)(AActor *this, TArray<AActor *,FDefaultAllocator> *);
/* 000004B0 */     void (__fastcall *Destroyed)(AActor *this);
/* 000004B8 */     void (__fastcall *FellOutOfWorld)(AActor *this, const UDamageType *);
/* 000004C0 */     void (__fastcall *OutsideWorldBounds)(AActor *this);
/* 000004C8 */     FBox *(__fastcall *GetComponentsBoundingBox)(AActor *this, FBox *result, bool);
/* 000004D0 */     FBox *(__fastcall *CalculateComponentsBoundingBoxInLocalSpace)(AActor *this, FBox *result, bool);
/* 000004D8 */     void (__fastcall *GetComponentsBoundingCylinder)(AActor *this, float *, float *, bool);
/* 000004E0 */     void (__fastcall *GetSimpleCollisionCylinder)(AActor *this, float *, float *);
/* 000004E8 */     bool (__fastcall *IsRootComponentCollisionRegistered)(AActor *this);
/* 000004F0 */     void (__fastcall *TornOff)(AActor *this);
/* 000004F8 */     ECollisionResponse (__fastcall *GetComponentsCollisionResponseToChannel)(AActor *this, ECollisionChannel);
/* 00000500 */     bool (__fastcall *CanBeBaseForCharacter)(AActor *this, APawn *);
/* 00000508 */     float (__fastcall *TakeDamage)(AActor *this, float, const FDamageEvent *, AController *, AActor *);
/* 00000510 */     float (__fastcall *InternalTakeRadialDamage)(AActor *this, float, const FRadialDamageEvent *, AController *, AActor *);
/* 00000518 */     float (__fastcall *InternalTakePointDamage)(AActor *this, float, const FPointDamageEvent *, AController *, AActor *);
/* 00000520 */     void (__fastcall *BecomeViewTarget)(AActor *this, APlayerController *);
/* 00000528 */     void (__fastcall *EndViewTarget)(AActor *this, APlayerController *);
/* 00000530 */     void (__fastcall *CalcCamera)(AActor *this, float, FMinimalViewInfo *);
/* 00000538 */     bool (__fastcall *HasActiveCameraComponent)(AActor *this);
/* 00000540 */     bool (__fastcall *HasActivePawnControlCameraComponent)(AActor *this);
/* 00000548 */     FString *(__fastcall *GetHumanReadableName)(AActor *this, FString *result);
/* 00000550 */     void (__fastcall *Reset)(AActor *this);
/* 00000558 */     float (__fastcall *GetLastRenderTime)(AActor *this);
/* 00000560 */     void (__fastcall *ForceNetRelevant)(AActor *this);
/* 00000568 */     void (__fastcall *ForceNetUpdate)(AActor *this);
/* 00000570 */     void (__fastcall *PrestreamTextures)(AActor *this, float, bool, int);
/* 00000578 */     void (__fastcall *GetActorEyesViewPoint)(AActor *this, FVector *, FRotator *);
/* 00000580 */     FVector *(__fastcall *GetTargetLocation)(AActor *this, FVector *result, AActor *);
/* 00000588 */     void (__fastcall *PostRenderFor)(AActor *this, APlayerController *, UCanvas *, FVector, FVector);
/* 00000590 */     UActorComponent *(__fastcall *FindComponentByClass)(AActor *this, const TSubclassOf<UActorComponent>);
/* 00000598 */     bool (__fastcall *IsComponentRelevantForNavigation)(AActor *this, UActorComponent *);
/* 000005A0 */     void (__fastcall *DisplayDebug)(AActor *this, UCanvas *, const FDebugDisplayInfo *, float *, float *);
/* 000005A8 */     bool (__fastcall *PlayerCanRestart_Implementation)(AGameMode *this, APlayerController *);
/* 000005B0 */     AActor *(__fastcall *ChoosePlayerStart_Implementation)(AGameMode *this, AController *);
/* 000005B8 */     AActor *(__fastcall *FindPlayerStart_Implementation)(AGameMode *this, AController *, const FString *);
/* 000005C0 */     bool (__fastcall *CanSpectate_Implementation)(AGameMode *this, APlayerController *, APlayerState *);
/* 000005C8 */     APawn *(__fastcall *SpawnDefaultPawnFor_Implementation)(AGameMode *this, AController *, AActor *);
/* 000005D0 */     void (__fastcall *InitStartSpot_Implementation)(AGameMode *this, AActor *, AController *);
/* 000005D8 */     UClass *(__fastcall *GetDefaultPawnClassForController_Implementation)(AGameMode *this, AController *);
/* 000005E0 */     bool (__fastcall *MustSpectate_Implementation)(AGameMode *this, APlayerController *);
/* 000005E8 */     bool (__fastcall *ShouldReset_Implementation)(AGameMode *this, AActor *);
/* 000005F0 */     bool (__fastcall *ReadyToEndMatch_Implementation)(AGameMode *this);
/* 000005F8 */     bool (__fastcall *ReadyToStartMatch_Implementation)(AGameMode *this);
/* 00000600 */     bool (__fastcall *HasMatchStarted)(AGameMode *this);
/* 00000608 */     bool (__fastcall *IsMatchInProgress)(AGameMode *this);
/* 00000610 */     bool (__fastcall *HasMatchEnded)(AGameMode *this);
/* 00000618 */     void (__fastcall *StartPlay)(AGameMode *this);
/* 00000620 */     void (__fastcall *PostSeamlessTravel)(AGameMode *this);
/* 00000628 */     void (__fastcall *StartMatch)(AGameMode *this);
/* 00000630 */     void (__fastcall *EndMatch)(AGameMode *this);
/* 00000638 */     void (__fastcall *StartToLeaveMap)(AGameMode *this);
/* 00000640 */     void (__fastcall *RestartGame)(AGameMode *this);
/* 00000648 */     void (__fastcall *ReturnToMainMenuHost)(AGameMode *this);
/* 00000650 */     void (__fastcall *AbortMatch)(AGameMode *this);
/* 00000658 */     void (__fastcall *SetMatchState)(AGameMode *this, FName);
/* 00000660 */     void (__fastcall *OnMatchStateSet)(AGameMode *this);
/* 00000668 */     void (__fastcall *HandleMatchIsWaitingToStart)(AGameMode *this);
/* 00000670 */     void (__fastcall *HandleMatchHasStarted)(AGameMode *this);
/* 00000678 */     void (__fastcall *HandleMatchHasEnded)(AGameMode *this);
/* 00000680 */     void (__fastcall *HandleLeavingMap)(AGameMode *this);
/* 00000688 */     void (__fastcall *HandleMatchAborted)(AGameMode *this);
/* 00000690 */     void (__fastcall *SetBandwidthLimit)(AGameMode *this, float);
/* 00000698 */     void (__fastcall *ResetLevel)(AGameMode *this);
/* 000006A0 */     void (__fastcall *InitGame)(AGameMode *this, const FString *, const FString *, FString *);
/* 000006A8 */     void (__fastcall *InitGameState)(AGameMode *this);
/* 000006B0 */     FString *(__fastcall *GetNetworkNumber)(AGameMode *this, FString *result);
/* 000006B8 */     int (__fastcall *GetNumPlayers)(AGameMode *this);
/* 000006C0 */     bool (__fastcall *SetPause)(AGameMode *this, APlayerController *, TBaseDelegate<bool>);
/* 000006C8 */     void (__fastcall *ClearPause)(AGameMode *this);
/* 000006D0 */     FString *(__fastcall *GetDefaultGameClassPath)(AGameMode *this, FString *result, const FString *, const FString *, const FString *);
/* 000006D8 */     TSubclassOf<AGameMode> *(__fastcall *GetGameModeClass)(AGameMode *this, TSubclassOf<AGameMode> *result, const FString *, const FString *, const FString *);
/* 000006E0 */     TSubclassOf<AGameSession> *(__fastcall *GetGameSessionClass)(AGameMode *this, TSubclassOf<AGameSession> *result);
/* 000006E8 */     void (__fastcall *NotifyPendingConnectionLost)(AGameMode *this);
/* 000006F0 */     bool (__fastcall *GetTravelType)(AGameMode *this);
/* 000006F8 */     void (__fastcall *ProcessServerTravel)(AGameMode *this, const FString *, bool);
/* 00000700 */     APlayerController *(__fastcall *ProcessClientTravel)(AGameMode *this, FString *, FGuid, bool, bool);
/* 00000708 */     void (__fastcall *PreLogin)(AGameMode *this, const FString *, const FString *, const FUniqueNetIdRepl *, FString *);
/* 00000710 */     void (__fastcall *PreLogin)(AGameMode *this, const FString *, const FString *, const TSharedPtr<FUniqueNetId const ,0> *, FString *);
/* 00000718 */     APlayerController *(__fastcall *Login)(AGameMode *this, UPlayer *, ENetRole, const FString *, const FString *, const FUniqueNetIdRepl *, FString *);
/* 00000720 */     APlayerController *(__fastcall *Login)(AGameMode *this, UPlayer *, ENetRole, const FString *, const FString *, const TSharedPtr<FUniqueNetId const ,0> *, FString *);
/* 00000728 */     void (__fastcall *PostLogin)(AGameMode *this, APlayerController *);
/* 00000730 */     APlayerController *(__fastcall *SpawnPlayerController)(AGameMode *this, ENetRole, const FVector *, const FRotator *);
/* 00000738 */     void (__fastcall *ReplicateStreamingStatus)(AGameMode *this, APlayerController *);
/* 00000740 */     void (__fastcall *GenericPlayerInitialization)(AGameMode *this, AController *);
/* 00000748 */     void (__fastcall *StartNewPlayer)(AGameMode *this, APlayerController *);
/* 00000750 */     void (__fastcall *Logout)(AGameMode *this, AController *);
/* 00000758 */     void (__fastcall *SetPlayerDefaults)(AGameMode *this, APawn *);
/* 00000760 */     void (__fastcall *ChangeName)(AGameMode *this, AController *, const FString *, bool);
/* 00000768 */     void (__fastcall *SendPlayer)(AGameMode *this, APlayerController *, const FString *);
/* 00000770 */     void (__fastcall *Broadcast)(AGameMode *this, AActor *, const FString *, FName);
/* 00000778 */     void (__fastcall *BroadcastLocalized)(AGameMode *this, AActor *, TSubclassOf<ULocalMessage>, int, APlayerState *, APlayerState *, UObject *);
/* 00000780 */     bool (__fastcall *ShouldSpawnAtStartSpot)(AGameMode *this, AController *);
/* 00000788 */     void (__fastcall *UpdateGameplayMuteList)(AGameMode *this, APlayerController *);
/* 00000790 */     bool (__fastcall *AllowCheats)(AGameMode *this, APlayerController *);
/* 00000798 */     bool (__fastcall *AllowPausing)(AGameMode *this, APlayerController *);
/* 000007A0 */     void (__fastcall *PreCommitMapChange)(AGameMode *this, const FString *, const FString *);
/* 000007A8 */     void (__fastcall *PostCommitMapChange)(AGameMode *this);
/* 000007B0 */     void (__fastcall *AddInactivePlayer)(AGameMode *this, APlayerState *, APlayerController *);
/* 000007B8 */     bool (__fastcall *FindInactivePlayer)(AGameMode *this, APlayerController *);
/* 000007C0 */     void (__fastcall *OverridePlayerState)(AGameMode *this, APlayerController *, APlayerState *);
/* 000007C8 */     void (__fastcall *GetSeamlessTravelActorList)(AGameMode *this, bool, TArray<AActor *,FDefaultAllocator> *);
/* 000007D0 */     FString *(__fastcall *GetRedirectURL)(AGameMode *this, FString *result, const FString *);
/* 000007D8 */     void (__fastcall *GameWelcomePlayer)(AGameMode *this, UNetConnection *, FString *);
/* 000007E0 */     void (__fastcall *SwapPlayerControllers)(AGameMode *this, APlayerController *, APlayerController *);
/* 000007E8 */     void (__fastcall *HandleSeamlessTravelPlayer)(AGameMode *this, AController **);
/* 000007F0 */     void (__fastcall *SetSeamlessTravelViewTarget)(AGameMode *this, APlayerController *);
/* 000007F8 */     void (__fastcall *MatineeCancelled)(AGameMode *this);
/* 00000800 */     void (__fastcall *RestartPlayer)(AGameMode *this, AController *);
/* 00000808 */     bool (__fastcall *IsHandlingReplays)(AGameMode *this);
/* 00000810 */     FString *(__fastcall *InitNewPlayer)(AGameMode *this, FString *result, APlayerController *, const FUniqueNetIdRepl *, const FString *, const FString *);
/* 00000818 */     FString *(__fastcall *InitNewPlayer)(AGameMode *this, FString *result, APlayerController *, const TSharedPtr<FUniqueNetId const ,0> *, const FString *, const FString *);
/* 00000820 */ };