class __base(AGameState, 0) ADBDGameState
{
/* 0x0000 */    struct ADBDGameState::VTable* vtable;
/* 0x0008 */    __inherited enum EObjectFlags UObjectBase::ObjectFlags;
/* 0x000c */    __inherited int32_t UObjectBase::InternalIndex;
/* 0x0010 */    __inherited class UClass* UObjectBase::ClassPrivate;
/* 0x0018 */    __inherited class FName UObjectBase::NamePrivate;
/* 0x0020 */    __inherited class UObject* UObjectBase::OuterPrivate;
/* 0x0028 */    __inherited struct FActorTickFunction AActor::PrimaryActorTick;
/* 0x0078 */    __inherited float AActor::CustomTimeDilation;
/* 0x007c */    __inherited union
/* 0x007c */    {
/* 0x007c+0x01 */        uint8_t bHidden;
/* 0x007c+0x02 */        uint8_t bNetTemporary;
/* 0x007c+0x04 */        uint8_t bNetStartup;
/* 0x007c+0x08 */        uint8_t bOnlyRelevantToOwner;
/* 0x007c+0x10 */        uint8_t bAlwaysRelevant;
/* 0x007c+0x20 */        uint8_t bReplicateMovement;
/* 0x007c+0x40 */        uint8_t bTearOff;
/* 0x007c+0x80 */        uint8_t bExchangedRoles;
/* 0x007c */    } __bitfield7c;
/* 0x007d */    __inherited union
/* 0x007d */    {
/* 0x007d+0x01 */        uint8_t bPendingNetUpdate;
/* 0x007d+0x02 */        uint8_t bNetLoadOnClient;
/* 0x007d+0x04 */        uint8_t bNetUseOwnerRelevancy;
/* 0x007d+0x08 */        uint8_t bBlockInput;
/* 0x007d+0x10 */        uint8_t bRunningUserConstructionScript;
/* 0x007d+0x20 */        uint8_t bAllowTickBeforeBeginPlay;
/* 0x007d+0x40 */        uint8_t bHasFinishedSpawning;
/* 0x007d+0x80 */        uint8_t bTickFunctionsRegistered;
/* 0x007d */    } __bitfield7d;
/* 0x007e */    __inherited union
/* 0x007e */    {
/* 0x007e+0x01 */        uint8_t bActorEnableCollision;
/* 0x007e+0x02 */        uint8_t bNetCheckedInitialPhysicsState;
/* 0x007e+0x04 */        uint8_t bReplicates;
/* 0x007e */    } __bitfield7e;
/* 0x007f */    __padding char _7f[1];
/* 0x0080 */    __inherited class FName AActor::NetDriverName;
/* 0x0088 */    __inherited class TEnumAsByte<enum ENetRole> AActor::RemoteRole;
/* 0x0090 */    __inherited class AActor* AActor::Owner;
/* 0x0098 */    __inherited struct FRepMovement AActor::ReplicatedMovement;
/* 0x00cc */    __padding char _cc[4];
/* 0x00d0 */    __inherited struct FRepAttachment AActor::AttachmentReplication;
/* 0x0110 */    __inherited class TEnumAsByte<enum ENetRole> AActor::Role;
/* 0x0111 */    __inherited class TEnumAsByte<enum ENetDormancy> AActor::NetDormancy;
/* 0x0112 */    __inherited class TEnumAsByte<enum EAutoReceiveInput::Type> AActor::AutoReceiveInput;
/* 0x0114 */    __inherited int32_t AActor::InputPriority;
/* 0x0118 */    __inherited class UInputComponent* AActor::InputComponent;
/* 0x0120 */    __inherited class TEnumAsByte<enum EInputConsumeOptions> AActor::InputConsumeOption_DEPRECATED;
/* 0x0124 */    __inherited float AActor::NetCullDistanceSquared;
/* 0x0128 */    __inherited int32_t AActor::NetTag;
/* 0x012c */    __inherited float AActor::NetUpdateTime;
/* 0x0130 */    __inherited float AActor::NetUpdateFrequency;
/* 0x0134 */    __inherited float AActor::MinNetUpdateFrequency;
/* 0x0138 */    __inherited float AActor::NetPriority;
/* 0x013c */    __inherited float AActor::LastNetUpdateTime;
/* 0x0140 */    __inherited union
/* 0x0140 */    {
/* 0x0140+0x01 */        uint8_t bAutoDestroyWhenFinished;
/* 0x0140+0x02 */        uint8_t bCanBeDamaged;
/* 0x0140+0x04 */        uint8_t bActorIsBeingDestroyed;
/* 0x0140+0x08 */        uint8_t bCollideWhenPlacing;
/* 0x0140+0x10 */        uint8_t bFindCameraComponentWhenViewTarget;
/* 0x0140+0x20 */        uint8_t bRelevantForNetworkReplays;
/* 0x0140+0x40 */        uint8_t bGenerateOverlapEventsDuringLevelStreaming;
/* 0x0140 */    } __bitfield140;
/* 0x0141 */    __inherited enum ESpawnActorCollisionHandlingMethod AActor::SpawnCollisionHandlingMethod;
/* 0x0144 */    __inherited float AActor::CreationTime;
/* 0x0148 */    __inherited class APawn* AActor::Instigator;
/* 0x0150 */    __inherited class TArray<AActor *,FDefaultAllocator> AActor::Children;
/* 0x0160 */    __inherited class USceneComponent* AActor::RootComponent;
/* 0x0168 */    __inherited class TArray<AMatineeActor *,FDefaultAllocator> AActor::ControllingMatineeActors;
/* 0x0178 */    __inherited float AActor::InitialLifeSpan;
/* 0x017c */    __padding char _17c[4];
/* 0x0180 */    __inherited struct FTimerHandle AActor::TimerHandle_LifeSpanExpired;
/* 0x0188 */    __inherited class TArray<FName,FDefaultAllocator> AActor::Layers;
/* 0x0198 */    __inherited struct TWeakObjectPtr<AActor,FWeakObjectPtr> AActor::ParentComponentActor_DEPRECATED;
/* 0x01a0 */    __inherited struct TWeakObjectPtr<UChildActorComponent,FWeakObjectPtr> AActor::ParentComponent;
/* 0x01a8 */    __inherited union
/* 0x01a8 */    {
/* 0x01a8+0x01 */        uint8_t bAllowReceiveTickEventOnDedicatedServer;
/* 0x01a8+0x02 */        uint8_t bActorInitialized;
/* 0x01a8+0x04 */        enum AActor::EActorBeginPlayState ActorHasBegunPlay;
/* 0x01a8+0x08 */        uint8_t bActorSeamlessTraveled;
/* 0x01a8+0x10 */        uint8_t bIgnoresOriginShifting;
/* 0x01a8+0x20 */        uint8_t bEnableAutoLODGeneration;
/* 0x01a8 */    } __bitfield1a8;
/* 0x01a9 */    __padding char _1a9[7];
/* 0x01b0 */    __inherited class TArray<FName,FDefaultAllocator> AActor::Tags;
/* 0x01c0 */    __inherited uint64_t AActor::HiddenEditorViews;
/* 0x01c8 */    __inherited class FTakeAnyDamageSignature AActor::OnTakeAnyDamage;
/* 0x01d8 */    __inherited class FTakePointDamageSignature AActor::OnTakePointDamage;
/* 0x01e8 */    __inherited class FActorBeginOverlapSignature AActor::OnActorBeginOverlap;
/* 0x01f8 */    __inherited class FActorEndOverlapSignature AActor::OnActorEndOverlap;
/* 0x0208 */    __inherited class FActorBeginCursorOverSignature AActor::OnBeginCursorOver;
/* 0x0218 */    __inherited class FActorEndCursorOverSignature AActor::OnEndCursorOver;
/* 0x0228 */    __inherited class FActorOnClickedSignature AActor::OnClicked;
/* 0x0238 */    __inherited class FActorOnReleasedSignature AActor::OnReleased;
/* 0x0248 */    __inherited class FActorOnInputTouchBeginSignature AActor::OnInputTouchBegin;
/* 0x0258 */    __inherited class FActorOnInputTouchEndSignature AActor::OnInputTouchEnd;
/* 0x0268 */    __inherited class FActorBeginTouchOverSignature AActor::OnInputTouchEnter;
/* 0x0278 */    __inherited class FActorEndTouchOverSignature AActor::OnInputTouchLeave;
/* 0x0288 */    __inherited class FActorHitSignature AActor::OnActorHit;
/* 0x0298 */    __inherited class FActorDestroyedSignature AActor::OnDestroyed;
/* 0x02a8 */    __inherited class FActorEndPlaySignature AActor::OnEndPlay;
/* 0x02b8 */    __inherited class TSet<UActorComponent *,DefaultKeyFuncs<UActorComponent *,0>,FDefaultSetAllocator> AActor::OwnedComponents;
/* 0x0308 */    __inherited class TSet<UActorComponent *,DefaultKeyFuncs<UActorComponent *,0>,FDefaultSetAllocator> AActor::ReplicatedComponents;
/* 0x0358 */    __inherited class TArray<UActorComponent *,FDefaultAllocator> AActor::BlueprintCreatedComponents;
/* 0x0368 */    __inherited class TArray<UActorComponent *,FDefaultAllocator> AActor::InstanceComponents;
/* 0x0378 */    __inherited class FRenderCommandFence AActor::DetachFence;
/* 0x0380 */    __inherited class TSubclassOf<AGameMode> AGameState::GameModeClass;
/* 0x0388 */    __inherited class AGameMode* AGameState::AuthorityGameMode;
/* 0x0390 */    __inherited class TSubclassOf<ASpectatorPawn> AGameState::SpectatorClass;
/* 0x0398 */    __inherited class FName AGameState::MatchState;
/* 0x03a0 */    __inherited class FName AGameState::PreviousMatchState;
/* 0x03a8 */    __inherited int32_t AGameState::ElapsedTime;
/* 0x03ac */    __padding char _3ac[4];
/* 0x03b0 */    __inherited class TArray<APlayerState *,FDefaultAllocator> AGameState::PlayerArray;
/* 0x03c0 */    __inherited float AGameState::ReplicatedWorldTimeSeconds;
/* 0x03c4 */    __inherited float AGameState::ServerWorldTimeSecondsDelta;
/* 0x03c8 */    __inherited float AGameState::ServerWorldTimeSecondsUpdateFrequency;
/* 0x03cc */    __padding char _3cc[4];
/* 0x03d0 */    __inherited struct FTimerHandle AGameState::TimerHandle_DefaultTimer;
/* 0x03d8 */    __inherited struct FTimerHandle AGameState::TimerHandle_UpdateServerTimeSeconds;
/* 0x03e0 */    class FEscapeDoorActivatedEvent OnEscapeDoorActivated;
/* 0x03f0 */    class TMulticastDelegate<void> OnEscapeDoorActivatedHud;
/* 0x0460 */    class TMulticastDelegate<void,bool> OnHatchOpened;
/* 0x04d0 */    class TMulticastDelegate<void,ADBDGameState *> _gameDataUpdatedDelegate;
/* 0x0540 */    class FLevelReadyToPlayEvent OnLevelReadyToPlay;
/* 0x0550 */    class FSurvivorsLeftChangedEvent OnSurvivorsLeftChanged;
/* 0x0560 */    class FAllPlayerLoadedEvent AuthorityOnAllPlayerLoaded;
/* 0x0570 */    class TMulticastDelegate<void,int> OnActivatedGeneratorCountChanged;
/* 0x05e0 */    class FActivatedGeneratorCountChangedDynamicEvent OnActivatedGeneratorCountChangedDynamic;
/* 0x05f0 */    class ASlasherPlayer* Slasher;
/* 0x05f8 */    int32_t GeneratorNeeded;
/* 0x05fc */    int32_t CamperDeadCount;
/* 0x0600 */    int32_t CamperInMeatLockerCount;
/* 0x0604 */    int32_t CamperEscaped;
/* 0x0608 */    int32_t WaitingForEscape;
/* 0x060c */    int32_t CamperCount;
/* 0x0610 */    uint8_t LeaveSpectateRequested;
/* 0x0611 */    uint8_t IsGameEnded;
/* 0x0612 */    uint8_t PlayersReadyToStart;
/* 0x0614 */    int32_t SecondsLeftInLobby;
/* 0x0618 */    union
/* 0x0618 */    {
/* 0x0618+0x01 */        uint32_t HasServerLeftTheGame;
/* 0x0618 */    } __bitfield618;
/* 0x061c */    uint8_t _lightingGenerated;
/* 0x061d */    uint8_t _introCompleted;
/* 0x061e */    uint8_t _displayMapName;
/* 0x0620 */    float _killerIntroCompleted;
/* 0x0624 */    uint8_t _gameLevelLoaded;
/* 0x0625 */    __padding char _625[3];
/* 0x0628 */    struct FBuiltLevelData _builtLevelData;
/* 0x0660 */    struct FOfferingData _levelOfferings;
/* 0x0678 */    class AClipManager* _clipManager;
/* 0x0680 */    struct FServerJoiningData _serverJoiningData;
/* 0x06b0 */    class FDelegateHandle _onJoinSessionLogDelegateHandle;
/* 0x06b8 */    class FDelegateHandle _onLobbySessionFoundDelegateHandle;
/* 0x06c0 */    class FDelegateHandle _onJoinSessionsCompleteDelegateHandle;
/* 0x06c8 */    class FDelegateHandle _onOnJoinSessionErrorDelegateHandle;
/* 0x06d0 */    class FDelegateHandle _onFindFriendSessionCompleteDelegateHandle;
/* 0x06d8 */    struct FGuid _sessionId;
/* 0x06e8 */    int32_t _activatedGeneratorCount;
/* 0x06ec */    uint8_t _escapeDoorActivated;
/* 0x06ed */    uint8_t _isHatchOpen;
/* 0x06ee */    uint8_t _levelReadyToPlay;
/* 0x06ef */    uint8_t _playerDistributionReady;
/* 0x06f0 */    uint8_t _usingWeakenedMechanic;
/* 0x06f4 */    int32_t _survivorLeft;
/* 0x06f8 */    uint8_t _gameHasBeenSetup;
/* 0x06fc */    int32_t _killerServerSearchAttempt;
/* 0x0700 */    uint8_t _travelToKillerServer;
/* 0x0701 */    uint8_t _killerServerSearchFailed;
/* 0x0702 */    uint8_t _killerServerSearchStarted;
/* 0x0703 */    enum ESurvivorGroupTransitionSteps _currentSurvivorGroupTransitionStep;
/* 0x0704 */    __padding char _704[4];
/* 0x0708 */    class TArray<unsigned int,FDefaultAllocator> JoinedKillerIds;
/* 0x0718 */    int32_t _camperEscapedThroughHatch;
/* 0x0720 */    class ACamperPlayer* _obsessionTarget;
/* 0x0728 */    uint8_t _cachedObsessionEscaped;
/* 0x072c */    int32_t _totalObsessionWeight;
/* 0x0730 */    class TArray<AActor *,FDefaultAllocator> _heartbeatEmitters;
/* 0x0740 */    class TArray<AInteractable *,FDefaultAllocator> _traps;
/* 0x0750 */    uint8_t _gamePresetDataInit;
/* 0x0751 */    __padding char _751[7];
/* 0x0758 */    struct FGamePresetData _gamePresetData;
/* 0x07d0 */
};
